kubesphere/console

scripts/webpack.base.js
server/controllers/view.js
server/routes.js
server/views/terminal.html
src/components/KubeTools/index.jsx
src/core/terminal.js
src/pages/console/routes/index.js
src/pages/terminal/index.jsx

update: add termianl entrance page

---

locales/en/pipeline.js
locales/en/project.js
locales/en/workload.js

UI updated

---

src/components/KubeTools/index.jsx
src/pages/terminal/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix terminal url

---

locales/en/alerting.js
locales/en/base.js
locales/en/devops.js
locales/en/group.js
locales/en/pipeline.js
locales/en/project.js
locales/en/s2i.js
locales/en/user.js
locales/en/workspace.js
locales/es/alerting.js
locales/es/group.js
locales/es/pipeline.js
locales/es/workspace.js
locales/tc/alerting.js
locales/tc/group.js
locales/tc/pipeline.js
locales/tc/workspace.js
locales/zh/alerting.js
locales/zh/application.js
locales/zh/group.js
locales/zh/logging.js
locales/zh/pipeline.js
locales/zh/workspace.js
src/components/Forms/AlertingPolicy/NotificationRule/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Card/index.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/index.jsx
src/pages/workspaces/containers/Groups/GroupUser/User.jsx
src/pages/workspaces/containers/Groups/index.jsx

Chore(locales): Update some UI text

---

locales/en/app.js
locales/es/app.js
locales/tc/app.js
locales/zh/app.js
src/pages/projects/components/Modals/AppTemplateEdit/index.jsx

update: Show current App version in app template edit

---

src/stores/edgenode.js

>
/kind bug
Fixes #
```
```
```docs
```

fix: Fix Edge Node apiVersion and listUrl

---

locales/en/version.js
locales/es/version.js
locales/tc/version.js
locales/zh/version.js
src/components/Base/Indicator/index.scss
src/configs/openpitrix/app.js
src/pages/projects/components/Modals/DeployApp/index.jsx
src/stores/openpitrix/base.js
src/utils/app.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix op app review status

---

src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
src/components/Forms/Workload/VolumeSettings/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/1569
```
```
```docs
```

fix: Fix storage class api in sts create form

---

scripts/webpack.e2e.js
scripts/webpack.prod.js
server/controllers/view.js
server/libs/utils.js
server/views/terminal.html
src/core/terminal.js

chore: Refactor webpack build script for multiple entries

---

server/public/loading.css
server/views/components/loading.html
server/views/index.html
server/views/terminal.html

page loading  animations opimization

---

package.json
src/components/Modals/AppRepoCreate/url.input.jsx
src/components/Modals/Network/IPPoolsCreate/index.jsx
yarn.lock

/kind bug
Fixes #
https://github.com/kubesphere/console/issues/1585
https://github.com/kubesphere/kubesphere/issues/3474
```
```
```docs
```

fix: Fix network ippool create validate error and input search

---

locales/en/nodes.js
locales/es/nodes.js
locales/tc/nodes.js
locales/zh/nodes.js
src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
src/stores/edgenode.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix the local language and the join URL

---

server/public/loading.css

fix: terminal page loading delay

---

src/actions/resource.edit.js

Fixes #1548 
```
```
```docs
```

update: update resource edit notify

---

src/pages/projects/containers/Secrets/Detail/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/1593
```
```
```docs
```

fix: Remove updatedTime in secret detail page

---

src/components/Layout/Nav/NavItem.jsx
src/components/Layout/Nav/index.jsx
src/components/Layout/Nav/index.scss

The current navigation hover effect is difficult to use, use click to expand instead.
Fixes #
```
```
```docs
```

refactor: Refactor navs hover and click behaviors

---

package.json
src/components/Modals/EditAuthorization/CheckItem.jsx
src/components/Modals/EditAuthorization/index.scss
yarn.lock

/kind bug
Fixes #1598
```
```
```docs
```

fix: Fix checkbox in edit authorization

---

src/components/Inputs/ResourceLimit/index.jsx

/kind bug
Fixes #1605
```
```
```docs
```

fix: Fix resource limit error tip

---

locales/zh/cluster.js
locales/zh/ippool.js
src/components/Modals/Network/IPPoolsCreate/index.jsx
src/pages/clusters/containers/Network/IPPools/Detail/index.jsx
src/pages/clusters/containers/Network/IPPools/index.jsx

/kind bug
Fixes #1599 #1602 #1608
```
```
```docs
```

fix: Fix ippool issues

---

src/components/Inputs/ResourceLimit/index.jsx
src/components/Modals/QuotaEdit/index.jsx
src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
src/pages/workspaces/components/Modals/QuotaEdit/index.jsx

/kind bug
Fixes #1580
```
```
```docs
```

fix: Fix resource limit error check

---

server/services/session.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix oauth cas provider

---

src/components/Forms/Pipelines/AdvanceSettings/index.jsx
src/components/Forms/Pipelines/BaseInfo/index.jsx
src/components/Modals/Pipelines/Copy/index.jsx
src/utils/devops.js

/kind bug
Fixes ##[kubesphere/kubesphere/3480](https://github.com/kubesphere/kubesphere/issues/3480)
```
```
```docs
```
/area devops

fix: Fix the issue about copy pipeline descripton

---

server/config.yaml
src/components/Forms/GrayRelease/Components/index.jsx
src/components/Forms/GrayRelease/Version/ContainerList/Card.jsx

/kind bug
Fixes ##https://github.com/kubesphere/console/issues/1621
#https://github.com/kubesphere/kubesphere/issues/3499
```
```
```docs
```

fix: Fix grayrelease component select and container edit

---

.gitignore
package.json
scripts/webpack.base.js
scripts/webpack.e2e.js
scripts/webpack.prod.js
src/components/Forms/AppDeploy/BasicInfo/index.jsx
src/utils/app.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3540
```
```
```docs
```

fix: Fix op app description and download package

---

src/components/Modals/Network/IPPoolsCreate/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix ip pool create

---

package.json
yarn.lock

/kind bug
Fixes #1633
```
```
```docs
```

fix: Fix total page error

---

locales/en/base.js
src/components/Modals/Delete/index.jsx
src/components/Modals/Delete/index.scss

Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>
/assign @leoendless @Sherlock113

Optimized text in the delete dialog box.

---

locales/en/serviceaccounts.js
locales/es/serviceaccounts.js
locales/tc/serviceaccounts.js
locales/zh/serviceaccounts.js
src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/Secret.jsx
src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/index.scss

feat: add kubeconfig desc in the service account

---

scripts/webpack.e2e.js
scripts/webpack.prod.js

/kind bug
Fixes #1647
```
```
```docs
```

fix: Fix css styles build error

---

locales/en/nodes.js
locales/es/nodes.js
locales/tc/nodes.js
locales/zh/nodes.js
src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
src/components/Forms/Cluster/EdgeNode/AddNode/index.scss
src/stores/node.js

>
/kind bug
Fixes ##1628
```
```
```docs
```

fix: FIx node list can not filter role and add edge node install tip

---

babel.config.js
locales/en/base.js
package.json
src/components/Modals/Delete/index.jsx
src/core/App.jsx
src/core/terminal.js
yarn.lock

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3539
```
```
```docs
```

chore: Fix kube design style compile script

---

src/pages/workspaces/containers/Base/List/index.jsx
src/pages/workspaces/routes/index.js

/kind bug
Fixes #1625 
```
```
```docs
```

fix: visit the workspace default page when user without permissions

---

package.json
src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/components/Inputs/ResourceLimit/index.jsx
src/components/Inputs/StringInput/index.jsx
src/utils/workload.js
yarn.lock

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3516 #https://github.com/kubesphere/console/issues/1603
```
```
```docs
```

fix: Fix workload quota tip

---

src/components/Modals/Network/IPPoolsCreate/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/1671 #https://github.com/kubesphere/console/issues/1668
```
```
```docs
```

fix: Fix ippool max mask length and first cidr error

---

src/pages/apps/components/Cards/UploadInfo/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3532
```
```
```docs
```

fix: Fix app reupload trigger twice error

---

src/components/Modals/EditAuthorization/CheckItem.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3581
```
```
```docs
```

fix: Fix related template check in authorization edit form

---

src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx

/kind bug
Fixes ##1674
```
```
```docs
```

fix: Fix crd resources filters

---

locales/tc/nodes.js

* Adjust the layout and the description of the docs\development-workflow.md to make it easier for readers to start.
>
* Adjust the layout and the description of the docs\development-workflow.md to make it easier for readers to start.
Fixes #
```
```
```docs
```

Update Traditional Chinese translations in nodes.js

---

locales/en/devops.js
locales/es/devops.js
locales/tc/devops.js
locales/zh/devops.js
src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
src/stores/devops/scm.js
src/utils/constants.js

>
/kind bug
/kind feature
Fixes #1642 #1645 #1576
```
```
```docs
```
/area devops

fix: fix some issue about Bitbucket

---

src/components/Inputs/ResourceLimit/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/1689
```
```
```docs
```

fix: Remove resource limit component debounce

---

locales/en/base.js
locales/en/lego.js
locales/en/storage.js
locales/en/workload.js
locales/en/workspace.js

Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>

Reviewed UI text related to workspaces.

---

server/config.yaml

Fix some links in https://github.com/kubesphere/kubesphere/issues/3492

Fix some links on the console

---

src/components/Modals/Node/TaintManagement/Batch.jsx
src/components/Modals/Node/TaintManagement/TaintInput/Item.jsx
src/components/Modals/Node/TaintManagement/TaintInput/index.jsx
src/components/Modals/Node/TaintManagement/index.jsx

/kind bug
Fixes ##1637
```
```
```docs
```

fix: fix add same key for taints in node

---

.github/workflows/deploy-backend.yml

fix: allow failure while deploying new env

---

src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/Details/Cluster/index.scss
src/components/Modals/Bill/components/Crumb/index.jsx
src/components/Modals/Bill/components/Crumb/index.scss
src/components/Modals/Bill/components/MeterDetailCard/index.jsx
src/components/Modals/Bill/components/MeterDetailCard/index.scss
src/components/Modals/Bill/components/SideCard/index.jsx
src/components/Modals/Bill/components/Tables/index.jsx
src/stores/meter/base.js
src/stores/meter/cluster.js
src/utils/meter.js

/kind bug
Fixes ##1683 ##1684 ##1688 ##1686 
```
```
```docs
```

fix: Fix some issues about meter page

---

src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx

/kind bug
Fixes #1664
```
```
```docs
```
/area devops

fix: Set the default status is queued in pipeline status detail

---

src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
src/pages/clusters/containers/Monitor/Cluster/Overview/index.scss

>
/kind bug
Fixes #
```
```
```docs
```

fix: Fix the card height in monitor-cluster overview

---

src/pages/apps/components/AppList/index.jsx
src/pages/apps/containers/Home/index.jsx

> /kind bug
Fixes #1698 
```
```
```docs
```

fix: Fix app categories overflow

---

locales/en/base.js
locales/en/storage.js
locales/es/base.js
locales/es/storage.js
locales/tc/base.js
locales/tc/storage.js
locales/zh/base.js
locales/zh/storage.js
src/components/Base/Indicator/index.scss
src/utils/constants.js
src/utils/object.mapper.js

> /kind bug
Fixes [#kubesphere/kubesphere#3603](https://github.com/kubesphere/kubesphere/issues/3603)
```
```
```docs
```

fix: Fix snapshot status

---

src/components/Modals/Bill/components/SideCard/index.jsx
src/components/Modals/Bill/components/SideCard/item.jsx
src/stores/meter/base.js
src/utils/meter.js

/kind bug
Fixes #
```
```
```docs
```
/assign @wenxin-01

fix: Fix batch export bill both application and openpitrix

---

src/components/Cards/Pods/index.jsx
src/stores/monitoring/base.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/1638
```
```
```docs
```

fix: Fix pod metrics with namespaced_resources_filter

---

src/actions/cluster.js
src/components/Forms/Cluster/Configuration/index.jsx
src/components/Forms/Cluster/Title/index.scss
src/configs/steps/clusters.js

/kind bug
Fixes #
```
```
```docs
```

fix: Disable creating cluster

---

locales/en/nodes.js
locales/es/nodes.js
locales/tc/nodes.js
locales/zh/nodes.js
src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
src/components/Forms/Cluster/EdgeNode/AddNode/index.scss

>
Fixes ##[kubesphere/kubesphere/issues/3602](https://github.com/kubesphere/kubesphere/issues/3602)
```
```
```docs
```

feat: Add checkbox to add default stain

---

src/components/Tables/Base/index.jsx
src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/1714
```
```
```docs
```

fix: Fix authorized user list loading state

---

server/config.yaml

fix 3.1 api doc link

---

src/utils/object.mapper.js

/kind bug
fix bug：Not found error appears when querying CR on the CRD page
Fixes #1723
```
```
```docs
```

Fix issue: Not found error appears when querying CR on the CRD page

---

locales/en/base.js

/kind bug
Fixes #
```
```
```docs
```

chore: Fix delete tip locale

---

src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Modals/Pipelines/PipelineEdit/index.jsx
src/pages/devops/components/Modals/JenkinsEdit/index.jsx
src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
src/stores/devops/pipelines.js
src/stores/devops/scm.js

/kind bug
Fixes #1575
```
```
```docs
```
/area devops

fix: fix the environment variables and bitbucket owner value in pipeline

---

src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/Details/index.jsx
src/components/Modals/Bill/components/SideCard/index.jsx
src/stores/meter/base.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix the start time of the total meter data

---

locales/en/alerting.js
locales/en/base.js
locales/en/devops.js
locales/en/grayrelease.js
locales/en/ingress.js
locales/es/base.js
locales/tc/base.js
locales/zh/base.js
src/components/Forms/Pipelines/ParamsInput/index.jsx

Few UI Updates

---

src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx

/kind bug
Fixes ##1708
```
```
```docs
```

fix: fix the color of progress

---

locales/en/alerting.js
locales/es/alerting.js
locales/tc/alerting.js
locales/zh/alerting.js

The original UI text is outdated. KubeSphere 3.1 has multiple notification channels on the console, not just email.

Update outdated alerting UI

---

locales/en/notification.js
locales/es/notification.js
locales/tc/notification.js
locales/zh/notification.js
src/components/Forms/Notification/MailForm/index.jsx
src/components/Forms/Notification/WeComForm/index.jsx

Minor fix. Recipient is commonly used for notifications.

Recipient UI Text Update

---

src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
src/stores/edgenode.js

chore: add the params of add default taint in url

---

src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/WorkloadSelect.jsx
src/pages/projects/containers/Alerting/Messages/index.jsx

Fixes #https://github.com/kubesphere/console/issues/1734
```
```
```docs
```

fix: Fix custom alerting table properties

---

src/components/Layout/LoginInfo/index.scss
src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
src/utils/alerting.js
src/utils/object.mapper.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix alerting message alerting resource

---

src/pages/devops/containers/Base/Detail/index.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3656](https://github.com/kubesphere/kubesphere/issues/3656)
```
```
```docs
```

fix: Fix the operation with differenrt role operator in pipeline

---

src/components/Forms/ImageBuilder/LanguageSelect/index.jsx
src/components/Forms/ImageBuilder/S2IForm/TemplateSelect/index.jsx

>
/kind bug
Fixes #
```
```
```docs
```

fix: fix the buildImage selected

---

locales/en/base.js
locales/es/base.js
locales/tc/base.js
locales/zh/base.js
server/config.yaml
src/pages/projects/containers/Alerting/Messages/index.jsx
src/pages/projects/containers/Alerting/Policies/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix data mismatch when switch alerting type

---

src/components/Modals/UserSetting/index.jsx

> /kind bug
Fixes #1738 
```
```
```docs
```

fix: user setting modal error

---

locales/en/group.js
locales/es/group.js
locales/tc/group.js
src/pages/workspaces/containers/Groups/GroupTree/index.scss
src/pages/workspaces/containers/Groups/GroupUser/index.jsx

upgrade: upgrade group delete modal tip

---

src/components/Modals/Bill/components/MeterDetailCard/index.scss
src/components/Modals/Bill/constats.js

Fixes #
```
```
```docs
```
/assign @Sherlock113

chore: Unify English fonts and convert plural names into singular

---

locales/en/alerting.js
locales/en/application.js
locales/en/cluster.js
locales/en/role.js
locales/zh/alerting.js
locales/zh/project.js

Chore(locales): Update some UI

---

locales/en/notification.js
locales/es/notification.js
locales/tc/notification.js
locales/zh/notification.js
server/config.yaml
src/components/Forms/Notification/DingTalkForm/index.jsx
src/components/Forms/Notification/MailForm/Item.jsx
src/components/Forms/Notification/SlackForm/Item.jsx
src/components/Forms/Notification/WeComForm/index.jsx

upgrade: add notification receiver quantity limit

---

locales/en/meter.js
src/components/Modals/Bill/components/ConstomPieChart/index.jsx

Update UI in metering and billing. Some UI text is redundant for English thus localized instead of translated directly.

Update metering and billing UI

---

src/stores/meter/base.js

fix: Add the cluster params in opresource

---

src/pages/devops/containers/Credential/detail/index.jsx
src/pages/devops/containers/Credential/index.jsx

Fixes #
```
```
```docs
```
/area devops

chore: move the sync status from vredential list to credential detail

---

src/pages/projects/components/Modals/AppTemplateEdit/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3563
```
```
```docs
```

fix: Fix op app update if not change the yaml template

---

.github/workflows/deploy-backend/kubesphere.tf

It is easier to identify after changing the name of the resource.

minor: rename deploy resource

---

server/controllers/session.js

Signed-off-by: hongming <talonwan@yunify.com>
/kind bug
Fix the wrong username in login confirm page.
Fixes #https://github.com/kubesphere/kubesphere/issues/3506

Fix pre-registration username

---

src/components/Modals/Network/IPPoolWorkspace/index.jsx
src/pages/clusters/containers/Network/IPPools/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3679
```
```
```docs
```

fix: Fix workspace list in ippool workspace assign modal

---

src/pages/clusters/containers/EdgeNodes/Detail/routes.js

Fixes #[#kubesphere/kubesphere/3533](https://github.com/kubesphere/kubesphere/issues/3533)
```
```
```docs
```

chore: Remove the monitor tab in edge node detail

---

src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.scss
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
src/components/Forms/Pipelines/RepoSelect/subForm.jsx
src/components/Modals/CredentialCreate/index.jsx
src/pages/devops/containers/Credential/detail/index.jsx
src/stores/devops/credential.js
src/stores/devops/scm.js

/kind feature
Fixes [#kubesphere/kubesphere/3675](https://github.com/kubesphere/kubesphere/issues/3675)
```
```
```docs
```
/area devops

feat: Add credential in github and bitbucket

---

package.json
src/configs/openpitrix/app.js
src/pages/projects/containers/Applications/CRDApps.jsx
src/pages/projects/containers/Applications/OPApps.jsx
src/pages/workspaces/containers/Repos/Detail/Events/index.jsx
src/stores/openpitrix/application.js
src/utils/index.js
yarn.lock

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3647
#https://github.com/kubesphere/kubesphere/issues/3646
```
```
```docs
```

fix: Fix some op applications issues

---

locales/en/pipeline.js
locales/es/pipeline.js
locales/tc/pipeline.js
locales/zh/base.js
locales/zh/pipeline.js
src/components/Forms/Pipelines/AdvanceSettings/index.jsx
src/components/Forms/Pipelines/BaseInfo/index.jsx
src/components/Forms/Pipelines/RepoSelect/GitForm/index.jsx
src/pages/devops/components/Pipeline/StepModals/input.jsx

Few UI Updated

---

locales/en/cluster.js
locales/es/cluster.js
locales/tc/cluster.js
locales/zh/cluster.js
server/config.yaml
src/components/Layout/Nav/NavItem.jsx
src/components/Layout/Nav/index.scss
src/configs/openpitrix/app.js
src/core/global.js
src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/ProjectSelect.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.scss
src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.jsx
src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.scss
src/stores/openpitrix/application.js
src/stores/terminal.js
src/utils/index.js
src/utils/object.mapper.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3664
```
```
```docs
```

fix: Compatible with old ks versions

---

locales/en/app_repo.js
locales/es/app_repo.js
locales/tc/app_repo.js
locales/zh/app_repo.js
src/components/Base/Indicator/index.scss
src/components/Modals/AppRepoCreate/index.scss
src/components/Modals/AppRepoCreate/url.input.jsx
src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
src/pages/projects/containers/Applications/OPAppDetail/index.jsx
src/pages/workspaces/containers/Repos/index.jsx
src/stores/openpitrix/repo.js

update: Add application status in detail page and repo watch

---

src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/index.scss
src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
src/stores/devops/scm.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix the repo selected is incorrect after search

---

locales/en/meter.js
locales/es/meter.js
locales/tc/meter.js
locales/zh/meter.js
src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/components/LineChart/MonitorTab/index.jsx
src/components/Modals/Bill/components/LineChart/index.jsx
src/components/Modals/Bill/components/LineChart/index.scss
src/components/Modals/Bill/components/SideCard/item.jsx
src/components/Modals/Bill/components/SideCard/item.scss
src/components/Modals/Bill/components/Title/index.scss
src/stores/meter/base.js

>
/kind bug
Fixes ##1750 ##1766 ##1768 ##1773
```
```
```docs
```

fix: Fix some issue about member cluster in metering

---

server/services/session.js
src/components/Modals/KubeCtl/index.jsx
src/core/global.js
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix cluster version check in single cluster mode

---

src/actions/federated.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3652
```
```
```docs
```

fix: Fix fedrated project creation

---

locales/en/application.js
locales/es/application.js
locales/tc/application.js
locales/zh/application.js
src/pages/fedprojects/containers/Applications/index.jsx
src/pages/projects/containers/Applications/Banner.jsx
src/pages/projects/containers/Applications/CRDApps.jsx

chore: Add Composing Apps local

---

src/components/Forms/Pipelines/RepoSelect/subForm.jsx
src/pages/devops/containers/layout.jsx

/kind feature
Fixes #
```
```
```docs
```

feat: Gitlab is not displayed when the current cluster version is 3.0.0

---

server/config.yaml

/kind bug
Fixes #
```
```
```docs
```

fix: Fix custom alerting auth key

---

src/components/Modals/KubeCtl/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix termianl url in single cluster mode

---

src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
src/stores/devops/scm.js

fix: Add empty message in repo form

---

src/pages/clusters/containers/Overview/Dashboard/ClusterInfo/index.jsx
src/utils/object.mapper.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix cluster ks version and metadata.finalizer

---

src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/components/LineChart/index.jsx
src/components/Modals/Bill/components/LineChart/index.scss
src/utils/meter.js

/kind bug
Fixes #
```
```
```docs
```
/assign @wenxin-01 

fix: Fix the price line-chart height and ws have disabled status

---

src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/Details/Cluster/index.scss
src/components/Modals/Bill/components/LineChart/MonitorTab/index.jsx
src/components/Modals/Bill/components/LineChart/MonitorTab/index.scss
src/components/Modals/Bill/components/LineChart/index.jsx
src/utils/monitoring.js

Fixes #
```
```
```docs
```
/assign @wenxin-01 

chore: Modify the decimal point in chart data

---

src/pages/apps/components/Cards/BaseInfo/index.jsx

>
/kind bug
Fixes #[#kubesphere/kubesphere/3720](https://github.com/kubesphere/kubesphere/issues/3720)
```
```
```docs
```

fix: Fix the url of service Provider Website on APP Review Content page

---

src/pages/apps/containers/Categories/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3724](https://github.com/kubesphere/kubesphere/issues/3724)
```
```
```docs
```

fix: Fix selected category doesn't match with the list

---

server/config.yaml

> /kind bug
Fixes [#kubesphere/kubesphere#3730](https://github.com/kubesphere/kubesphere/issues/3730)
```
```
```docs
```

fix: fix storageclass doc link

---

locales/en/alerting.js
locales/en/base.js
locales/en/logging.js
locales/en/service.monitor.js

Update some UI text

---

src/actions/pipeline.js

Fixes #[#kubesphere/kubesphere/3510](https://github.com/kubesphere/kubesphere/issues/3510)
```
```
```docs
```

chore: Remove Update Notice when the pipeline run

---

src/components/Modals/ContianerTerminal/index.jsx
src/components/Terminal/index.jsx

/kind bug
Fixes #[#/kubesphere/kubesphere/3519](https://github.com/kubesphere/kubesphere/issues/3519)
```
```
```docs
```
/assign @zryfish

fix: Fix the pod terminal with different cluster version

---

src/pages/projects/containers/Alerting/Policies/index.jsx

/kind bug
Fixes ##1800
```
```
```docs
```

fix: Fix the create button in empty of alert policies page

---

src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
src/pages/devops/components/Pipeline/StepsSelector/index.jsx
src/pages/devops/components/Pipeline/store.js

fix: Fix the checkbox in kubernetesDeploy

---

locales/en/cluster.js
locales/es/cluster.js
locales/tc/cluster.js
locales/zh/cluster.js
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/DevopsSelect.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/ProjectSelect.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx

Fixes [#kubesphere/kubesphere#3664](https://github.com/kubesphere/kubesphere/issues/3664)
```
```
```docs
```

feat: add cluster upgrade tip to the group

---

locales/en/s2i.js
locales/zh/s2i.js
server/config.yaml

Fix https://github.com/kubesphere/kubesphere/issues/3762

fix a s2i link

---

server/config.yaml

> /kind bug
Fixes [#kubesphere/kubesphere#3756](https://github.com/kubesphere/kubesphere/issues/3756)
```
```
```docs
```

fix: project custom alert page error in old version

---

locales/es/group.js
locales/tc/group.js
locales/zh/group.js
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx

Update UI text on the Department Management page.

---

src/components/Inputs/ProjectSelect/index.jsx
src/components/Modals/Network/Policies/index.jsx
src/components/Modals/Network/Policies/index.scss

/kind bug
Fixes #[#kubesphere/kubesphere/3520](https://github.com/kubesphere/kubesphere/issues/3520)
```
```
```docs
```
/assign @duanjiong

fix: Disable multiple cluster projects when creating network policy

---

src/pages/projects/components/Modals/ExpandVolume/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3752](https://github.com/kubesphere/kubesphere/issues/3752)
```
```
```docs
```

fix: Add input in expand volume modal

---

src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/components/LineChart/index.jsx
src/components/Modals/Bill/components/MeterDetailCard/index.jsx
src/components/Modals/Bill/components/Tables/index.jsx
src/stores/meter/base.js

/kind bug
Fixes [#kubesphere/kubesphere/3747](https://github.com/kubesphere/kubesphere/issues/3747)
```
```
```docs
```

fix: Fix the price data with less 0

---

src/components/Base/Indicator/index.jsx
src/components/Base/Indicator/index.scss
src/components/Base/Status/index.jsx

/kind bug
Fixes ##1815
```
```
```docs
```

fix: Add bouncing in some type of status

---

OWNERS

chore: Add reviewers

---

src/stores/meter/base.js
src/stores/meter/cluster.js

/kind bug
Fixes #
```
```
```docs
```
/assign @wenxin-01

chore: Fix the bug that the status code is 503 in resource list API

---

src/components/Cards/Pods/index.jsx
src/stores/monitoring/base.js

/kind bug
Fixes ##1816
```
```
```docs
```
/assign @junotx

fix: Replace namespaced_resources_filter to resources_filter

---

src/components/Modals/ContianerTerminal/index.jsx

/kind bug
Fixes #
```
```
```docs
```
/assign @RolandMa1986

fix: Fix the pod name is Incorrect in terminal modal

---

src/components/Base/Indicator/index.jsx
src/components/Base/Indicator/index.scss
src/components/Base/Status/index.jsx
src/pages/projects/containers/Applications/CRDApps.jsx
src/pages/projects/containers/Applications/OPApps.jsx
src/pages/workspaces/containers/Repos/index.jsx

/kind bug
Fixes #1815 #1824 
```
```
```docs
```

fix: Fix application template and repo status

---

src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/components/Crumb/index.scss
src/components/Modals/Bill/components/SideCard/index.jsx
src/components/Modals/Bill/components/SideCard/index.scss
src/components/Modals/Bill/components/SideCard/item.jsx
src/components/Modals/Bill/components/SideCard/item.scss
src/utils/meter.js

/kind bug
Fixes #
```
```
```docs
```
/assign @zryfish

fix: Fix metering of single cluster in disabled status

---

locales/en/role.js
locales/en/s2i.js
locales/es/role.js
locales/zh/role.js
locales/zh/s2i.js

Update image builder UI

---

locales/en/cluster.js
locales/es/cluster.js
locales/tc/cluster.js
locales/zh/cluster.js

upgrade: Update user group workspace role description

---

locales/en/alerting.js
locales/en/cluster.js
locales/tc/alerting.js
locales/zh/alerting.js

Fix https://github.com/kubesphere/console/issues/1837

fix alerting desc

---

locales/en/s2i.js
locales/es/s2i.js
locales/tc/s2i.js
locales/zh/s2i.js
src/components/Inputs/S2iEnviroment/index.jsx

Chore(locales): Update few S2I-related UI

---

src/components/Forms/AlertingPolicy/AlertingRule/QueryMonitor/index.jsx
src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/Monitoring.jsx

> /kind bug
Fixes #1829 
```
```
```docs
```

fix: alerting rule and policies query api error

---

server/controllers/session.js
server/services/session.js
src/core/containers/Login/index.jsx
src/stores/root.js

/kind feature
Fixes #[#kubesphere/kubesphere/3775](https://github.com/kubesphere/kubesphere/issues/3775)
```
```
```docs
```

feat: support OpenID Connect RP-Initiated Logout

---

locales/zh/role.js
locales/zh/s2i.js

update image builder cn UI

---

src/components/Forms/Pipelines/AdvanceSettings/index.jsx

>
/kind bug
Fixes #[#kubesphere/kubesphere/3807](https://github.com/kubesphere/kubesphere/issues/3807)
```
```
```docs
```

fix: Fix the enable_discarder checkbox

---

src/pages/devops/components/Pipeline/Sider/index.jsx
src/pages/devops/components/Pipeline/StepsEditor/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3808](https://github.com/kubesphere/kubesphere/issues/3808)
```
```
```docs
```

fix: Fix the yaml editor in pipeline step

---

src/pages/console/containers/Dashboard/index.jsx

/kind bug
Fixes ##1797
```
```
```docs
```

fix: Fix the role match the  users-manager

---

src/components/Modals/Bill/components/Crumb/index.scss
src/components/Modals/Bill/components/SideCard/index.jsx
src/components/Modals/Bill/components/SideCard/index.scss
src/components/Modals/Bill/components/SideCard/item.jsx
src/components/Modals/Bill/components/SideCard/item.scss

/kind bug
Fixes #[#kubesphere/kubesphere/3811](https://github.com/kubesphere/kubesphere/issues/3811)
```
```
```docs
```
/assign @yunkunrao

fix: Fix the export resource UI in bill

---

locales/en/login.js
locales/en/user.js
locales/es/login.js
locales/es/user.js
locales/tc/login.js
locales/tc/user.js
locales/zh/login.js
locales/zh/user.js
src/components/Modals/UserCreate/index.jsx
src/core/containers/LoginConfirm/index.jsx

Fix third party login console UI

---

server/controllers/session.js

/kind bug
Fixes #
```
```
```docs
```
/cc @wansir 

fix: Remove post_logout_redirect_uri

---

src/pages/apps/components/Modals/AppDeploy/index.jsx
src/pages/apps/containers/AppDeploy/index.jsx

/kind bug
Fix the problem that the application name contains capital letters and spaces when the deployment page is incorrect

fix: deploy app failed

---

docs/development-workflow.md

Signed-off-by: PeiHongbing1223 <peihongbing1223@gmail.com>
>
> /kind bug
> /kind design
Fixes #
```
```
```docs
```

Development-workflow.md content link error fix.

---

.github/workflows/main.yaml

Signed-off-by: Zhengyi Lai <zheng1@yunify.com>
/kind cleanup

Update github actions

---

.github/workflows/nightly-builds.yml

Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>
>
> /kind bug
> /kind design
Fixes #
```
```
```docs
```

send notfication only when failed

---

server/services/session.js

>
/kind bug
Fixes ##1858
```
```
```docs
```

fix: Fix the last login time of user in dashboard

---

locales/es/role.js
locales/tc/role.js
locales/zh/role.js

Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>
/assign @Sherlock113 @harrisonliu5

Fix bug in ROLE_USER_TIP.

---

src/pages/apps/components/Forms/VersionEdit/index.jsx
src/utils/constants.js

>
/kind bug
Fixes ##1832
```
```
```docs
```
/assign @junotx 

fix: Fix the app template version

---

src/components/Forms/Notification/MailForm/index.jsx
src/utils/constants.js

> /kind bug
Fixes ##1795 
```
```
```docs
```

fix: smtp server port

---

src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx

/kind bug
Fixes ##[kubesphere/kubesphere/3828](https://github.com/kubesphere/kubesphere/issues/3828)
```
```
```docs
```

fix: Fix the time of alarm message displayed

---

src/pages/projects/containers/Applications/CRDAppDetail/routes.js

/kind bug
Fixes ##1782
```
```
```docs
```

fix: Remove the logging of tracing in clusterModule

---

src/actions/configmap.js
src/actions/resource.edit.js
src/actions/router.js
src/actions/service.js
src/actions/serviceaccount.js
src/components/Modals/EditBasicInfo/index.jsx
src/components/Modals/EditServiceAccount/index.jsx
src/components/Modals/EditYaml/index.jsx
src/components/Modals/ModifyServiceAccountRole/index.jsx
src/pages/clusters/containers/ServiceAccounts/index.jsx
src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
src/pages/projects/components/Modals/RouteAnnotationsEdit/index.jsx
src/pages/projects/components/Modals/RouteRulesEdit/index.jsx
src/pages/projects/components/Modals/ServiceGatewaySetting/index.jsx
src/pages/projects/components/Modals/ServiceSetting/index.jsx

Fixes ##793
```
```
```docs
```

fix: deselect the svg after performing an action on the svg like editing

---

src/pages/devops/components/Pipeline/StepsEditor/index.jsx

>
/kind bug
Fixes ##1810
```
```
```docs
```

fix: Fix the agent label is reset when the drawer is blur

---

src/pages/access/containers/Workspaces/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3764](https://github.com/kubesphere/kubesphere/issues/3764)
```
```
```docs
```

fix: Modify default description infomation on Workspaces page

---

src/pages/projects/containers/ImageBuilder/Detail/index.jsx

/kind bug
rename the button 'Rerun' to 'Run' on the b2i page #1543
Fixes  #1543
**Special notes for reviewers:**
```
```
**Additional documentation, usage docs, etc.:**
```
```

fix: rename the button 'Rerun' to 'Run' on the b2i page #1543

---

locales/en/meter.js
locales/es/meter.js
locales/tc/meter.js
locales/zh/meter.js
src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/Bill/components/Crumb/index.scss
src/components/Modals/Bill/components/SideCard/item.jsx
src/components/Modals/Bill/components/SideCard/item.scss
src/components/Modals/Bill/components/Title/index.jsx
src/stores/meter/base.js

/kind bug
Fixes #[#kubesphere/kubesphere/3822](https://github.com/kubesphere/kubesphere/issues/3822) ##1827 ##1862
```
```
```docs
```

fix: UI adjustment for Metering and Billing

---

src/pages/apps/components/Modals/AppEdit/index.jsx

/kind bug
Fixes ##1830
```
```
https://user-images.githubusercontent.com/63338728/118584250-2a3ecb80-b7c9-11eb-8fc0-3c62c6712e28.mov
```docs
```

fix: Screenshots wolud be deleted only if the edit is saved

---

locales/en/role.js
locales/es/role.js
locales/tc/role.js
locales/zh/role.js
src/components/Modals/RoleDelete/index.jsx
src/stores/group.js

> /kind bug
Fixes ##1876 
```
```
```docs
```

fix: Deleted workspace roles can not be used in Department Management

---

locales/en/user.js
locales/es/user.js
locales/tc/user.js
locales/zh/user.js
src/components/Modals/UserCreate/index.jsx
src/core/containers/LoginConfirm/index.jsx
src/utils/constants.js

/kind bug
Fixes #[#kubesphere/kubesphere/3875](https://github.com/kubesphere/kubesphere/issues/3875)
```
```
```docs
```

fix: Modify the naming rules of account names

---

src/pages/devops/containers/Credential/detail/index.jsx
src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
src/pages/devops/containers/Pipelines/PipelinesList/index.jsx

>
/kind bug
Fixes #[#kubesphere/kubesphere/3851](https://github.com/kubesphere/kubesphere/issues/3851)
```
```
```docs
```
/area devops

fix: Update the sync status of credential

---

src/components/Forms/Pipelines/ActionsInput/index.jsx

/kind bug
Fixes ##1898
```
```
```docs
```

fix: Trusted User in multi-branch pipeline

---

src/components/Modals/EditBasicInfo/index.jsx
src/components/Modals/EditYaml/index.jsx

/kind bug
Fixes ##1910
```
```
https://user-images.githubusercontent.com/63338728/118784804-e62ff180-b8c2-11eb-92e0-0ae174bd706f.mov
```docs
```

fix: Modify the EditYaml module and EditBasicInfo module

---

src/components/Forms/Pipelines/ParamsFormModal/index.jsx

/kind bug
Fixes ##1877
```
```
```docs
```

fix: Fix the multi-branch Pipeline run API is incorrect

---

.gitignore
.gitpod.Dockerfile
.gitpod.yml
README.md
scripts/webpack.dev.js

If you want to try this PR, please visit [here](https://gitpod.io/#https://github.com/linuxsuren/console/tree/gitpod). But please remember that this link only works before this PR gets merged. You can use the [master branch](https://github.com/kubesphere/console) once the PR gets merged.
/kind cleanup
Make it be easier to run the front-end for the newcomers.
None.
None.
None.

Add gitpod as a tool to browser code lines

---

src/actions/configmap.js
src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
src/pages/projects/components/Modals/ServiceSetting/index.jsx

/kind bug
Fixes ##1903
```
```
https://user-images.githubusercontent.com/63338728/118946032-9b78ad00-b988-11eb-83a8-1020660c4299.mov
```docs
```

fix: Remove the console error

---

src/components/Forms/ImageBuilder/S2IForm/TemplateSelect/index.jsx

Signed-off-by: liuboaibc <kukudehero@gmail.com>
>
> /kind bug
Fixes #1908
```
```
```docs
```

fix builderImage default value

---

src/components/Base/Cascader/Item.jsx
src/components/Base/Cascader/index.jsx

/kind bug
Fixes ##1865
```
```
https://user-images.githubusercontent.com/63338728/118623121-8241f600-b7fa-11eb-99f5-bed86947cc72.mov
```docs
```

fix: Modify the display height and position of the cascader module

---

src/components/Forms/Pipelines/BaseInfo/index.jsx
src/components/Forms/Pipelines/RepoSelect/index.scss

>
Fixes ##1781 
```
```
```docs
```
/assign @xuliwenwenwen 
/area devops

chore: Fix the UI of code repository

---

src/components/Forms/ImageBuilder/RerunForm/index.jsx

/kind bug
Fixes ##1919
On #1543 suggest that change 'Rerun' for 'Run'.
```docs
```

fix: Rename the 'Rerun' to 'Run'

---

locales/en/workspace.js
locales/es/workspace.js
locales/tc/workspace.js
locales/zh/workspace.js
src/actions/workspace.js
src/pages/access/containers/Workspaces/index.jsx
src/pages/workspaces/components/Modals/WorkspaceDelete/index.jsx
src/pages/workspaces/components/Modals/WorkspaceDelete/index.scss
src/pages/workspaces/containers/BaseInfo/index.jsx
src/stores/workspace.js

Fixes [#Kubesphere/Kubesphere#3192](https://github.com/kubesphere/kubesphere/issues/3192)
```
```
```docs
```

feat: delete related resources when deleting workspace

---

src/pages/devops/components/Pipeline/store.js

>
/kind bug
Fixes #1924
```
```
```docs
```

fix: Fix the node label list of member cluster

---

src/pages/devops/components/Pipeline/StepsEditor/index.jsx

Fixes #1930
```
```
```docs
```

chore: Remove the description of drag in the pipeline

---

src/pages/devops/containers/Pipelines/PipelinesList/index.jsx

/kind bug
Fixes #1928
```
```
```docs
```

fix: Fix the pipeline detail page could not use the browser go back button

---

src/pages/workspaces/containers/Members/Detail/DevOps/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3934](https://github.com/kubesphere/kubesphere/issues/3934)
```
```
```docs
```

fix: Fix the page of member in workspace is not displayed correctly after refreshing

---

src/components/Inputs/StringInput/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere#3489](https://github.com/kubesphere/kubesphere/issues/3489)
```
```
```docs
```

fix: Fix command input box validation failed

---

src/components/Inputs/AddonsInput/index.scss

/kind bug
Fixes #[#kubusphere/kubusphere/3488](https://github.com/kubesphere/kubesphere/issues/3488)
```
```
https://user-images.githubusercontent.com/63338728/121324753-9aadb800-c943-11eb-9e5a-e37ee4c90726.mov
```docs
```

fix: Modify the style of Select

---

locales/en/role.js
locales/es/role.js
locales/tc/role.js
locales/zh/role.js

/kind bug
Fixes [kubesphere/kubesphere#3754
](https://github.com/kubesphere/kubesphere/issues/3754)
```
```
```docs
```

fix: Fix workspace settings name duplicate when creating custom workspace roles

---

src/pages/devops/components/Pipeline/Card/detail.jsx
src/pages/devops/components/Pipeline/StepModals/script.jsx
src/pages/devops/components/Pipeline/StepModals/shell.jsx
src/pages/devops/components/Pipeline/StepsEditor/StepContainer.jsx
src/pages/devops/components/Pipeline/StepsEditor/index.jsx
src/pages/devops/components/Pipeline/store.js

/kind bug
Fixes #[kubesphere/kubesphere/3950](#https://github.com/kubesphere/kubesphere/issues/3950) #[kubesphere/kubesphere/3949](#https://github.com/kubesphere/kubesphere/issues/3949)
```
```
```docs
```
/area devops

fix: Fix the sh and lable is not correct in pipeline editor

---

src/core/index.js
src/utils/index.js
src/utils/request.js

>
/kind feature
Fixes #[#kubesphere/kubesphere/3935](https://github.com/kubesphere/kubesphere/issues/3935)
```
```
```docs
```
/cc @wansir

feat: Determine whether to log out according to the 401 and error messages on the member cluster page

---

src/actions/project.js

/kind bug
Fixes [##kubesphere/kubesphere#3819](https://github.com/kubesphere/kubesphere/issues/3819)
```
```
```docs
```

fix: Fix failed to assign an administrator to a project

---

src/components/Modals/ContianerTerminal/index.jsx
src/components/Modals/KubeCtl/index.jsx
src/stores/terminal.js

/kind bug
Fixes #[#kubesphere/kubesphere/3905](https://github.com/kubesphere/kubesphere/issues/3905)
```
```
```docs
```

fix: Fix unable connect to container terminal due to forbidden error

---

locales/en/role.js
locales/es/role.js
locales/tc/role.js
locales/zh/role.js
src/actions/configmap.js
src/components/Modals/EditBasicInfo/index.jsx
src/components/Modals/EditYaml/index.jsx
src/components/Modals/RoleDelete/index.jsx
src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
src/pages/projects/components/Modals/ServiceSetting/index.jsx
src/stores/group.js

>
/kind bug
Fixes #
```
```
```docs
```

[release-3.1] fix: Deleted workspace roles can not be used in Department Management

---

src/pages/workspaces/components/Modals/QuotaEdit/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix workspace quota api path error

---

src/components/Base/Modal/modal.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/1308](https://github.com/kubesphere/kubesphere/issues/1308)
```
```
```docs
```

fix: Cancel closing modal due to clicking mask

---

src/components/Cards/Containers/EnvVariables/index.jsx
src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/1342](https://github.com/kubesphere/kubesphere/issues/1342)
```
```
```docs
```
/assign @zryfish

fix: Hide the password value in env

---

src/pages/apps/components/Modals/AppCreate/index.jsx

/kind bug
Fixes #[#kubusphere/kubusphere/3531](https://github.com/kubesphere/kubesphere/issues/3531)
```
```
```docs
```

fix: Modify the link of AppCreate modal

---

server/libs/utils.js

/kind bug
Fixes #[#kubesphere/kubesphere/3975](https://github.com/kubesphere/kubesphere/issues/3975)
```
```
```docs
```

fix: Fix the problem of redirection when logging out caused by apps in the route

---

locales/en/pipeline.js
locales/es/pipeline.js
locales/tc/pipeline.js
locales/zh/pipeline.js
src/components/Forms/Pipelines/AdvanceSettings/index.jsx
src/components/Modals/Pipelines/ScanRepositoryLogs/index.jsx
src/pages/devops/components/Pipeline/StepModals/environment.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
src/utils/constants.js

/kind feature
Fixes #1878
```
```
```docs
```
/area devops

feat: Add scan repo trigger in GitLab

---

src/components/Cards/ContainerLog/index.jsx
src/components/Modals/ContainerLog/index.jsx

/kind bug
Fixes ##1972
```
```
```docs
```
/assign @zryfish

fix: Remove the previous parameter of log

---

src/components/Inputs/EnvironmentInput/Item.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3483](https://github.com/kubesphere/kubesphere/issues/3483)
```
```
```docs
```

fix: Add placeholder for 'Select resource'

---

OWNERS

To add fuchunlan to the list of reviewers
Fixes #
```
```
```docs
```

fix: Add fuchunlan to the list of reviewers

---

src/pages/projects/components/Modals/ServiceCreate/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Add cancel button in create service modal

---

src/components/Modals/Bill/Home/index.scss
src/components/Modals/Bill/components/Crumb/index.scss

/kind feature
Fixes ##1818
```
```
```docs
```

fix: Change the color of the button on the Metering and Billing page.

---

src/components/Modals/QuotaEdit/Quotas/Item.jsx
src/components/Modals/QuotaEdit/Quotas/index.jsx

/kind feature
Fixes #[#kubesphere/kubesphere/3854](https://github.com/kubesphere/kubesphere/issues/3854)
```docs
Now there is a question that you can fill in duplicates, but all duplicates will be deleted when deleting
```

feat: Able to create resource quota for extended resources

---

src/pages/settings/containers/Notification/Mail/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix receiver mail sync error

---

src/pages/clusters/containers/Base/Detail/index.jsx
src/scss/custom.scss

/kind bug
Fixes #[#kubesphere/kubesphere/3649](https://github.com/kubesphere/kubesphere/issues/3649)
https://user-images.githubusercontent.com/63338728/122542509-5914bf80-d05d-11eb-9c13-8beeabd479ed.mov
```
```
```docs
```

fix: Show action button on alertPolicyDetail. 

---

OWNERS

chore: Add fuchunlan reviewers

---

package.json
yarn.lock

update: Update the kube-design version

---

src/pages/apps/components/Modals/AppCreate/index.jsx

/kind bug
Fixes ##2040
```
```
```docs
```

fix: Add the cancel button in app create modal

---

src/pages/apps/components/Modals/AppCreate/index.jsx
src/pages/apps/components/Modals/HelmUpload/index.jsx

/kind bug
Change the link from `kubesphere.io` to `v3-1.docs.kubesphere.io` ,and consistent with other pages
Fixes #
```
```
```docs
```

fix: Change the guide link in AppCreate and HelmUpload

---

src/components/Cards/Monitoring/Controller/TimeSelector/index.jsx
src/pages/fedprojects/containers/Applications/Detail/AppComponents/Components/ServiceCard/index.jsx
src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
src/pages/fedprojects/containers/Applications/Detail/Tracing/index.scss
src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.jsx
src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.scss
src/pages/projects/containers/Services/Detail/index.jsx
src/stores/application/crd.js

/kind bug
Fixes #
```
```
```docs
```

fix: Change the method of time select in trace

---

src/components/Inputs/ArrayInput/index.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/DevopsSelect.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/ProjectSelect.jsx
src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3307](https://github.com/kubesphere/kubesphere/issues/3307)
```
```
```docs
```

fix: Modify the red prompt box on Maintain Organization Modal.

---

OWNERS

Add fuchunlan reviewer in release-3.1 branch
Fixes #
```
```
```docs
```

fix: Add fuchunlan reviewer

---

src/components/Modals/Bill/Details/Cluster/index.jsx

/kind bug
Fixes #
```
```
```docs
```
/assign @xyz-li

fix: Fix Bill page view error caused by the dependence of workspace on unloaded clusters

---

src/components/Modals/ProjectSelect/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere#4016](https://github.com/kubesphere/kubesphere/issues/4016)
```
```
```docs
```

fix: Multi-cluster projects appear in the project list of a cluster

---

src/utils/meter.js

/kind bug
Fixes #[#kubesphere/kubesphere/4018](https://github.com/kubesphere/kubesphere/issues/4018)
```
```
```docs
```

fix: Add fedproject in bill

---

src/pages/projects/containers/Services/Detail/index.jsx

Signed-off-by: liuboaibc <kukudehero@gmail.com>
/kind bug
Fixes #2055
```
```
```docs
```

fix:remove edit extranet access button in stateful service detail page

---

server/config.yaml

/kind bug
Fixes #[#kubesphere/kubesphere/3839](https://github.com/kubesphere/kubesphere/issues/3839)
```
```
```docs
```

fix: Fix the permission of workspace quota

---

src/pages/projects/components/Modals/DeployApp/index.jsx

/kind bug
Fixes ##2040
```
```
```docs
```

fix: Add close button in create app template modal

---

src/utils/index.js

/kind bug
Fixes #[#kubesphere/kubesphere/4038](https://github.com/kubesphere/kubesphere/issues/4038)
```
```
```docs
```

fix: Fix auto logout when the clusterRole is not member

---

src/utils/meter.js

/kind bug
Fixes ##1862
```
```
```docs
```
/assign @fuchunlan

fix: Fix get cluster list in bill have no cluster view permission

---

src/components/Forms/Workload/ClusterDiffSettings/EditForm/index.jsx

/kind bug
Fixes ##2092
```
```
```docs
```

[release-3.1]fix: Fix the component click bubble problem

---

src/components/Forms/Pipelines/RepoSelect/subForm.jsx

/kind bug
Fixes ##2094
```
```
```docs
```

fix: Fix the error caused by judgment conditions of cluster version in gitlab

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx

/kind bug
Fixes ##2092
```
```
```docs
fix the Resource requests should not be greater than resource limits
```
/assign @liuboaibc

fix: Fix add validator of limit resource in container image

---

src/actions/project.js

/kind bug
Fixes ##2099
```
```
```docs
```
/assign @liuboaibc

fix: Fix the project quota can not submit

---

src/actions/resource.delete.js

/kind bug
Fixes #
```
```
```docs
```

fix: Fix error of deleting multiple resources in cluster

---

Makefile

Signed-off-by: yuswift <yuswift2018@gmail.com>
/kind feature
support setting tag env in Makefile
```release-note
Support setting TAG env in Makefile
```

support setting tag env in Makefile

---

README.md

documentation
Add documentation to help solve the problem of installing packages on mac of M1 chip
Fixes #
```
```
```release-note
```
```docs
```

docs: compatible with the Mac of M1 chip

---

locales/en/workload.js
locales/es/workload.js
locales/tc/workload.js
locales/zh/workload.js
src/components/Forms/Workload/BaseInfo/index.jsx

/kind bug
Fixes ##2105
```
```
```release-note
Control cannot select a multi-cluster project as input
```
```docs
```
https://user-images.githubusercontent.com/63338728/126759650-54d8c7f1-f9e8-490a-b30d-c58c7ed5f39a.mov

fix: Fix multi-cluster projects should not be able to select on BaseInfo step

---

src/pages/projects/containers/CronJobs/Detail/JobRecords/index.jsx

/kind bug
Fixes ##2106
```
```
no warning
```docs
```

fix: fix CronJobs rerun request url

---

src/components/Forms/Workload/BaseInfo/index.jsx
yarn.lock

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: Fix the project can not be selected in cluster

---

src/actions/project.js

/kind bug
Fixes ##2104
```
```
```release-note
Fix the bug that the value of quota changes to 0 when it is infinity 
```
https://user-images.githubusercontent.com/63338728/126584259-c7583388-438c-4541-ad28-3f5d1eadaa77.mov
```docs
```

fix: Fix the value of quota when it's equal to infinity

---

locales/tc/workspace.js
locales/zh/workspace.js

/kind bug
To fix the  Chinese translation of workspace members
Fixes ##1657
```release-note
None
```
```
```
```docs
```

fix: Fix the translation for workspace members

---

src/pages/fedprojects/containers/Overview/ResourceUsage/index.jsx

/kind bug
Fixes ##2140
```
```
```release-note
```

fix: Remove the pod count in fedproject overview

---

src/stores/devops/run.js

Signed-off-by: Ryan Wang <i@ryanc.cc>
/kind bug
Show the full changeset of a pipeline run.
Fixes https://github.com/kubesphere/ks-devops/issues/108
```
```
```release-note
Fix the changeset of a Pipeline run incomplete
```
```docs
```

fix: Didn't show the full changeset of a pipeline run.

---

src/pages/projects/components/Cards/Replica/Status/NumberControl.jsx
src/pages/projects/components/Cards/Replica/Status/index.scss

/kind feature
Fixes ##2135 
```docs
```

feat: The number of replicas button is change to "+" and "-"

---

src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx

/kind bug
Fixes #[#kubesphere/kubesphere#3820](https://github.com/kubesphere/kubesphere/issues/3820)
```release-note
```
```docs
```

fix: The name of devops project is wrong in branch detail page

---

src/components/Cards/Pods/Item.jsx
src/components/Cards/Pods/index.scss
src/utils/object.mapper.js

/kind feature
Fixes ##2116 
```release-note
```
```docs
```

feat: Support to display multiple ip's of pod

---

src/utils/object.mapper.js

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: Fix networksStatus error in pod

---

locales/en/base.js
locales/en/workload.js
locales/es/base.js
locales/es/workload.js
locales/tc/base.js
locales/tc/workload.js
locales/zh/base.js
locales/zh/workload.js
src/components/Cards/Pods/Item.jsx
src/pages/clusters/containers/Workload/Pods/index.jsx
src/pages/projects/containers/Pods/Detail/index.jsx
src/pages/projects/containers/Pods/index.jsx

Update UI text on the Pods page under Cluster Management.

Update Pods Page

---

locales/en/project.js
locales/es/project.js
locales/tc/project.js
locales/zh/project.js
src/actions/federated.js
src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
src/pages/fedprojects/App.jsx
src/pages/fedprojects/containers/BaseInfo/ProjectInfo/index.jsx
src/pages/fedprojects/containers/BaseInfo/index.jsx
src/pages/workspaces/components/Modals/FedProjectAddCluster/index.jsx
src/pages/workspaces/components/Modals/FedProjectAddCluster/index.scss
src/pages/workspaces/containers/FedProjects/index.jsx

/kind feature
Fixes ##https://github.com/kubesphere/kubesphere/issues/3246
/assign @yuswift

feat: The fedProject add the clusters feature

---

locales/en/app_store.js
locales/es/app_store.js
locales/tc/app_store.js
locales/zh/app_store.js
src/pages/apps/components/AppInfo/index.jsx
src/pages/apps/components/AppInfo/index.scss
src/pages/apps/containers/AppDetail/index.jsx

/kind feature
Fixes ##2162 
```release-note
feat: Disclaimer at app store(#2162 )
```
```docs
```

feat: Disclaimer at app store

---

src/pages/fedprojects/components/ServiceSetting/index.jsx
src/pages/projects/components/Modals/ServiceSetting/Form.jsx
src/pages/projects/components/Modals/ServiceSetting/index.jsx
src/utils/constants.js

/kind bug
Fixes ##2168 
```release-note
fix: Fix access type error on the edit service page. (#2171)
```
```docs
```

fix: Fix access type error on the edit service page

---

Makefile

/kind cleanup
Use `latest` as tag name when the branch name is master.
None.
See the test result:
```
➜  console git:(master-to-latest) git cm
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.
➜  console git:(master) git rev-parse --abbrev-ref HEAD | sed -e 's/\//-/g' | sed 's/master/latest/g'
latest
```
```release-note
None
```
```docs
None.
```

Replace the tag name to latest if branch name is master

---

src/utils/constants.js

/kind bug
Fixes ##2168
```
```
```release-note
fix: Fix access type error on the edit service page. (#2168 )
```
```docs
```

update: Update service types value

---

src/components/Modals/QuotaEdit/Quotas/Item.jsx
src/components/Modals/QuotaEdit/Quotas/index.jsx
src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.jsx
src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.scss
src/pages/projects/containers/BaseInfo/ResourceQuota/index.jsx

/kind bug
Fixes #
```
```
```docs
```

fix: Fix the repeat key in quota editor modal

---

locales/en/workload.js
locales/es/workload.js
locales/zh/workload.js
src/actions/workload.js
src/components/Forms/Workload/ContainerSettings/Affinity/index.jsx

Signed-off-by: qinyueshang <yue_hong_y@163.com>
/kind bug
Fixes ##1604
```release-note
Fix Custom pod replicas deployment. (#1604, @qinyueshang)
```
1.  Original design
2. Modified design

fix: Custom pod replicas deployment

---

locales/en/workload.js
locales/es/workload.js
locales/tc/workload.js
locales/zh/workload.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/components/Inputs/ResourceLimit/index.jsx
src/components/Inputs/ResourceLimit/index.scss
src/components/Modals/QuotaEdit/index.jsx

/kind bug
Fixes ##1600
```
```
https://user-images.githubusercontent.com/33231138/129540936-553f9ac9-150e-448b-8e60-720d49f79223.mov
```release-note
NONE
```
```docs
```

fix: Project Quota or Container Quota greater than Workspace Quota

---

src/actions/workload.js
src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx

/kind feature
set fixed replicas as default mode in workload create form.
Fixes #
```
```
https://user-images.githubusercontent.com/33231138/131436414-e2119826-6912-41e6-8c87-f953a9c21f0b.mov
```release-note
NONE
```
```docs
```

fix: set fixed replicas mode as default mode in workload create form

---

server/controllers/view.js

/kind bug
Fixes #
```
```
```release-note
fix the referer URL that it is have '&'
```
```docs
```

fix: Fix the referer url

---

src/pages/fedprojects/containers/Services/index.jsx

kind feature
Fixes ##https://github.com/kubesphere/kubesphere/issues/2658
```release-note
fix: The fedProject service supports the sort and edit service. (https://github.com/kubesphere/kubesphere/issues/2658, @harrisonliu5 )
```

feat: The fedProject service support the sort and edit service

---

src/actions/storageclass.js
src/components/Modals/VolumeFunctionManage/index.jsx
src/pages/projects/containers/Volumes/Detail/index.jsx

/kind bug
the code in the previous pr(#2199) will not be effective.
Fixes #
```
```
```release-note
none
```
```docs
```

fix: Code optimization about pr #2199

---

src/actions/resource.edit.js
src/components/Modals/Create/index.jsx
src/components/Modals/EditYaml/index.jsx
src/stores/federated.js

/kind feature
Fixes #
https://user-images.githubusercontent.com/33231138/130913788-005fa4b5-1df4-46a9-be28-7edf582344d7.mov
```release-note
none
```
```docs
```

feature: support edit schedule template

---

locales/en/storage.js
locales/es/storage.js
locales/tc/storage.js
locales/zh/storage.js
src/actions/volume.js
src/pages/projects/components/Modals/ResourceSnapshot/index.jsx
src/pages/projects/containers/Volumes/Detail/index.jsx
src/stores/volume.js

/kind feature
Fixes ##2182
```release-note
support multiple snapshotclass. user can choose the snapshot type when create snapshot.
```

feat: support multiple snapshotclass when taking snapshot

---

.github/workflows/main.yaml

/kind cleanup
Change workflow build image tag to branch name
Fixes #
```
```
```release-note
None
```
```docs
```

change image tag to match branch name

---

src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
src/pages/devops/containers/Pipelines/Detail/Branch/index.scss
src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
src/pages/devops/containers/Pipelines/Detail/PullRequest/index.scss

Fixes ##https://github.com/kubesphere/ks-devops/issues/125
```
```
```release-note
Fix the status of the branches in the pipeline
```
```docs
```
/area devops

fix: Fix the status of the branches in the pipeline

---

src/actions/volume.js
src/pages/projects/containers/Volumes/Detail/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Code optimization about pr #2218

---

locales/en/storage.js
locales/es/storage.js
locales/tc/storage.js
locales/zh/storage.js
src/components/Forms/StorageClass/StorageClassSettings/index.jsx
src/utils/form.templates.js

/kind feature
Fixes ##2184
```release-note
support choose volume binding mode when create storageclass
```
```docs
```

feat: support choose volume binding mode when create storageclass

---

src/components/Base/Switch/index.scss
src/pages/fedprojects/containers/Routes/index.jsx

/kind feature
Fixes ##https://github.com/kubesphere/kubesphere/issues/2660
```release-note
feat: The fedProject router supports the sort. edit rules and edit annotation. (#https://github.com/kubesphere/kubesphere/issues/2660, @harrisonliu5 )
```

feat: The fedProject router support the sort, edit rules and edit annotation

---

src/utils/constants.js

/kind bug
Fixes ##2235
```release-note
NONE
```

Fix: Can not get snapshot events in snapshot detail page

---

src/pages/fedprojects/containers/Volumes/Detail/VolumeMounts/PodsCard/index.jsx

/kind bug
Fixes ##2175
```release-note
NONE
```
```docs
```

fix: Close jump function of clicking pod in PVC detail page of multi-cluster

---

src/pages/clusters/containers/Storage/PV/detail/index.jsx
src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
src/pages/clusters/containers/Storage/Volumes/index.jsx
src/pages/clusters/containers/Storage/Volumes/routes.js
src/pages/clusters/routes/index.js

/kind bug
Fixes #
```release-note
NONE
```

fix: Refactor volume manage routes

---

src/actions/secret.js
src/components/Forms/Secret/SecretSettings/index.jsx
src/pages/projects/components/Modals/SecretEdit/index.jsx

/kind bug
Fixes ##2213
```release-note
NONE
```

fix: Disable the drapdown of type during editing secret

---

locales/en/terminal.js
locales/es/terminal.js
locales/tc/terminal.js
locales/zh/terminal.js
src/components/KubeTools/index.jsx
src/components/Modals/KubeConfig/index.jsx

/kind feature
Fixes ##https://github.com/kubesphere/kubesphere/issues/4160
```
```
```release-note
NONE
```
```docs
```

feat: Add the kubeconfig in toolbox

---

src/actions/project.js
src/components/Inputs/ResourceLimit/index.jsx
src/components/Modals/QuotaEdit/index.jsx

/kind feature
Fixes #
https://user-images.githubusercontent.com/33231138/133749024-dde7a876-61da-4bf4-b54b-4455276f9e88.mov
```release-note
NONE
```

feat: Support set gpu limit of project quota

---

src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
src/stores/devops.js
src/stores/devops/pipelines.js

/area devops
/milestone v3.2
- Refactor with PipelineRun listing API
- Refactor with PipelineRun creation API
We have made some API changes in DevOps area. Please see:
- https://github.com/kubesphere/ks-devops/pull/230
- https://github.com/kubesphere/ks-devops/pull/233
Fixes #
```
Docker image for test: `johnniang/ks-console:pipeline-run-api`
```
```release-note
Refactor with PipelineRun listing and creation API
```
```docs
```

Refactor with PipelineRun listing and creation API

---

src/actions/workload.js
src/utils/index.js

/kind feature
Fixes #
https://user-images.githubusercontent.com/33231138/133764320-cda23a37-27bf-475e-8172-8bab8f5130fe.mov
i will fix the problem of  selectInput with later.
```release-note
NONE
```

feat: Support edit gpu limit for Jobs and CronJob

---

src/actions/federated.js
src/actions/workload.js
src/components/EditForms/Workload/PodTemplate/index.jsx

/kind feature
Fixes #
```
```
```release-note
NONE
```
```docs
```

feat: Support edit gpu limit of deployment template

---

src/components/Forms/Workload/ContainerSettings/index.jsx
src/components/Inputs/ResourceLimit/index.jsx

/kind feature
Fixes #
https://user-images.githubusercontent.com/33231138/133751289-d1157af3-1e71-4bc2-a71f-68f070b0034f.mov
```release-note
NONE
```
```docs
```

feat: Support set gpu limit for deployment

---

src/pages/projects/components/Modals/GatewaySetting/index.jsx

/kind bug
Fixes ##2243 
```release-note
Bugfix: The cancel button is missing in the Gateway Settings page
```

fix: No cancel button in Gateway setting page

---

src/components/Inputs/ResourceLimit/index.jsx
src/components/Inputs/ResourceLimit/index.scss

/kind bug
before, the selecte input width shorter than the input width.
Fixes #
```release-note
NONE
```

fix: Update input label width and ui text

---

src/actions/project.js

/kind bug
```release-note
NONE
```

fix: Container default resource modal can't close

---

src/components/Inputs/ResourceLimit/index.jsx

/kind bug
```release-note
NONE
```
```docs
```

fix: Resource limit input bug

---

src/components/Forms/Workload/ContainerSettings/index.jsx

/kind bug
Fixes #
https://user-images.githubusercontent.com/33231138/134273015-d78cae7d-4a20-4882-b5aa-8879cfd4dbb6.mov
```release-note
NONE
```

fix: Can not save container image when creating deployment

---

src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
src/components/Forms/Notification/BaseForm/ConditionSelect/index.scss
src/components/Forms/Notification/BaseForm/index.jsx

/kind feature
Fixes #
```
```
```release-note
```
```docs
```

feat: Support notification filter key custom

---

locales/zh/pipeline.js

/kind bug
Fixes  https://github.com/kubesphere/ks-devops/issues/126
I tried to package it locally, but it may not be released successfully because of the version.

fix: Unified translation

---

src/pages/clusters/containers/Storage/PV/detail/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/index.jsx

/kind bug
Fixes #
```release-note
NONE
```
```docs
```

fix: Storageclass status Incorrect

---

locales/en/app_repo.js
locales/es/app_repo.js
locales/tc/app_repo.js
locales/zh/app_repo.js
src/components/Modals/AppRepoCreate/index.jsx
src/components/Modals/AppRepoCreate/index.scss
src/components/Modals/AppRepoCreate/time.input.jsx

/kind feature
Fixes #[#kubesphere/kubesphere#4107](https://github.com/kubesphere/kubesphere/issues/4107)
```
```
```release-note
feat: Add app repo sync period
```
```docs
```

feat: Add app repo sync period

---

src/actions/federated.js
src/actions/project.js
src/actions/workload.js
src/components/EditForms/Workload/PodTemplate/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/components/Inputs/ResourceLimit/index.jsx
src/components/Modals/QuotaEdit/index.jsx
src/pages/fedprojects/containers/Deployments/Detail/index.jsx
src/pages/fedprojects/containers/Deployments/index.jsx
src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
src/pages/projects/containers/BaseInfo/index.jsx
src/pages/projects/containers/CronJobs/index.jsx
src/pages/projects/containers/Deployments/Detail/index.jsx
src/pages/projects/containers/Deployments/index.jsx
src/pages/projects/containers/Jobs/index.jsx
src/stores/federated.js
src/stores/limitrange.js
src/utils/index.js

/kind bug
Fixes #
```
```
```release-note
NONE
```
<!--

fix: Disallow set gpu limit for workSpace

---

locales/en/notification.js
locales/es/notification.js
locales/tc/notification.js
locales/zh/notification.js
package.json
src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
src/components/Forms/Notification/BaseForm/index.jsx
src/components/Forms/Notification/MailForm/index.jsx
src/components/Forms/Notification/WebhookForm/index.jsx
src/pages/settings/containers/Notification/DingTalk/index.jsx
src/pages/settings/containers/Notification/Mail/index.jsx
src/pages/settings/containers/Notification/Slack/index.jsx
src/pages/settings/containers/Notification/WeCom/index.jsx
src/pages/settings/containers/Notification/Webhook/index.jsx
yarn.lock

/kind bug
Fixes ##2315 ##2299 #[#kubesphere/kubesphere4269](https://github.com/kubesphere/kubesphere/issues/4269)
##2287 ##2285 ##2281 ##2279 
```
```
```release-note
```
```docs
```

fix: Fix some notification issues

---

locales/zh/workload.js
src/components/Inputs/ResourceLimit/index.jsx
src/components/Inputs/ResourceLimit/index.scss

/kind bug
Fixes #[#4266](https://github.com/kubesphere/kubesphere/issues/4266#issue-1004408746)
(1) fix style problem:
(2) delete gpu  params:
```release-note
NONE
```

fix:  ResourceLimit component input style problem and can't create deployment

---

src/components/HOCs/withTableActions.js
src/pages/clusters/containers/Storage/PV/index.jsx

/kind bug
Fixes ##2312
```release-note
NONE
```

fix: Bound pv can't delete

---

src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
src/pages/clusters/containers/Workload/Deployments/index.jsx

/kind bug
Fixes ##2309
```release-note
NONE
```

fix: Storage type didn't display

---

src/actions/project.js
src/components/Inputs/ResourceLimit/index.jsx

/kind bug
Fixes ##2339
https://user-images.githubusercontent.com/33231138/135040696-873c3fd9-c251-463a-affd-80f0b8db1ac9.mov
```release-note
NONE
```

fix: Requets is equal to limits and allow user to cancel gpu limits

---

src/actions/storageclass.js
src/components/HOCs/withTableActions.js
src/components/Modals/VolumeFunctionManage/index.jsx
src/pages/clusters/containers/Storage/PV/index.jsx
src/pages/clusters/containers/Storage/Volumes/index.jsx
src/stores/base.js

/kind bug
Fixes ##2327
```release-note
NONE
```

fix: Update storageClass Capability logic

---

src/pages/clusters/containers/Storage/PV/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: Pv delete button status incrrect

---

src/components/Base/Breadcrumb/index.test.js
src/pages/clusters/containers/CustomResources/Detail/routes.js
src/pages/clusters/containers/Gateway/Detail/routes.js
src/pages/clusters/containers/LogCollections/Detail/routes.js
src/pages/clusters/containers/Storage/PV/detail/routes.js
src/pages/fedprojects/containers/Deployments/Detail/routes.js
src/pages/fedprojects/containers/Routes/Detail/routes.js
src/pages/fedprojects/containers/Services/Detail/routes.js
src/pages/fedprojects/containers/StatefulSets/Detail/routes.js
src/pages/fedprojects/containers/Volumes/Detail/routes.js
src/pages/projects/containers/Applications/OPAppDetail/routes.js
src/pages/projects/containers/DaemonSets/Detail/routes.js
src/pages/projects/containers/ImageBuilder/Detail/routes.js
src/pages/projects/containers/Jobs/Detail/routes.js
src/pages/projects/containers/Pods/Containers/routes.js
src/pages/projects/containers/Pods/Detail/routes.js
src/pages/projects/containers/Routes/Detail/routes.js
src/pages/projects/containers/Services/Detail/routes.js
src/pages/projects/containers/StatefulSets/Detail/routes.js
src/pages/projects/containers/Volumes/Detail/routes.js

Fixes #
```
```
```release-note
none
```
```docs
```

docs: Change the resource status to RESOURCE_STATUS

---

src/actions/gateways.js
src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
src/pages/clusters/containers/Projects/Detail/Gateway/index.jsx
src/pages/fedprojects/containers/Gateway/Access/index.jsx
src/pages/projects/components/Modals/GatewaySetting/index.jsx
src/pages/projects/containers/Gateway/index.jsx
src/stores/gateway.js

Fixes #
```
```
```release-note
none
```
```docs
```

fix: The old gateway can not view

---

src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
src/components/Forms/Secret/SecretSettings/index.jsx
src/stores/secret.js

/kind bug
- fix [secret verify](https://github.com/kubesphere/kubesphere/issues/4154)
```
```
```release-note
Change the secret verify api
```
```docs
```

fix: Change the secret verify api

---

src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx

/kind bug
Fixes ##2576
https://user-images.githubusercontent.com/33231138/139644847-c8d4def9-cb59-449e-826c-7cf5dbe7bace.mov
```release-note
NONE
```

fix: Can't mount configMap in federatedDeployment

---

src/components/Modals/CustomMonitoring/containers/GraphMonitorForm.jsx
src/components/Modals/CustomMonitoring/containers/TextMonitorForm.jsx
src/stores/monitoring/custom/template.json

/kind feature
Fixes #
```
```
```release-note
feat: Add GPU monitor template in custom monitor dashboard
```
```docs
```

feat: Add GPU monitor template in custom monitor dashboard

---

src/actions/gateways.js

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix the tracing not display in create gateway modal

---

locales/es/pipeline.js

/kind bug
Synchronous modification with other languages
None
None
```release-note
NONE
```

Fix: Update es pipeline options

---

src/components/Cards/Volumes/Item.jsx
src/utils/volume.js

/kind bug
Fixes ##2467
https://user-images.githubusercontent.com/33231138/139796382-0f0c2aa2-3626-4ed2-98a3-625a4f313adf.mov
```release-note
NONE
```

fix: Mount hostpath volume error

---

src/components/Forms/Workload/ClusterDiffSettings/ContainerImage/index.jsx
src/components/Forms/Workload/ClusterDiffSettings/index.jsx
src/pages/fedprojects/components/ClusterDiffSettings/index.jsx
src/pages/fedprojects/components/ContainerImage/index.jsx
src/pages/fedprojects/components/ContainerSetting/index.jsx

/kind feature
Fixes #
https://user-images.githubusercontent.com/33231138/140698351-e89dabb5-be81-4ad0-931c-196abdf01c21.mov
```release-note
NONE
```

feat: Add available quotas tip during editing cluster different setting

---

src/components/Cards/Pods/Item.jsx
src/pages/clusters/containers/Gateway/Components/Pods/Item.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: Sonarqube bug

---

server/config.yaml

Signed-off-by: 123liubao <chenly_61@163.com>
/kind bug
Fixes #2595
```
```
```release-note
None
```
```docs
```

fix: modify the address jump url of 'User Manual'.

---

src/stores/devops/run.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/2593
```
```
```release-note
Fix the running status and log not be auto-updated in the pipeline
```
```docs
```

fix:  Fix the running status and log not be auto-updated in the pipeline

---

locales/en/app_repo.js
locales/es/app_repo.js
locales/tc/app_repo.js
locales/zh/app_repo.js

Optimize UI decriptions.
Fixes #2569 
```
```
```release-note
None
```
Issue fixed. Please take a look, thanks!
/assign @xuliwenwenwen @harrisonliu5

fix: Optimize Synchronization Interval Descriptions.

---

package.json
src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.jsx
src/pages/workspaces/containers/QuotaManage/ResourceQuota/QuotaItem/index.jsx
src/utils/constants.js
yarn.lock

/kind bug
Fixes #
```
```
```release-note
None
```

fix: Fix the UI of gpu quota

---

server/config.yaml
src/components/Forms/Pipelines/AdvanceSettings/index.jsx

Signed-off-by: mango <xu.weiKyrie@foxmail.com>
/kind design
/area devops
Fixes #2546
```release-note
None
```

fix: Change UI element layout in the pipeline creation dialog box 

---

src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
src/pages/clusters/containers/Gateway/Detail/index.jsx

/kind bug
Fixes ##2551
```release-note
Cancel update button in gateway page.
```

fix: Delete update button in gateway page

---

src/pages/devops/containers/Credential/detail/index.jsx

/kind deprecation
Fixes #2452
```release-note
fix: Remove Labels shown on the credential detail page
```

fix: Remove Labels shown on the credential detail page

---

locales/en/pipeline.js
locales/es/pipeline.js
locales/tc/pipeline.js
locales/zh/pipeline.js
src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx

Change Run Count to Run ID.
/assign @harrisonliu5 @JohnNiang  Please take a look. Thanks!
```release-note
None
```

Change Run Count to Run ID.

---

locales/en/app.js
locales/en/logging.js
locales/en/meter.js
locales/es/app.js
locales/tc/app.js
locales/zh/app.js
locales/zh/logging.js
locales/zh/meter.js
server/config.yaml
src/components/Layout/Header/index.jsx
src/components/Modals/AuditingSearch/index.jsx
src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/EventSearch/index.jsx
src/components/Modals/LogSearch/index.jsx
src/pages/apps/components/Cards/TestSteps/index.jsx
src/pages/apps/components/Modals/AppCreate/index.jsx
src/pages/apps/components/Modals/HelmUpload/index.jsx
src/utils/index.js

/kind bug
Fixes ##2624
https://user-images.githubusercontent.com/33231138/142810000-f74690ba-ce3c-4630-b21e-501eac6c723f.mov
```release-note
Update documentation links to kubesphere.io and kubesphere.com.cn.
```

fix: Update documentation links to kubesphere.io and kubesphere.com.cn

---

src/pages/fedprojects/containers/Volumes/index.jsx
src/pages/projects/containers/Volumes/index.jsx
src/pages/projects/containers/Volumes/index.scss

/kind bug
Fixes #
```release-note
NONE
```

fix: Update ui style in pv management page

---

src/components/Modals/LogSearch/Logging/Detail/index.jsx
src/components/Modals/LogSearch/Logging/Detail/index.scss

/kind feature
/kind design
Fixes ##2490 
```release-note
NONE
```
```docs
```

feat: Optimize log query style

---

src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
src/stores/workload/env.js

Signed-off-by: TheYoungManLi <33231138+weili520@users.noreply.github.com>
/kind bug
Fixes #
before:
Now:
```release-note
```

fix: Statefulsets deployment deatil page error

---

locales/en/base.js
locales/zh/base.js

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: Ui text error in pods management page

---

locales/en/devops.js
locales/es/devops.js
locales/tc/devops.js
locales/zh/devops.js
src/pages/devops/components/Pipeline/StepsSelector/index.jsx
src/pages/devops/components/Pipeline/StepsSelector/index.scss

/kind bug
Fixes #
```release-note
fix: Add the Deprecated tip of Kubernetes Deploy in Pipeline
```
```docs
```

fix: Add the Deprecated tip of Kubernetes Deploy in Pipeline

---

src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
src/pages/clusters/containers/Monitor/Cluster/Overview/index.scss

/kind bug
Fixes ##2666
```release-note
None
```

fix: modify the jump of 'Component Status' of 'Cluster Status' page.

---

src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/index.jsx

/kind bug
https://user-images.githubusercontent.com/33231138/143798136-fa228a0f-58b4-4130-b583-48131c590775.mov
Fixes #
```release-note
NONE
```

fix: StatefulSet setting modal can't open

---

src/components/HOCs/withList.js
src/pages/projects/containers/Services/index.jsx
src/stores/base.js

/kind bug
Fixes ##2671
https://user-images.githubusercontent.com/33231138/143805925-7e070576-3b33-4da1-b1fe-011578bab9ab.mov
```release-note
NONE
```

fix: Cannot use application fields for filtering

---

src/components/Modals/AppRepoCreate/index.jsx

/kind bug
Fixes ##2670
```release-note
NONE
```

fix: Update seconds verification rule

---

locales/en/l10n-clusterManagement-projects-list.js
locales/zh/base.js
src/actions/gateways.js

/kind bug
Fixes ##2697
```release-note
NONE
```

fix: Update gateway delete tip text

---

src/pages/devops/components/Modals/JenkinsEdit/index.scss

/kind bug
Fixes ##2683
https://user-images.githubusercontent.com/33231138/144186751-b1370981-d333-4bb1-bbfd-86d10b2fe501.mov
```release-note
NONE
```

fix: Jenkins edit modal scroll

---

src/pages/apps/containers/AppDeploy/index.jsx

/kind bug
Fixes ##2684
```
```
```release-note
NONE
```

fix: Application deployment fails if we click too fast

---

locales/en/s2i.js
locales/zh/s2i.js
server/controllers/view.js
server/services/session.js
src/components/Forms/ImageBuilder/LanguageSelect/index.jsx
src/components/Forms/ImageBuilder/LanguageSelect/index.scss

/kind feature
Fixes ##[2714](https://github.com/kubesphere/console/issues/2714)
```release-note
Add an S2i tip for not supporting containerd runtime.
```

feat: Add an s2i tip for not supporting containerd runtime

---

src/utils/index.js

Signed-off-by: 123liubao <chenly_61@163.com>
/kind bug
The storage volume access mode display error , the 'RWM' have been updated to 'RWX'.
This PR is to modify 'ROM' to 'ROX'.
Fixes https://github.com/kubesphere/kubesphere/issues/4509
```release-note
None
```
```docs
```

fix : modify volume access mode 'ROM' to 'ROX'.

---

locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
src/actions/gateways.js

/kind bug
Fixes ##2723
https://user-images.githubusercontent.com/33231138/144956525-c52ec171-5725-4013-9e8e-c938895ce56d.mov
```release-note
NONE
```

fix: Update gateway setting conflect

---

src/pages/clusters/containers/Gateway/Components/TimeSelector/index.jsx

/kind bug
Fixes ##2738
https://user-images.githubusercontent.com/33231138/144954812-14864539-5b13-4d6f-b78e-6d9d060e82ff.mov
```release-note
NONE
```
```docs
```

fix: Gateway time range switch problem

---

src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx

/kind bug
Fixes ##2740
https://user-images.githubusercontent.com/33231138/145162953-0d955e71-65b7-4546-80bb-8457568979e5.mov
```release-note
NONE
```

fix: Update gateway Replicas error

---

src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.jsx
src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.scss

/kind bug
Fixes ##2739
```release-note
NONE
```

fix: highlight the matched keywords in the query result of gateway logs

---

src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
src/pages/clusters/containers/Gateway/Detail/index.jsx

/kind bug
Fixes ##2551
Uploading 屏幕录制2021-12-08 10.41.54.mov…
```release-note
NONE
```

fix: Delete update button on gateway page if the gateway doesn't need to update

---

locales/en/l10n-clusterManagement-clusterSettings-logReceivers-details.js
locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
locales/en/l10n-devopsProjects-pipeline-details.js
locales/en/l10n-projects-applicationWorkloads-services-list.js
locales/en/l10n-projects-overview.js
locales/en/role.js

Signed-off-by: Felixnoo <felixliu@kubesphere.io>
Update EN UI strings.
This is part of the efforts to fix ##2760.
```
None.
```
```release-note
None
```
/cc @Patrick-LuoYu 
/cc @harrisonliu5 
Please take a look, thanks.

docs: Update EN Locales

---

src/components/Layout/Header/index.jsx

/kind bug
Fixes ##2791
https://user-images.githubusercontent.com/33231138/145187777-204a2677-647b-48ef-b029-4a519182e291.mov
```release-note
NONE
```

fix: Document link error

---

src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx

/kind bug
Fixes #
```
```
```release-note
fix: Fix the url is http need annotations in docker repo secret
```
```docs
```

fix: Fix the url is http need annotations in docker repo secret

---

server/config.yaml
src/components/Modals/UserSetting/BaseInfo/index.jsx

/kind feature
The console now supports more languages, but some minor translations are still being refined, so if you don't need them, you can turn off restore in the configuration file. As an example `showAllLangs: false`
Fixes ##2771 
```
```
```release-note
feat: Support for more languages
```
```docs
```

feat: Add more support for language configuration

---

src/pages/clusters/containers/Gateway/Components/Pods/Item.jsx
src/pages/clusters/containers/Gateway/Components/Pods/index.jsx
src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/2803
```
```
```release-note
None
```
```docs
```

fix: Fix the link of gateway pod container

---

locales/ar/role.js
locales/ar/workload.js
locales/en/l10n-projects-applicationWorkloads-apps-composedApps-list.js
locales/en/role.js
locales/en/workload.js
locales/es/role.js
locales/es/workload.js
locales/fr/role.js
locales/fr/workload.js
locales/hi/role.js
locales/hi/workload.js
locales/lt/role.js
locales/lt/workload.js
locales/pl/role.js
locales/pl/workload.js
locales/tc/role.js
locales/tc/workload.js
locales/tr/role.js
locales/tr/workload.js
locales/zh/role.js
locales/zh/workload.js

Update locale package.
/assign @harrisonliu5 @xuliwenwenwen @FeynmanZhou 
```release-note
None
```

docs: Update locale package.

---

docs/join-the-kubesphere-localization-project.md

Update l10n guide.
/assign @harrisonliu5 @xuliwenwenwen @FeynmanZhou 
```release-note
None
```

docs: Update l10n guide.

---

server/config.yaml

Update language options.
/assign @harrisonliu5 @xuliwenwenwen
```release-note
None
```

docs: Update language options.

---

docs/join-the-kubesphere-localization-project.md

Fix minor issue in localization guide.
/assign @harrisonliu5 @xuliwenwenwen
```release-note
None
```

docs: Fix minor issue in localization guide.

---

locales/zh/l10n-clusterManagement-clusterSettings-logReceivers-details.js
locales/zh/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/zh/l10n-devopsProjects-devopsProjectSettings-credentials-details.js
locales/zh/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
locales/zh/l10n-devopsProjects-pipeline-details.js
locales/zh/l10n-devopsProjects-pipeline-list.js
locales/zh/l10n-projects-applicationWorkloads-services-list.js
locales/zh/l10n-projects-overview.js
locales/zh/l10n-projects-projectSettings-basicInformation.js
locales/zh/l10n-projects-projectSettings-gatewaySettings-list.js
locales/zh/l10n-projects-projectSettings-projectRoles-list.js
locales/zh/l10n-toobox-auditLogSearch-details.js
locales/zh/l10n-toobox-resourceConsumptionStatistics-clusterResourceConsumption.js

Sync zh locale files from master.
/assign @harrisonliu5 @xuliwenwenwen
```release-note
None
```

docs: Sync zh locale files from master.

---

src/components/Inputs/PropertiesInput/index.jsx

/kind bug
Fixes ##2466
https://user-images.githubusercontent.com/33231138/146114342-976f873c-0e42-4cda-a412-c0da6b31355e.mov
```release-note
Gateway configuration options input error.
```

fix: Gateway configuration options input error

---

locales/en/l10n-projects-applicationWorkloads-deployments-list.js
src/components/Inputs/ArrayInput/Item.jsx
src/components/Inputs/ArrayInput/index.scss
src/components/Inputs/EnvironmentInput/Item.jsx
src/components/Inputs/EnvironmentInput/index.scss
src/utils/constants.js

/kind bug
Fixes ##2790
https://user-images.githubusercontent.com/33231138/146139315-cd82dfd5-a89f-4066-8026-ad99c2ebadfd.mov
```release-note
Add environment variables validation and error prompt in the container edit page.
```

fix: Add environment variables validation and tips

---

src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
src/pages/clusters/containers/Storage/PV/index.jsx
src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
src/pages/fedprojects/containers/Volumes/index.jsx
src/pages/projects/containers/Volumes/index.jsx

/kind bug
Fixes ##2317
https://user-images.githubusercontent.com/33231138/146315653-58b6c1f1-d4c6-4610-b3e8-40f578ce48b4.mov
```release-note
Deleted PV still in the list.
```

fix: Deleted pv still in the table list

---

src/pages/projects/containers/Volumes/Detail/index.jsx

/kind bug
Fixes ##2856
```release-note
Disable PVC expand, clone and create snapshot when it's in pending
```

fix: Disable PVC expand, clone and create snapshot when it's in pending

---

locales/zh/role.js

/kind bug
Fixes ##2680
```
```
```release-note
NONE
```

fix: prompt is missing a period

---

src/pages/console/containers/Dashboard/Admin/index.jsx

/kind bug
Fixes ##2513
```release-note
NONE
```

fix: Platform version incorrect

---

src/components/Modals/ProjectSelect/Card/index.jsx

/kind bug
Fixes ##2713
```release-note
NONE
```

fix: Devops are not shown in grey disabled mode.

---

src/components/Modals/KubeCtl/index.jsx
src/pages/clusters/containers/EdgeNodes/index.jsx
src/pages/clusters/containers/Nodes/index.jsx
src/pages/terminal/index.jsx
src/stores/terminal.js

/kind feature
This function can make it easier for us to manage the edge host, such as
+ Download Image before updating edge application
+ Update edgecore or docker at the edge
+ Modify the edge host configuration
+ ...
Fixes #
issue: [kubesphere#4569](https://github.com/kubesphere/kubesphere/issues/4569)
```
None
```
added a button in nodes page
```release-note
None
```
```docs
None
```

feat: Add shell access to nodes

---

locales/ar/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/es/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/fr/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/hi/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/lt/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/pl/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/tc/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/zh/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx

/kind bug
Fixes ##2470
Add a prompt when the start time or end time is not set
```release-note
NONE
```

fix: Error occurs on the console when the time range is not set.

---

src/pages/clusters/containers/Gateway/Detail/Monitoring/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/2899
```
```
```release-note
None
```
```docs
```

fix: Fix the data of gateway not have the key of metric.ingress

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix the page block by search image without permission

---

src/components/Graph/index.jsx
src/pages/projects/containers/Applications/CRDAppDetail/TrafficManangement/index.jsx
src/pages/projects/containers/Applications/CRDAppDetail/TrafficManangement/index.scss
src/stores/application/crd.js

/kind bug
Fixes #[#4491](https://github.com/kubesphere/kubesphere/issues/4491)
```
Add time controller component
```
https://user-images.githubusercontent.com/33231138/149742835-ec73d1d2-a50c-4fb5-a313-9afad5931565.mov
```release-note
In the composed app's details page, users cannot customize the time interval for the traffic monitoring.
```

fix: In the composed app's details page, users cannot customize the time interval for the traffic monitoring

---

src/stores/edgenode.js

Fixes #
This PR is related to https://github.com/kubesphere/kubesphere/pull/4478
```release-note
None
```
```docs
```

chore: Change the edge node api

---

src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx

/kind bug
Fixes ##2925 
```
```
```release-note
fix: Invalid API request of persistentvolumeclaims in  member cluster environment.
```
```docs
```

fix: Invalid API request of persistentvolumeclaims in  member cluster environment

---

docs/join-the-kubesphere-localization-project.md

Signed-off-by: Felixnoo <felixliu@kubesphere.io>
```release-note
None
```
/assign @Patrick-LuoYu @FeynmanZhou 
Hi, I updated the localization guide to make a note that Chinese (Simplified) doesn't require localization. Please take a look, thanks.

docs: Minor Update in Localization Guide

---

src/components/Base/List/index.scss
src/pages/projects/containers/Services/Topology/Detail/BaseInfo/index.scss
src/pages/projects/containers/Services/Topology/Detail/Childrens/Card/index.jsx
src/pages/projects/containers/Services/Topology/Detail/Childrens/Card/index.scss
src/pages/projects/containers/Services/Topology/Detail/Childrens/index.jsx
src/pages/projects/containers/Services/Topology/Detail/Containers/index.jsx
src/pages/projects/containers/Services/Topology/Detail/Containers/index.scss
src/pages/projects/containers/Services/Topology/Detail/Table/index.scss
src/pages/projects/containers/Services/Topology/Detail/Tables/index.jsx
src/pages/projects/containers/Services/Topology/Detail/Tables/index.scss
src/pages/projects/containers/Services/Topology/Detail/index.jsx
src/pages/projects/containers/Services/Topology/Detail/index.scss

/kind feature
A feature about improve the service Topology Details Layout for a Specific Service.
https://www.figma.com/file/G6LDkjRMGtHq1NGkr5bIyI/Design-Requirements-Pool?node-id=78%3A146477
Fixes ##2392
```
UI diagram has changed
```
```release-note
Improve the Service Topology Details Layout for a Specific Service.
```
```docs
NONE
```

feat:Improve the Service Topology Details Layout

---

locales/ar/l10n-accessControl-users-list.js
locales/ar/user.js
locales/en/l10n-accessControl-users-list.js
locales/en/user.js
locales/es/l10n-accessControl-users-list.js
locales/es/user.js
locales/fr/l10n-accessControl-users-list.js
locales/fr/user.js
locales/hi/l10n-accessControl-users-list.js
locales/hi/user.js
locales/lt/l10n-accessControl-users-list.js
locales/lt/user.js
locales/pl/l10n-accessControl-users-list.js
locales/pl/user.js
locales/tc/l10n-accessControl-users-list.js
locales/tc/user.js
locales/tr/l10n-accessControl-users-list.js
locales/tr/user.js
locales/zh/l10n-accessControl-users-list.js
locales/zh/user.js
src/utils/constants.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4441
```
```
```release-note
fix: Modify the user password to at least 8 characters
```
```docs
```

fix: Modify the user password to at least 8 characters

---

src/components/Cards/Pods/index.jsx
src/components/Modals/KubeCtl/index.jsx
src/pages/terminal/index.jsx
src/stores/federated.js

/kind bug
The page that the detail of workload resource,  after modified the config of it, the pods list not updated. 
Fixes #
```
```
```release-note
fix: Fix the pods not updated after modifying the config of workload in fedProject
```
```docs
```

fix: Fix the pods not updated after modifying the config of workload in fedProject

---

src/utils/socket.client.js

/kind bug
Wait for a while to see the console output
Fixes [#kubesphere/4648](https://github.com/kubesphere/kubesphere/issues/4648)
```
NONE
```
```release-note
fix: Fix WebSocket connection recreate unexpected
```
```docs
```

fix: Fix websocket connection recreate unexpected

---

build/Dockerfile

Update https://registry.npm.taobao.org to https://registry.npmmirror.com, Please refer to https://zhuanlan.zhihu.com/p/430580607.

update https://registry.npm.taobao.org to https://registry.npmmirror.com

---

src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
src/pages/clusters/containers/Storage/Volumes/index.jsx
src/pages/projects/containers/Volumes/index.jsx
src/stores/base.js

/kind bug
Some new features require back-end support to be demonstrated.
Fixes #
```
```
```release-note
NONE
```

fix: Update kubeSphere backend version judgement logic

---

locales/en/l10n-clusterManagement-nodes-clusterNodes-list.js
src/pages/clusters/containers/Nodes/Detail/index.jsx
src/pages/clusters/containers/Nodes/index.jsx

Change UI text 'master' to 'control plane'.
/assign @harrisonliu5 @xuliwenwenwen Please take a look. Thanks!
```release-note
None
```

Change UI text 'master' to 'control plane'.

---

locales/en/l10n-clusterManagement-nodes-clusterNodes-details.js

Update node health status UI text.
/assign @harrisonliu5 @xuliwenwenwen Please take a look. Thanks!
```release-note
None
```

Update node health status UI text.

---

locales/en/base.js
locales/en/l10n-clusterManagement-nodes-clusterNodes-details.js
locales/en/l10n-clusterManagement-nodes-clusterNodes-list.js
locales/en/l10n-clusterManagement-projects-list.js
locales/en/l10n-clusterManagement-systemComponents-details.js
locales/en/l10n-clusterManagement-systemComponents-list.js
locales/en/project.js
src/pages/clusters/containers/EdgeNodes/index.jsx
src/pages/clusters/containers/Nodes/index.jsx
src/pages/clusters/containers/Projects/index.jsx
src/pages/clusters/containers/ServiceComponents/Card/index.jsx
src/pages/clusters/containers/ServiceComponents/Detail/index.jsx
src/pages/clusters/containers/ServiceComponents/Detail/routes.js
src/pages/clusters/containers/ServiceComponents/index.jsx

Update UI text of Cluster Management.
/assign @harrisonliu5 @xuliwenwenwen Please take a look. Thanks!
```release-note
None
```

Update UI text of Cluster Management.

---

src/pages/projects/components/Modals/GatewaySetting/contants.js
src/pages/projects/components/Modals/GatewaySetting/index.jsx

/kind feature
Fixes ##[4574](https://github.com/kubesphere/kubesphere/issues/4574)
```release-note
Integrate OpenELB in KubeSphere for exposing the LoadBalancer type of service.
```

feat: Integrate OpenELB in KubeSphere for exposing the LoadBalancer type of service.

---

locales/ar/l10n-projects-configuration-serviceAccounts-details.js
locales/en/l10n-projects-applicationWorkloads-routes-details.js
locales/en/l10n-projects-configuration-serviceAccounts-details.js
locales/fr/l10n-projects-configuration-serviceAccounts-details.js
locales/hi/l10n-projects-configuration-serviceAccounts-details.js
locales/lt/l10n-projects-configuration-serviceAccounts-details.js
locales/pl/l10n-projects-configuration-serviceAccounts-details.js
locales/tr/l10n-projects-configuration-serviceAccounts-details.js
locales/zh/l10n-projects-applicationWorkloads-routes-details.js
src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Rule/index.jsx
src/pages/projects/containers/Routes/Detail/ResourceStatus/Rule.jsx

Fix grammar mistakes and typos on the web console.
```
None
```
```release-note
None
```
/assign @Patrick-LuoYu @harrisonliu5 
Please take a look at this PR, thanks :)

docs: Fix grammar mistakes and typos.

---

src/stores/node.js

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: Node num incorrect

---

src/components/Modals/EditServiceAccount/index.jsx

/kind bug
Fixes ##3000
```release-note
NONE
```

fix: Remove role select function for service account edit modal.

---

src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
src/stores/devops/run.js

/kind feature
/area devops
It's not good to use any Jenkins API directly.
See https://github.com/kubesphere/ks-devops/pull/479
Fixes #
```
```
```release-note
None
```
```docs
```

Change the artifact download link on the Pipeline run page

---

src/pages/clusters/containers/EdgeNodes/Detail/index.jsx
src/pages/clusters/containers/Nodes/Detail/index.jsx

/kind bug
Fixes ##2971
```
```
```release-note
NONE
```

fix: Remove the **Schedulable** field in cluster node details and edge node details

---

locales/en/l10n-clusterManagement-clusterSettings-basicInformation.js
locales/zh/l10n-clusterManagement-clusterSettings-basicInformation.js
src/actions/cluster.js
src/components/Modals/Delete/index.jsx
src/pages/clusters/containers/BaseInfo/ManageButton/index.jsx
src/pages/clusters/containers/BaseInfo/ManageButton/index.scss
src/pages/clusters/containers/BaseInfo/index.jsx
src/pages/clusters/containers/BaseInfo/index.scss
src/pages/fedprojects/containers/BaseInfo/ProjectInfo/index.jsx
src/pages/projects/containers/BaseInfo/ProjectInfo/index.jsx
src/pages/projects/containers/BaseInfo/ProjectInfo/index.scss
src/pages/workspaces/containers/BaseInfo/index.jsx
src/pages/workspaces/containers/BaseInfo/index.scss

/kind bug
Fixes ##2982
```release-note
Optimize the UI of deleting a cluster, workspace, and project.
```

fix: Optimize the UI of deleting a cluster, workspace, and project.

---

locales/zh/l10n-clusterManagement-storage-storageClasses-list.js
src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
src/pages/clusters/containers/Storage/PV/index.jsx

Update UI text to meet the requirements of our style guide and remove a duplicate tip icon.
As there is already a tip icon on the right of **Access mode**, I removed a duplicate icon from the following file:
```
src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
```
Please take a look to make sure everything looks good, thanks.
```release-note
None
```
/assign @Patrick-LuoYu @weili520

docs: Update UI text.

---

locales/en/l10n-clusterManagement-applicationWorkloads-pods-list.js
locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/Capabilities/index.jsx
src/pages/projects/containers/Pods/index.jsx
src/utils/constants.js

Update UI text of 'Cluster Management'.
```release-note
None
```

Update UI text of 'Cluster Management'.

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Tables/Base/index.scss

Fixes #https://github.com/kubesphere/kubesphere/issues/4703
https://user-images.githubusercontent.com/17872673/159669828-81299885-22fe-43f5-9843-c91d2b1036fe.mp4
```release-note
Fix The repository will switch to the dockerhub even though we have set the private registry.
```
```docs
```

fix: Fix value of the private dockerhub repository in the container

---

src/pages/workspaces/containers/Roles/index.jsx

Signed-off-by: moweiwei [moweiwei6@gmail.com](moweiwei6@gmail.com)
/kind bug
Fixes ##2989
```
```
```release-note
fix: Fix workspace role table not show aliasName
```

fix: Fix workspace role table not show aliasName

---

src/components/HOCs/withTableActions.js
src/components/Tables/Base/index.jsx
src/pages/access/containers/Accounts/index.jsx
src/stores/user.js

/kind feature
Fixes #https://github.com/kubesphere/kubesphere/issues/4442
https://user-images.githubusercontent.com/17872673/160068145-a71501ad-5b4d-422a-8f65-481929c6f5c3.mp4
```release-note
feat: Add account enalbe or disable function
```
```docs
```

feat: Add account enalbe or disable function

---

src/assets/cd/syncfailed.svg
src/pages/devops/containers/CD/Components/StatusText/index.scss
src/pages/devops/containers/CD/detail/index.jsx

/area devops
Fixes #
I did two things in this PR:
* remove the unused filed: `image`
* add the missing icon of syncFailed
before:
after:
Please feel free to use the following image if you want to help to test it:
```
surenpi/ks-console:latest@sha256:83f3b26ad8a97f53fd76f0338d1a0e06582d5ab418585df6f74b41610bf3c635
```
```release-note
None
```
```docs
None
```

chore: Add the missing icon for syncfailed on the ArgoCD status list page

---

src/pages/clusters/containers/Storage/PV/index.jsx
src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: User can enter detail page when a volume in terminating status.

---

src/utils/object.mapper.js

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: Update volume inUse judgment condition

---

locales/en/l10n-devopsProjects-cd-list.js
src/actions/cd.js
src/components/Forms/CD/BaseInfo/index.jsx
src/pages/devops/containers/CD/CDList/index.jsx
src/stores/cd.js

/kind feature
Fixes #
```release-note
None
```
```docs
```

feat: Add cd summary data in cd page

---

server/config.yaml
src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/stores/devops.js
src/stores/devops/scm.js

Signed-off-by: mango <xu.weiKyrie@foxmail.com>
/kind feature
Please see #2893
Fixes #2893
The request Payload screenshot like below:
```release-note
None
```
```docs
```

feat: Avoid use the secret value in the DevOps scm verify API.

---

src/actions/cd.js
src/assets/cd/syncfailed.svg
src/components/Modals/SyncModal/index.jsx
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CD/Components/StatusText/index.scss
src/pages/devops/containers/CD/detail/index.jsx
src/stores/cd.js

Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Modify the sync api

---

locales/en/l10n-clusterManagement-clusters.js
locales/zh/l10n-clusterManagement-clusters.js
src/actions/cluster.js
src/components/Clusters/ClusterTitle/index.jsx
src/components/Clusters/ClusterTitle/index.scss
src/components/EditMode/index.jsx
src/components/Forms/Cluster/Configuration/index.jsx
src/components/Forms/Cluster/KubeConfig/index.jsx
src/components/Forms/Cluster/KubeConfig/index.scss
src/pages/clusters/components/Cards/Cluster/index.jsx
src/pages/clusters/components/Cards/Cluster/index.scss
src/pages/clusters/containers/Clusters/index.jsx
src/stores/cluster/index.js
src/utils/index.js
src/utils/object.mapper.js

/kind feature
Fixes #https://github.com/kubesphere/kubesphere/issues/4426 #https://github.com/kubesphere/console/issues/2898
```
feat: Add the status and operation of cluster KubeConfig expired
```
```release-note
feat: Add the status and operation of cluster KubeConfig expired
```
```docs
```

feat: Add the status and operation of cluster KubeConfig expired

---

server/controllers/session.js

/kind cleanup
Optimize HTTP status code and error message.
Fixes #https://github.com/kubesphere/kubesphere/issues/4496
```release-note
None
```

Optimize HTTP status code

---

locales/en/l10n-devopsProjects-codeRepo-list.js
package.json
server/config.yaml
src/actions/codeRepo.js
src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/subForm.jsx
src/components/Modals/CodeRepoCreate/index.jsx
src/components/Modals/CodeRepoCreate/index.scss
src/components/Tables/Base/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.scss
src/pages/devops/routes/index.js
src/stores/codeRepo.js
src/utils/constants.js
src/utils/form.templates.js
src/utils/object.mapper.js
yarn.lock

/kind feature
Fixes #
```
```
```release-note
feat: Add code repo page
```
```docs
```

feat: Add code repo page

---

locales/en/l10n-toobox-auditLogSearch-list.js
locales/zh/l10n-toobox-auditLogSearch-list.js
src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
src/components/Modals/AuditingSearch/Auditing/Home/index.scss

/kind feature
Fixes #https://github.com/kubesphere/kubesphere/issues/4554
```release-note
feat: Add prompt to enable audit log
```
```docs
```

feat: Add prompt to enable audit log

---

locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
locales/zh/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
package.json
src/actions/devops.js
src/components/Modals/DevOpsAllowList/Destinations.jsx
src/components/Modals/DevOpsAllowList/index.jsx
src/components/Modals/DevOpsAllowList/index.scss
src/pages/devops/containers/BaseInfo/index.jsx
src/pages/devops/containers/BaseInfo/index.scss
src/stores/devops.js
src/utils/constants.js
src/utils/object.mapper.js
yarn.lock

/kind feature
Fixes #
```
```
```release-note
NONE
```
```docs
```

feat: Add the cd allowlist in devops base info

---

locales/en/l10n-clusterManagement-member-list.js
locales/en/l10n-clusterManagement-role-list.js
locales/zh/l10n-clusterManagement-member-list.js
locales/zh/l10n-clusterManagement-role-list.js
server/config.yaml
src/pages/clusters/containers/Roles/index.jsx

Fixes #https://github.com/kubesphere/kubesphere/issues/4587
```release-note
feat: Add the cluster member and cluster role
```
```docs
```

feat: Add the cluster member and cluster role

---

server/services/session.js

/kind bug
There has a bug
```
```
```release-note
NONE
```

fix: Get cluster role error

---

package.json
yarn.lock

/kind bug
Fixes ##3047
https://user-images.githubusercontent.com/33231138/162402165-794c55e2-eb6b-4f4f-94ca-962036e80302.mov
```release-note
Service session affinity is not working 
```

fix: Update kube-design version

---

src/actions/cd.js
src/components/Forms/CD/Advance/Placement/index.jsx
src/components/Forms/CD/BaseInfo/index.jsx
src/components/Forms/CD/BaseInfo/index.scss
src/components/Modals/DevOpsAllowList/Destinations.jsx
src/components/Modals/DevOpsAllowList/index.jsx
src/pages/devops/containers/BaseInfo/index.jsx
src/pages/devops/containers/CD/Components/Destination/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.jsx
src/utils/index.js

/kind feature
Fixes #
```release-note
None
```
```docs
```

feat: Relate code repo with cd and allowlist

---

src/pages/projects/containers/CronJobs/Detail/index.jsx

/kind bug
Fixes ##3053
```
```
```release-note
fix: Fix cronjob status display err in detail page
```
```docs
```

fix: Fix cronjob status display err in detail page

---

src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx

/kind bug
Fixes ##3098
```
```
```release-note
NONE
```

fix: Create OpenLB gateway, the page shows error

---

locales/ar/l10n-clusterManagement-storage-volumeSnapshots-list.js
locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js
locales/en/l10n-projects-applicationWorkloads-services-details.js
src/pages/projects/components/Modals/ServiceMonitor/Authorization/index.jsx
src/pages/projects/components/Modals/ServiceMonitor/Endpoint/index.jsx
src/pages/projects/components/Modals/ServiceMonitor/index.jsx

Update UI text of 'Cluster Management'.
```release-note
None
```

Update UI text of 'Cluster Management'

---

src/pages/devops/containers/CD/detail/SyncStatus/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3105
```
```
```release-note
reload status of CD every 4 seconds
```
```docs
```

fix: Fix reload status of CD every 4 seconds

---

README.md

/kind cleanup
The NPM mirror address has changed. It changed from 'registry.npm.taobao.org' to 'registry.npmmirror.com'.
See also this [article](https://zhuanlan.zhihu.com/p/465424728).
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

Update the URL of npm mirror

---

locales/ar/l10n-clusterManagement-monitoring&Alerting-customMonitoring.js
locales/en/l10n-clusterManagement-storage-storageClasses-details.js
locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js
src/components/Forms/Dashboard/BaseInfo/index.jsx
src/components/Modals/StorageclassAutoresizer/index.jsx
src/components/Modals/VolumeFunctionManage/index.jsx
src/pages/clusters/components/Modals/Accessor/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx

Update UI text of 'Storage Classes'.
```release-note
None
```

Update UI text of 'Storage Classes'

---

src/components/EditMode/index.jsx
src/components/Forms/Cluster/KubeConfig/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3107
```
```
```release-note
None
```
```docs
```

fix: Fix the empty value when upload the file in cluster kubeconfig

---

src/actions/codeRepo.js

/kind bug
Fixes ##3101
```release-note
NONE
```

fix: Incorrect URL of a git repository

---

locales/en/l10n-clusterManagement-storage-storageClasses-details.js
locales/zh/l10n-clusterManagement-storage-storageClasses-details.js
src/components/Modals/StorageclassAutoresizer/TailItemInput/index.jsx
src/components/Modals/StorageclassAutoresizer/index.jsx

/kind bug
Fixes #[#4793](https://github.com/kubesphere/kubesphere/issues/4793), ##3114
https://user-images.githubusercontent.com/33231138/163550409-2209eb9e-1a2e-4acd-b12e-a1e23209b584.mov
```release-note
NONE
```

fix: Failed to enable automatic restart of workloads

---

src/actions/volume.js
src/components/Forms/VolumeSnapshot/SnapshotClassSettings/index.jsx

/kind bug
Fixes ##3123
```release-note
NONE
```
```docs
```

fix: Support select a CSI plugin when creating a volume snapshot class

---

locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
src/components/Modals/DevOpsAllowList/Destinations.jsx
src/components/Modals/DevOpsAllowList/index.jsx
src/pages/devops/containers/BaseInfo/index.jsx

Update UI text of 'Continuous Deployment Allowlist'.
/assign @harrisonliu5 @LinuxSuRen Please take a look. Thanks!
```release-note
None
```

Update UI text of 'Continuous Deployment Allowlist'

---

locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
server/config.yaml
src/components/Modals/EditAuthorization/constants.js
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.jsx
src/pages/devops/routes/index.js

/kind feature
Fixes #
```release-note
Add CD and Code Repo role
```
```docs
```

feat: Add CD and Code Repo role

---

locales/en/l10n-clusterManagement-storage-storageClasses-details.js

Update UI text of 'Set Auto Expansion'.
/assign @harrisonliu5 Please take a look. Thanks!
```release-note
None
```

Update UI text of 'Set Auto Expansion'

---

locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js

Update UI text of 'DevOps Project Roles'.
/assign @harrisonliu5 @LinuxSuRen Please take a look. Thanks!
```release-note
None
```

Update UI text of 'DevOps Project Roles'

---

src/actions/federated.js
src/actions/workload.js
src/components/Forms/Workload/VolumeSettings/index.jsx

/kind bug
Fixes #[#4196](https://github.com/kubesphere/kubesphere/issues/4196)
```release-note
NONE
```

fix: Hide the volume template card in statefulsets setting modal

---

src/components/Modals/StorageclassAutoresizer/index.jsx

/kind bug
Fixes #
- Now
```release-note
None
```
```docs
```

fix: Update storageclass expansion text

---

src/pages/clusters/components/Modals/Accessor/index.jsx

/kind bug
Fixes ##3135
```
```
```release-note
NONE
```

fix: Storage type permission setting error

---

src/actions/codeRepo.js
src/components/Modals/CodeRepoCreate/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3140 #https://github.com/kubesphere/console/issues/3137 #https://github.com/kubesphere/console/issues/3136
```
```
```release-note
None
```
```docs
```

fix: Fix the code repo issues about edit and create time

---

.eslintignore

/kind bug
```
```
```release-note
NONE
```

fix: Do not check the locales folder

---

src/components/Forms/CD/BaseInfo/index.jsx

/kind bug
Fixes ##3151
```
```
```release-note
NONE
```

fix: The character length limit for aliases does not work

---

src/pages/projects/components/Modals/GatewaySetting/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3139
https://user-images.githubusercontent.com/17872673/163913577-0d3d6dc1-bdd6-45bc-bf64-05e19def093a.mov
```release-note
None
```
```docs
```

fix: Fix the annotations in gateway modal

---

locales/en/l10n-devopsProjects-continuousDeployments-list.js
src/actions/cd.js
src/components/Modals/CDDelete/index.jsx
src/components/Modals/CDDelete/index.scss
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CD/detail/index.jsx
src/stores/cd.js

/kind feature
Fixes #https://github.com/kubesphere/console/issues/3119
```release-note
Request to support cascade deletion of the CD resource
```
```docs
```

feat: Optimize CD delete modal

---

.gitpod.yml
Makefile

/kind cleanup
Before change the tag name always be `latest`. See the following partial output:
```shell
@LinuxSuRen ➜ /workspaces/console (fix/devops-role ✗) $ make container
DRY_RUN=true TAG=fix-devops-role hack/docker_build.sh
+ set -o pipefail
+ TAG=fix-devops-role
+ REPO=kubespheredev
+ PUSH=
+ CONTAINER_CLI=docker
+ CONTAINER_BUILDER=build
+ docker build -f build/Dockerfile -t kubespheredev/ks-console:fix-devops-role .
```
see the partial output with this PR:
```shell
@LinuxSuRen ➜ /workspaces/console (fix/devops-role) $ make container
DRY_RUN=true TAG=fix-devops-role hack/docker_build.sh
+ set -o pipefail
+ TAG=fix-devops-role
+ REPO=kubespheredev
+ PUSH=
+ CONTAINER_CLI=docker
+ CONTAINER_BUILDER=build
+ docker build -f build/Dockerfile -t kubespheredev/ks-console:fix-devops-role . …
```

Fix the image tag when build it with make command

---

src/components/Forms/CD/Advance/Placement/index.jsx
src/components/Modals/DevOpsAllowList/index.jsx
src/stores/cd.js
src/utils/index.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3154 #https://github.com/kubesphere/ks-devops/issues/558
```
```
```release-note
None
```
```docs
```

fix: Fix the location in CD create modal

---

src/pages/clusters/containers/Storage/VolumeSnapshots/Snapshots/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: User still can click the delete button when the snapshot in deleting status

---

locales/ar/alerting.js
locales/en/alerting.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/en/l10n-clusterManagement-nodes-clusterNodes-list.js
locales/en/l10n-clusterManagement-storage-storageClasses-details.js
locales/en/l10n-devopsProjects-continuousDeployments-list.js
locales/es/alerting.js
locales/fr/alerting.js
locales/hi/alerting.js
locales/lt/alerting.js
locales/pl/alerting.js
locales/tc/alerting.js
locales/tr/alerting.js
locales/zh/alerting.js
locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingMessages.js
src/components/Cards/RankTable/NodeTable/index.jsx
src/components/Forms/Cluster/NodeList/AddNode.jsx
src/pages/clusters/containers/Nodes/Detail/index.jsx
src/pages/clusters/containers/Nodes/index.jsx
src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
src/pages/projects/containers/Alerting/Messages/index.jsx
src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx
src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleItem.jsx
src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/index.jsx
src/pages/projects/containers/Alerting/Policies/Detail/routes.js
src/utils/index.js
src/utils/index.test.js

Update UI text of 'Continuous Deployment'.
```release-note
None
```

Update UI text of 'Continuous Deployment'

---

server/controllers/session.js

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix redirect when logging in with OAuth

---

locales/en/l10n-devopsProjects-continuousDeployments-details.js
src/components/Forms/CD/BaseInfo/index.jsx
src/components/Forms/CD/BaseInfo/index.scss
src/pages/devops/containers/CD/detail/SyncStatus/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3160 #https://github.com/kubesphere/console/issues/3156
```
```
```release-note
None
```
```docs
```

fix: Fix display of value of code repository

---

src/pages/devops/containers/CD/Components/ChartCard/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3172
```
```
```release-note
None
```
```docs
```

fix: Fix the filter of health status and sync status in CD page

---

src/components/Inputs/EnvironmentInput/Item.jsx

/kind bug
Fixes # #3185
https://user-images.githubusercontent.com/33231138/164646342-043a251d-2e96-4ccd-84b9-4c06a0b37804.mov
```release-note
NONE
```

fix: Error select environment variable

---

server/config.yaml
server/controllers/view.js
server/services/session.js

/kind bug
According to this pull request [#1671](https://github.com/kubesphere/ks-installer/pull/1671).
Fixes #
```
```
```release-note
```

fix: Get support gpu list from apiserver

---

src/components/Graph/Card/index.jsx
src/components/Graph/Card/index.scss
src/pages/fedprojects/containers/Applications/Detail/TrafficManangement/index.jsx
src/pages/fedprojects/containers/Applications/Detail/TrafficManangement/index.scss

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4818
```
```
```release-note
None
```
```docs
```

fix: Add time select in fedproject applications traffic

---

server/config.yaml

/kind bug
Fixes ##3182
```
```
```release-note
Update the edge node component's name
```

fix: Update edge node component name

---

src/components/Forms/CD/Advance/index.jsx
src/components/Modals/SyncModal/index.jsx
src/utils/constants.js
src/utils/object.mapper.js

/kind feature
Fixes #https://github.com/kubesphere/console/issues/3194
```
```
```release-note
None
```
```docs
```

feat: Add options of prune propagation policy in cd modal

---

src/components/Inputs/ArrayInput/Item.jsx
src/components/Inputs/ArrayInput/index.jsx
src/components/Inputs/EnvironmentInput/Item.jsx
src/components/Inputs/EnvironmentInput/index.jsx

/kind bug
Fixes ##3183
https://user-images.githubusercontent.com/33231138/164971037-f2a04b58-c002-407f-bdc7-d3b5433dd900.mov
```release-note
NONE
```

fix: Fix environment variables duplicate key name

---

src/pages/clusters/components/Cards/Cluster/index.jsx
src/utils/index.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3203
```
```
```release-note
None
```
```docs
```

fix: Fix the cluster expiredDay less than 0

---

src/components/Forms/Workload/VolumeSettings/AddVolume/index.jsx

/kind bug
Fixes ##3009
https://user-images.githubusercontent.com/33231138/165318562-fac5edd5-b1bf-4f84-9675-5d9744454e72.mov
```release-note
NONE
```

fix: Failed to edit the volume for the container again when creating a deployment

---

locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/en/l10n-multiclusterProjects-applicationWorkloads-statefulsets-list.js
locales/en/l10n-projects-applicationWorkloads-deployments-list.js
src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
src/pages/projects/components/Modals/ResourceSnapshot/index.jsx

Update UI text of 'Workloads'.
```release-note
None
```

Update UI text of 'Workloads'

---

locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js

Update UI text of 'Volume Snapshots'.
```release-note
None
```

Update UI text of 'Volume Snapshots'

---

src/components/Cards/Containers/Item.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
src/pages/projects/components/Cards/ContainerTemplate/Item.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4345
```
```
```release-note
None
```
```docs
```

fix: Fix not show probe tooltip when it has data

---

src/pages/clusters/containers/Network/IPPools/Detail/index.jsx

/kind bug
Fixes ##3192
```
```
```release-note
NONE
```
```docs
```

fix: Mask field does not need to be displayed

---

src/actions/cd.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3214
```
```
```release-note
None
```
```docs
```

fix: Fix no sync options in the manual method

---

locales/en/l10n-clusterManagement-storage-storageClasses-details.js
locales/en/l10n-clusterManagement-storage-volumes-list.js
src/components/Modals/VolumeFunctionManage/index.jsx
src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/index.jsx
src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx

Update UI text of 'Storage'.
```release-note
None
```

Update UI text of 'Storage'

---

locales/en/l10n-devopsProjects-continuousDeployments-list.js
src/pages/devops/containers/CD/CDList/index.jsx
src/utils/constants.js

Update UI text of 'Continuous Deployments'.
/assign @harrisonliu5 @LinuxSuRen
```release-note
None
```

Update UI text of 'Continuous Deployments'

---

src/components/Forms/CD/Advance/index.jsx

/kind bug
Fixes ##3209
```
```
```release-note
NONE
```

fix: When creating a CD task, selecting ‘replace resource' did not take effect

---

OWNERS

Add Patrick-LuoYu to the approver list so that translations from Crowdin can be merged in time.
/assign @harrisonliu5 @zheng1 
```release-note
None
```

Add Patrick-LuoYu to the approver list

---

src/pages/clusters/components/Cards/Cluster/index.jsx
src/pages/clusters/components/Cards/Cluster/index.scss
src/pages/clusters/containers/BaseInfo/index.jsx

/kind design
Fixes #
```release-note
NONE
```

fix: Update button list style

---

server/config.yaml
src/components/Base/ScrollLoad/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
src/stores/devops/scm.js

/kind feature
Fixes #https://github.com/kubesphere/console/issues/3072
```
```
```release-note
Add more repos and orgs in Github
```
```docs
```

feat: Add more repos and orgs in Github

---

src/components/Inputs/ResourceLimit/Slider.jsx

perf
Add throttle for Slider components, Reduce non-essential results returned
```
Test on  project quota config
```
```release-note
None
```
```
None
```

perf: Add throttle for Slider components

---

src/pages/access/containers/Accounts/index.jsx

Fix bug in account item actions.
```release-note
None
```

Fix bug in account item actions

---

locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
src/pages/devops/containers/BaseInfo/index.jsx
src/pages/devops/containers/BaseInfo/index.scss

/kind feature
Fixes #
https://user-images.githubusercontent.com/17872673/165935175-58500493-0151-4cfe-a830-bd647232bb94.mov
```release-note
None
```
```docs
```

feat: Add enabled or disabled of allow list in devops base info

---

src/pages/projects/components/StatusReason/index.scss

/kind bug
Fixes ##3238
```release-note
NONE
```

fix: Container information is blocked

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/LifeManagement/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx

/kind bug
Fixes ##3239
```
```
```release-note
NONE
```

fix: Can not cancel Post-Start or Pre-Stop alone

---

src/pages/projects/containers/Services/Topology/Detail/BaseInfo/index.jsx

/kind bug
Fixes ##3244
```
```
```release-note
NONE
```

fix: The created time of service in Service Topology is error

---

locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
locales/en/workload.js
src/pages/devops/containers/BaseInfo/index.jsx

Update UI text of 'DevOps Projects'.
/assign @harrisonliu5 @LinuxSuRen 
```release-note
None
```

Update UI text of 'DevOps Projects'

---

src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/stores/devops/scm.js

Fixes #https://github.com/kubesphere/ks-devops/issues/577
```
```
```release-note
None
```
```docs
```

fix: Modify the api of get bitbucket org

---

server/config.yaml
src/actions/codeRepo.js
src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Modals/DevOpsAllowList/Destinations.jsx
src/components/Modals/DevOpsAllowList/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.jsx
src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
src/stores/devops/pipelines.js
src/stores/project.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3251 #https://github.com/kubesphere/console/issues/3250 #https://github.com/kubesphere/console/issues/3249
```
```
```release-note
None
```
```docs
```

fix: Add all in repo and placement in allowlist

---

src/pages/projects/containers/Services/Topology/Detail/BaseInfo/index.jsx

/kind bug
Fixes ##3247
```release-note
NONE
```

fix: Update key name for service topology detail item

---

src/actions/devops.js
src/components/Modals/DevOpsAllowList/Destinations.jsx
src/components/Modals/DevOpsAllowList/index.jsx
src/pages/devops/containers/BaseInfo/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3254 #https://github.com/kubesphere/console/issues/3255 #https://github.com/kubesphere/console/issues/3256
```
```
```release-note
None
```
```docs
```

fix: Fix the display error in allowlist

---

server/controllers/session.js

/kind feature
Fixes #
```
```
```release-note
None
```
```docs
```

feat: Support state parameter in OAuth URL

---

locales/en/l10n-clusterManagement-storage-persistentVolumeClaims-list.js
src/actions/volume.js

Update UI text of 'Persistent Volume Claims'.
```release-note
None
```

Update UI text of 'Persistent Volume Claims'

---

src/pages/projects/containers/Services/Topology/Detail/Containers/index.jsx

/kind bug
Fixes #[#4853](https://github.com/kubesphere/kubesphere/issues/4853)
```
```
```release-note
NONE
```

fix: Wrong name of containers in service details in Service Topology

---

src/pages/devops/containers/Base/List/index.jsx
src/pages/devops/routes/index.js

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Optimize the index path in devops by role

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
src/components/Forms/Workload/ContainerSettings/index.scss
src/components/Graph/Card/index.scss
src/pages/clusters/containers/Overview/Initializing/KubeKeyCluster/Logs/index.scss
src/pages/fedprojects/components/ClusterWorkloadStatus/index.scss
src/pages/projects/components/Cards/ImageRunRecord/Item/index.scss
src/scss/markdown.scss
src/scss/mixins.scss

/kind bug
Fixes ##3275
```
```
```release-note
NONE
```

The sonarqube test bug for v3.3.0-alpha.x

---

src/pages/clusters/containers/Nodes/index.jsx
src/stores/node.js

/kind bug
Fixes #[#4783](https://github.com/kubesphere/kubesphere/issues/4783)
a user-facing change?
```release-note
NONE
```
```docs
The control-plane node also can be a work node.
```

fix: Worker node statistics error

---

server/config.yaml
src/actions/codeRepo.js
src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
src/pages/devops/containers/BaseInfo/index.jsx
src/stores/devops/scm.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3265 #https://github.com/kubesphere/console/issues/3280
```
```
```release-note
None
```
```docs
```

fix: Compatible with version 3.2 of Devops

---

locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleItem.jsx

Update UI text of 'Alerting Policies'.
```release-note
None
```

Update UI text of 'Alerting Policies'

---

src/pages/clusters/containers/BaseInfo/index.jsx
src/pages/clusters/containers/BaseInfo/index.scss

/kind bug
Fixes #
```release-note
NONE
```

fix: Update button width

---

server/services/session.js
src/actions/cd.js
src/components/Forms/CD/BaseInfo/index.jsx
src/components/Modals/DevOpsAllowList/CodeRepoSelect.jsx
src/components/Modals/DevOpsAllowList/index.jsx

Fixes #https://github.com/kubesphere/console/issues/3156 #https://github.com/kubesphere/ks-devops/issues/584
```
```
```release-note
None
```
```docs
```

fix: Fix code repository option show

---

server/services/session.js

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: Update cluster role

---

server/services/session.js

/kind bug
Fixes #
```
```
```release-note
Add cluster view permission when user add one cluster
```
```docs
```

feat: Add cluster view permission when user add one cluster

---

src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
src/pages/fedprojects/containers/Gateway/Access/index.jsx

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix the permission of gateway view

---

server/services/session.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4898
```
```
```release-note
```
```docs
```

fix: Fix workspace api error due to error cluster role

---

src/components/Base/Image/index.jsx
src/pages/apps/containers/Reviews/index.jsx

/kind bug
Fixes #
```
```
```release-note
```
```docs
```

fix: Fix the workspace show error in app review list

---

locales/en/l10n-clusterManagement-storage-volumeSnapshotClasses-list.js

Signed-off-by: Bettygogo2021 <91529409+Bettygogo2021@users.noreply.github.com>
What type of PR is this?
What this PR does / why we need it:
Fix a grammar issue in the description.
Special notes for reviewers:
Does this PR introduce a user-facing change?
```release-note
None
```

Fix UI description in volume snapshot class

---

src/pages/projects/containers/Services/index.jsx

/kind bug
Fixes ##3046
```release-note
NONE
```

fix: Optimize the 'Service Type' and 'External Access' columns of the service list for project

---

src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
src/pages/clusters/containers/Gateway/Components/GatewayEmpty/index.jsx
src/pages/clusters/containers/Visibility/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3309 #https://github.com/kubesphere/kubesphere/issues/4907
```
```
```release-note
None
```
```docs
```

fix: Fix the permission of user in cluster page

---

locales/en/l10n-workspaces-appManagement-appTemplates-details.js
src/configs/openpitrix/version.js
src/pages/apps/components/Modals/VersionSubmit/index.jsx
src/utils/app.js

Update UI text of 'App Templates'.
```release-note
None
```

docs: Update UI text of 'App Templates'

---

src/pages/devops/components/Pipeline/PipelineTemplate/index.jsx
src/scss/mixins.scss

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Optimize the css style of webkit-box-orient

---

locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js

Update UI text of permissions.
```release-note
None
```

docs: Update UI text of permissions.

---

server/controllers/session.js
server/controllers/view.js
server/libs/utils.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3205
```
```
```release-note
None
```
```docs
```

fix: Fix the error that the user name is Chinese when logging in by oath

---

server/config.yaml
src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
src/pages/clusters/containers/Storage/VolumeSnapshots/Snapshots/index.jsx
src/pages/projects/containers/Volumes/Detail/index.jsx

/kind bug
Fixes ##3335,##3336
```
```
```release-note
NONE
```

fix: In member clusters below v3.3.0, some functions should be disabled and prompt to upgrade

---

package.json
src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.jsx
src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.scss
src/pages/devops/containers/CD/CDList/index.jsx
yarn.lock

/kind bug
1. fix the cd and code repo icon not change color when it is selected.
2. hide the summary of the cd that it is of no value.
3. remove the extra padding in detail of volume-snapshot
Fixes #
```release-note
None
```
```docs
```

fix: Optimize the UI

---

server/services/session.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3342
```
```
```release-note
None
```
```docs
```

fix: Fix the select not open in select image

---

src/actions/volume.js

/kind bug
Fixes # #3336
```
```
```release-note
NONE
```

fix: Create a snapshot of the storage volume, the page is not refreshed

---

src/actions/cd.js
src/actions/codeRepo.js
src/components/Forms/CD/Advance/Placement/index.jsx
src/components/Forms/CD/BaseInfo/index.jsx
src/components/Modals/DevOpsAllowList/CodeRepoSelect.jsx
src/components/Modals/DevOpsAllowList/index.jsx
src/components/Modals/ProjectSelect/Card/index.jsx
src/pages/devops/containers/Base/List/index.jsx
src/pages/devops/containers/BaseInfo/index.jsx
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CD/detail/SyncStatus/index.jsx
src/pages/devops/containers/CD/detail/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.jsx
src/pages/devops/containers/layout.jsx
src/stores/cd.js
src/stores/codeRepo.js
src/stores/devops.js

/kind bug
Fixes #https://github.com/kubesphere/ks-devops/issues/619
```
```
```release-note
None
```
```docs
```

fix: Fix Add the cluster in code repo API

---

src/pages/clusters/components/Modals/Accessor/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Project list data not incorrect

---

src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx
src/components/Forms/Workload/ContainerSettings/Affinity/index.jsx
src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
src/pages/projects/containers/DaemonSets/Detail/index.jsx
src/pages/projects/containers/StatefulSets/Detail/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/2367#issuecomment-1148232457 #https://github.com/kubesphere/console/issues/2408
```
```
```release-note
None
```
```docs
```

fix: Edit the workload resources not refresh

---

locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx

/kind bug
Fixes ##2430
https://user-images.githubusercontent.com/33231138/172339500-efc013c4-6e41-46ac-979b-979be488e505.mov
```release-note
NONE
```
```docs
```

fix: The mounted path of specific keys should be the relative path for multi-cluster deployment

---

locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx

/kind bug
Fixes #
https://user-images.githubusercontent.com/33231138/172515440-babd4cdd-5e6a-420c-a915-839bbd1d27f2.mov
```release-note
NONE
```
```docs
```

fix: The relative path does not recognize '../'

---

src/scss/base.scss

/kind bug
Fixes ##3357
```release-note
NONE
```
```docs
```

fix: Alert message overflow out of box

---

src/components/Modals/StorageclassAutoresizer/TailItemInput/index.jsx
src/components/Modals/StorageclassAutoresizer/index.jsx

/kind bug
Fixes ##[4968](https://github.com/kubesphere/kubesphere/issues/4968)
Now, no space field is here.
```release-note
NONE
```
```docs
```

fix: Disallow input value with space filed

---

src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.jsx
src/pages/clusters/containers/Storage/VolumeSnapshots/Snapshots/index.jsx
src/utils/constants.js

/kind bug
Fixes ##[4957](https://github.com/kubesphere/kubesphere/issues/4957),##3368
https://user-images.githubusercontent.com/33231138/173302262-c64cd492-1401-4874-8feb-dcabde725005.mov
```release-note
NONE
```
```docs
```

fix: Storageclass name incorrect when creating a volume from a snapshot

---

src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
src/pages/projects/containers/Volumes/Detail/index.jsx

/kind bug
Fixes ##3371
```
```
```release-note
NONE
```
```docs
```

fix: Member clusters below v3.3.0 should not support automatic expansion

---

src/components/Cards/Containers/Item.jsx
src/components/Inputs/EnvironmentInput/ArrowModal/index.jsx
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CD/Components/ChartCard/index.jsx
src/pages/devops/containers/CD/Components/StatusText/index.jsx
src/pages/devops/containers/CD/detail/index.jsx
src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
src/pages/projects/containers/Services/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4970#event-6794332049 #https://github.com/kubesphere/kubesphere/issues/4967#event-6794435166 #https://github.com/kubesphere/kubesphere/issues/4960 #https://github.com/kubesphere/kubesphere/issues/4961
```
```
```release-note
None
```
```docs
```

fix: Fix some bug about CD and service

---

src/components/Inputs/EnvironmentInput/Item.jsx

/kind bug
Fixes ##[4962](https://github.com/kubesphere/kubesphere/issues/4962)
```
```
https://user-images.githubusercontent.com/33231138/173338737-abbb9b0d-e385-45c0-b811-304b51d5e527.mov
```release-note
NONE
```
```docs
```

fix: Unable to delete the last character of env variable key

---

src/actions/codeRepo.js
src/components/Modals/StorageclassAutoresizer/Slider/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4978 #https://github.com/kubesphere/kubesphere/issues/4975
```
```
```release-note
None
```
```docs
```

fix: Fix the repo url is incorrect when edit

---

src/components/Inputs/EnvironmentInput/Item.jsx

/kind bug
Fixes #
Now:
https://user-images.githubusercontent.com/33231138/173488969-f86a447f-5676-43a3-aa77-44d81980cff6.mov
```release-note
NONE
```
```docs
```

opt: Unable to delete the last character of env variable key

---

locales/en/l10n-projects-overview.js
src/pages/projects/containers/Overview/Applications/index.jsx

Update UI text of 'Projects' and 'Clusters'.
```release-note
None
```

docs: Update UI text of 'Projects' and 'Clusters'

---

locales/en/l10n-clusterManagement-storage-volumeSnapshots-details.js
locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js

Update UI text of 'Volume Snapshots'.
```release-note
None
```

docs: Update UI text of 'Volume Snapshots'

---

src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CD/detail/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4979
```
```
```release-note
None
```
```docs
```

fix: Fix the update time is '-' when it is empty

---

src/components/Modals/ContianerTerminal/index.jsx
src/components/Modals/KubeCtl/index.jsx
src/components/Terminal/index.jsx
src/components/Terminal/terminal.jsx
src/stores/terminal.js

/kind bug
Fixes ##[4982](https://github.com/kubesphere/kubesphere/issues/4982)
```
```
```release-note
NONE
```
```docs
```

fix: Can't connect to kubectl due to the url

---

src/components/Inputs/EnvironmentInput/ArrowModal/index.jsx
src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.jsx

/kind bug
Fixes #
https://user-images.githubusercontent.com/33231138/173801405-f4cebbb0-b5ab-46eb-8653-74b5708bf4fb.mov
```release-note
NONE
```
```docs
```

fix: Batch reference modal's position incorrect

---

src/utils/socket.client.js

/kind bug
Fixes #
The bug is here:
https://user-images.githubusercontent.com/33231138/174250298-c559bc82-edfc-4291-aa29-606e09724915.mov
```release-note
NONE
```
```docs
```

fix: Kubectl terminal shell text error

---

locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/en/l10n-devopsProjects-continuousDeployments-list.js
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/projects/components/Modals/AppTemplateEdit/index.jsx
src/utils/constants.js

Fix bugs of UI text.
```release-note
None
```

docs: Fix bugs of UI text

---

server/config.yaml
server/controllers/api.js
server/controllers/session.js
server/libs/request.js
server/routes.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/core/containers/Login/index.jsx
src/stores/container.js
src/utils/index.js

/kind bug
Fixes #https://github.com/kubesphere/security/issues/56 #https://github.com/kubesphere/security/issues/57
```
```
```release-note
None
```
```docs
```

fix: Fix harbor and dockerhub api formget to post

---

locales/ar/pipeline.js
locales/en/l10n-clusterManagement-storage-storageClasses-details.js
locales/en/pipeline.js
locales/es/pipeline.js
locales/fr/pipeline.js
locales/hi/pipeline.js
locales/ko/pipeline.js
locales/lt/pipeline.js
locales/pl/pipeline.js
locales/tc/pipeline.js
locales/tr/pipeline.js
locales/zh/pipeline.js
src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx

Update UI text of 'Auto Expansion'.
Fix issue #[3403](https://github.com/kubesphere/console/issues/3403).
```release-note
None
```

docs: Update UI text of 'Auto Expansion'

---

src/components/Modals/KubeCtl/index.jsx
src/pages/clusters/containers/Nodes/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: The kubectl url of member cluster's node incorrect

---

src/pages/clusters/containers/EdgeNodes/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: The kubectl url of member edge node incorrect

---

server/libs/utils.js

/kind bug
Fixes #https://github.com/kubesphere/security/issues/58
```
```
```release-note
None
```
```docs
```

fix: Fix the valide of referer url

---

server/config.yaml

Signed-off-by: Prajwal Borkar <prajwalborkar5075@gmail.com>
The documentation in the Pipelines page is not found.
Fixes #https://github.com/kubesphere/ks-devops/issues/721
```
```
```release-note
fix: docs in pipeline page 404 not found 
```
```docs
None
```

fix: docs in pipeline page 404 not found

---

src/components/Forms/StorageClass/StorageClassSettings/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/index.jsx

/kind bug
Fixes #[#kubesphere/5051](https://github.com/kubesphere/kubesphere/issues/5051)
```
```
```release-note
NONE
```

fix: Wrong "volumeBindingMode" params when I add PVC 

---

locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
src/components/Tables/Base/Pagination/index.jsx
src/components/Tables/Base/Pagination/index.scss
src/components/Tables/Base/index.jsx
src/components/Tables/Base/index.scss
src/utils/constants.js

/kind feature
Fixes #
https://user-images.githubusercontent.com/33231138/178916175-c07d77df-aefe-4548-ae7a-253fee8d8df1.mov
```release-note
Support for modifying the number of data per page of table
```

feat: Support for modifying the number of data per page of table

---

locales/en/l10n-clusterManagement-nodes-clusterNodes-details.js
locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-details.js
src/components/Cards/Pods/Item.jsx
src/components/Tables/Base/index.jsx
src/pages/clusters/containers/Gateway/Components/Pods/Item.jsx
src/pages/projects/components/Cards/Workloads/Item.jsx
src/pages/projects/containers/Services/index.jsx

Update UI text of creation/update time.
```release-note
None
```

docs: Update UI text of creation/update time

---

docs/development-workflow.md

kubesphere console community requires signature(GPG or S/MIME) verification when submitting code, but it is not mentioned in the  development-workflow.md document about how to submit a PR, also it is not reflected in the git commit submission command. 
The error git commit command mislead the commiters when submit a commit,  Thus this  result in repeated submissions or modify commit message.
```
```
```release-note
None
```

docs: modify git commit command line and add signature reference documentation

---

src/pages/projects/components/Cards/Services/Item.jsx
src/pages/projects/containers/Applications/CRDAppDetail/index.jsx

/kind bug
Fixes #[#4985](https://github.com/kubesphere/kubesphere/issues/4985)
For `Template-based app`:
For composed App:
```release-note
NONE
```
```docs
```

fix: Optimize the 'Application governance' parameter on the app details page

---

locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
package.json
server/config.yaml
src/components/Forms/Notification/DingTalkForm/KeyWords.jsx
src/components/Forms/Notification/FeiShuForm/index.jsx
src/components/Forms/Notification/FeiShuForm/index.scss
src/components/Modals/CustomMonitoring/components/Graph/Compose/index.scss
src/components/Tree/style.scss
src/pages/settings/components/Cards/Banner/index.jsx
src/pages/settings/containers/Notification/DingTalk/index.jsx
src/pages/settings/containers/Notification/FeiShu/index.jsx
src/pages/settings/containers/Notification/Mail/index.jsx
src/pages/settings/containers/Notification/Slack/index.jsx
src/pages/settings/containers/Notification/WeCom/index.jsx
src/pages/settings/routes/index.js
src/stores/notification/base.js
src/utils/form.templates.js
yarn.lock

/kind feature
Fixes #
```
```
```release-note
feat: add feishu in notification and update the version of notification api
```
```docs
```

feat: add feishu in notification and update the version of notification api

---

locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
locales/en/l10n-projects-applicationWorkloads-statefulsets-list.js
src/pages/clusters/containers/Workload/DaemonSets/index.jsx
src/pages/clusters/containers/Workload/StatefulSets/index.jsx
src/pages/fedprojects/containers/Deployments/index.jsx
src/pages/fedprojects/containers/StatefulSets/index.jsx
src/pages/projects/containers/DaemonSets/index.jsx
src/pages/projects/containers/Deployments/index.jsx
src/pages/projects/containers/StatefulSets/index.jsx
src/stores/federated.js
src/stores/workload/index.js

/kind feature
Fixes ##3349
```
```
```release-note
Support batch stop workloads
```
```docs
```

feat: Support batch stop workloads

---

locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
src/components/Forms/Service/AdvanceSettings/InternetAccess/index.jsx
src/components/Forms/Service/AdvanceSettings/InternetAccess/index.scss
src/components/Forms/Service/AdvanceSettings/index.jsx
src/stores/openelb.js

/kind bug
Fixes ##[5006](https://github.com/kubesphere/kubesphere/issues/5006)
https://user-images.githubusercontent.com/33231138/180372106-42d4b132-7eca-462c-87b7-592777ec3e47.mov
```release-note
fix: Missing openelb annotation hint when creating service of type loadbalancer
```
```docs
```

fix: Missing openelb annotation hint when creating service of type loadbalancer

---

locales/en/l10n-devopsProjects-pipeline-details.js
src/actions/pipeline.js
src/pages/devops/components/Modals/JenkinsEdit/index.jsx
src/pages/devops/components/Pipeline/Sider/index.jsx
src/pages/devops/components/Pipeline/store.js
src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
src/pages/devops/containers/Pipelines/Detail/PipeLine/index.scss
src/stores/devops/pipelines.js

/kind feature
This PR avoids using API tojson and tojenkinsfile
Fixes #[714](https://github.com/kubesphere/ks-devops/issues/714)
```
```
```release-note
NONE
```
```docs
```

refactor: Avoid using API tojson and tojenkinsfile

---

src/stores/openelb.js

Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Update OpenELB check url

---

src/components/Forms/StorageClass/StorageClassSettings/index.jsx
src/utils/constants.js

/kind bug
Fixes ##3362
```
```
```release-note
NONE
```
```docs
```

fix: incorrect parameters were created by glusterfs storageclass

---

src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
src/pages/fedprojects/components/ClusterWorkloadStatus/ScheduleCluster.jsx
src/pages/fedprojects/components/ClusterWorkloadStatus/index.scss

/kind bug
Before:
Fixes #
Now:
```release-note
NONE
```
```docs
```

fix: Status icon not show in multi-cluster deployment

---

locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-details.js
locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
src/components/Tables/Base/Pagination/index.jsx
src/pages/projects/containers/Applications/OPApps.jsx

Update UI text.
```release-note
None
```

docs: Update UI text

---

locales/en/l10n-clusterManagement-storage-storageClasses-list.js
src/components/Forms/StorageClass/StorageClassSettings/index.jsx
src/components/Inputs/TailIUnitInput/index.jsx

/kind bug
Fixes ##3463
```
```
```release-note
NONE
```
```docs
```

fix: The gidMax and gidMin in the storage class GlusterFs are not format checked

---

src/pages/clusters/containers/BaseInfo/index.jsx

/kind bug
Fixes #[#3445](https://github.com/kubesphere/console/issues/3445)
```
```
```release-note
NONE
```
```docs
```

fix: For single-cluster environments, the 'Update kubeconfig' button should be canceled.

---

src/actions/cd.js
src/components/Forms/CD/Advance/Parameter/HelmForm/index.jsx
src/components/Forms/CD/Advance/Parameter/ImagesInput/index.jsx
src/components/Forms/CD/Advance/Parameter/KustomizeForm/index.jsx
src/components/Forms/CD/Advance/Parameter/index.jsx
src/components/Forms/CD/Advance/Placement/index.jsx
src/components/Forms/CD/Advance/index.jsx
src/components/Modals/CDAdvanceEdit/index.jsx
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CD/detail/index.jsx

Signed-off-by: elichen95 <elichen95@163.com>
/kind feature
Fixes #
```release-note
feat: Support to edit continuous deployments settings
```
```docs
```

feat: Support to edit continuous deployments settings

---

src/pages/projects/components/Modals/CreateApp/index.jsx
src/pages/projects/components/Modals/GatewaySetting/index.jsx
src/pages/projects/components/Modals/ServiceGatewaySetting/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3410
```release-note
fix: Editing a network watcher to understand the error
```
```docs
```

fix: Fix the key is not display in LoadBalancer

---

src/utils/object.mapper.js

/kind bug
Fixes ##[3419](https://github.com/kubesphere/console/issues/3419)
```
```
```release-note
NONE
```
```docs
```

fix: When accessing an edge node, the page is blank and no content is displayed

---

package.json
scripts/checkLocales.js
scripts/locale-plugin.js

/kind feature
Fixes #
```release-note
None
```
```docs
```

feat: Add reminder to sync locales files in command before compiling

---

locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
locales/en/l10n-projects-grayscaleRelease.js
locales/en/l10n-projects-projectSettings-projectRoles-list.js
src/components/Forms/GrayRelease/Components/Card/index.jsx
src/pages/projects/components/Modals/GrayReleaseDetail/Edit/index.jsx
src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
src/pages/projects/containers/Applications/CRDAppDetail/GrayRelease/index.jsx
src/pages/projects/containers/GrayRelease/Categories/index.jsx
src/pages/projects/containers/GrayRelease/Jobs/index.jsx
src/pages/projects/routes/grayrelease.js

Change 'grayscale release job' to 'grayscale release task'
```release-note
None
```

docs: Change 'grayscale release job' to 'grayscale release task'

---

locales/en/l10n-accessControl-workspaces-list.js
locales/en/l10n-toobox-auditLogSearch-list.js
locales/en/l10n-toobox-containerLogSearch-list.js
locales/en/l10n-toobox-resourceEventSearch-list.js
src/components/Modals/AuditingSearch/index.jsx
src/components/Modals/Bill/Details/Cluster/index.jsx
src/components/Modals/EventSearch/index.jsx
src/components/Modals/LogSearch/index.jsx
src/pages/workspaces/components/ResourceTable/index.jsx
src/pages/workspaces/containers/BaseInfo/index.jsx
src/pages/workspaces/containers/Clusters/index.jsx
src/pages/workspaces/containers/Overview/Clusters/index.jsx
src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
src/pages/workspaces/containers/Overview/UsageRanking/index.jsx

Update UI text of log search.
```release-note
None
```

docs: Update UI text of log search

---

locales/ar/l10n-projects-grayscaleRelease.js
locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js

Update UI text of grayscale release.
```release-note
None
```

docs: Update UI text of grayscale release

---

locales/en/l10n-clusterManagement-storage-storageClasses-list.js
server/services/session.js
src/actions/storageclass.js

/kind bug
Fixes #
```release-note
NONE
```
```docs
```

fix: Update delete text for storageclass

---

locales/en/l10n-projects-imageBuilders-details.js
locales/en/l10n-projects-imageBuilders-list.js
src/pages/projects/containers/ImageBuilder/Detail/index.jsx
src/pages/projects/containers/ImageBuilder/index.jsx

Update UI text of image builders.
```release-note
None
```

docs: Update UI text of image builders

---

src/pages/projects/containers/ImageBuilder/index.jsx

Fix bug of UI text.
```release-note
None
```

Fix bug of UI text

---

locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
locales/en/l10n-clusterManagement-storage-storageClasses-list.js
locales/en/l10n-devopsProjects-pipeline-details.js
locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
src/pages/clusters/containers/Workload/DaemonSets/index.jsx

Update UI text for release 3.3.1.
```release-note
None
```

docs: Update UI text for release 3.3.1

---

locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
locales/en/l10n-clusterManagement-storage-storageClasses-list.js
locales/en/l10n-devopsProjects-pipeline-details.js
locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-details.js
locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
src/components/Tables/Base/Pagination/index.jsx
src/pages/clusters/containers/Workload/DaemonSets/index.jsx
src/pages/projects/containers/Applications/OPApps.jsx

Cherry pick UI text to release-3.3.
```release-note
None
```

docs: Cherry pick UI text to release-3.3.

---

locales/en/l10n-projects-imageBuilders-list.js
src/components/Forms/ImageBuilder/LanguageSelect/index.jsx

/kind bug
Fixes #
```release-note
fix: Add empty message in image builder create modal
```
```docs
```

fix: Add empty message in image builder create modal

---

src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx

Fix bug of UI text.
```release-note
None
```

docs: Fix bug of UI text

---

locales/en/l10n-projects-projectSettings-basicInformation.js
src/pages/projects/containers/BaseInfo/index.jsx

Update UI text of project deletion
```release-note
None
```

docs: Update UI text of project deletion

---

src/pages/devops/components/Pipeline/index.jsx
src/pages/devops/components/Pipeline/store.js

Signed-off-by: Bunny <qimiao@yunify.com>
kind api-change
Using the new Jenkins agent label list API
Fixes #[739](https://github.com/kubesphere/ks-devops/issues/739)
```
```
```release-note
NONE
```
```docs
```

refactor: Replace the labelsData api with the nodelabels api

---

src/components/Forms/Service/AdvanceSettings/NodeSchedule/NodeSelect/index.jsx
src/components/Forms/Workload/AdvanceSettings/NodeSchedule/NodeSelect/index.jsx

/kind bug
Fixes #
```
```
```release-note
fix: Modify the cluster module key of edge node
```
```docs
```

fix: Modify the cluster module key of edge node

---

src/stores/openelb.js

/kind bug
Fixes #
```
```
```release-note
fix: Update OpenELB check url 
```
```docs
```

[release-3.3] fix: Update OpenELB check url 

---

package.json
src/pages/projects/containers/Services/index.jsx
src/pages/workspaces/containers/Repos/index.jsx

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

[release-3.3]fix: Fix the External services cause the "Services" page to crash

---

src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx

/kind bug
Fixes ##[5017](https://github.com/kubesphere/kubesphere/issues/5017)
```
```
```release-note
NONE
```
```docs
```

fix: User with cluster view role, view storage class details error

---

src/pages/clusters/containers/Gateway/Components/MonitoringOverview/index.jsx

/kind bug
The units of these metrics should be **seconds**, not **milliseconds**.
Fixes #3537
```
```
```release-note
Fix ingress monitoring data time unit.
```
```docs
```
/cc @harrisonliu5

fix: Fix ingress monitoring data time unit

---

locales/en/l10n-devopsProjects-continuousDeployments-list.js
src/components/Forms/CD/Advance/index.jsx
src/components/Forms/CD/Advance/index.scss

Signed-off-by: elichen95 <elichen95@163.com>
/kind feature
Fixes #
```release-note
feat: Support CD directory recurse
```
```docs
```

feat: Support CD directory recurse

---

server/services/session.js

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Give the cluster view role when a list of clusters can be obtained

---

src/components/Tables/Base/Pagination/index.jsx
src/components/Tables/Base/Pagination/index.scss

/kind bug
Fixes #
```
```
https://user-images.githubusercontent.com/33231138/185286143-55932273-5168-4e74-a9cd-5b1012295519.mov
```release-note
NONE
```
```docs
```

fix: Table pgaesize scroll style

---

server/controllers/session.js

Signed-off-by: elichen95 <elichen95@163.com>
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: OAuth login state error

---

src/pages/projects/components/Modals/ServiceGatewaySetting/index.jsx
src/pages/projects/components/Modals/ServiceGatewaySetting/index.scss

/kind bug
Fixes ##[5006](https://github.com/kubesphere/kubesphere/issues/5006)
```
```
```release-note
NONE
```
```docs
```

fix: Missing openelb annotation hint when editing service of type loadbalancer

---

src/stores/devops/pipelines.js
src/stores/devops/run.js

/kind bug
Fixes #https://github.com/kubesphere/ks-devops/issues/790 #https://github.com/kubesphere/ks-devops/issues/789
```
```
```release-note
None
```
```docs
```

fix: Fix the limit not change in pagination

---

src/components/Base/Image/index.jsx

/kind bug
Fixes ##3584
```
```
```release-note
NONE
```
```docs
```

fix: App review list page settings pagination fault

---

locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
locales/zh/l10n-toobox-resourceConsumptionStatistics.js
server/controllers/view.js
server/services/session.js
src/components/Base/Image/index.jsx
src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
src/components/Modals/Bill/components/SideCard/item.jsx
src/pages/clusters/containers/Workload/DaemonSets/index.jsx
src/pages/projects/containers/Applications/OPAppDetail/index.jsx

Fixes 
#https://github.com/kubesphere/console/issues/3570 
#https://github.com/kubesphere/kubesphere/issues/4987 
#https://github.com/kubesphere/kubesphere/issues/5104
#https://github.com/kubesphere/kubesphere/issues/5149
```
```
```release-note
None
```
```docs
```

fix: Fix some bugs with testing in rc0

---

src/pages/access/containers/Roles/Detail/AuthorizationList/index.jsx
src/pages/clusters/containers/Roles/index.jsx
src/stores/role.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5149 #https://github.com/kubesphere/console/issues/3569
```
```
```release-note
None
```
```docs
```

fix: Fix the query param of role template in role detail page

---

src/components/Inputs/RulePath/index.jsx
src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
src/pages/projects/components/Modals/CreateApp/Routes/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3598
```
```
```release-note
None
```
```docs
```

fix: Fix router data is incorrect after canceling editing

---

src/components/Modals/Bill/components/TimeSelect/index.jsx
src/components/Modals/Bill/components/TimeSelect/index.scss

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3594
```release-note
None
```
```docs
```

fix: Fix the word is blocked in bill page

---

locales/en/l10n-clusterManagement-clusters.js

Update UI text of cluster management.
```release-note
None
```

docs: Update UI text of cluster management

---

locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js

Update UI text of daemonsets.
```release-note
None
```

docs: Update UI text of daemonsets

---

src/components/Forms/AppDeploy/AppConfig/SchemaForm/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
src/pages/clusters/containers/Clusters/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5173 https://github.com/kubesphere/console/issues/3611
```
```
```release-note
None
```
```docs
```

fix: Fix some issues about image search and edit cluster config

---

locales/en/l10n-clusterManagement-clusterSettings-logReceivers-details.js

Update UI text of 'Log Receivers'.
/cherry-pick release-3.3
```release-note
None
```

docs: Update UI text of 'Log Receivers'

---

src/components/Forms/Workload/VolumeSettings/VolumeList/index.jsx
src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/index.jsx

Fixes #https://github.com/kubesphere/console/issues/3630
```
```
```release-note
None
```
```docs
```

fix: Fix the initial container is incorrect when deleting the volume

---

src/pages/projects/components/Modals/ServiceGatewaySetting/index.scss

/kind bug
Fixes ##[5006](https://github.com/kubesphere/kubesphere/issues/5006)
```
```
```release-note
NONE
```
```docs
```

fix: Update openelb style

---

locales/en/idle-components.js

Remove redundant locale entries.
```release-note
None
```

docs: Remove redundant locale entries

---

src/pages/clusters/actions/cluster.js

Here: #[5187](https://github.com/kubesphere/kubesphere/pull/5187)
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Update PatchWorkspaceTemplate PatchType to JsonPathType

---

src/pages/clusters/actions/cluster.js

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Update workspaceapi params

---

locales/en/l10n-accessControl-platformRoles-list.js
locales/en/l10n-clusterManagement-overview.js
locales/en/l10n-workspaces-workspaceSettings-workspaceRoles-list.js

Update UI text of platform roles.
```release-note
None
```

docs: Update UI text of platform roles

---

locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
locales/en/pipeline.js
server/config.yaml
src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
src/components/Forms/Notification/DingTalkForm/index.jsx
src/components/Forms/Notification/FeiShuForm/index.jsx
src/pages/settings/components/Cards/Banner/index.jsx

docs: Update UI text of notification settings.
```release-note
None
```

docs: Update UI text of notification settings

---

src/components/Forms/Service/AdvanceSettings/index.jsx
src/components/Forms/Service/BaseInfo/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/pages/projects/containers/Services/index.jsx

/kind bug
Fixes ##3651
```
```
```release-note
NONE
```
```docs
```

fix: Optimize the description of the application.

---

src/pages/clusters/actions/cluster.js

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Update workspaceapi params structure

---

src/pages/clusters/actions/cluster.js

Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Update workspace api params structure

---

locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
src/pages/apps/containers/StoreManage/index.jsx

Update UI text of notification channels.
```release-note
None
```

Update UI text of notification channels

---

locales/zh/l10n-platformSettings-notificationManagement-notificationChannels.js

Cherry pick locale files from master.
```release-note
None
```

docs: Cherry pick locale files from master.

---

src/components/Forms/Service/BaseInfo/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx

/kind bug
Fixes ##3727,#3728
```
```
```release-note
NONE
```
```docs
```

fix: Create service error

---

server/services/session.js

/kind bug
Fixes ##[5177](https://github.com/kubesphere/kubesphere/issues/5177)
```
```
```release-note
NONE
```
```docs
```

fix: Role 'platform-regular' should not access cluster manager

---

locales/en/idle-components.js
locales/en/l10n-clusterManagement-clusterSettings-clusterRoles-list.js
locales/en/l10n-clusterManagement-overview.js
locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
locales/en/l10n-devopsProjects-pipeline-list.js
locales/en/l10n-projects-projectSettings-projectRoles-list.js
locales/en/l10n-toobox-auditLogSearch-list.js
locales/en/l10n-toobox-containerLogSearch-list.js
locales/en/l10n-toobox-resourceEventSearch-list.js
locales/en/l10n-workspaces-workspaceSettings-workspaceMembers-list.js
locales/en/l10n-workspaces-workspaceSettings-workspaceRoles-list.js
server/config.yaml
src/components/Forms/Route/RouteRules/RuleForm/index.jsx
src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
src/components/Modals/EventSearch/Event/Home/index.jsx
src/components/Modals/LogSearch/Logging/Home/index.jsx
src/pages/clusters/components/Modals/UnbindCluster/index.jsx
src/pages/devops/containers/CodeRepo/CRList/index.jsx
src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
src/pages/projects/components/WorkloadStatus/index.jsx
src/pages/workspaces/containers/DevOps/index.jsx

Fix issue [5149](https://github.com/kubesphere/kubesphere/issues/5149).
```release-note
None
```

docs: Fix UI text bugs

---

src/pages/settings/components/Cards/Banner/index.jsx
src/stores/notification/base.js

Fixes ##3755
```
```
```release-note
NONE
```
```docs
```

fix: Update notification api version

---

src/stores/cluster/index.js

Fixes ##[5226](https://github.com/kubesphere/kubesphere/issues/5226)
```
```
```release-note
NONE
```
```docs
```

fix: Update api version

---

server/config.yaml

Fixes ##[5220](https://github.com/kubesphere/kubesphere/issues/5220)
```
```
```release-note
NONE
```
```docs
```

fix: Role 'platform-self-provisioner' should not be edited.

---

server/config.yaml

Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Delete config field

---

src/actions/cluster.js
src/components/Forms/Secret/SecretSettings/DataForm/index.jsx

Signed-off-by: moweiwei <mo.weiwei@99cloud.net>
/kind bug
Fixes #3437
```
```
```release-note
fix: fix save secret value err when value is chinese
```
```docs
```

fix: fix save secret value err when value is chinese

---

locales/en/l10n-accessControl-platformRoles-list.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
src/pages/projects/containers/Alerting/Messages/index.jsx
src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
src/pages/projects/containers/Alerting/Policies/index.jsx

Update UI text of access control.
```release-note
None
```

docs: Update UI text of access control

---

src/actions/resource.edit.js
src/pages/workspaces/containers/BaseInfo/index.jsx

/kind bug
Fixes ##[5254](https://github.com/kubesphere/kubesphere/issues/5254)
```
```
```release-note
NONE
```
```docs
```

fix: Update workspace update structure

---

locales/en/l10n-clusterManagement-clusterSettings-logReceivers-list.js
src/components/Forms/KafkaForm/Settings/BrokersInput/index.jsx
src/components/Forms/KafkaForm/Settings/index.jsx
src/components/Modals/LogCollectionCreate/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3601
```
```
```release-note
None
```
```docs
```

fix: Fix the service address in log collection form

---

locales/en/l10n-toobox-resourceConsumptionStatistics-workspaceResourceConsumption.js
src/components/Modals/Bill/components/SideCard/item.jsx

/kind bug
Fixes ##3754
```
```
```release-note
NONE
```
```docs
```

fix: Workspace shows error in resource consumption statistics.

---

src/pages/projects/containers/Services/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Update app name

---

docs/join-the-kubesphere-localization-project.md

Update localization guide.
```release-note
None
```

docs: Update localization guide

---

src/pages/projects/components/Cards/Workloads/Item.jsx

/kind feature
the statefulsets or datmonsets workload has the revision(The user can see it on the rollback panel), the revision shouldn't be hidden on the workload list.
```
```
```release-note
display the revision record when the workload type is  statefulsets or daemonsets
```

feat: add revision record on the workload item when type is statefulsets or daemonsets

---

src/pages/clusters/containers/Visibility/index.jsx
src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
src/stores/cluster/index.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5301
```
```
```release-note
None
```
```docs
```

fix: Fixed the cluster list was incorrectly displayed due to roles

---

package.json
src/components/Inputs/ResourceLimit/index.jsx
yarn.lock

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

[release-3.3]fix: Support the value is 0 in resource quotas (#3856)

---

src/components/Inputs/ResourceLimit/index.jsx
src/pages/devops/components/Pipeline/Sider/index.jsx
src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Get detail when pipeline run and add kubeconfigFile credential

---

server/controllers/view.js
server/services/session.js
src/actions/cd.js
src/actions/fluxcd.js
src/components/Forms/CD/FluxCD/Advance/index.jsx
src/components/Forms/CD/FluxCD/Advance/index.scss
src/configs/steps/fluxcd.js
src/pages/devops/containers/CD/CDList/index.jsx
src/pages/devops/containers/CD/detail/FluxApp/index.jsx
src/pages/devops/containers/CD/detail/FluxApp/index.scss
src/pages/devops/containers/CD/detail/SyncStatus/index.jsx
src/pages/devops/containers/CD/detail/index.jsx
src/pages/devops/containers/CD/detail/routes.js
src/utils/constants.js
src/utils/devops.js
src/utils/form.templates.js
src/utils/object.mapper.js

/kind feature
/kind design
Hi guys. This is the frontend part of the FluxCD Integration plan https://github.com/kubesphere/ks-devops/issues/716.
This is the [Demo](https://youtu.be/bWr5dsyR7O4). Here is the [TODOs](https://github.com/kubesphere/ks-devops/discussions/824).
Sorry. I have to say this code may has much "worst practice" in frontend area due to my poor frontend skills. If you are confuse about some lines of code please let me know at the first time.
Fixes #
```
```
```release-note
Yes, It change the CDSMapper in the object.mapper.js
```
```docs
```

feat: Support Basic FluxCD Application management

---

src/pages/clusters/actions/cluster.js
src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
src/pages/clusters/containers/BaseInfo/index.jsx
src/pages/clusters/containers/Visibility/index.jsx
src/stores/workspace.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5260
```
```
```release-note
None
```
```docs
```

fix: Fix visibility and edit cluster button in cluster displayed incorrectly

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md

Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Update slack channel address

---

src/pages/clusters/containers/BaseInfo/index.jsx
src/stores/workspace.js

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Remove cluster in cluster visibility

---

server/config.yaml
src/pages/console/containers/Support/index.jsx
src/pages/console/containers/Support/index.scss

Fixes #
```
```
```release-note
None
```
```docs
```

docs: Modify the link in suport page

---

locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
src/configs/alerting/metrics/node.js

Update UI text of rule groups.
```release-note
None
```

docs: Update UI text of rule groups

---

locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js

Update UI text of FeiShu.
```release-note
None
```

docs: Update UI text of FeiShu

---

locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js

Update UI text of notification management.
```release-note
None
```

docs: Update UI text of notification management

---

src/actions/fluxcd.js
src/components/Forms/CD/FluxCD/Advance/index.jsx

/kind feature
Need to use the ArrayInput component rather than the simple Input.
I described this in the [tech blog](https://kubesphere.io/zh/blogs/fluxcd-design/):
Result:
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

feat: change helm valuesFiles Input component to ArrayInput

---

locales/en/l10n-devopsProjects-continuousDeployments-list.js
src/components/Forms/CD/FluxCD/Advance/index.jsx

/kind chore
Add Crowdin UI string for FluxCD App.
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

chore: Add Crowdin UI string for FluxCD App

---

locales/en/l10n-clusterManagement-clusters.js
src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx

Update UI text of cluster removal.
```release-note
None
```

docs: Update UI text of cluster removal

---

src/components/Inputs/ProjectSelect/index.jsx
src/components/Modals/Network/Policies/index.jsx
src/components/Modals/Network/Policies/index.scss

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5444
```
```
```release-note
fix: Fix some resources not belong current workspace
```
```docs
```

fix: Fix some resources not belong current workspace

---

src/pages/projects/components/Modals/ServiceDelete/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4658
```
```
```release-note
Fix bug: when deleting a service, validate associated pods
```
```docs
```

fix:Fix issue 4658, when deleting a service, validate associated pods

---

src/pages/clusters/containers/Nodes/index.jsx

/kind bug
Node list page, remove work node statistics, node list add role filter
Fixes #https://github.com/kubesphere/console/issues/3079
```
```
```release-note
Fix bug: node list page, remove work node statistics, node list add role filter
```
```docs
```

fix:Fix issue 3079, remove work node statistics, node list add role filter

---

src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5360
```
```
```release-note
fix: Fix the delete button not display in gray release detail page
```
```docs
```

fix: Fix the delete button not display in gray release detail page

---

src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx

/kind bug
Fix devops artifacts download link
Fixes #
```
```
```release-note
Fix devops artifacts download link
```
```docs
```

fix:Fix devops artifacts download link

---

src/pages/projects/components/Modals/CreateApp/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5449
```
```
```release-note
fix: Fix the governance is not changed when creating the sample bookinfo application
```
```docs
```

fix: Fix the governance is not changed when creating the sample bookinfo application

---

locales/en/l10n-projects-applicationWorkloads-services-details.js
src/components/Forms/Workload/VolumeSettings/VolumeList/Card.jsx

/kind bug
Fixes ##[4042](https://github.com/kubesphere/console/issues/4042)
```
```
```release-note
NONE
```
```docs
```

fix: Add translation entries

---

src/actions/volume.js
src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
src/components/Forms/Volume/VolumeSettings/index.jsx
src/pages/fedprojects/components/VolumeSetting/VolumeSettingForm.jsx
src/pages/fedprojects/containers/Volumes/Detail/index.jsx

/kind bug
Fix edit Persistent Volume Claims storage type error in federation project
Fixes #https://github.com/kubesphere/kubesphere/issues/5183
```
```
```release-note
fix: Fix edit Persistent Volume Claims storage type error in federation project
```
```docs
```

fix: Fix edit Persistent Volume Claims storage type error in federation project

---

src/components/EditForms/Workload/PodTemplate/index.jsx
src/components/Forms/Workload/ClusterDiffSettings/ContainersMapper/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/components/Inputs/ContainerPort/index.jsx
src/pages/fedprojects/components/ContainerImage/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3861
```
```
```release-note
fix: Fix image pull secrets deleted by edit page
```
```docs
```

fix: Fix image pull secrets deleted by edit page

---

locales/en/l10n-projects-applicationWorkloads-services-details.js

Signed-off-by: Bettygogo2021 <bettygogo@kubesphere.io>
Fixes #
```
```
```release-note
none
```
```docs
```

fix spelling

---

locales/en/l10n-clusterManagement-applicationWorkloads-routes-list.js
locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/en/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
locales/en/l10n-multiclusterProjects-applicationWorkloads-apps-list.js
locales/en/l10n-multiclusterProjects-applicationWorkloads-routes-list.js
locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
locales/en/l10n-projects-applicationWorkloads-apps-composedApps-list.js
locales/en/l10n-projects-overview.js
locales/en/l10n-projects-projectSettings-basicInformation.js
locales/en/l10n-projects-projectSettings-gatewaySettings-list.js

Signed-off-by: Bettygogo2021 <bettygogo@kubesphere.io>
/assign @VioZhang @harrisonliu5 
Hi, folks, pls review this PR.
Fixes #
```
@VioZhang pls check this PR.
```
```release-note
change route to ingress
```
```docs
```

docs: change route to ingress

---

package.json
src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx
yarn.lock

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix the username and password is empty in secret detail

---

src/components/Clusters/ClusterTitle/index.scss

/kind bug
style: Fix the style of clusters with too long names
Fixes #https://github.com/kubesphere/issues/issues/550
```
```
```release-note
style: Fix the style of clusters with too long names
```
```docs
```

style: Fix the style of clusters with too long names

---

locales/en/l10n-clusterManagement-applicationWorkloads-routes-list.js
locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/en/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
locales/en/l10n-multiclusterProjects-applicationWorkloads-apps-list.js
locales/en/l10n-multiclusterProjects-applicationWorkloads-routes-list.js
locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
locales/en/l10n-projects-applicationWorkloads-apps-composedApps-list.js
locales/en/l10n-projects-overview.js
locales/en/l10n-projects-projectSettings-basicInformation.js
locales/en/l10n-projects-projectSettings-gatewaySettings-list.js

change route to ingress
Signed-off-by: Bettygogo2021 <bettygogo@kubesphere.io>
Signed-off-by: Bettygogo2021 <bettygogo@kubesphere.io>
Co-authored-by: Bettygogo2021 <bettygogo@kubesphere.io>
Fixes #
```
```
```release-note
None
```
```docs
```

[release-3.3]docs: change route to ingress (#4055)

---

src/pages/devops/containers/CD/detail/routes.js
src/stores/cd.js
src/utils/constants.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5461
```
```
```release-note
fix: Change the pod status filter options in page
```
```docs
```

fix: Change the pod status filter options in page

---

src/stores/cd.js
src/utils/constants.js

/kind bug
Fixes #
```
```
```release-note
fix: Change the pod status filter options in page (#4063)
```
```docs
```

[release-3.3]fix: Change the pod status filter options in page (#4063)

---

src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx

/kind bug
Fixes ##3879
```
```
```release-note
NONE
```
```docs
```

fix: Fedrate service's pod replicas can not auto refres

---

src/utils/constants.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5461
```
```
```release-note
fix: Change the Failed to Error in Pod status filter in pod page
```
```docs
```

fix: Change the Failed to Error in Pod status filter in pod page

---

locales/en/l10n-devopsProjects-continuousDeployments-list.js
src/components/Forms/CD/Advance/CodeRepoSetting.jsx
src/components/Forms/CD/Advance/Placement/index.scss
src/components/Forms/CD/Advance/SyncSetting.jsx
src/components/Forms/CD/Advance/index.scss
src/components/Forms/CD/BaseInfo/index.jsx
src/configs/steps/cd.js

Signed-off-by: 胡亚洲 <yazhouhu@yunify.com>
/kind bug
Add more information for continuous deployment parameters
Fixes #https://github.com/kubesphere/console/pull/3454
```
```
```release-note
Add more information for continuous deployment parameters
```
```docs
```

fix:Fix issue 872, add more information for continuous deployment parameters

---

locales/de/index.js
locales/pt/index.js

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

docs: Add the index.js in de and pt

---

locales/en/l10n-devopsProjects-continuousDeployments-list.js
src/components/Base/TypeSelect/index.jsx
src/components/CodeRepoSelector/index.jsx

…t parameters
/kind feature
feat: Replace code repository component in continuous deployments
Fixes #https://github.com/kubesphere/ks-devops/issues/872
```
```
```release-note
feat: Replace code repository component in continuous deployments
```
```docs
```

feat: Replace code repository component in continuous deployments

---

src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
src/utils/object.mapper.js

/kind bug
fix: Add jenkins validate field, fixed jenkins file validate status
Fixes #https://github.com/kubesphere/ks-devops/issues/714
```fix: update jenkins validate status
```
```release-note
fix: Add jenkins validate field, fixed jenkins file validate status
```
```docs
```

fix: Add jenkins validate field, fixed jenkins file validate status

---

locales/en/l10n-devopsProjects-pipeline-list.js
src/components/Forms/Pipelines/BaseInfo/index.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
src/stores/devops/pipelines.js
src/utils/object.mapper.js

/kind feature
Optimize user experience for multi branch pipeline
Fixes #https://github.com/kubesphere/ks-devops/issues/865
```
```
```release-note
Optimize user experience for multi branch pipeline
```
```docs
```

feat: Optimize user experience for multi branch pipeline

---

locales/en/l10n-projects-projectSettings-gatewaySettings-list.js

Fixes #
```
```
```release-note
None
```
```docs
```

doc: Add the project gateway empty desc

---

src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
src/utils/object.mapper.js

/kind bug
feat: When 'jenkinsfile.edit.mode' is json, show the pipeline
Fixes #https://github.com/kubesphere/ks-devops/issues/714
```
```
```release-note
fix: When 'jenkinsfile.edit.mode' is json, show the pipeline
```
```docs
```

fix: When 'jenkinsfile.edit.mode' is json, show the pipeline

---

locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js

/kind bug
Fixes #
```release-note
NONE
```
```docs
```

fix: Update gateway modal text

---

locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js

Fixes #
```
```
```release-note
none
```
```docs
```

Fix: fix typo

---

src/pages/workspaces/containers/BaseInfo/index.jsx

/kind bug
Fixes ##3337
```release-note
NONE
```
```docs
```

fix: Delete manager filed in workspace base info page

---

locales/en/l10n-devopsProjects-pipeline-details.js

fix: Fix devops locales
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix devops locales

---

src/pages/clusters/containers/Gateway/Components/ProjectGatewayList/index.jsx
src/pages/clusters/containers/Gateway/index.jsx

/kind bug
fix: Remove cluster gateway in project gateway list
Fixes #https://github.com/kubesphere/kubesphere/issues/5712
```
```
```release-note
None
```
```docs
```

fix: Remove cluster gateway in project gateway list

---

src/pages/settings/containers/Notification/Slack/index.jsx
src/pages/settings/containers/Notification/Webhook/index.jsx
src/stores/notification/base.js
src/stores/notification/verify.js

/kind bug
fix: Fix notification form field
Fixes #https://github.com/kubesphere/kubesphere/issues/5758
Fixes #https://github.com/kubesphere/kubesphere/issues/5756
Fixes #https://github.com/kubesphere/kubesphere/issues/5754
Fixes #https://github.com/kubesphere/kubesphere/issues/5751
Fixes #https://github.com/kubesphere/kubesphere/issues/5746
```
```
```release-note
None
```
```docs
```

fix: Fix notification form field

---

locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
src/actions/alerting.js
src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
src/pages/projects/containers/Alerting/Policies/index.jsx

Fixes #
```release-note
NONE
```
```docs
```

fix: Add edit basic info modal for rule group

---

locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/CustomExpr/MetircQueryInput/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/CustomExpr/MetircQueryInput/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/CustomExpr/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/NodeSelect.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/WorkloadSelect.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/NodeRule.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/NodeSelector/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/RuleInput/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/RuleInput/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/WorkloadRule.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/RuleList/Card/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/RuleList/Card/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/RuleList/index.jsx
src/components/Forms/AlertingPolicy/AlertingRules/RuleList/index.scss
src/components/Forms/AlertingPolicy/AlertingRules/index.jsx

Fixes #
```release-note
NONE
```
```docs
```

fix: Add rule group edit form

---

src/actions/alerting.js
src/components/Modals/Monitoring/AlertMonitoring/index.jsx
src/components/Modals/Monitoring/AlertMonitoring/index.scss

Fixes #
```release-note
NONE
```
```docs
```

fix: Add rule monitor modal

---

locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
yarn.lock

Fixes #
```
```
```release-note
None
```
```docs
```

docs: Add the USE_IMAGE_DEFAULT_PORTS word

---

src/pages/devops/components/Pipeline/StepModals/application.jsx

/kind bug
fix: Fix devops cd application form field 
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix devops cd application form field (#1479)

---

src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx

/kind bug
fix: Remove multi-branch API request from non-multi-branch pipeline run record page. (#1439)
Fixes #https://github.com/kubesphere/issues/issues/1190
```
```
```release-note
None
```
```docs
```

fix: Remove multi-branch API request from non-multi-branch pipeline run record page. (#1439)

---

server/controllers/api.js
src/components/Cards/Pods/Item.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/ImageTagRadioList/ImageTagRadio.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/ImageTagRadioList/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/ImageTagRadioList/index.scss
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/Ports/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/Ports/index.scss
src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/pages/fedprojects/components/ClusterDiffSettings/index.jsx
src/pages/fedprojects/components/ContainerImage/index.jsx
src/stores/container.js

* feat: Refactor image search
/kind feature
Fixes #
```
```
```release-note
feat: Refactor image search 
```
```docs
```

feat: Refactor image search 

---

src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx

/kind bug
fix: Fix the error when downloading pipeline logs. (#1441)
Fixes #https://github.com/kubesphere/kubesphere/issues/5826
Fixes #https://github.com/kubesphere/kubesphere/issues/5821
```
```
```release-note
None
```
```docs
```

fix: Fix the error when downloading pipeline logs. (#1441)

---

src/actions/cd.js
src/components/Base/TypeSelect/index.jsx
src/components/Forms/CD/Advance/CodeRepoSetting.jsx
src/components/Modals/CredentialCreate/index.jsx
src/pages/devops/containers/CD/CDList/index.jsx

/kind bug
fix: fix cd repoURL error when create cd 
Fixes #https://github.com/kubesphere/kubesphere/issues/5815
Fixes #https://github.com/kubesphere/kubesphere/issues/5816
Fixes #https://github.com/kubesphere/kubesphere/issues/5824
```
```
```release-note
none
```
```docs
```

fix: Fix devops bugs

---

src/utils/devOpsRepos.js

/kind bug
fix: fix create multi branch pipeline git source field
Fixes #
```
```
```release-note
None
```
```docs
```

fix: fix create multi branch pipeline git source field

---

src/components/Forms/CD/Advance/Placement/index.jsx

/kind bug
fix: Filter cd deployment location clusters options by host cluster name
Fixes #https://github.com/kubesphere/kubesphere/issues/5844
```
```
```release-note
None
```
```docs
```

fix: Filter cd deployment location clusters options by host cluster name

---

src/components/Cards/Pods/index.scss

/kind bug
Fixes #https://github.com/kubesphere/console/issues/4175
```
```
```release-note
None
```
```docs
```

fix: Update monitors charts style to fix TinyArea not show bug

---

src/stores/notification/config.js
src/stores/notification/receiver.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/4178
```
```
```release-note
None
```
```docs
```

fix: Update the apiVersion of notification config and receiver

---

locales/en/l10n-logIn.js
locales/zh/l10n-logIn.js
server/controllers/session.js
server/routes.js
server/services/session.js
src/core/containers/Login/index.jsx
src/core/containers/Login/index.scss
src/stores/root.js

feat: Cherry pick LADP
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5862
```
```
```release-note
None
```
```docs
```

feat: Cherry pick LADP

---

src/stores/openpitrix/base.js

/kind bug
https://github.com/kubesphere/kubesphere/issues/5873
```
```
```release-note
None
```

fix: Fix error in applications template page (#5873)

---

locales/ar/l10n-multiclusterProjects-persistentVolumeClaims-details.js
locales/en/l10n-multiclusterProjects-persistentVolumeClaims-details.js
locales/es/l10n-multiclusterProjects-persistentVolumeClaims-details.js
locales/fr/l10n-multiclusterProjects-persistentVolumeClaims-details.js
locales/hi/l10n-multiclusterProjects-persistentVolumeClaims-details.js
locales/pl/l10n-multiclusterProjects-persistentVolumeClaims-details.js
locales/pt/l10n-multiclusterProjects-persistentVolumeClaims-details.js
locales/zh/l10n-multiclusterProjects-persistentVolumeClaims-details.js

Fixes #
```
```
```release-note
doc: fix the poc description
```
```docs
```

doc: fix the poc description

---

build/Dockerfile
build/Dockerfile.dapper

/kind bug
This PR resolves the issue #3839.
Fixes #3839 
```
It would be great to cherry-pick this check-in to 3.3.2 as well.
```
```release-note
chore: support to run in ARM64 environment
```
```docs
```

fix: support to run in ARM64 environment

---

locales/zh/l10n-clusterManagement-nodes-clusterNodes-details.js

/kind bug
Modifying literal expression errors.
Fixes https://github.com/kubesphere/console/issues/4197
```
```
```release-note
doc: Fix a Chinese alias
```
```docs
```

doc: Fix a Chinese alias

---

src/components/Base/CodeEditor/index.jsx
src/pages/devops/components/Pipeline/StepModals/params.jsx

/kind bug
fix: Fix pipeline shell params can't save
Fixes #https://github.com/kubesphere/issues/issues/2050
Fixes #https://github.com/kubesphere/kubesphere/issues/5902
```
```
```release-note
None
```
```docs
```

fix: Fix pipeline shell command can't save

---

src/pages/clusters/containers/Gateway/Components/ProjectGatewayList/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5843
```
```
```release-note
fix: fix project gateway not display in cluster
```
```docs
```

fix: fix project gateway not display in cluster

---

src/pages/console/containers/Dashboard/Admin/History/Card.jsx
src/pages/console/containers/Dashboard/Admin/History/index.jsx
src/pages/console/containers/Dashboard/Admin/History/index.scss

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5831
```
```
```release-note
style: Update dashboard history card style
```
```docs
```

style: Update dashboard history card style

---

src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5906
```
```
```release-note
fix: Fix the status of schedule in pod schedule page
```
```docs
```

fix: Fix the status of schedule in pod schedule page

---

src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
src/utils/devOpsRepos.js

/kind bug
feat: Pipeline detail add code repo attr
Fixes #https://github.com/kubesphere/ks-devops/issues/807
```
```
```release-note
feat: Pipeline detail add code repo attr
```
```docs
```

feat: Pipeline detail add code repo attr

---

locales/ar/l10n-clusterManagement-storage-storageClasses-list.js
locales/de/l10n-clusterManagement-storage-storageClasses-list.js
locales/en/l10n-clusterManagement-storage-storageClasses-list.js
locales/es/l10n-clusterManagement-storage-storageClasses-list.js
locales/fr/l10n-clusterManagement-storage-storageClasses-list.js
locales/hi/l10n-clusterManagement-storage-storageClasses-list.js
locales/ko/l10n-clusterManagement-storage-storageClasses-list.js
locales/lt/l10n-clusterManagement-storage-storageClasses-list.js
locales/pl/l10n-clusterManagement-storage-storageClasses-list.js
locales/pt/l10n-clusterManagement-storage-storageClasses-list.js
locales/tc/l10n-clusterManagement-storage-storageClasses-list.js
locales/tr/l10n-clusterManagement-storage-storageClasses-list.js
locales/zh/l10n-clusterManagement-storage-storageClasses-list.js

/kind bug
This PR fix the translation mistakes when deleting a storage class.
Fixes #4185 
yes
```release-note
fix some translation mistakes.
```

doc: Fix Storage Class translation mistakes

---

locales/ar/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/ar/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/de/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/de/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/es/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/es/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/fr/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/fr/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/hi/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/hi/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/ko/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/ko/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/lt/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/lt/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/pl/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/pl/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/pt/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/pt/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/tc/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/tc/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/tr/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/tr/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/zh/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
locales/zh/l10n-clusterManagement-storage-storageClasses-list.js

Fixes #https://github.com/kubesphere/kubesphere/issues/5828
```
```
```release-note
None
```
```docs
```

dos: fix some words in mistakes

---

server/controllers/api.js
server/libs/request.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss
src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
src/pages/fedprojects/components/ContainerImage/index.jsx
src/stores/container.js

Fixes #https://github.com/kubesphere/kubesphere/issues/5851
```
```
```release-note
fix: fix the tag version of image after the tag is selected 
```
```docs
```

fix: fix the tag version of image after the tag is selected 

---

.github/workflows/main.yaml
.github/workflows/manually.yaml
.github/workflows/nightly-builds.yaml

/kind feature
add github action. when push tags v* to release-*. it will build image.
Fixes #
```
```
```release-note
add github action
```
```docs
```

feat: add github action

---

.github/workflows/main.yaml

/kind bug
Fixes #
change main runtime. when PR is merge run this action.
```
```
```release-note
change main runtime.
```
```docs
```

fix(action): change main runtime.

---

src/pages/apps/containers/Home/index.jsx

Signed-off-by: nyuxiao nyuxiao@163.com
/kind bug
Fix the error occured when user click the menu "New Apps"
```
```
```release-note
None
```
```docs
```

fix: Fix error in AppStore

---

src/pages/projects/components/Cards/HPA/index.jsx
src/pages/projects/components/Cards/HPA/index.scss
src/utils/constants.js
src/utils/index.js

/kind bug
Fixes #https://github.com/kubesphere/issues/issues/2205
```
```
```release-note
fix: fix the window have scroller when it have hpa card
```
```docs
```

fix: fix the window have scroller when it have hpa card

---

src/pages/workspaces/containers/DevOps/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/ks-devops/issues/607
```
```
```release-note
None
```
```docs
```

fix: fix the devops page is block

---

server/config.yaml

/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/5804
```
```
```release-note
None
```
```docs
```

feat: update zh document link in config.yaml

---

src/pages/settings/containers/BaseInfo/index.jsx

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: remove the how to modify platform info in base info

---

server/config.yaml

/kind feature
This PR enables language support for Korean.
(FYI: Korean-localized string files already exist in [`locales/ko`](https://github.com/kubesphere/console/tree/master/locales/ko))
Fixes #4269
```
```
```release-note
None
```
```docs
```

Enable language support for Korean

---

.github/workflows/main.yaml

Fixes #
```
```
```release-note
None
```
```docs
```

ci: add workflow_dispatch trigger to main.yaml

---

packages/core/src/Pages.tsx

Fixes #
```
```
```release-note
None
```
```docs
```

fix: set initial value of isRemoteExtensionLoading to true

---

.github/workflows/sync-to-kse.yml

Fixes #
```
```
```release-note
None
```
```docs
```

ci: update .github/workflows/sync-to-kse.yml

---

.github/workflows/sync-to-kse.yml

Signed-off-by: donniean <donniean1@gmail.com>
Fixes #
```
```
```release-note
None
```
```docs
```

ci: fix TARGET_BRANCH in .github/workflows/sync-to-kse.yml

---

.github/workflows/sync-to-kse.yml

Fixes #
```
```
```release-note
None
```
```docs
```

ci: add setup for Git in sync-to-kse.yml workflow

---

.github/workflows/release.yml

/kind cleanup
sync images to huaweicloud
Fixes #
```
```
```release-note
sync images to huaweicloud
```
```docs
```

sync images to huaweicloud

---

src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
yarn.lock

/kind bug
Fixes #
https://github.com/kubesphere/console/issues/4288
```
```
```release-note
None
```
```docs
```

fix: resourceStatus get podNums (#4280)

---

packages/core/src/run.tsx

/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```

feat: Add KUBESPHERE_EDITION constants to globals config

---

server/controllers/view.js
server/services/session.js

/kind cleanup
The endpoints `/kapis/config.kubesphere.io/v1alpha2/configs/gpu/kinds` and `/apis/installer.kubesphere.io/v1alpha1/clusterconfigurations?name=ks-installer` have been deprecated in version 4.x, so the related requests have been removed.
Fixes #
```
```
```release-note
None
```
```docs
```

chore: remove useless API

---

packages/shared/src/components/UrlInput/index.tsx

/kind feature
for adapting oci-based helmchart repo
Fixes #
```
```
```release-note
add oci protocol to share/UrlInput
```
```docs
```

add oci protocol to share/UrlInput

---

locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
locales/tc/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
locales/zh/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
packages/shared/src/components/Apps/Applications/index.tsx

Fixes #https://github.com/kubesphere/kubesphere/issues/6186
```
```
```release-note
none
```
```docs
```

enhancement: application text adjust

---

.github/workflows/release.yml

/kind cleanup
Remove aliyuncs image registry in `.github/workflows/release.yml`
Fixes #
```
```
```release-note
None
```
```docs
```

ci: remove aliyuncs image registry

---

LICENSE

Fixes #
```
```
```release-note
None
```
```docs
```

Correct and clarify potentially misleading terms in the license file

---

packages/shared/src/components/Apps/Applications/DetailInfo/AppTemplate/index.tsx

/kind bug
resolve tables in the app description readme file not rendering properly
before:
now:
Fixes #
```
```
```release-note
fix: displaying readme of markdown format in appTemplate
```
```docs
```

fix: displaying readme of markdown format in appTemplate

---

.github/PULL_REQUEST_TEMPLATE.md

Update PULL_REQUEST_TEMPLATE to avoid conflict with the GitHub Project.
Fixes #
```
```
```release-note
None
```
```docs
```

ci: update PULL_REQUEST_TEMPLATE.md

---

packages/console/src/pages/clusters/containers/ClusterSetting/Members/index.tsx
packages/console/src/pages/projects/containers/Members/index.tsx
packages/console/src/pages/workspaces/containers/Members/index.tsx
packages/shared/src/components/Roles/AuthorizedUsers/index.tsx
packages/shared/src/components/index.ts
packages/shared/src/stores/user.ts
packages/shared/src/utils/table/hooks/useUrlSearchParamsStatus.ts

/kind bug
1. Members in the Cluster / Workspace / Project will call the users API when refreshed.
2. The "Role" - "Authorized Users" in Cluster / Workspace will invoke the users API.
Links https://github.com/kubesphere/kubesphere/issues/6263
```
```
```release-note
None
```
```docs
```

fix: role and member users issues in clusters / workspaces / projects

---

locales/en/l10n-clusterManagement-clusterSettings-clusterVisibility.js
locales/es/l10n-clusterManagement-clusterSettings-clusterVisibility.js
locales/tc/l10n-clusterManagement-clusterSettings-clusterVisibility.js
locales/zh/l10n-clusterManagement-clusterSettings-clusterVisibility.js
packages/console/src/pages/access/containers/Workspaces/index.tsx
packages/console/src/pages/access/containers/Workspaces/styles.ts
packages/shared/src/components/Modals/DeleteConfirm/DeleteConfirm.tsx
packages/shared/src/stores/workspace.ts

/kind bug
fix: remove workspace support remove projects
Links # https://github.com/kubesphere/project/issues/4803
```
```
```release-note
fix: remove workspace support remove projects
```
```docs
```

fix: remove workspace support remove projects

---

packages/core/src/components/Layouts/BaseLayout/index.tsx

fix: v3Notify show error
Links # https://github.com/kubesphere/kubesphere/issues/6242
```
```
```release-note
fix: v3Notify show error
```
```docs
```

fix: v3Notify show error

---

server/controllers/session.js
server/proxy.js

/kind bug
fix: clear authAuthorizeUrl cookie when redirecting to login
Links #https://github.com/kubesphere/project/issues/4846
https://github.com/kubesphere/kubesphere/issues/6274
```
```
```release-note
none
```
```docs
```

fix: clear authAuthorizeUrl cookie when redirecting to login

---

server/proxy.js

/kind bug
fix: correct spelling mistake in pull request #4340
Links #
```
```
```release-note
none
```
```docs
```

fix:correct spelling mistake

---

locales/en/l10n-logIn.js
locales/es/l10n-logIn.js
locales/tc/l10n-logIn.js
locales/zh/l10n-logIn.js
packages/console/src/pages/access/containers/Accounts/components/UserCreateModal/index.tsx
packages/console/src/pages/access/containers/Accounts/components/UserEditModal/index.tsx
packages/core/src/components/Layouts/Header/UserSetting/BasicInfo/index.tsx

/kind bug
Added validation to the email mentioned in the issue.
Links https://github.com/kubesphere/kubesphere/issues/6306
```
1. modify translations
2. add validation for email
```
```release-note
Added validation to the email mentioned in the issue
```
```docs
```

chore: validate email when editing basic information

---

server/controllers/view.js
server/services/extension.js
server/views/index.html

/kind feature
ref：[#6308](https://github.com/kubesphere/kubesphere/pull/6308)
Links #
```
```
```release-note
support for loading styles provided by extension components
```
```docs
```

feat:Support loading styles declared by extended components

---

server/sample/bookinfo.yaml

/kind bug
Links https://github.com/kubesphere/project/issues/4797
```
none
```
```release-note
none
```
```docs
```

Update bookinfo version to 1.17.0

---

.github/workflows/codeql-analysis.yml

Links #
```
```
```release-note
None
```
```docs
```

ci: v3dist does not require CodeQL

---

packages/console/src/pages/clusters/components/SecretSettings/ImagerRegistry/index.tsx
packages/console/src/pages/clusters/components/SecretSettings/ImagerRegistry/styles.ts
packages/shared/src/stores/secret.ts

/kind bug
Links https://github.com/kubesphere/kubesphere/issues/6318
```
```
```release-note
None
```
```docs
```

fix(secret): update error handling in validateImageRegistrySecret to use response data

---

packages/shared/src/components/Apps/AppCreate/CreateYamlApp/index.tsx
packages/shared/src/constants/patterns.ts

/kind bug
Links #https://github.com/kubesphere/project/issues/4869
```
```
```release-note
None
```
```docs
```

fix: add name rules when create yaml app

---

locales/en/ent-appStore-list.js
locales/es/ent-appStore-list.js
locales/tc/ent-appStore-list.js
locales/zh/ent-appStore-list.js
packages/shared/src/components/Apps/AppsDashBoard/Card.tsx
packages/shared/src/components/Apps/AppsDashBoard/UseGuide.tsx
packages/shared/src/components/Apps/AppsDashBoard/index.tsx

Links https://github.com/kubesphere/kubesphere/issues/6326
```
```
```release-note
none
```
```docs
```

feat: Add KubeSphere App Store usage guide

---

packages/shared/src/components/Apps/AppCreate/CreateHelmApp/index.tsx
packages/shared/src/components/Apps/AppCreate/index.tsx
packages/shared/src/components/Apps/PackageUpload/index.tsx
packages/shared/src/stores/openpitrix/app.ts
packages/shared/src/stores/openpitrix/files.ts
packages/shared/src/stores/openpitrix/version.ts
packages/shared/src/utils/apps.ts

/kind feature
Links #https://github.com/kubesphere/project/issues/4849
the modified components seem to be shared by other parts of the project, so i add new parts (to make formdata request, similar to the original code), and try not to affect original logic 
```
some functions for handling helm chart uploads are defined in openpitrix entension, need to make some modifications there
```
```release-note
None
```
```docs
```

feat: add formdata version of creating helm app

---

packages/console/src/pages/access/containers/Accounts/Detail/components/LoginHistory/index.tsx

Links https://github.com/kubesphere/project/issues/5297
```
```
```release-note
None
```
```docs
```

fix: remove footer display option from LoginHistory component

---

server/services/session.js

Links
https://github.com/kubesphere/project/issues/5051#issuecomment-2588855466
https://github.com/kubesphere/kse-console/pull/5539
```
```
```release-note
None
```
```docs
```

chore: update version api url (#5539)

---

packages/shared/src/components/Apps/AppsDashBoard/Card.tsx
packages/shared/src/components/Apps/AppsDashBoard/UseGuide.tsx

- Adjust Card component width and remove border radius
- Modify operations styling in Card component
- Update UseGuide component spacing and background
Links #https://github.com/kubesphere/project/issues/5486
```
```
```release-note
none
```
```docs
```

fix(UseGuid): update Card and UseGuide components layout

---

package.json

Improve the `dev:client` in npm scripts.
No need to run other scripts before run `yarn run dev:client` .
Links #
```
```
```release-note
None
```
```docs
```

chore: improve npm scripts

---

server/controllers/api.js
server/libs/request.base.js
server/libs/request.js
server/package.json
server/routes.js
yarn.lock

/kind bug
Remove Docker Hub and Harbor API in Node.js
Links
https://github.com/kubesphere/project/issues/5543
https://github.com/kubesphere/project/issues/5454
https://github.com/kubesphere/project/issues/5264
```
```
```release-note
None
```
```docs
```

refactor(container): replace Docker Hub and Harbor image search Node.js API with backend API

---

server/configs/config.yaml

/kind bug
Links #https://github.com/kubesphere/project/issues/5513
```
```
```release-note
None
```
```docs
```

fix: Change cluster overview and base-info auth

---

locales/en/l10n-projects-applicationWorkloads-jobs-list.js
locales/es/l10n-projects-applicationWorkloads-jobs-list.js
locales/tc/l10n-projects-applicationWorkloads-jobs-list.js
locales/zh/l10n-projects-applicationWorkloads-jobs-list.js
packages/console/src/pages/clusters/containers/ApplicationWorkloads/Jobs/Job/index.tsx
packages/console/src/pages/clusters/containers/Workload/Jobs/index.tsx
packages/console/src/pages/projects/containers/ApplicationWorkloads/Jobs/Job/Detail/index.tsx

/kind bug
feat: Add notifications for job re-run operation
Links #https://github.com/kubesphere/project/issues/5476
```
```
```release-note
none
```
```docs
```

feat: Add notifications for job re-run operation

---

packages/core/src/containers/Extensions/Management/Detail/index.tsx

/kind bug
https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-watch
> Start a watch at the most recent resource version, which must be consistent (in detail: served from etcd via a quorum read). To establish initial state, the watch begins with synthetic "Added" events of all resources instances that exist at the starting resource version. All following watch events are for all changes that occurred after the resource version the watch started at.
Links https://github.com/kubesphere/project/issues/5561
```
```
```release-note
None
```
```docs
```

refactor: optimize the WebSocket of InstallPlan on the extension detail page

---

locales/en/l10n-logIn.js
locales/es/l10n-logIn.js
locales/tc/l10n-logIn.js
locales/zh/l10n-logIn.js
packages/core/src/containers/Session/LoginConfirm/index.tsx

/kind bug
Update login confirmation localization files with new messages for account info confirmation and username input across multiple languages (English, Spanish, Traditional Chinese, and Simplified Chinese)
Links #https://github.com/kubesphere/project/issues/5574
```
```
```release-note
none
```
```docs
```

feat: Add new localization strings for login confirmation screen

---

server/controllers/session.js

/kind bug
refactor: Simplify OAuth login redirect handling
Links #https://github.com/kubesphere/project/issues/5578
```
```
```release-note
none
```
```docs
```

refactor: Simplify OAuth login redirect handling

---

packages/core/package.json
packages/core/src/Pages.tsx

/kind bug
fix: refactor page router
Links #https://github.com/kubesphere/project/issues/5652
```
```
```release-note
none
```
```docs
```

fix: refactor page router

---

packages/core/src/Pages.tsx

/kind bug
fix: Fix page router
Links #
```
```
```release-note
none
```
```docs
```

fix: Fix page router

---

packages/console/package.json
packages/shared/package.json
yarn.lock

/kind bug
fix: Fix wujie version
Links #
```
```
```release-note
none
```
```docs
```

fix: Fix wujie version

---

packages/shared/package.json
packages/shared/src/components/Markdown/Markdown.tsx
yarn.lock

/kind feature
Links #
```
```
```release-note
None
```
```docs
```

feat: add id to headings in Markdown component

---

packages/shared/src/stores/base.ts
packages/shared/src/stores/store.ts
packages/shared/src/utils/request.helper.ts

Introduce a new utility function for total count calculation and enhance pagination logic to handle edge cases more effectively. Refactor existing code to utilize the new pagination information structure.
Links #
```
```
```release-note
None
```
```docs
```

refactor: improve pagination handling with new utility functions

---

server/package.json
yarn.lock

/kind bug
node-fetch 2.6.1 has a security vulnerability, 2.6.7 Fixed this vulnerability.
Links 
https://www.cve.org/CVERecord?id=CVE-2022-0235
https://huntr.com/bounties/d26ab655-38d6-48b3-be15-f9ad6b6ae6f7
https://github.com/advisories/GHSA-r683-j2x4-v87g
https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
```
```
```release-note
None
```
```docs
```

chore: update node-fetch to version 2.6.7

---

package.json
yarn.lock

fix CVE-2022-24999
Links https://www.cve.org/CVERecord?id=CVE-2022-24999
```
```
```release-note
None
```
```docs
```

chore: update qs package to version 6.10.3

---

packages/shared/src/stores/base.ts
packages/shared/src/stores/store.ts
packages/shared/src/utils/request.helper.ts

Links #
```
```
```release-note
None
```
```docs
```

refactor: enhance pagination handling to calculate total page count and item count more effectively

---

locales/en/l10n-errors.js
locales/es/l10n-errors.js
locales/tc/l10n-errors.js
locales/zh/l10n-errors.js

fix: improve readability

---

packages/core/src/utils/emitter.tsx

Links #
```
```
```release-note
None
```
```docs
```

refactor: optimize imports in emitter utility by removing unused imports and adjusting import statements

---

packages/console/src/components/EditQuotas/StorageResourceQuota/index.tsx
packages/console/src/pages/clusters/stores/storageClass.ts

/kind bug
Links #https://github.com/kubesphere/project/issues/5794
```
```
```release-note
None
```
```docs
```

fix: Update fetch storage class list api

---

packages/core/src/containers/Errors/403/index.tsx
packages/core/src/containers/Errors/components/ErrorLayout/index.tsx
packages/core/src/containers/Errors/components/ErrorLayout/styles.tsx

Links #
```
```
```release-note
None
```
```docs
```

refactor: replace 403 error page with ErrorLayout component for improved structure and maintainability

---

locales/en/l10n-errors.js
locales/es/l10n-errors.js
locales/tc/l10n-errors.js
locales/zh/l10n-errors.js
packages/core/src/Pages.tsx
packages/core/src/containers/Errors/404/index.tsx
packages/core/src/containers/Errors/routes.tsx

Introduce a NotFound component and route to handle 404 errors, along with localization for error messages.
Links #
```
```
```release-note
None
```
```docs
```

feat: add 404 error page

---

packages/shared/src/hooks/useList/index.ts

can't load all data when create app by app template
Links #https://github.com/kubesphere/kubesphere/issues/6482
```
```
```release-note
none
```
```docs
```

fix(app): app template fetch error

---

packages/shared/src/components/Modals/KubeConfig/index.tsx
packages/shared/src/components/Modals/KubeCtl/index.tsx
packages/shared/src/stores/cluster/index.ts

/kind bug
fix: Filter clusters by role binding existence in KubeConfig and KubeCtl modals
Link #https://github.com/kubesphere/project/issues/4575
```
```
```release-note
none
```
```docs
```

fix: Filter clusters by role binding existence in KubeConfig and KubeCtl modals

---

packages/console/src/components/EditQuotas/utils.ts

/kind bug
feat: enhance resource quota handling and add unit conversion utility
Links #
```
```
```release-note
none
```
```docs
```

feat: enhance resource quota handling and add unit conversion utility

---

packages/console/src/pages/workspaces/containers/Projects/index.tsx

/kind bug
fix: refetch project table after updating quotas
Links #
```
```
```release-note
none
```
```docs
```

fix: refetch project table after updating quotas

---

.github/workflows/kubed-bump.yml
.github/workflows/license-headers.yml
.github/workflows/lock-file-update.yml
.github/workflows/npm-release-canary.yml
.github/workflows/npm-release-next.yml
.github/workflows/npm-release.yml

Links #
```
```
```release-note
None
```
```docs
```

ci: update Node.js setup to use .nvmrc and enable yarn caching

---

.husky/post-checkout
.husky/post-merge
package.json

Links #
```
```
```release-note
None
```
```docs
```

ci: update husky hooks to use lint-staged and add nvm setup scripts

---

.husky/post-checkout
.husky/post-merge

Links #
```
```
```release-note
None
```
```docs
```

ci: enhance nvm setup in husky hooks for better Node.js version management

---

packages/console/src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.tsx

Links https://github.com/kubesphere/project/issues/6361
```
```
```release-note
None
```
```docs
```

fix: change rowKey from "name" to "uid" for better resource identification

---

packages/shared/src/utils/status.ts

/kind bug
fix: Fix deployment status by status.conditions
Links #https://github.com/kubesphere/project/issues/6236
```
```
```release-note
none
```
```docs
```

fix: Fix deployment status by status.conditions
