kubesphere/console

- README.md
- docs/contributing-guide.md
- docs/development-workflow.md
> update(docs): Update docs links

- README.md
- docs/access-backend.md
> update(docs): Add access the backend services of KubeSphere guide

- src/components/Inputs/ArrayInput/index.test.js
- src/components/Inputs/CPUInput/index.test.js
- src/components/Inputs/ContainerPort/index.test.js
- src/components/Inputs/ContainerServicePort/index.test.js
- src/components/Inputs/NumberInput/index.test.js
- src/components/Inputs/ObjectInput/index.test.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> test: add inputs unit test

- README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> refine readme for contribution.

- src/stores/devops/pipelines.js
/kind bug
Fixes #
Fix: https://github.com/kubesphere/console/issues/24
> fix: fix pipeline not update when parameters changed

- src/components/Forms/CICDs/paramsModal.jsx
- src/stores/s2i/builder.js
> /kind bug
Fixes #
Fix: https://github.com/kubesphere/kubesphere/issues/1629
> fix: fix create image builder failed when used special charactors

- README.md
- docs/access-backend.md
- docs/development-with-docker.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> Update dev doc

- src/pages/devops/components/Pipeline/Card/detail.jsx
- src/stores/devops/pipelines.js
- src/utils/devops.js
- src/utils/devops.test.js
- src/utils/object.mapper.js
> /kind bug
> /kind test
fix: https://github.com/kubesphere/console/issues/42
> fix filled wrong default-value when edit hpa

- .github/workflows/clear.yaml
- .github/workflows/main.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> chore: Update github actions

- src/components/Base/Text/index.jsx
- src/components/Cards/Volumes/Item.jsx
- src/components/Cards/Volumes/index.scss
- src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.jsx
- src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.scss
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix pod schedule page styles error

- src/components/Inputs/ResourceLimit/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix resource limit compare error

- src/locales/zh/cicd.js
- src/pages/devops/components/PipelineStatus/card.jsx
- src/pages/devops/components/Status/index.scss
- src/utils/status.js
> /kind bug
fix unstable pipeline status display
https://github.com/kubesphere/kubesphere/issues/1428
> fix: add pipeline new status

- server/libs/request.base.js
- src/components/Modals/ContainerLog/index.jsx
- src/pages/projects/containers/Pods/Containers/Logs.jsx
- src/utils/request.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1518
```
```
```docs
```
> fix: show empty card instead of container log if container is creating

- src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
- src/components/Forms/Service/ServiceSettings/SelectorsInput/index.scss
- src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
- src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.scss
- src/components/Forms/Workload/VolumeSettings/index.jsx
- src/pages/clusters/containers/MonitoringCenter/Monitoring/Cluster/Overview/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fix https://github.com/kubesphere/kubesphere/issues/1591
Fix https://github.com/kubesphere/kubesphere/issues/1610
Fix https://github.com/kubesphere/kubesphere/issues/1596
Fixes #
```
```
```docs
```
> fix: Fix workload select

- src/stores/base.js
> /kind bug
https://github.com/kubesphere/console/issues/49
when deleting item which is selected, the selected item will disappear in delete modal if the list update currently
> fix: delete selected item failed when list update

- src/stores/container.js
> /kind bug
Fixes [#1652](https://github.com/kubesphere/kubesphere/issues/1652)
> fix(docker): docker miss application property when the pod have

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerList/Card.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/locales/zh/workload.js
>
> /kind bug
> /kind design
> 
/kind feature
Fixes https://github.com/kubesphere/kubesphere/issues/1488
```
```
```docs
```
> feat: Support init containers in workload create

- src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.scss
- src/locales/en/workload.js
- src/locales/zh/workload.js
/kind feature
Fixes https://github.com/kubesphere/kubesphere/issues/1487
```
```
```docs
```
> update: Update container probe parameters

- src/pages/projects/components/Cards/AppComponents/Item.jsx
>
> /kind bug
> /kind design
> /kind flake
Fix https://github.com/kubesphere/kubesphere/issues/1714
Fixes #
```
```
```docs
```
> fix: Fix app service protocol error

- src/utils/constants.js
Fixes [#1593](https://github.com/kubesphere/kubesphere/issues/1593)
> refactor: change default image features value

- src/pages/clusters/containers/Workspaces/index.jsx
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/1053
```
```
```docs
```
> fix: Fix workspace search order

- .github/workflows/main.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> chore: Update workflow

- src/stores/role.js
> /kind bug
filter s2i system roles
https://github.com/kubesphere/kubesphere/issues/1023
> fix: filter s2i system roles

- src/stores/base.js
> refactor: use -1 for infinity

- src/stores/devops/pipelines.js
> /kind bug
https://github.com/kubesphere/kubesphere/issues/1517
> fix: pipeline branch list wrong total number

- src/components/Forms/AppTemplate/index.jsx
- src/pages/appStore/containers/App/index.jsx
- src/pages/apps/components/Forms/AppDeploy/index.jsx
- src/pages/apps/containers/Templates/Detail/index.jsx
- src/utils/app.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1770
```
```
```docs
```
> fix: Fix helm values yaml loading

- server/controllers/session.js
- src/utils/request.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1600
```
```
```docs
```
> fix: check token validate before request send

- src/pages/projects/containers/StatefulSets/Detail/ResourceStatus.jsx
- src/stores/workload/resource.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix statefulset service edit if serviceName is empty

- src/components/Tables/Base/index.scss
- src/core/containers/Base/List/index.jsx
- src/pages/projects/containers/CronJobs/index.jsx
- src/pages/projects/containers/Jobs/index.jsx
- src/pages/projects/containers/Routes/index.jsx
- src/pages/projects/containers/Routes/index.scss
- src/pages/projects/containers/Workloads/Base.jsx
- src/pages/projects/containers/Workloads/index.jsx
- src/scss/lego.custom.scss
- src/stores/workload/index.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/console/issues/82
```
```
```docs
```
> update: Update ingress gateway tips and workload counts

- src/locales/en/storage.js
- src/locales/zh/storage.js
- src/pages/clusters/containers/Infrastructure/StorageClasses/Detail/index.jsx
- src/pages/clusters/containers/Infrastructure/StorageClasses/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
- src/utils/object.mapper.js
> /kind bug
Fixes [https://github.com/kubesphere/kubesphere/issues/1580](https://github.com/kubesphere/kubesphere/issues/1580)
> fix: volume detail page report 404 when dependent storage class deleted

- src/components/Forms/Service/BaseInfo/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/console/issues/90
```
```
```docs
```
> fix: Fix service base info form no apps show

- server/components/locale.js
- server/config.yaml
- src/core/i18n.js
- src/utils/index.js
- src/utils/index.test.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> update: Update default language to english

- src/locales/zh/s2i.js
- src/utils/constants.js
https://github.com/kubesphere/kubesphere/issues/1747
> fix: correct s2i deployment status text

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
> /kind bug
concat url prefix judge has / or not
> fix: fix image registry url judgement

- src/components/Cards/ContainerLog/index.jsx
- src/components/Modals/ContainerLog/index.jsx
- src/components/Modals/ContainerLog/index.scss
- src/pages/projects/containers/Pods/Containers/Logs.jsx
- src/stores/container.js
- src/utils/constants.js
- src/utils/request.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1650
```
```
```docs
```
> update: Update container log fecth method

- src/locales/en/storage.js
- src/locales/zh/storage.js
- src/pages/clusters/containers/Infrastructure/StorageClasses/Detail/index.jsx
- src/pages/clusters/containers/Infrastructure/StorageClasses/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
- src/utils/object.mapper.js
> /kind bug
Fixes [https://github.com/kubesphere/kubesphere/issues/1580](https://github.com/kubesphere/kubesphere/issues/1580)
```
the pre pr was merged in 3.0
```
```docs
```
> fix: volume detail page report 404 when denpendent storageclass deleted

- src/pages/projects/containers/Volumes/index.jsx
- src/utils/constants.js
> /kind bug
Fixes [https://github.com/kubesphere/kubesphere/issues/1582](https://github.com/kubesphere/kubesphere/issues/1582)
```
the fix pr is merged in 3.0
```
```docs
```
> Fix/volume status filter no work in 2.1

- src/components/Forms/ImageBuilder/S2IForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/index.jsx
- src/stores/s2i/builder.js
- src/stores/service.js
> /kind bug
https://github.com/kubesphere/kubesphere/issues/1748
https://github.com/kubesphere/kubesphere/issues/1749
> fix: s2i service private image repo bug

- server/controllers/session.js
- server/controllers/view.js
- server/locales/zh.properties
- server/views/error.html
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/console/issues/43
```
```
```docs
```
> update: Ehance error tips when backend services cannot access

- src/pages/projects/containers/Overview/UsageRanking/index.jsx
- src/pages/projects/containers/Overview/UsageRanking/index.scss
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/846
```
```
```docs
```
> update: Update top5 title style

- src/components/Base/Indicator/index.scss
- src/pages/projects/components/JobStatus/index.jsx
- src/pages/projects/containers/Jobs/index.jsx
- src/scss/lego.custom.scss
>
> /kind bug
> /kind design
> /kind flake
Fixes  
https://github.com/kubesphere/kubesphere/issues/1391  
https://github.com/kubesphere/kubesphere/issues/1299  
```
```
```docs
```
> fix: Fix job running flicker status

- src/components/Forms/Secret/SecretSettings/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
- src/locales/zh/secret.js
https://github.com/kubesphere/console/issues/114
remove url scheme in image name
> fix: remove image name with scheme

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/index.jsx
> fix: add image search cache

- src/components/Cards/Containers/Item.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/components/Inputs/ResourceLimit/index.jsx
- src/components/Inputs/StringInput/index.jsx
- src/components/Modals/Create/index.jsx
- src/locales/zh/workload.js
- src/utils/status.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1187
```
```
```docs
```
> update: Update pod status and container status

- src/components/Forms/CICDs/BaseInfo/index.jsx
- src/components/Forms/CICDs/RepoSelect/subForm.jsx
- src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
- src/utils/devops.js
https://github.com/kubesphere/kubesphere/issues/1784
https://github.com/kubesphere/kubesphere/issues/1783
> fix single svn bug

- src/utils/status.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix pod status error

- src/configs/openpitrix/app.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix openpitrix app query params

- src/components/Forms/CICDs/ParamsInput/Item.jsx
- src/pages/devops/containers/Pipelines/Modals/editPipelineConfigModal.jsx
- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/pages/projects/components/Cards/S2iBuilder/log.jsx
- src/pages/projects/containers/ImageBuilder/Detail/Components/EditModal.jsx
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
- src/stores/s2i/run.js
show empty card when s2i container not ready
https://github.com/kubesphere/console/issues/128
change s2i name desc 
https://github.com/kubesphere/console/issues/129
https://github.com/kubesphere/console/issues/124
> fix: get s2i log error when container not ready

- src/stores/workload/revision.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix api version for k8s v1.16

- src/pages/projects/components/WorkloadStatus/index.jsx
- src/utils/status.js
> /kind bug
cant distinguish s2i status or pod status, so add S2I_ prefix.
> fix: need to distinguish s2i status and pod status

- src/locales/en/service.js
Signed-off-by: FeynmanZhou <zpf0610@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> refine description of S2i svc

- src/stores/openpitrix/base.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix op app query conditions

- src/stores/container.js
- src/stores/s2i/builder.js
https://github.com/kubesphere/console/issues/140
> fix: change image search back structure

- src/components/Base/Indicator/index.scss
- src/locales/zh/version.js
- src/pages/projects/containers/Applications/OPApps.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #135 
```
```
```docs
```
> fix: Fix op app status translation

- src/components/Modals/ProjectSelect/index.jsx
- src/pages/workspaces/containers/layout.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1844
```
```
```docs
```
> fix: Fix workspace redirect 404 rule

- src/components/Forms/GrayRelease/Version/ContainerList/index.jsx
- src/configs/openpitrix/app.js
- src/locales/en/app.js
- src/locales/zh/app.js
- src/pages/apps/components/Cards/ScreenshotsEdit/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Remove app screen resolution check

- src/pages/clusters/containers/MonitoringCenter/Alerting/Policy/index.jsx
> /kind bug
Fixes #61 
```
```
```docs
```
> fix: alert list target count different in detail page

- src/stores/notification/mailService.js
> /kind bug
Fixes #144 
```
```
```docs
```
> refactor: remove password field from mail config form

- src/stores/devops/pipelines.js
https://github.com/kubesphere/kubesphere/issues/1867
> fix: fix create pipeline error

- src/components/Graph/Detail/Monitors/TrafficCard.jsx
- src/components/Graph/Detail/PolicyForm/index.jsx
- src/components/Graph/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix update service policy resource version

- src/pages/projects/containers/Jobs/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1874
```
```
```docs
```
> fix: Fix job actions permissions

- src/pages/clusters/containers/MonitoringCenter/Monitoring/Cluster/Overview/index.jsx
- src/stores/monitoring/component.js
> /kind bug
Fixes [https://github.com/kubesphere/kubesphere/issues/1858#event-3033267512](https://github.com/kubesphere/kubesphere/issues/1858#event-3033267512)
> fix: monitor component status display wrong

- src/stores/alerting/resource.js
- src/stores/application/crd.js
- src/stores/base.js
- src/stores/openpitrix/application.js
- src/stores/pod.js
- src/stores/project.js
- src/stores/role.js
- src/stores/s2i/run.js
- src/stores/user.js
- src/stores/workspace/index.js
- src/stores/workspace/member.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1878
```
```
```docs
```
> update: Update list api default order

- src/pages/clusters/containers/MonitoringCenter/Alerting/Message/Detail/Comment/index.jsx
- src/pages/clusters/containers/MonitoringCenter/Alerting/Policy/index.jsx
- src/pages/projects/containers/ImageBuilder/index.jsx
- src/stores/alerting/message.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1873  https://github.com/kubesphere/kubesphere/issues/1870
```
```
```docs
```
> fix: Fix authority errors

- src/pages/projects/containers/Pods/index.jsx
- src/stores/pod.js
- src/utils/object.mapper.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1878
```
```
```docs
```
> fix: Fix pod list sort order

- src/pages/projects/containers/Applications/CRDApps.jsx
- src/pages/projects/containers/Jobs/index.jsx
- src/stores/base.js
- src/stores/openpitrix/application.js
- src/utils/constants.js
- src/utils/object.mapper.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1878#issuecomment-586550610
```
```
```docs
```
> fix: Fix resources list orders

- src/pages/devops/containers/Members/index.jsx
- src/pages/projects/containers/Members/index.jsx
- src/pages/workspaces/containers/Members/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Remove batch modify members

- src/components/Forms/Workload/AdvanceSettings/Metadata/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/console/issues/148
```
```
```docs
```
> fix: Remove labels empty check

- src/utils/yaml.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Remove refs in yaml

- src/components/Cards/ContainerLog/index.jsx
> refactor: remove hightlight word

- src/stores/monitoring/component.js
> /kind bug
Fixes [https://github.com/kubesphere/kubesphere/issues/1858](https://github.com/kubesphere/kubesphere/issues/1858)
> fix: change ks component model healthy check logic

- src/pages/projects/containers/Secrets/Detail/index.jsx
- src/pages/projects/containers/Secrets/index.jsx
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/console/issues/167
```
```
```docs
```
> update: Add secret edit yaml modal

- src/pages/projects/containers/Secrets/Detail/index.jsx
- src/pages/projects/containers/Secrets/index.jsx
- src/stores/secret.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix secret edit yaml

- src/stores/monitoring/pod.js
> /kind bug
Fixes [https://github.com/kubesphere/kubesphere/issues/1256](https://github.com/kubesphere/kubesphere/issues/1256)
```
```
```docs
```
> fix: pod monitoring miss zero data display

- src/components/Base/Avatar/index.jsx
- src/components/Modals/InviteMember/User.jsx
- src/components/Modals/InviteMember/index.scss
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1895
```
```
```docs
```
> fix: Fix role desc expand in invite member modal

- src/configs/openpitrix/app.js
- src/pages/apps/components/Cards/ScreenshotsEdit/index.jsx
- src/pages/projects/components/Modals/RepoApp/Apps/index.jsx
- src/stores/openpitrix/app.js
- src/stores/openpitrix/base.js
fix: Openpitrix api change in github issue
> /kind bug
[issue 1862: Screenshots uploaded in sequence](https://github.com/kubesphere/kubesphere/issues/1862)
[issue 1814: openpitrix api change](https://github.com/kubesphere/kubesphere/issues/1814)
> fix: Screenshots of application uploaded in sequence

- src/locales/en/workload.js
Signed-off-by: FeynmanZhou <zpf0610@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix mistaken words

- server/sample/bookinfo.yaml
- src/pages/projects/components/Modals/CreateApp/Resources/index.jsx
- src/utils/constants.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix application crd componentKinds

- server/libs/utils.js
- src/components/Layout/LoginInfo/index.jsx
- src/utils/index.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1906
```
```
```docs
```
> fix: Fix app manage page logout redirect

- src/pages/projects/components/Cards/S2iBuilder/index.jsx
- src/pages/projects/components/Modals/RebuildS2i/index.jsx
- src/pages/projects/components/Modals/ServiceDelete/index.jsx
- src/stores/s2i/builder.js
if s2ibuilder is deleted, deployment detail page will show error.
> fix: hide error when s2i not found

- src/components/Forms/CronJob/BaseInfo/index.jsx
- src/locales/en/workload.js
- src/locales/zh/workload.js
- src/utils/constants.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1911
```
```
```docs
```
> fix: Fix cronjob max length validate

- src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
- src/locales/en/s2i.js
- src/locales/zh/s2i.js
> fix: remove custom b2i files limit

- src/locales/en/cicd.js
- src/locales/zh/cicd.js
- src/pages/devops/containers/Pipelines/Modals/scanRepositoryLogsModal.jsx
https://github.com/kubesphere/kubesphere/issues/1912
> fix: fix filter out scaner error

- src/components/Forms/CICDs/AdvanceSettings/index.jsx
- src/locales/zh/cicd.js
Signed-off-by: FeynmanZhou <zpf0610@gmail.com>
>
> /kind flake
Fixes #
```
```
```docs
```
> fix mistaken words in pipeline

- src/pages/projects/containers/Pods/index.jsx
- src/pages/projects/containers/Routes/index.jsx
- src/pages/projects/containers/Services/index.jsx
- src/pages/projects/containers/Workloads/Base.jsx
- src/utils/index.js
- src/utils/index.test.js
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1917
```
```
```docs
```
> fix: Fix search by app

- src/utils/object.mapper.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix event start time

- src/components/Forms/Workload/ContainerSettings/ContainerForm/Commands/index.jsx
- src/locales/zh/s2i.js
Signed-off-by: FeynmanZhou <zpf0610@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> fix typo in container settings page

- src/pages/clusters/containers/Dashboard/User/Resources/index.jsx
- src/pages/clusters/containers/Dashboard/User/Resources/index.scss
- src/stores/user.js
/kind bug
Fix pagination problem of project list in normal user dashboard page.
> fix: Fix user dashboard project list pagination

- src/components/Forms/Workload/VolumeSettings/index.jsx
- src/components/HOCs/withList.js
- src/components/HOCs/withTableActions.js
- src/components/Tables/List/index.jsx
- src/core/actions/resource.delete.js
- src/pages/access/containers/Accounts/index.jsx
- src/pages/access/containers/Roles/index.jsx
- src/pages/access/containers/Workspaces/index.jsx
- src/pages/clusters/components/Modals/ClusterSelect/index.jsx
- src/pages/clusters/components/ResourceTable/index.jsx
- src/pages/clusters/containers/Workload/CronJobs/Detail/index.jsx
- src/pages/clusters/containers/Workload/CronJobs/index.jsx
- src/pages/clusters/containers/Workload/DaemonSets/Detail/index.jsx
- src/pages/clusters/containers/Workload/DaemonSets/index.jsx
- src/pages/clusters/containers/Workload/Deployments/Detail/index.jsx
- src/pages/clusters/containers/Workload/Deployments/index.jsx
- src/pages/clusters/containers/Workload/Jobs/Detail/index.jsx
- src/pages/clusters/containers/Workload/Jobs/index.jsx
- src/pages/clusters/containers/Workload/Pods/Detail/index.jsx
- src/pages/clusters/containers/Workload/Pods/index.jsx
- src/pages/clusters/containers/Workload/Routes/Detail/index.jsx
- src/pages/clusters/containers/Workload/Routes/index.jsx
- src/pages/clusters/containers/Workload/Services/Detail/index.jsx
- src/pages/clusters/containers/Workload/Services/index.jsx
- src/pages/clusters/containers/Workload/StatefulSets/Detail/index.jsx
- src/pages/clusters/containers/Workload/StatefulSets/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/pod.js
/kind feature
Refact withList hoc, extract routing subscribe and websocket listen to ListPage Component, extract table actions filter to withTableActions.
> refact: Refact withList hoc

- src/components/Cards/EmptyList/index.jsx
- src/components/Cards/EmptyList/index.scss
- src/components/Cards/LimitRange/index.jsx
- src/components/Cards/LimitRange/index.scss
- src/components/Cards/Pods/index.jsx
- src/components/Cards/ProjectQuota/QuotaItem/index.jsx
- src/components/Cards/ProjectQuota/QuotaItem/index.scss
- src/components/Cards/ProjectQuota/index.jsx
- src/components/Cards/ProjectQuota/index.scss
- src/components/Modals/ProjectCreate/index.jsx
- src/locales/zh/project.js
- src/pages/clusters/containers/Projects/Detail/Gateway/index.jsx
- src/pages/clusters/containers/Projects/Detail/Overview/index.jsx
- src/pages/clusters/containers/Projects/Detail/Pods/index.jsx
- src/pages/clusters/containers/Projects/Detail/Quota/index.jsx
- src/pages/clusters/containers/Projects/Detail/index.jsx
- src/pages/clusters/containers/Projects/Detail/routes.js
- src/pages/clusters/containers/Projects/index.jsx
- src/pages/clusters/routes/detail.js
- src/pages/clusters/routes/index.js
/kind feature
add cluster projects pages
> feat: Add cluster projects pages

- package.json
- src/components/Base/Breadcrumb/index.test.js
- src/components/DiffYaml/index.jsx
- src/components/DiffYaml/index.scss
- src/locales/zh/base.js
- src/locales/zh/workload.js
- src/pages/clusters/containers/Workload/DaemonSets/Detail/routes.js
- src/pages/clusters/containers/Workload/Deployments/Detail/routes.js
- src/pages/clusters/containers/Workload/StatefulSets/Detail/routes.js
- src/pages/projects/containers/AdvancedSettings/LogCollection/index.jsx
- src/pages/projects/containers/BaseInfo/index.jsx
- src/pages/projects/containers/Deployments/Detail/RevisionControl/index.jsx
- src/pages/projects/containers/Deployments/Detail/RevisionControl/index.scss
- src/pages/projects/containers/Overview/Applications/index.jsx
- src/pages/projects/containers/Overview/index.jsx
- src/pages/projects/routes/workload/daemonset.js
- src/pages/projects/routes/workload/deployment.js
- src/pages/projects/routes/workload/statefulset.js
- yarn.lock
/kind feature
Add workload revision compare
> feat: Add workload revision compare

- src/pages/projects/components/Modals/ServiceCreate/index.jsx
- src/pages/projects/containers/Applications/index.jsx
/kind bug
Fix app template list page and service creating modal error.
> fix: Fix app template list and service create modal error

- src/pages/clusters/containers/Nodes/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
> refactor: new montior api

- src/pages/clusters/containers/Nodes/index.jsx
- src/stores/node.js
> /kind bug
cluster node count incorrect
> fix: cluster node count error

- src/configs/alerting/metrics/rule.config.js
- src/locales/zh/workload.js
- src/utils/monitoring.js
/kind feature
Unify memory units
> update: Unify memory units

- server/config.yaml
- src/core/i18n.js
- src/locales/zh/crd.js
- src/pages/clusters/containers/Clusters/index.jsx
- src/pages/clusters/containers/CustomResources/Detail/ConfigFile/index.jsx
- src/pages/clusters/containers/CustomResources/Detail/index.jsx
- src/pages/clusters/containers/CustomResources/Detail/routes.js
- src/pages/clusters/containers/CustomResources/index.jsx
- src/pages/clusters/containers/Overview/index.jsx
- src/pages/clusters/routes/detail.js
- src/pages/clusters/routes/index.js
- src/stores/crd.js
- src/utils/constants.js
- src/utils/index.js
- src/utils/object.mapper.js
/kind feature
Add custom resources definitions page
> feat: Add custom resources definitions page

- server/components/wsProxy.js
- src/components/HOCs/withList.js
- src/components/KubeTools/index.scss
- src/components/Tables/Base/index.jsx
- src/pages/clusters/containers/Nodes/index.jsx
- src/pages/clusters/containers/Projects/index.jsx
- src/pages/projects/containers/Applications/OPApps.jsx
- src/pages/projects/containers/CustomMonitoring/index.jsx
- src/utils/constants.js
/kind bug
fix WebSocket proxy authentication error
> fix: Fix k8s websocket error

- src/components/Forms/AppTemplate/index.jsx
- src/components/KubeTools/index.jsx
- src/components/KubeTools/index.scss
- src/pages/apps/containers/Reviews/index.jsx
- src/pages/projects/components/Modals/DeployApp/index.jsx
- src/stores/openpitrix/application.js
> fix: Fix openpitrix apps loading error

- src/actions/resource.delete.js
- src/pages/access/containers/Workspaces/index.jsx
- src/pages/clusters/components/ResourceTable/ProjectSelect/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/index.jsx
- src/pages/workspaces/components/ResourceTable/ClusterSelect/index.jsx
/kind bug
Fix workspace creating error, when no clusters selected.
> fix: Fix workspace create error

- src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.scss
- src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.scss
- src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
> /kind bug
add cluster select in workspace monitor page
> fix(monitoring): workspace monitor miss params

- src/components/Forms/AppTemplate/index.jsx
- src/components/Forms/ValuesYamlForm/index.jsx
- src/components/Forms/ValuesYamlForm/index.scss
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> feat: add helm chart form support

- scripts/webpack.dev.js
- src/components/Forms/CICDs/AdvanceSettings/index.jsx
- src/components/Forms/CICDs/BaseInfo/index.jsx
- src/components/Forms/CICDs/RepoSelect/subForm.jsx
- src/components/Forms/CICDs/paramsModal.jsx
- src/pages/devops/containers/Cridential/credentialModal.jsx
- src/pages/devops/containers/Cridential/detail/index.jsx
- src/pages/devops/containers/Cridential/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/pages/devops/containers/Pipelines/Modals/editPipelineConfigModal.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops.js
- src/stores/devops/base.js
- src/stores/devops/cridential.js
- src/stores/devops/pipelines.js
- src/utils/constants.js
- src/utils/devops.js
- src/utils/object.mapper.js
change the pipeline api 
Fixes #
```
```
```docs
```
> update:change pipeline api

- server/config.yaml
- server/services/session.js
- src/components/Base/Text/index.scss
- src/components/KubeTools/index.jsx
- src/core/containers/Base/Detail/Page/index.jsx
- src/locales/zh/base.js
- src/locales/zh/settings.js
- src/pages/clusters/containers/Base/Detail/index.jsx
- src/pages/console/containers/Dashboard/Admin/PlatformStatus/Resource.jsx
- src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
- src/pages/console/containers/Dashboard/Admin/index.jsx
- src/pages/projects/containers/Base/Detail/index.jsx
- src/pages/settings/containers/ThirdPartyLogin/index.jsx
- src/pages/settings/containers/ThirdPartyLogin/index.scss
- src/pages/settings/routes/index.js
> fix: Fix dashboard links

- server/services/session.js
- src/components/Layout/LoginInfo/index.jsx
- src/components/Modals/UserSetting/BaseInfo/index.jsx
- src/components/Modals/UserSetting/index.jsx
- src/stores/user.js
/kind bug
Fix language switch.
> fix: Fix language switch

- server/services/session.js
- server/views/blank_markdown.html
- src/locales/zh/app.js
- src/pages/appStore/components/AppPreview/index.jsx
- src/pages/appStore/components/AppPreview/index.scss
- src/pages/appStore/components/Banner/index.jsx
- src/pages/appStore/components/Banner/index.scss
- src/pages/appStore/containers/AppDeploy/AppConfig/index.jsx
- src/pages/appStore/containers/AppDeploy/AppConfig/index.scss
- src/pages/appStore/containers/AppDeploy/BasicInfo/index.jsx
- src/pages/appStore/containers/AppDeploy/BasicInfo/index.scss
- src/pages/appStore/containers/AppDeploy/Placement/index.jsx
- src/pages/appStore/containers/AppDeploy/Placement/index.scss
- src/pages/appStore/containers/AppDeploy/SchemaForm/index.jsx
- src/pages/appStore/containers/AppDeploy/SchemaForm/index.scss
- src/pages/appStore/containers/AppDeploy/Steps/index.jsx
- src/pages/appStore/containers/AppDeploy/Steps/index.scss
- src/pages/appStore/containers/AppDeploy/index.jsx
- src/pages/appStore/containers/AppDeploy/index.scss
- src/pages/appStore/containers/AppDetail/index.jsx
- src/pages/appStore/containers/AppDetail/index.scss
- src/pages/appStore/routes/index.js
- src/pages/projects/containers/Applications/OPAppDetail/index.jsx
- src/pages/projects/containers/Applications/OPApps.jsx
- src/scss/lego.custom.scss
- src/utils/yaml.js
/kind enhancement
Update openpitrix app deploying with a new design.
> update: Update openpitrix app deploy

- src/actions/service.js
- src/actions/workload.js
- src/pages/clusters/containers/Overview/Dashboard/KubernetesStatus/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/ResourcesUsage/index.scss
- src/pages/projects/components/Modals/CreateApp/Services/index.jsx
- src/pages/projects/components/Modals/CreateApp/index.jsx
- src/pages/projects/components/Modals/ServiceDelete/index.jsx
- src/pages/projects/components/Modals/WorkloadDelete/index.jsx
- src/pages/projects/containers/DaemonSets/Detail/index.jsx
- src/pages/projects/containers/DaemonSets/index.jsx
- src/pages/projects/containers/Deployments/Detail/index.jsx
- src/pages/projects/containers/Deployments/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/pages/projects/containers/Services/index.jsx
- src/pages/projects/containers/StatefulSets/Detail/index.jsx
- src/pages/projects/containers/StatefulSets/index.jsx
- src/stores/application/crd.js
- src/stores/base.js
- src/utils/constants.js
/kind bug
Fix related resource deletion tip missing.
> fix: Fix related resource delete

- src/utils/constants.js
- src/utils/form.templates.js
> fix: Fix workspace kind

- package.json
- server/config.yaml
- src/actions/devops.js
- src/components/Forms/Service/AdvanceSettings/index.jsx
- src/components/Forms/Service/ContainerSetting/ContainerForm/index.jsx
- src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
- src/components/Forms/Service/ContainerSetting/index.jsx
- src/components/Modals/DevOpsCreate/index.jsx
- src/components/Modals/DevOpsCreate/index.scss
- src/locales/en/project.js
- src/locales/zh/devops.js
- src/locales/zh/project.js
- src/pages/devops/containers/Members/index.jsx
- src/pages/devops/containers/Roles/Detail/index.jsx
- src/pages/devops/containers/Roles/Detail/routes.js
- src/pages/devops/containers/Roles/index.jsx
- src/pages/devops/routes/detail.js
- src/pages/devops/routes/index.js
- src/pages/projects/components/Modals/ServiceCreate/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/devops.js
- yarn.lock
/kind bug
Fix cluster settings in DevOps creating modal, and add DevOps roles detail, eg.
> fix: Fix devops create modal and devops roles & members

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
> fix: Remove unuse code in container form.

- src/components/HOCs/withList.js
- src/components/Tables/Base/index.jsx
/kind bug
Fix custom columns bug in the table.
> fix: Save hide columns in localStorage by table id

- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/components/Modals/LogSearch/Logging/Detail/index.scss
- src/stores/logging/index.js
- src/stores/logging/query.js
- src/stores/logging/statistics.js
> refactor: remove old api of log query

- src/pages/clusters/containers/Nodes/index.jsx
- src/pages/clusters/containers/Nodes/index.scss
show danger icon when utilization bigger than 0.8
> update: Update node resource request tip

- server/config.yaml
- src/locales/zh/cluster.js
- src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.scss
- src/pages/clusters/containers/Clusters/AddCluster/index.jsx
- src/stores/cluster/index.js
Add validation for cluster creating with kubeconfig
> update: Add validation for cluster creating with kubeconfig

- src/locales/zh/workload.js
- src/stores/terminal.js
/kind bug
Fix kubectl and container terminal link errors
> fix: Fix terminal link

- src/components/Modals/CustomMonitoring/components/GraphOverviewLayout/index.jsx
- src/components/Modals/CustomMonitoring/components/GraphOverviewLayout/index.scss
- src/components/Modals/CustomMonitoring/containers/GraphOverview.jsx
- src/components/Modals/CustomMonitoring/index.jsx
- src/stores/monitoring/custom/monitor.js
cache the Component to pass the react diff and event logic lifecyc
Fixes #
```
```
```docs
```
> perf(custom-monitor): cache the graph list data

- src/components/Base/SearchSelect/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
- src/components/HOCs/withList.js
- src/components/Tables/Base/index.jsx
- src/locales/zh/cluster.js
- src/pages/clusters/components/ResourceTable/ProjectSelect/index.jsx
- src/pages/clusters/components/ResourceTable/ProjectSelect/index.scss
- src/pages/clusters/components/ResourceTable/index.jsx
- src/pages/clusters/containers/Projects/index.jsx
- src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
- src/pages/clusters/containers/Storage/Volumes/index.jsx
- src/pages/clusters/containers/Workload/CronJobs/index.jsx
- src/pages/clusters/containers/Workload/DaemonSets/index.jsx
- src/pages/clusters/containers/Workload/Deployments/index.jsx
- src/pages/clusters/containers/Workload/Jobs/index.jsx
- src/pages/clusters/containers/Workload/Pods/index.jsx
- src/pages/clusters/containers/Workload/Routes/index.jsx
- src/pages/clusters/containers/Workload/Services/index.jsx
- src/pages/clusters/containers/Workload/StatefulSets/index.jsx
- src/pages/clusters/containers/layout.jsx
- src/scss/lego.custom.scss
- src/stores/base.list.js
- src/stores/cluster/index.js
/kind bug
Fix project search error in cluster resource list
> fix: Fix project search in cluster resource list

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- README.md
- src/locales/zh/base.js
> Refine platform setting Chinese description

- src/components/Modals/InviteMember/index.jsx
- src/pages/devops/components/Pipeline/StepModals/git.jsx
- src/pages/devops/components/Pipeline/StepsSelector/index.jsx
- src/pages/devops/containers/Roles/index.jsx
- src/pages/projects/containers/Roles/index.jsx
- src/pages/workspaces/containers/Members/Detail/DevOps/index.jsx
- src/pages/workspaces/containers/Members/Detail/Projects/index.jsx
- src/pages/workspaces/containers/Members/Detail/index.jsx
- src/stores/devops.js
- src/stores/user.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix some errs in devops inclue role and user

- src/components/History/Card.jsx
- src/components/History/index.jsx
- src/components/History/index.scss
/kind bug
Hide history modal if item clicked.
> fix: Hide history modal if item clicked.

- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/components/Modals/LogSearch/Logging/Home/index.jsx
- src/components/Modals/LogSearch/Logging/Home/index.scss
- src/components/Modals/LogSearch/Logging/Search/index.jsx
- src/components/Modals/LogSearch/Logging/Search/index.scss
- src/components/Modals/LogSearch/index.jsx
- src/stores/logging/index.js
add a cluster selector for log query page
> refactor: add cluster selector for log query tools

- src/components/Forms/AppDeploy/BasicInfo/index.jsx
- src/pages/appStore/containers/AppDeploy/index.jsx
- src/pages/apps/components/Modals/AppDeploy/index.jsx
/kind bug
Fix version fetch bug in app deploying form. All versions will be fetched in the project or workspace app deploying form, and only the active versions will be fetched in apps store.
> fix: Fix version fetching status conditions in app deploy form

- src/components/KubeTools/index.jsx
- src/components/KubeTools/index.scss
> fix: Fix toolbox trigger and position

- .github/workflows/main.yaml
/kind bug
Preview env is not suitable for v3.0, remove preview actions.
> chore: Update github workflow, remove preview deploy

- src/components/Cards/Pods/index.jsx
- src/pages/projects/components/Cards/ClusterWorkloadStatus/Cluster.jsx
- src/pages/projects/components/Cards/ClusterWorkloadStatus/index.jsx
- src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
- src/stores/federated.js
/kind bug
Fix resource updating when workload scaled.
> fix: Fix resource update when workload scale

- src/components/Modals/DevOpsCreate/index.jsx
- src/components/Modals/DevOpsCreate/index.scss
- src/components/Modals/ProjectCreate/index.jsx
- src/components/Modals/ProjectCreate/index.scss
- src/components/TextPreview/index.jsx
- src/locales/zh/app.js
- src/locales/zh/app_template.js
- src/locales/zh/service.js
- src/pages/appStore/components/AppPreview/index.jsx
- src/pages/apps/components/AppPreview/index.jsx
- src/pages/apps/components/Lists/VersionList/Item.jsx
- src/pages/apps/components/Modals/AppReview/index.jsx
- src/pages/apps/components/TextPreview/index.jsx
- src/pages/clusters/components/Cards/Cluster/index.jsx
- src/pages/clusters/components/Cards/Cluster/index.scss
- src/pages/clusters/containers/Overview/Dashboard/index.jsx
- src/pages/projects/components/Cards/ClusterWorkloadStatus/Cluster.jsx
- src/pages/projects/components/Modals/CreateApp/Code/index.scss
- src/pages/projects/components/Modals/CreateApp/index.jsx
- src/pages/projects/components/Modals/CreateApp/index.scss
- src/pages/projects/components/Modals/ServiceCreate/InApp.jsx
- src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
- src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.scss
/kind bug
1. Fix cluster group label.
2. Fix application crd app creating error.
> fix: Fix cluster group label and application crd app creating error

- src/components/Modals/EventSearch/Event/Detail/index.jsx
- src/components/Modals/EventSearchs/Event/Detail/MetadataModal/Metadata/index.jsx
- src/components/Modals/EventSearchs/Event/Detail/MetadataModal/Metadata/index.scss
- src/components/Modals/EventSearchs/Event/Detail/MetadataModal/index.jsx
- src/components/Modals/EventSearchs/Event/Detail/MetadataModal/index.scss
- src/components/Modals/EventSearchs/Event/Detail/index.jsx
- src/components/Modals/EventSearchs/Event/Detail/index.scss
- src/components/Modals/EventSearchs/Event/Detail/schema.js
- src/components/Modals/EventSearchs/Event/Home/index.jsx
- src/components/Modals/EventSearchs/Event/Home/index.scss
- src/components/Modals/EventSearchs/Event/index.js
- src/components/Modals/EventSearchs/Event/utils.js
- src/components/Modals/EventSearchs/index.jsx
- src/locales/zh/base.js
- src/stores/eventSearch.js
/kind bug
Fixes https://github.com/kubesphere/console/issues/280
```
```
```docs
```
> event search

- src/components/Modals/Network/Policies/index.scss
- src/pages/projects/containers/Network/Policies/IsolateInfo/index.scss
- src/pages/projects/containers/Network/Policies/index.jsx
/kind flake
update network-isolate status under project 
change the "*true*" to "*enabled*"
> fix:  update network-isolate status under project

- src/components/Base/Tag/index.scss
- src/components/Base/Text/index.jsx
- src/components/Base/Text/index.scss
- src/components/History/Card.jsx
- src/components/Inputs/SelectInput/index.jsx
- src/components/Inputs/SelectInput/index.scss
- src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
- src/pages/clusters/containers/Projects/Detail/Pods/index.jsx
- src/pages/projects/components/Cards/ClusterWorkloadStatus/Cluster.jsx
- src/pages/projects/components/Cards/ClusterWorkloadStatus/index.scss
- src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
- src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.scss
- src/pages/projects/containers/Services/Detail/ServiceAccess/index.jsx
- src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
- src/pages/projects/routes/detail.js
- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
- src/utils/constants.js
> fix: Fix pod link error

- src/stores/user.js
> update: Update api for cluster members

- src/components/Terminal/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/index.jsx
- src/stores/logging/index.js
- src/stores/terminal.js
/kind bug
Fix URL proxy for  single cluster
> fix: Fix api for single cluster

- src/actions/devops.js
- src/pages/clusters/containers/BaseInfo/index.jsx
- src/pages/clusters/routes/index.js
- src/pages/projects/routes/detail.js
- src/pages/projects/routes/index.js
- src/pages/workspaces/components/Modals/WorkspaceCreate/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/cluster/index.js
- src/stores/project.js
/kind bug
Hide some page if there is only one cluster
> fix: Hide some pages in single cluster mode

- server/config.yaml
- src/components/Base/Steps/index.jsx
- src/components/Modals/EditAuthorization/index.jsx
- src/locales/en/base.js
- src/locales/en/cluster.js
- src/locales/en/nodes.js
- src/locales/en/project.js
- src/locales/en/user.js
- src/locales/zh/app.js
- src/locales/zh/base.js
- src/locales/zh/cluster.js
- src/locales/zh/nodes.js
- src/locales/zh/project.js
- src/locales/zh/role.js
- src/pages/access/containers/layout.jsx
- src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
- src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
> chore(locales): Update english locales

- src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
Fixes #301
```
```
```docs
```
> refactor: add ip metric in node rank list

- src/components/Modals/Network/Policies/index.jsx
- src/pages/projects/containers/Network/Policies/index.jsx
- src/pages/projects/containers/Network/Policies/index.scss
/kind bug
remove workspace param on fetch projects and services
> fix: remove workspace param on fetch projects and services

- server/config.yaml
- src/components/Layout/GlobalNav/item.jsx
- src/core/containers/Base/Detail/Page/index.jsx
- src/core/global.js
- src/locales/en/base.js
- src/locales/zh/base.js
- src/locales/zh/role.js
- src/pages/access/containers/Roles/index.jsx
- src/pages/clusters/components/Modals/ClusterSelect/index.jsx
- src/pages/clusters/containers/Clusters/index.jsx
- src/pages/devops/containers/layout.jsx
- src/pages/projects/containers/Base/Detail/index.jsx
- src/pages/projects/containers/layout.jsx
- src/stores/user.js
/kind update
Use rules from upper level when no rules in current level
> update: Use rules from upper level when no rules in current level

- src/components/KubeTools/index.jsx
- src/core/global.js
/kind bug
Update page control with ks module config
> update: Update page control with ks mdoule

- src/components/Cards/Containers/Item.jsx
- src/components/Cards/Pods/index.jsx
- src/core/global.js
- src/locales/en/base.js
- src/locales/zh/base.js
- src/pages/clusters/containers/Projects/Detail/Overview/index.jsx
- src/pages/console/routes/index.js
- src/pages/projects/containers/Overview/ResourceUsage/AppResourceItem/index.jsx
- src/pages/projects/containers/Overview/ResourceUsage/index.jsx
- src/pages/projects/containers/Overview/UsageRanking/index.jsx
- src/pages/projects/containers/Pods/Containers/Detail.jsx
- src/pages/projects/containers/Pods/Detail/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
/kind bug
1. Fix some link errors.
2. terminal path conflict with new project path.
3. get navs return directly if there is no rules found.
> fix: Fix some link errors

- src/pages/projects/containers/Overview/ResourceUsage/AppResourceItem/index.jsx
/kind bug
Fix links in cluster project overview page
> fix: Fix links in cluster project overview page

- src/components/Modals/EditAuthorization/constants.js
- src/components/Modals/EditAuthorization/index.jsx
- src/pages/access/containers/Accounts/index.jsx
- src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
/kind bug
Hide some content when the depend on ks module not installed.
> fix: Fix some ks module dependencies

- src/stores/monitoring/custom/template.json
Signed-off-by: huanggze <loganhuang@yunify.com>
>
/kind bug
> /kind design
> /kind flake
Fixes #
- update template content (most important)
- change legend variable format from `{}` to `{{}}`
- change valueName from `avg` to `last`
- remove the follwing redudant fields.
```docs
```
> update: update custom monitoring templates

- src/components/Forms/StorageClass/ProvisionerSettings/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/369
> fix: Fix error content in storage class create modal

- src/components/Modals/RoleCreate/index.jsx
- src/components/Tables/Base/Empty/index.jsx
- src/locales/zh/cluster.js
- src/pages/clusters/containers/BaseInfo/index.jsx
- src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
- src/pages/clusters/containers/CustomResources/index.jsx
- src/pages/clusters/containers/Nodes/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/ClusterInfo/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/ServiceComponents/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/ServiceComponents/index.scss
- src/pages/clusters/containers/Overview/Dashboard/index.jsx
- src/pages/clusters/containers/Projects/Detail/index.jsx
- src/pages/clusters/containers/ServiceComponents/index.jsx
- src/stores/cluster/index.js
/kind bug
1. render empty tip in crd objects table
2. show kubernetes version in single cluster mode
3. add link for service components in cluster overview
4. add enter project in cluster project detail page
Fixes https://github.com/kubesphere/console/issues/360 https://github.com/kubesphere/console/issues/366 https://github.com/kubesphere/console/issues/365 https://github.com/kubesphere/console/issues/364 https://github.com/kubesphere/console/issues/363
> fix: Fix issues

- src/components/EditMode/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/367
> fix: Generated an appropriate file name when download yaml

- src/locales/en/monitoring.js
- src/locales/zh/monitoring.js
add custom monitoring dashboard description 
Fixes #
```
```
```docs
```
> docs(custom-monitoring): add english translation

- src/components/Forms/Workload/ContainerSettings/ContainerForm/Commands/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/376#event-3418464930
```
```
```docs
```
> fix: Fix data merge error in container settings form

- src/components/Modals/LogSearch/index.jsx
- src/utils/index.js
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix log search api

- src/utils/index.js
> fix: Replace double slash in url

- server/config.yaml
- src/locales/zh/monitoring.js
/kind bug
Fix custom monitoring nav authKey
> fix: Fix custom monitoring nav authKey

- server/store/index.js
/kind bug
Fix default Redis session maxAge.
> fix: Fix redis default maxAge

- src/components/Modals/ProjectSelect/index.jsx
- src/pages/devops/components/Pipeline/Sider/index.jsx
- src/pages/devops/containers/BaseInfo/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/devops.js
- src/utils/devops.js
/kind bug
fix DevOps list create time in the table
> fix: Fix devops create time in the table

- src/components/Cards/LogQuery/index.jsx
- src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx
- src/components/Cards/Monitoring/Controller/TimeSelector/Range/Default.jsx
- src/components/Forms/AlertingPolicy/AlertingRule/RuleForm/index.jsx
- src/components/Layout/Header/index.jsx
- src/components/Modals/CustomMonitoring/components/TimeRangeSelect/index.jsx
- src/components/Modals/EventSearch/Event/Home/index.jsx
- src/components/Modals/InviteMember/index.jsx
- src/components/Modals/Network/Policies/index.jsx
- src/components/Tables/Visible/index.jsx
- src/locales/en/alerting.js
- src/locales/en/base.js
- src/locales/en/monitoring.js
- src/locales/en/network.js
- src/locales/en/project.js
- src/locales/zh/base.js
- src/locales/zh/logging.js
- src/locales/zh/monitoring.js
- src/locales/zh/network.js
- src/locales/zh/project.js
- src/pages/devops/containers/Members/index.jsx
- src/pages/projects/containers/Members/index.jsx
- src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
> chores(locales): Update En UI

- src/stores/role.js
/kind bug
Remove workspace in project role fetch url
> fix: Fix project roles fetch path

- src/pages/projects/containers/Volumes/Detail/index.jsx
- src/stores/storageclasscapabilities.js
fix #381
Fixes #
```
```
```docs
```
> fix: hide 404 when storageclasscapabilities is not exist

- src/pages/projects/containers/CustomMonitoring/index.jsx
batch delete custom monitoring dashboards error
Fixes #
```
```
```docs
```
> fix(custom-monitoring): batch delete custom monitoring dashboards error

- src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
/kind bug
some keywords in the pull-request data may be lost, it will make some errors.
> fix: Fix the PullRequest table bug

- src/components/Modals/CustomMonitoring/components/RowsSortItem/index.scss
fix layout issue
Fixes #
```
```
```docs
```
> fix(custom-monitoring): long-text-layout-error

- src/actions/project.js
- src/components/Modals/Monitoring/ApplicationResource/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
- src/stores/devops.js
- src/stores/monitoring/cluster.js
- src/stores/monitoring/workspace.js
- src/stores/project.js
> fix: Fix project creation in workspace

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix image search error

- server/config.yaml
- src/components/Inputs/InputPassword/index.jsx
- src/locales/en/app.js
- src/locales/en/app_repo.js
- src/locales/en/application.js
- src/locales/en/base.js
- src/locales/en/cluster.js
- src/locales/en/devops.js
- src/locales/en/project.js
- src/locales/en/role.js
- src/locales/en/service.js
- src/locales/en/storage.js
- src/locales/en/user.js
- src/locales/en/workload.js
- src/locales/en/workspace.js
- src/locales/zh/base.js
- src/locales/zh/user.js
- src/locales/zh/workspace.js
- src/pages/access/containers/Workspaces/index.jsx
- src/pages/access/containers/layout.jsx
- src/pages/console/components/Cards/Workspace/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.jsx
- src/pages/workspaces/containers/Clusters/index.jsx
Signed-off-by: sherlock <sherlockxu07@gmail.com>
En UI update
> chores(locales): EN UI update

- src/components/Base/Avatar/index.jsx
- src/components/Modals/AssignWorkspace/index.jsx
- src/components/Modals/ModifyPassword/index.jsx
- src/locales/en/app.js
- src/locales/en/application.js
- src/locales/en/base.js
- src/locales/en/project.js
- src/locales/en/role.js
- src/locales/zh/app.js
- src/locales/zh/base.js
- src/locales/zh/cluster.js
- src/locales/zh/project.js
- src/locales/zh/user.js
- src/pages/access/containers/Accounts/Detail/index.jsx
- src/pages/apps/components/Cards/BaseInfo/index.jsx
- src/pages/apps/components/Forms/AppBaseEdit/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
- src/pages/projects/containers/Overview/Help/index.jsx
Signed-off-by: sherlock <sherlockxu07@gmail.com>
Update En UI
> chores(locales): EN loc update

- src/pages/devops/containers/Roles/Detail/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/devops.js
- src/stores/s2i/builder.js
/kind bug
fix the params of s2irun , fix the DevOps data isn't refreshed, fix the role in DevOps.
> fix: Fix the params of s2irun and the DevOps data isn't refreshed bug

- src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
- src/utils/monitoring.js
create custom monitor dashboard error when using yaml
Fixes #
```
```
```docs
```
> fix: create custom monitor dashboard error in yaml mode

- src/actions/project.js
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/stores/project.js
/kind bug
Fix project create API error
> fix: Fix project create url error

- src/components/Forms/Workload/ClusterDiffSettings/ContainersMapper/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/Environments/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/Environments/index.scss
- src/components/Forms/Workload/ClusterDiffSettings/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/Environments/index.jsx
- src/locales/en/workload.js
- src/locales/zh/workload.js
/kind update
Add container env diff in workload create.
> update: Add envs diff in workload create

- src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Display related workload resource status if there is workloadName in svc.
> fix: Fix federated svc resource status

- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
- src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/pages/fedprojects/containers/Base/List/index.jsx
/kind bug
Update the role authority in devops
> update: Update the role authority in devops

- src/components/Forms/Workload/ClusterDiffSettings/ContainerImage/index.jsx
- src/components/Modals/ProjectSelect/index.jsx
- src/components/Modals/ProjectSelect/index.scss
- src/locales/zh/base.js
- src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
- src/pages/fedprojects/containers/Base/List/index.jsx
- src/pages/projects/components/Selector/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/workspace.js
- src/utils/constants.js
/kind bug
Add cluster select in project selector
> fix: Add cluster select in project selector

- src/pages/settings/containers/LogCollection/index.jsx
- src/stores/logging/collection/output.js
add label selector filter for log output list
Fixes #
```
```
```docs
```
> fix: add label selector filter for log output list

- src/pages/projects/containers/Volumes/Detail/Snapshots/index.jsx
fix wrong PVC snapshot link address
Fixes #
```
```
```docs
```
> fix: wrong pvc snapshot link address

- src/components/Base/Empty/index.jsx
- src/components/Base/List/index.test.js
- src/components/Forms/AppDeploy/BasicInfo/index.jsx
- src/components/Forms/ConfigMap/ConfigMapSettings/DataForm/index.jsx
- src/components/Forms/ConfigMap/ConfigMapSettings/DataList/index.jsx
- src/components/Forms/Route/RouteRules/RuleForm/index.jsx
- src/components/Forms/Route/RouteRules/RuleList/Item.jsx
- src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
- src/components/Forms/Secret/SecretSettings/DataList/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/configs/steps/imagebuilder.js
- src/locales/en/nodes.js
- src/locales/en/project.js
- src/locales/en/storage.js
- src/locales/zh/base.js
- src/locales/zh/s2i.js
- src/locales/zh/secret.js
- src/locales/zh/workload.js
- src/pages/clusters/containers/Alerting/Messages/Detail/AlertDetail/index.jsx
- src/pages/clusters/containers/Alerting/Messages/Detail/Comment/index.jsx
- src/pages/clusters/containers/Alerting/Messages/Detail/NotificationHistory/index.jsx
- src/pages/fedprojects/containers/Overview/UsageRanking/index.jsx
- src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
- src/pages/projects/components/Modals/CreateApp/Routes/RuleList/Item.jsx
- src/pages/projects/components/Modals/CreateApp/Services/ServiceList/Item.jsx
- src/pages/projects/containers/Network/Policies/Detail/Viewer/index.jsx
- src/pages/projects/containers/Overview/UsageRanking/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/stores/secret.js
> En UI update

- src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/index.jsx
/kind update
Add joinFederation, and remove required of cluster API server.
> update: Update add cluster form

- src/stores/role.js
/kind bug
Fix roles fetch api.
> fix: Fix roles fetch

- src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/PodAffinity/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/components/TextPreview/index.jsx
- src/locales/en/application.js
- src/locales/en/configmap.js
- src/locales/en/network.js
- src/locales/en/service.js
- src/locales/en/workload.js
- src/locales/zh/app_template.js
- src/locales/zh/application.js
- src/locales/zh/s2i.js
- src/locales/zh/workload.js
- src/pages/appStore/components/AppPreview/index.jsx
- src/pages/apps/components/AppPreview/index.jsx
- src/pages/apps/components/Cards/AppReadme/index.jsx
- src/pages/apps/components/Cards/Introduction/index.jsx
- src/pages/apps/components/TextPreview/index.jsx
- src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
> chore(locales): EN UI update

- src/pages/access/containers/Accounts/index.jsx
- src/utils/constants.js
/kind bug
Add WebSocket watch for users.
Fixes https://github.com/kubesphere/console/issues/451
```
```
```docs
```
> fix: Fix users update by websocket

- src/pages/clusters/containers/Overview/Initializing/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2228
```
```
```docs
```
> fix: Fix cluster overview agent yaml

- src/actions/project.js
- src/components/HOCs/withList.js
- src/components/Modals/Create/index.jsx
- src/components/Tables/Base/index.jsx
- src/core/global.js
- src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
- src/pages/fedprojects/containers/Deployments/Detail/Monitoring/index.jsx
- src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
- src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
- src/pages/projects/App.jsx
- src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
- src/pages/projects/containers/AdvancedSettings/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/federated.js
- src/stores/project.js
- src/utils/socket.client.js
/kind bug
Fix workspace’s project list realtime updating.
Fix federated workload resource status realtime updating.
Fixes https://github.com/kubesphere/kubesphere/issues/2229
```
```
```docs
```
> fix: Fix project and workload resource realtime update

- src/locales/zh/logging.js
- src/pages/projects/containers/Secrets/index.jsx
- src/stores/cluster/index.js
- src/stores/project.js
- src/stores/secret.js
/kind bug
1. Fix project list refresh after creation.
2. Fix secret creation error.
Fixes https://github.com/kubesphere/console/issues/458#event-3461009911
```
```
```docs
```
> fix: Fix project create and secret create error

- src/components/Forms/ImageBuilder/S2IForm/TemplateSelect/index.jsx
/kind bug
Fix the wrong value of the target template when s2i is rebuild
Fixes #450 
> fix: Fix the wrong value of the target template when s2i is rebuild

- src/pages/projects/components/Modals/CreateApp/Services/ServiceList/Item.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix application create error

- src/pages/clusters/containers/Overview/Initializing/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/464
```
```
```docs
```
> fix: Add cluster detail websocket when adding cluster

- src/pages/fedprojects/containers/ConfigMaps/Detail/index.jsx
- src/pages/projects/containers/ConfigMaps/Detail/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/467#event-3466183617
```
```
```docs
```
> fix: Fix configmap detail return title

- src/components/Modals/Network/Policies/IpBlock.jsx
- src/locales/en/network.js
- src/locales/zh/network.js
/kind flake
modify network policy the rule for CIDR to add ports
allow null ports
> fix:  modify network policy the rule for CIDR to add ports

- src/components/Modals/AuditingSearch/index.jsx
- src/components/Modals/EventSearch/index.jsx
- src/components/Modals/LogSearch/index.jsx
- src/locales/zh/logging.js
- src/scss/utilities.scss
> fix: Fix logging, events, auditing clusters filter

- server/config.yaml
- src/components/Modals/AuditingSearch/Auditing/Home/index.scss
- src/components/Modals/AuditingSearch/index.jsx
- src/components/Modals/EventSearch/Event/Home/index.scss
- src/components/Modals/EventSearch/index.jsx
- src/components/Modals/LogSearch/Logging/Home/index.scss
- src/components/Modals/LogSearch/Logging/Search/index.scss
- src/components/Modals/LogSearch/index.jsx
- src/components/Modals/ProjectCreate/index.jsx
- src/core/global.js
- src/pages/projects/containers/Network/Policies/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
/kind bug
Add config for network isolate default value
> fix: Add config for network isolate default value

- src/components/Graph/Detail/PolicyForm/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix policy form api

- src/actions/resource.edit.js
- src/actions/service.js
- src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
- src/stores/cluster/index.js
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2247
```
```
```docs
```
> fix: Fix cluster api

- src/actions/project.js
- src/components/Forms/Workload/VolumeSettings/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/ClusterInfo/index.jsx
- src/pages/projects/containers/Routes/Detail/ResourceStatus/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
- src/pages/workspaces/components/ResourceTable/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/project.js
/kind bug
Fixes https://github.com/kubesphere/console/issues/481
```
```
```docs
```
> fix: Fix some multi clusters issues.

- src/actions/imagebuilder.js
- src/components/Base/Upload/utils/request.js
- src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
- src/components/Forms/ImageBuilder/B2IForm/index.jsx
- src/components/Forms/ImageBuilder/S2IForm/index.jsx
- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/pages/projects/components/Cards/S2iBuilder/log.jsx
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
- src/stores/s2i/builder.js
- src/stores/s2i/run.js
/kind bug
Fix no project name and mirror name when creating a mirror.
Fixes #472
> fix: Fix no project name and mirror name when creating a mirror.

- server/config.yaml
- src/actions/member.js
- src/components/Modals/UserCreate/index.jsx
- src/locales/en/role.js
- src/locales/zh/role.js
- src/pages/access/containers/Roles/Detail/index.jsx
- src/pages/access/containers/Roles/index.jsx
- src/pages/clusters/containers/Roles/Detail/index.jsx
- src/pages/clusters/containers/Roles/index.jsx
- src/pages/devops/containers/Roles/Detail/index.jsx
- src/pages/devops/containers/Roles/index.jsx
- src/pages/projects/containers/Roles/Detail/index.jsx
- src/pages/projects/containers/Roles/index.jsx
- src/pages/workspaces/containers/Roles/Detail/index.jsx
- src/pages/workspaces/containers/Roles/index.jsx
- src/stores/cluster/index.js
- src/stores/role.js
- src/utils/object.mapper.js
/kind bug
Fixes #485 
```
```
```docs
```
> fix: Fix preset roles description.

- src/components/Base/CodeEditor/index.jsx
- src/components/Forms/AppDeploy/AppConfig/index.jsx
/kind bug
Fixes https://kubesphere.com.cn/forum/d/1596-member-kubeconfig-host
```
```
```docs
```
> fix: Add props upadte logic for code editor

- src/components/Forms/CICDs/BaseInfo/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops/pipelines.js
/kind bug
Fix no devopsRoles after refreshing the pipeline page
FIx download URL of the artifacts
Fixes#441 #446 #486 #44
> fix: Fix no devopsRoles after refreshing the pipeline page

- src/actions/openpitrix.js
- src/components/Forms/AppDeploy/AppConfig/index.jsx
- src/components/Modals/ProjectSelect/index.jsx
- src/locales/zh/application.js
- src/pages/apps/components/Lists/InstanceList/Item.jsx
- src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
- src/pages/projects/containers/Applications/OPAppDetail/VersionInfo/index.jsx
- src/stores/openpitrix/app.js
- src/stores/openpitrix/application.js
- src/stores/openpitrix/version.js
/kind update
Fixes https://github.com/kubesphere/console/issues/218
```
```
```docs
```
> fix: Add upgrade for openpitrix app instance

- src/components/Modals/Create/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix create modal data update

- server/config.yaml
- src/core/global.js
- src/pages/workspaces/App.jsx
- src/pages/workspaces/containers/Projects/index.jsx
> /kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2263 https://github.com/kubesphere/kubesphere/issues/2261
```
```
```docs
```
> fix: Fix workspace nav with ks module

- src/components/Forms/ImageBuilder/B2IForm/index.jsx
- src/locales/en/cluster.js
- src/locales/en/logging.js
- src/locales/en/version.js
- src/locales/en/workspace.js
- src/locales/zh/s2i.js
- src/locales/zh/version.js
Update en wording, fix typo and punctuation
> chore(locales): minor wording and punctuation updates

- src/components/Modals/ProjectSelect/ClusterSelect/index.jsx
- src/components/Modals/ProjectSelect/ClusterSelect/index.scss
- src/components/Modals/ProjectSelect/index.jsx
- src/components/Modals/ProjectSelect/index.scss
- src/pages/clusters/containers/Projects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
/kind update
Add project monitoring data in workspace project list and cluster project list pages.
Fixes #
```
```
```docs
```
> update: Add project monitoring data in project list

- src/pages/workspaces/containers/DevOps/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Abort data fetch if there is no cluster

- server/controllers/api.js
- src/stores/user.js
- src/utils/cookie.js
/kind bug
Fixes #508 
```
```
```docs
```
> fix: Fix lang switch error

- src/components/Modals/EditAuthorization/CheckItem.jsx
- src/components/Modals/EditAuthorization/constants.js
- src/components/Modals/ProjectSelect/index.jsx
- src/components/Modals/ProjectSelect/index.scss
- src/locales/en/network.js
- src/locales/en/role.js
- src/locales/zh/project.js
- src/pages/access/containers/Workspaces/index.jsx
- src/pages/access/containers/Workspaces/index.scss
- src/pages/clusters/containers/Projects/Detail/Overview/index.jsx
- src/pages/clusters/containers/Projects/Detail/Overview/index.scss
- src/pages/console/components/Cards/Workspace/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.scss
- src/pages/workspaces/components/Modals/WorkspaceSelect/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/Statistics/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/devops.js
- src/stores/monitoring/project.js
- src/stores/openpitrix/application.js
- src/utils/object.mapper.js
/kind bug
1. Fix application api in single cluster mode.
2. Fix checkbox click in authorization edit.
3. Add cluster info in cluster project detail.
4. Show cluster info in workspace list.
Fixes #
```
```
```docs
```
> fix: Fix some issues

- src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
- src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
- src/components/Modals/AuditingSearch/index.jsx
- src/components/Modals/EventSearch/Event/Detail/index.jsx
- src/components/Modals/EventSearch/Event/Home/index.jsx
- src/components/Modals/EventSearch/Event/Home/index.scss
- src/components/Modals/EventSearch/index.jsx
- src/components/Modals/LogSearch/Logging/Home/index.jsx
- src/components/Modals/LogSearch/Logging/Search/index.jsx
- src/components/Modals/LogSearch/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix cluster filter in eventSearch and auditingSearch

- src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
- src/locales/en/base.js
- src/locales/en/logging.js
- src/locales/en/monitoring.js
- src/locales/en/role.js
- src/locales/zh/app.js
- src/locales/zh/logging.js
- src/locales/zh/role.js
- src/pages/apps/components/Forms/AppBaseEdit/index.jsx
- src/stores/monitoring/custom/template.json
Typo fix and role description wording improvement
> Typo fix and role description wording improvement

- src/locales/en/role.js
- src/locales/zh/role.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix locales error

- server/config.yaml
- src/components/Base/RadioGroup/index.jsx
- src/pages/clusters/containers/LogCollections/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/515
```
```
```docs
```
> fix: Fix cluster log collection

- src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/517
```
```
```docs
```
> style: Change font size of component status in cluster monitoing

- src/locales/en/cluster.js
- src/locales/en/logging.js
- src/locales/zh/cluster.js
Wording fix
Fix https://github.com/kubesphere/console/issues/516
> Add cluster authorization desc and fix log collecting wording

- src/components/Modals/LogCollectionCreate/index.jsx
- src/locales/en/logging.js
- src/locales/zh/logging.js
- src/pages/clusters/containers/LogCollections/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix log collector title and styles

- src/stores/logging/collection/output.js
/kind bug
Fixes https://github.com/kubesphere/console/issues/523
```
```
```docs
```
> fix: Fix log collector form data

- src/pages/clusters/components/Modals/ClusterVisibility/WorkspaceItem/index.jsx
- src/pages/clusters/components/Modals/ClusterVisibility/WorkspaceItem/index.scss
- src/pages/clusters/containers/Visibility/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes https://github.com/kubesphere/console/issues/383
```
```
```docs
```
> fix: Add manager for cluster visibility table

- src/locales/zh/service.js
- src/pages/clusters/containers/Workload/Routes/index.jsx
- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
- src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
- src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
- src/pages/projects/containers/Routes/Detail/index.jsx
- src/pages/projects/containers/Routes/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2000
```
```
```docs
```
> fix: Show hostname in loadBalancerIngress

- src/actions/project.js
- src/components/Modals/ProjectCreate/index.jsx
- src/locales/zh/project.js
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2271
```
```
```docs
```
> fix: Fix project create modal clusters select

- src/locales/en/role.js
- src/locales/zh/role.js
> correct workspace role description

- src/components/Forms/Route/RouteRules/RuleForm/index.jsx
- src/pages/clusters/actions/cluster.js
- src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
- src/pages/projects/components/Modals/CreateApp/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix ingress host with aws lb

- src/pages/workspaces/containers/Projects/index.jsx
/kind bug
Fixes #536
```
```
```docs
```
> fix: Fix project create not refresh

- src/components/Modals/EditAuthorization/CheckItem.jsx
- src/components/Modals/EditAuthorization/index.jsx
- src/components/Modals/EditAuthorization/index.scss
/kind bug
Fixes #362
```
```
```docs
```
> fix: Sort role templates by aliasName

- src/pages/clusters/actions/cluster.js
- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
- src/pages/clusters/containers/Visibility/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Show only fedmanaged workspaces in cluster visibility

- src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix prob input issues

- docs/access-backend.md
> chore: Update access backend doc

- docker-compose.builder.yaml
- docker-compose.yaml
/kind bug
node:8-alpine is in conflict with diff2html.
Fixes #
```
```
```docs
```
> chore: Update base dev image

- src/pages/devops/containers/Pipelines/index.jsx
> fix:Fix empty form display in pipeline

- src/locales/en/role.js
- src/locales/en/storage.js
- src/locales/en/workload.js
- src/locales/zh/role.js
- src/locales/zh/workload.js
> Minor punctuation and typo fix

- src/locales/en/cluster.js
- src/locales/en/workspace.js
- src/locales/zh/workspace.js
- src/pages/clusters/containers/Clusters/index.jsx
- src/pages/workspaces/components/ResourceTable/index.jsx
- src/pages/workspaces/containers/Clusters/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
- src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
- src/stores/project.js
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2279
```
```
```docs
```
> fix: Fix project create error

- src/actions/project.js
- src/components/HOCs/withList.js
- src/components/Modals/ProjectCreate/index.jsx
- src/components/Tables/Base/index.jsx
- src/locales/zh/cluster.js
- src/locales/zh/project.js
- src/pages/clusters/containers/Monitor/Resource/Ranking/Project/Table/index.jsx
- src/pages/fedprojects/containers/Deployments/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/cluster/index.js
- src/stores/federated.list.js
- src/stores/project.js
- src/utils/constants.js
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix federated namespace operations

- src/pages/clusters/components/ResourceTable/index.jsx
/kind bug
Clear the filter in the table after selecting the project
Fixes #559 
> fix: Clear the filter in the table after selecting the project

- src/actions/workload.js
/kind bug
Fixes https://github.com/kubesphere/console/issues/574
```
```
```docs
```
> fix: Fix statfulset createc in cluster

- src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
- src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
- src/components/Modals/EventSearch/Event/Detail/index.jsx
- src/components/Modals/EventSearch/Event/Home/index.jsx
- src/components/Modals/LogSearch/Logging/Home/index.jsx
- src/components/Modals/LogSearch/Logging/Search/index.jsx
/kind bug
Fixes #568 
```
```
```docs
```
> fix: Fix log search in single cluster mode.

- src/locales/en/project.js
Add multicluster tip UI and fix log collection wording
> Add multicluster tip UI and fix log collection wording

- src/pages/projects/containers/Network/Policies/Detail/index.jsx
> fix:Fix the url returned to the previous page in the network strategy

- src/actions/workload.js
- src/components/Forms/CronJob/BaseInfo/index.jsx
- src/components/Forms/Service/BaseInfo/index.jsx
- src/components/Forms/Workload/BaseInfo/index.jsx
- src/pages/projects/components/Modals/ConfigTemplate/config.js
- src/utils/yaml.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix statefulset edit config template

- src/locales/en/cluster.js
- src/locales/zh/cluster.js
/kind locales
Fixes #
```
```
```docs
```
> Chore: Update cluster locales

- server/config.yaml
- src/actions/project.js
- src/components/Base/Indicator/index.scss
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
- src/components/Forms/Workload/VolumeSettings/index.jsx
- src/components/Tables/Base/Empty/index.scss
- src/locales/en/role.js
- src/locales/en/secret.js
- src/locales/zh/project.js
- src/locales/zh/role.js
- src/pages/fedprojects/containers/Applications/index.jsx
- src/pages/fedprojects/containers/BaseInfo/index.jsx
- src/pages/fedprojects/containers/ConfigMaps/index.jsx
- src/pages/fedprojects/containers/Deployments/index.jsx
- src/pages/fedprojects/containers/Routes/index.jsx
- src/pages/fedprojects/containers/Secrets/index.jsx
- src/pages/fedprojects/containers/Services/index.jsx
- src/pages/fedprojects/containers/StatefulSets/index.jsx
- src/pages/fedprojects/containers/Volumes/index.jsx
- src/utils/constants.js
- src/utils/object.mapper.js
/kind bug
1. fix image secret querying in federated workload creating modal.
2. fix secrets and configmaps querying in federated workload creating modal.
3. fix federated resources status in the list page. 
4. hide cluster roles and members.
Fixes #
```
```
```docs
```
> fix: Fix federated resources create and list status

- src/actions/openpitrix.js
- src/pages/projects/containers/Applications/OPApps.jsx
- src/pages/projects/containers/Overview/Applications/index.jsx
- src/stores/openpitrix/app.js
- src/stores/openpitrix/application.js
Reference PR: https://github.com/kubesphere/kubesphere/pull/2293
Fixes #
```
```
```docs
```
> update: Update op application API

- server/config.yaml
- src/actions/project.js
- src/components/Modals/EditAuthorization/constants.js
- src/locales/en/role.js
- src/locales/zh/role.js
- src/pages/workspaces/containers/BaseInfo/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
/kind bug
Fixes #604 #605
```
```
```docs
```
> fix: Fix project create redirect

- src/pages/workspaces/components/Modals/EditBasicInfo/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix workspace manager edit

- src/components/Inputs/ProjectSelect/index.jsx
- src/components/Modals/ProjectCreate/index.jsx
- src/pages/clusters/containers/Nodes/Detail/index.jsx
- src/pages/clusters/containers/Workload/Deployments/index.jsx
- src/pages/clusters/containers/Workload/Pods/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
/kind bug
Fixes #624 #621
```
```
```docs
```
> fix: Fix project create validation

- src/stores/devops/base.js
- src/stores/devops/pipelines.js
/kind bug
add cluster to getCrumb
Fixes #
> fix: add cluster param to getCrumb

- src/pages/devops/containers/layout.jsx
- src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Rule/index.jsx
- src/pages/projects/App.jsx
- src/pages/projects/containers/CronJobs/index.jsx
- src/stores/cluster/index.js
- src/stores/workload/env.js
- src/stores/workspace.js
/kind bug
Fixes #633 #630 https://github.com/kubesphere/kubesphere/issues/2317
```
```
```docs
```
> fix: Fix 404 redirect if resource not found

- src/actions/openpitrix.js
- src/pages/clusters/containers/ConfigMaps/index.jsx
- src/pages/clusters/containers/Secrets/index.jsx
- src/pages/clusters/containers/Storage/Volumes/index.jsx
- src/pages/clusters/containers/Workload/Deployments/index.jsx
- src/pages/clusters/containers/Workload/Routes/index.jsx
- src/pages/clusters/containers/Workload/Services/index.jsx
- src/pages/clusters/containers/Workload/StatefulSets/index.jsx
- src/pages/projects/components/Modals/RepoApp/Apps/index.jsx
- src/pages/workspaces/containers/Apps/index.jsx
/kind bug
Fixes #623
```
```
```docs
```
> fix: Disable multi cluster resource selection in cluster.

- src/pages/devops/containers/Credential/detail/index.jsx
>
/kind bug
No access to the credentials page
Fixes #
> fix: Fix Credential role

- src/pages/devops/containers/layout.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix devops 404 error

- server/controllers/session.js
- server/controllers/view.js
- server/locales/en.properties
- server/locales/zh.properties
- src/locales/en/role.js
- src/stores/devops/scm.js
Fix login page and role desc en wording
> Fix login page and role desc en wording

- src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
- src/pages/projects/containers/CustomMonitoring/index.jsx
- src/stores/customMonitorDashboard.js
- src/stores/monitoring/custom/monitor.js
- src/stores/monitoring/custom/template.js
/kind bug
Add cluster prefix for custom monitor api
Fixes #
```
```
```docs
```
> fix: Fix custom monitor with cluster prefix

- src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
- src/components/Forms/Workload/VolumeSettings/index.jsx
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2320
```
```
```docs
```
> fix: Fix workload mount volume readonly

- src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.jsx
- src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.scss
/kind bug
Fixes #641
```
```
```docs
```
> fix: Fix authorized users list

- src/components/Forms/Workload/VolumeSettings/AddTemporary/index.jsx
- src/components/Forms/Workload/VolumeSettings/index.jsx
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2321
```
```
```docs
```
> fix: Fix workload volume name edit error

- src/pages/projects/containers/CustomMonitoring/EditDashborad/index.jsx
- src/pages/projects/containers/CustomMonitoring/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix api in custom monitor detail

- src/components/Forms/LoggingCollection/Status/index.jsx
- src/components/Modals/EditAuthorization/constants.js
- src/locales/en/logging.js
- src/locales/zh/app.js
- src/locales/zh/project.js
- src/locales/zh/role.js
- src/pages/apps/containers/Store/Detail/AuditRecord/index.jsx
- src/pages/fedprojects/containers/AdvancedSettings/LogCollection/index.jsx
- src/pages/projects/containers/AdvancedSettings/LogCollection/index.jsx
capitalization fix and minor wording adjustment
> Capitalization fix and minor wording adjustment

- src/components/Modals/Network/Policies/IpBlock.jsx
- src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
> fix: Fix network policy rule displays error && validate rules

- src/locales/en/role.js
- src/locales/en/user.js
- src/locales/zh/role.js
> Add role identifier desc and fix role creation wording

- src/components/Base/Avatar/index.scss
- src/pages/clusters/containers/Monitor/Resource/Ranking/Project/Table/index.jsx
- src/pages/clusters/containers/Monitor/Resource/Ranking/Project/index.jsx
- src/pages/clusters/containers/Monitor/Resource/routes.js
- src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/632
```
```
```docs
```
> fix: Fix link in project ranking table.

- src/actions/resource.edit.js
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2327
```
```
```docs
```
> fix: Using PUT instead of PATCH when update yaml

- src/actions/openpitrix.js
- src/locales/zh/app.js
- src/pages/appStore/components/AppInfo/ImageSlider/index.jsx
- src/pages/appStore/components/AppInfo/index.jsx
- src/pages/appStore/components/AppList/index.jsx
- src/pages/appStore/containers/Home/index.jsx
- src/pages/apps/components/Cards/ScreenshotsEdit/index.jsx
- src/pages/apps/components/Modals/AppEdit/index.jsx
- src/pages/workspaces/containers/Apps/Detail/index.jsx
- src/pages/workspaces/containers/Apps/index.jsx
- src/stores/openpitrix/app.js
/kind bug
fix some issues in App template
Fixes  [#1953](https://github.com/kubesphere/kubesphere/issues/1953) [#1957](https://github.com/kubesphere/kubesphere/issues/1957) [#1958](https://github.com/kubesphere/kubesphere/issues/1958) [#1959](https://github.com/kubesphere/kubesphere/issues/1959)
> fix: Fix some bugs in App template

- src/configs/alerting/metrics/workload.js
/kind bug
Fixes https://github.com/kubesphere/console/issues/648
```
```
```docs
```
> update: Update alerting rule metrics

- src/utils/constants.js
/kind bug
Fixes #658
```
```
```docs
```
> fix: Fix labels mission in statfulset create

- src/components/Tables/Base/index.jsx
/kind bug
Fixes #654
```
```
```docs
```
> fix: Hide custom columns if no hideableColumns

- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/2325
```
```
```docs
```
> fix: Disable remove system-workspace in cluster visibility

- src/pages/projects/components/WorkloadStatus/index.jsx
- src/utils/status.js
- src/utils/workload.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/636
```
```
```docs
```
> fix: Fix daemonset ready pods

- src/pages/projects/containers/Members/index.jsx
/kind bug
Fixes ##666
```
```
```docs
```
> fix: Fix project members enable actions

- src/components/Forms/Workload/ContainerSettings/PodAffinity/index.jsx
- src/locales/zh/workload.js
fix replica deployment wording
> fix replica deployment wording

- src/components/Modals/Network/Policies/IpBlock.jsx
- src/components/Modals/Network/Policies/index.scss
- src/locales/en/network.js
- src/locales/zh/network.js
- src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
/kind feature
optimize network policy rule direction default status
> feat: optimize network policy rule direction default status

- src/components/Modals/EditAuthorization/CheckItem.jsx
- src/pages/projects/components/Modals/RollBack/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2326
```
```
```docs
```
> fix: Fix check item action in EditAuthorization

- src/components/Forms/Workload/ContainerSettings/ContainerList/Card.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2335
```
```
```docs
```
> fix: Fix delete initContainer in ContainerSettings

- src/locales/zh/cluster.js
/kind locale
Fixes #
```
```
```docs
```
> Chore(cn): minor update

- src/stores/openpitrix/repo.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2345
```
```
```docs
```
> fix: Fix repo delete

- src/pages/clusters/containers/Network/Policies/index.jsx
- src/pages/projects/containers/Network/Policies/Detail/Viewer/index.jsx
/kind bug
fix some issues about network policy
Fixes #https://github.com/kubesphere/kubesphere/issues/2344
Fixes #https://github.com/kubesphere/kubesphere/issues/2343
Fixes #https://github.com/kubesphere/kubesphere/issues/2342
Fixes #https://github.com/kubesphere/kubesphere/issues/2173
> fix: Fix network policy some bugs

- src/components/Forms/Workload/ClusterDiffSettings/ClustersMapper/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/index.jsx
- src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/pages/fedprojects/components/ClusterWorkloadStatus/index.jsx
- src/pages/fedprojects/components/FedWorkloadStatus/index.jsx
- src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/Deployments/Detail/index.jsx
- src/pages/fedprojects/containers/Deployments/index.jsx
- src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/Services/Detail/ServiceAccess/index.jsx
- src/pages/fedprojects/containers/Services/Detail/index.jsx
- src/pages/fedprojects/containers/Services/index.jsx
- src/pages/fedprojects/containers/StatefulSets/Detail/index.jsx
- src/pages/fedprojects/containers/StatefulSets/index.jsx
- src/pages/projects/components/Modals/ServiceDelete/index.jsx
- src/pages/projects/components/Modals/WorkloadDelete/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2337
```
```
```docs
```
> fix: Fix multicluster resources

- src/actions/configmap.js
- src/actions/secret.js
- src/actions/service.js
- src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
- src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
- src/pages/clusters/containers/ConfigMaps/index.jsx
- src/pages/clusters/containers/Secrets/index.jsx
- src/pages/clusters/containers/Workload/Services/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2348 
```
```
```docs
```
> fix: Fix cluster resource create mission namespace

- src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2337
```
```
```docs
```
> fix: Fix cluster replicas control

- src/pages/clusters/containers/Network/Policies/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2344#issuecomment-655934339
```
```
```docs
```
> fix: Fix network policy search

- src/components/Base/TextArea/index.jsx
- src/stores/container.js
/kind bug
Fixes [#2346](https://github.com/kubesphere/kubesphere/issues/2346)
> fix persistentvolumeclaims not found

- src/actions/federated.js
- src/actions/project.js
- src/components/Modals/FedProjectCreate/index.jsx
- src/components/Modals/FedProjectCreate/index.scss
- src/components/Modals/ProjectSelect/index.jsx
- src/locales/en/project.js
- src/locales/zh/project.js
- src/pages/clusters/containers/Projects/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
/kind enhancement
Fixes #https://github.com/kubesphere/kubesphere/issues/2362
```
```
```docs
```
> update: Seperate project create into two actions

- src/components/Forms/CICDs/paramsModal.jsx
- src/pages/devops/containers/Credential/detail/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops/pipelines.js
/kind bug
fix: Fix the bug that the branch doesn't change in ParamsModal of the pipeline page
Fixes #
> fix: Fix the branch doesn't change in ParamsModal of the pipeline page

- src/components/Forms/CICDs/paramsModal.jsx
> fix: Fix the ParamsModal has mounted should not request data

- src/actions/configmap.js
- src/actions/federated.js
- src/actions/imagebuilder.js
- src/actions/router.js
- src/actions/service.js
- src/components/Cards/Pods/index.scss
- src/components/Clusters/ClusterTitle/index.jsx
- src/components/Modals/DevOpsCreate/index.jsx
- src/components/Modals/FedProjectCreate/index.jsx
- src/components/Modals/Monitoring/ApplicationResource/index.jsx
- src/components/Modals/ProjectSelect/index.jsx
- src/locales/en/cluster.js
- src/locales/zh/cluster.js
- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
- src/pages/clusters/components/Modals/ClusterVisibility/index.scss
- src/pages/clusters/containers/Clusters/index.jsx
- src/pages/fedprojects/containers/BaseInfo/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/stores/project.js
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> update: Update ui for host cluster

- src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx
/kind bug
If range smaller than steps, set times to 1
Fixes #https://github.com/kubesphere/kubesphere/issues/2382
```
```
```docs
```
> fix: Fix monitoring custom range query

- src/components/Modals/ProjectSelect/index.jsx
- src/locales/zh/base.js
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
- src/pages/fedprojects/containers/Deployments/Detail/index.jsx
- src/pages/fedprojects/containers/Routes/Detail/index.jsx
- src/pages/fedprojects/containers/Routes/index.jsx
- src/pages/fedprojects/containers/Services/index.jsx
- src/pages/fedprojects/containers/StatefulSets/Detail/index.jsx
- src/pages/fedprojects/containers/StatefulSets/index.jsx
- src/pages/projects/containers/DaemonSets/Detail/index.jsx
- src/pages/projects/containers/DaemonSets/index.jsx
- src/pages/projects/containers/Deployments/Detail/index.jsx
- src/pages/projects/containers/Deployments/index.jsx
- src/pages/projects/containers/Pods/Containers/Detail.jsx
- src/pages/projects/containers/Pods/Detail/index.jsx
- src/pages/projects/containers/Pods/index.jsx
- src/pages/projects/containers/Routes/Detail/index.jsx
- src/pages/projects/containers/Routes/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/pages/projects/containers/Services/index.jsx
- src/pages/projects/containers/StatefulSets/Detail/index.jsx
- src/pages/projects/containers/StatefulSets/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/stores/base.js
- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/560 #https://github.com/kubesphere/kubesphere/issues/2376 #https://github.com/kubesphere/console/issues/698
```
```
```docs
```
> fix: Fix project resources search by app

- src/locales/zh/application.js
- src/pages/fedprojects/containers/Applications/Detail/AppComponents/Components/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/AppComponents/Components/index.scss
- src/pages/fedprojects/containers/Applications/Detail/index.jsx
- src/pages/fedprojects/containers/Applications/index.jsx
- src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2381
```
```
```docs
```
> fix: Fix federated application create and version

- src/locales/en/role.js
- src/locales/tc/role.js
- src/locales/zh/role.js
- src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.jsx
Fixes #703
```
```
```docs
```
> update: Update locales

- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/pages/projects/components/Modals/HPA/index.jsx
- src/utils/object.mapper.js
- src/utils/workload.js
/kind bug
14a246d Fixes [#2378](https://github.com/kubesphere/kubesphere/issues/2378)
f0abfed Fixes [#2379](https://github.com/kubesphere/kubesphere/issues/2379)
943be41 Fixes [#2361](https://github.com/kubesphere/kubesphere/issues/2361)
> Fix some issures in deployment and s2ibuilders

- src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
- src/components/Forms/Volume/VolumeSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2384
```
```
```docs
```
> fix: Fix snapshots fetching in volume create

- src/pages/projects/components/Cards/HPA/index.jsx
- src/pages/projects/components/Modals/HPA/index.jsx
- src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Deployments/Detail/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix workload hpa settings

- src/locales/en/alerting.js
- src/locales/en/app_repo.js
- src/locales/en/cicd.js
- src/locales/en/grayrelease.js
- src/locales/en/mail.js
- src/locales/en/version.js
- src/locales/tc/s2i.js
- src/locales/zh/cicd.js
- src/locales/zh/s2i.js
> chore: Fix missing lint

- src/locales/tc/application.js
- src/locales/zh/application.js
- src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
- src/pages/fedprojects/containers/Applications/index.jsx
- src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
- src/pages/projects/components/Modals/ServiceDelete/index.jsx
- src/pages/projects/components/Modals/WorkloadDelete/index.jsx
- src/pages/projects/containers/Applications/CRDApps.jsx
- src/pages/workspaces/containers/BaseInfo/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2383 #https://github.com/kubesphere/kubesphere/issues/2385
#https://github.com/kubesphere/kubesphere/issues/2350 ##710
```
```
```docs
```
> fix: Fix application ingress

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/stores/container.js
/kind bug
Fixes [#2367](https://github.com/kubesphere/kubesphere/issues/2367)
/assign  @leoendless
> fix: Add cluster to the selected mirror apis in deployment

- src/pages/workspaces/containers/BaseInfo/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> chore: Fix typo

- src/locales/tc/cicd.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> update: Update tc locales, the cicd.js part has been translated.

- src/core/containers/Base/Detail/Page/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/routes.js
- src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
- src/pages/workspaces/containers/Members/Detail/routes.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/718
```
```
```docs
```
> fix: Fix detail navs module control

- src/locales/zh/role.js
- src/pages/access/containers/Workspaces/index.jsx
- src/pages/projects/containers/BaseInfo/index.jsx
- src/pages/projects/containers/CustomMonitoring/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/project.js
/kind bug
Fixes  ##711 ##715 ##716 ##717 ##718
```
```
```docs
```
> fix: Fix issues of self provisioner

- src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
- src/stores/openpitrix/application.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix app upgrade

- src/core/i18n.js
/kind bug
If there is a cookie `lang` with a non-root path, such as `/access`, the language switch will fail.
Fixes #
```
```
```docs
```
> fix: Fix language switch error

- src/pages/workspaces/containers/DevOps/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
/kind bug
Fixes ##https://github.com/kubesphere/kubesphere/issues/2397
```
```
```docs
```
> fix: Fix workspace projects permission check

- src/locales/en/application.js
- src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2380
```
```
```docs
```
> fix: Fix application description

- src/components/Cards/ProjectQuota/QuotaItem/index.scss
- src/components/Inputs/ContainerPort/index.jsx
- src/pages/access/containers/Roles/index.jsx
- src/pages/clusters/containers/Roles/index.jsx
- src/pages/devops/containers/Roles/index.jsx
- src/pages/fedprojects/containers/QuotaManage/ResourceQuota/QuotaItem/index.scss
- src/pages/projects/containers/Roles/index.jsx
- src/pages/workspaces/containers/Roles/index.jsx
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2349
#https://github.com/kubesphere/kubesphere/issues/2400
#https://github.com/kubesphere/console/issues/729
```
```
```docs
```
> fix: Remove role's batch delete operation

- src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/StatefulSets/Detail/ResourceStatus.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2398
```
```
```docs
```
> fix: Fix related resource not found tip

- server/public/login.css
- server/views/login.html
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix captcha style in login page

- src/components/Cards/Monitoring/Controller/index.scss
- src/components/Modals/Monitoring/ApplicationResource/index.jsx
- src/pages/clusters/containers/Monitor/Resource/Usage/Physical/index.jsx
- src/pages/clusters/containers/Monitor/Resource/Usage/Virtual/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.jsx
- src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
- src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2405
```
```
```docs
```
> fix: Fix workspace overview page cluster switch

- src/components/Forms/CICDs/paramsModal.jsx
- src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
- src/components/Inputs/MountInput/Item.jsx
- src/components/Inputs/MountInput/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops/pipelines.js
> fix: Configmap and secret mount interface do not displays read-write

- src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/StatefulSets/Detail/ServiceCard/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2410
```
```
```docs
```
> fix: Fix workload ports missing when update replicas

- src/components/Cards/Banner/Tip.jsx
- src/locales/tc/network.js
- src/locales/zh/network.js
> /kind bug
add network policy tips link
> add tips link

- src/components/Base/TextArea/index.jsx
- src/components/Modals/AppRepoCreate/index.jsx
- src/components/Modals/DevOpsCreate/index.jsx
- src/components/Modals/DevOpsEdit/index.jsx
- src/components/Modals/EditBasicInfo/index.jsx
- src/pages/devops/components/Modals/DevOpsEdit/index.jsx
- src/pages/projects/components/Modals/AppEdit/index.jsx
- src/pages/workspaces/components/Modals/EditBasicInfo/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
/kind bug
Fixes [#2369](https://github.com/kubesphere/kubesphere/issues/2369)
> fix description limit

- src/locales/en/workload.js
- src/locales/tc/workload.js
- src/locales/zh/workload.js
- src/pages/projects/components/Modals/WorkloadDelete/index.jsx
Fix https://github.com/kubesphere/console/issues/732
> Add loc for workload deletion

- src/pages/workspaces/components/Modals/EditBasicInfo/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Show workspace default manager when create and edit

- src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
- src/locales/tc/workload.js
- src/locales/zh/workload.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2414
```
```
```docs
```
> fix: Fix successThreshold for liveness and startup prob

- src/actions/user.js
- src/components/Modals/ModifyPassword/index.jsx
- src/components/Modals/UserSetting/PasswordSetting/index.jsx
- src/components/Modals/UserSetting/index.jsx
- src/stores/federated.js
- src/stores/user.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix user modify password

- src/components/Forms/GrayRelease/PolicyConfig/Bluegreen/index.jsx
- src/components/Layout/LoginInfo/index.jsx
- src/locales/en/application.js
- src/locales/en/base.js
- src/locales/en/cluster.js
- src/locales/tc/cluster.js
- src/locales/tc/devops.js
- src/locales/tc/grayrelease.js
- src/locales/tc/workload.js
- src/locales/zh/cluster.js
- src/locales/zh/devops.js
- src/locales/zh/grayrelease.js
- src/pages/devops/containers/BaseInfo/index.jsx
> Chore(locales): En wording adjustment

- src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.scss
/kind bug
Fixes #https://github.com/kubesphere/console/issues/729
```
```
```docs
```
> fix: Remove quota item hover cursor

- src/components/Cards/Containers/Ports/index.jsx
- src/components/EditForms/Workload/UpdateStrategy/index.jsx
- src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
- src/components/Forms/Workload/VolumeSettings/VolumeList/Card.jsx
- src/components/Forms/Workload/VolumeSettings/index.jsx
- src/components/HOCs/withList.js
- src/locales/en/workload.js
- src/locales/tc/workload.js
- src/locales/zh/workload.js
- src/pages/projects/containers/CronJobs/Detail/index.jsx
- src/pages/projects/containers/DaemonSets/Detail/index.jsx
- src/pages/projects/containers/Deployments/Detail/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/pages/projects/containers/StatefulSets/Detail/index.jsx
/kind bug
1. fix workload volume edit error in the edit config template.
2. fix workload update strategy edit error.
Fixes #
```
```
```docs
```
> fix: Fix workload edit config template error

- src/actions/user.js
- src/components/Modals/UserSetting/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix user settings error

- src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
- src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
- src/components/Forms/Service/ServiceSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2425
```
```
```docs
```
> fix: Fix service workload select modal

- src/components/Cards/Containers/Ports/index.jsx
/kind bug
Fixes ##757
```
```
```docs
```
> fix: Fix workload ports without name

- src/components/Cards/Containers/Item.jsx
- src/locales/en/workload.js
- src/locales/tc/workload.js
- src/locales/zh/workload.js
- src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
- src/pages/projects/components/Cards/Probe/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2428
```
```
```docs
```
> fix: Fix workload prob card missing startUp probe

- src/pages/projects/components/Modals/ServiceDelete/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes [#2431](https://github.com/kubesphere/kubesphere/issues/2431)
```
```
```docs
```
> fix: Fix the build image still exists in the build image list when deleting the service

- .eslintrc.js
- src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
- src/components/Forms/AppDeploy/BasicInfo/index.jsx
- src/components/Forms/Workload/AdvanceSettings/index.jsx
/kind bug 
Fixes #https://github.com/kubesphere/kubesphere/issues/2433
```
```
```docs
```
> fix: Update workload's spec.selector.matchLabels when labels change

- src/pages/projects/containers/ImageBuilder/index.jsx
/kind bug
Fixes #[#2432](https://github.com/kubesphere/kubesphere/issues/2432)
```
```
```docs
```
> fix: Fix the query in the build mirror list has not taken effect

- src/components/Cards/Pods/index.jsx
- src/components/Forms/Service/ServiceSettings/index.jsx
- src/locales/zh/service.js
- src/pages/clusters/containers/Nodes/Detail/index.jsx
- src/pages/clusters/containers/Nodes/index.jsx
- src/pages/projects/components/Modals/ServiceDelete/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2437
#https://github.com/kubesphere/kubesphere/issues/2438
```
```
```docs
```
> fix: Fix service edit error

- src/pages/devops/containers/Pipelines/index.jsx
/kind bug
the data of status in the pipeline list need more actions to get , the interface needs change in the future. now remove the status bar in the pipeline list.
Fixes #
```
```
```docs
```
> fix: Remove the status bar in the pipeline list

- src/components/Forms/Secret/SecretSettings/Base64Wrapper/index.jsx
- src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
- src/components/Forms/Secret/SecretSettings/DataList/index.jsx
- src/stores/workload/env.js
- src/utils/app.js
- src/utils/index.js
- src/utils/object.mapper.js
/kind bug
Fix `atob` throw error in secret page.
Fixes #
```
```
```docs
```
> fix: Add try catch wrapper for atob

- src/pages/fedprojects/containers/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2455
```
```
```docs
```
> fix: Fix federated project baseinfo edit

- src/components/Modals/FedProjectCreate/index.jsx
/kind bug
Fix federated project error when open creation modal.
Fixes #
```
```
```docs
```
> fix: Fix federated project create

- src/actions/imagebuilder.js
/kind bug
Fixes #[2454](https://github.com/kubesphere/kubesphere/issues/2454)
```
```
```docs
```
> fix: Fix the bug that the advance setting is empty in the image build when created

- src/pages/clusters/containers/Workload/Jobs/index.jsx
- src/pages/projects/containers/Jobs/index.jsx
- src/stores/workload/index.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/554
```
```
```docs
```
> fix: Fix job rerun api error

- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.scss
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2461
```
```
```docs
```
> style: Fix gateway settings style in federated project

- src/locales/zh/workload.js
- src/pages/fedprojects/App.jsx
- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
/kind bug
Fixes 
#https://github.com/kubesphere/console/issues/782
#https://github.com/kubesphere/kubesphere/issues/2463
```
```
```docs
```
> fix: Fix servicemesh settings in federated project

- src/locales/tc/project.js
- src/locales/zh/project.js
Fixes #https://github.com/kubesphere/kubesphere/issues/2460
```
```
```docs
```
> chore: Update locales

- src/components/Cards/ContainerLog/index.jsx
- src/components/Cards/Pods/index.jsx
- src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Pods/Detail/index.jsx
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2468
#https://github.com/kubesphere/kubesphere/issues/2467
#https://github.com/kubesphere/console/issues/784
```
```
```docs
```
> fix: Fix pods cards in multicluster project

- src/actions/workspace.js
- src/components/Base/Indicator/index.scss
- src/locales/tc/base.js
- src/locales/zh/workspace.js
- src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
- src/pages/workspaces/containers/BaseInfo/index.jsx
- src/pages/workspaces/containers/BaseInfo/index.scss
- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/724
```
```
```docs
```
> fix: Fix workspace network isolation in single cluster mode

- src/stores/notification/mailService.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix single cluster mail settings

- src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/Environment/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/Events/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
- src/stores/s2i/builder.js
- src/stores/workload/env.js
/kind bug
Fix some issues in the image build
Fixes [#2473](https://github.com/kubesphere/kubesphere/issues/2473) [#2471](https://github.com/kubesphere/kubesphere/issues/2471) [#2470](https://github.com/kubesphere/kubesphere/issues/2470) [#2469](https://github.com/kubesphere/kubesphere/issues/2469) [#2444](https://github.com/kubesphere/kubesphere/issues/2444) 
> fix: Fix some issues in the image build

- src/components/Cards/Pods/index.jsx
- src/locales/en/project.js
- src/locales/tc/project.js
- src/locales/zh/project.js
- src/pages/clusters/containers/ConfigMaps/index.jsx
- src/pages/clusters/containers/Secrets/index.jsx
- src/pages/clusters/containers/Storage/Volumes/index.jsx
- src/pages/clusters/containers/Workload/Deployments/index.jsx
- src/pages/clusters/containers/Workload/Routes/index.jsx
- src/pages/clusters/containers/Workload/Services/index.jsx
- src/pages/clusters/containers/Workload/StatefulSets/index.jsx
- src/pages/clusters/routes/detail.js
- src/pages/projects/components/Cards/Placement/index.jsx
- src/pages/projects/components/Cards/Placement/index.scss
- src/pages/projects/containers/ConfigMaps/Detail/ConfigDetail/index.jsx
- src/pages/projects/containers/ConfigMaps/Detail/index.jsx
- src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Deployments/Detail/index.jsx
- src/pages/projects/containers/Routes/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Routes/Detail/index.jsx
- src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx
- src/pages/projects/containers/Secrets/Detail/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/pages/projects/containers/StatefulSets/Detail/ResourceStatus.jsx
- src/pages/projects/containers/StatefulSets/Detail/index.jsx
- src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
/kind bug
Adjust multi-cluster resource in cluster management page.
Fixes #
```
```
```docs
```
> fix: Fix multi-cluster resource detail page in cluster management

- src/actions/configmap.js
- src/actions/secret.js
- src/pages/fedprojects/containers/ConfigMaps/Detail/index.jsx
- src/pages/fedprojects/containers/ConfigMaps/index.jsx
- src/pages/fedprojects/containers/Secrets/Detail/index.jsx
- src/pages/fedprojects/containers/Secrets/index.jsx
- src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
- src/pages/projects/components/Modals/SecretEdit/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2451
```
```
```docs
```
> fix: Fix federated secrets and configmaps edit

- src/pages/workspaces/containers/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/796
```
```
```docs
```
> fix: Hide network policy if network disabled

- src/components/Modals/InviteMember/index.jsx
- src/pages/clusters/containers/Nodes/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2478
```
```
```docs
```
> fix: Fix memory format in nodes list

- server/config.yaml
- src/components/Modals/FedProjectCreate/index.jsx
- src/components/Modals/ProjectCreate/index.jsx
- src/core/global.js
- src/locales/tc/workload.js
- src/locales/zh/workload.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix workspace project validating

- src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.scss
/kind bug
Fixes #https://github.com/kubesphere/console/issues/591
```
```
```docs
```
> fix: Fix node role in cluster overview

- src/utils/constants.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/804
```
```
```docs
```
> fix: Fix crd api version

- server/config.yaml
/kind bug
Fixes #https://github.com/kubesphere/console/issues/798
```
```
```docs
```
> fix: Fix cluster email settings

- server/config.yaml
- src/components/Modals/FedProjectCreate/index.jsx
- src/components/Modals/ProjectCreate/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/809
```
```
```docs
```
> fix: Remove network isolation setting in project create

- src/locales/en/nodes.js
- src/locales/zh/nodes.js
- src/pages/access/containers/Workspaces/index.jsx
- src/pages/clusters/containers/Nodes/index.jsx
- src/pages/clusters/containers/Projects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/utils/index.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2462
```
```
```docs
```
> update: Update allocated resource display in cluster nodes

- src/actions/federated.js
- src/pages/fedprojects/containers/BaseInfo/index.jsx
- src/pages/projects/containers/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2486
```
```
```docs
```
> fix: Fix redirect after project delete

- src/pages/projects/containers/Overview/ResourceUsage/index.jsx
/kind bug
Fixes [#2489](https://github.com/kubesphere/kubesphere/issues/2489)
```
```
```docs
```
/ assign @leoendless
> fix: Fix the link of project route In the project overview

- src/actions/federated.js
- src/actions/storageclass.js
- src/pages/workspaces/containers/FedProjects/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix federated projects batch delete

- src/actions/storageclass.js
- src/components/Modals/History/index.jsx
- src/core/global.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2485
```
```
```docs
```
> fix: Cache history by user

- src/components/Modals/FedProjectCreate/index.jsx
- src/components/Modals/ModifyPassword/index.jsx
- src/components/Modals/UserSetting/PasswordSetting/index.jsx
- src/locales/en/app.js
- src/locales/en/project.js
- src/locales/en/storage.js
- src/locales/en/user.js
- src/locales/en/version.js
- src/locales/en/workload.js
- src/locales/tc/app.js
- src/locales/tc/project.js
- src/locales/tc/user.js
- src/locales/tc/version.js
- src/locales/zh/app.js
- src/locales/zh/project.js
- src/locales/zh/user.js
- src/locales/zh/version.js
- src/pages/apps/components/Forms/AppBaseEdit/index.jsx
Update UI wording and fix punctuation
> chore(locales): Update UI wording and fix punctuation

- src/pages/projects/containers/ImageBuilder/index.jsx
/kind bug
Fixes [#2491](https://github.com/kubesphere/kubesphere/issues/2491)
```
```
```docs
```
> fix: Fix the content customization lacks service option inthe build mirror list

- src/actions/federated.js
- src/utils/fed.templates.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2499
```
```
```docs
```
> fix: Fix fedrated project create missing annotation

- src/pages/fedprojects/components/ClusterSelect/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2500
```
```
```docs
```
> fix: Fix error when no cluster group

- src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
- src/components/Forms/AppDeploy/BasicInfo/index.jsx
- src/components/Forms/CronJob/BaseInfo/index.jsx
- src/components/Forms/Dashboard/BaseInfo/index.jsx
- src/components/Forms/DevOps/BaseInfo/index.jsx
- src/components/Forms/GrayRelease/BaseInfo/index.jsx
- src/components/Forms/Service/BaseInfo/index.jsx
- src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
- src/components/Forms/Workload/BaseInfo/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/components/Forms/Workload/VolumeSettings/AddHostPath/index.jsx
- src/components/Forms/Workload/VolumeSettings/AddTemporary/index.jsx
- src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
- src/components/Modals/DevOpsCreate/index.jsx
- src/components/Modals/FedProjectCreate/index.jsx
- src/components/Modals/ProjectCreate/index.jsx
- src/components/Modals/RoleCreate/index.jsx
- src/pages/clusters/components/Modals/AddNodeType/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
- src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
- src/pages/projects/components/Modals/ResourceNamed/index.jsx
- src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
- src/utils/constants.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2503
```
```
```docs
```
> fix: Fix resource name length limit

- src/locales/en/monitoring.js
Fixes #https://github.com/kubesphere/kubesphere/issues/2495
```
```
```docs
```
> chore: Fix en locales error

- src/components/Tables/Base/index.jsx
- src/pages/access/containers/Accounts/index.jsx
- src/pages/access/containers/Roles/index.jsx
- src/pages/access/containers/Workspaces/index.jsx
- src/pages/clusters/containers/Alerting/Policies/index.jsx
- src/pages/clusters/containers/ConfigMaps/index.jsx
- src/pages/clusters/containers/CustomResources/index.jsx
- src/pages/clusters/containers/Members/index.jsx
- src/pages/clusters/containers/Projects/index.jsx
- src/pages/clusters/containers/Roles/index.jsx
- src/pages/clusters/containers/Secrets/index.jsx
- src/pages/clusters/containers/Workload/CronJobs/index.jsx
- src/pages/devops/containers/Members/index.jsx
- src/pages/devops/containers/Roles/index.jsx
- src/pages/fedprojects/containers/Alerting/Policies/index.jsx
- src/pages/fedprojects/containers/Services/index.jsx
- src/pages/projects/containers/ConfigMaps/index.jsx
- src/pages/projects/containers/CronJobs/index.jsx
- src/pages/projects/containers/CustomMonitoring/index.jsx
- src/pages/projects/containers/Members/index.jsx
- src/pages/projects/containers/Roles/index.jsx
- src/pages/projects/containers/Secrets/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/pages/workspaces/containers/Members/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/pages/workspaces/containers/Repos/index.jsx
- src/pages/workspaces/containers/Roles/index.jsx
- src/stores/alerting/base.js
- src/stores/notification/address.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/560
```
```
```docs
```
> fix: Fix base table filter input default key

- src/pages/projects/containers/CronJobs/Detail/JobRecords/index.jsx
- src/pages/projects/containers/CronJobs/Detail/JobRecords/index.scss
- src/pages/projects/containers/Jobs/Detail/ExcuteRecords/index.jsx
- src/pages/projects/containers/Jobs/Detail/ExcuteRecords/index.scss
- src/stores/workload/index.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/829
```
```
```docs
```
> fix: Fix job rerun resourceVersion error

- src/pages/clusters/containers/Workload/CronJobs/index.jsx
- src/pages/projects/containers/CronJobs/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2511
```
```
```docs
```
> fix: Fix cronjob createTime

- src/stores/base.js
- src/stores/service.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix resourceVersion conflict when put resource

- src/components/Forms/Workload/AdvanceSettings/index.jsx
- src/configs/steps/cronjobs.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/832
```
```
```docs
```
> fix: Fix cronjob node selector spec

- src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
- src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.jsx
- src/components/Modals/EventSearch/Event/Detail/index.jsx
- src/locales/en/base.js
- src/locales/en/logging.js
- src/locales/tc/base.js
- src/locales/tc/logging.js
- src/locales/zh/base.js
- src/locales/zh/logging.js
- src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2507
```
```
```docs
```
> fix: Fix event search resource title

- src/components/Modals/QuotaEdit/Quotas/Item.jsx
- src/components/Modals/QuotaEdit/Quotas/constants.js
- src/components/Modals/QuotaEdit/Quotas/index.jsx
- src/components/Modals/QuotaEdit/index.jsx
- src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2510
```
```
```docs
```
> fix: Filter support quota item for federated project

- src/components/Forms/Service/AdvanceSettings/Metadata/index.jsx
- src/components/Forms/Service/AdvanceSettings/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Remove service annotations edit to avoid conflict with loadBalancer

- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
- src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/nav.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/stores/devops/pipelines.js
/kind bug
Fixes ##446 
```
```
```docs
```
> fix: Fix some issues in pipeline about the pagination and the download url

- src/components/Modals/History/Card.jsx
- src/pages/clusters/containers/Nodes/Detail/index.jsx
- src/pages/clusters/containers/Nodes/index.jsx
- src/pages/fedprojects/containers/Overview/BaseInfo/index.jsx
- src/stores/base.js
- src/stores/node.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix node detail info

- src/actions/router.js
- src/pages/projects/components/Modals/RouteRulesEdit/index.jsx
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2518
#https://github.com/kubesphere/kubesphere/issues/2519
```
```
```docs
```
> fix: Fix edit router rules

- src/pages/clusters/components/Modals/ClusterVisibility/WorkspaceItem/index.jsx
- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix cluster visibility modal style

- src/core/containers/Base/Detail/Events/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2411
#https://github.com/kubesphere/kubesphere/issues/2399
#https://github.com/kubesphere/kubesphere/issues/2375
#https://github.com/kubesphere/console/issues/848
```
```
```docs
```
> fix: Fix event kind

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
- src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/BuildRecords/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
- src/stores/container.js
/kind bug
2f7987c Fixes #830
8f1a5a7 Fixes [#2472](https://github.com/kubesphere/kubesphere/issues/2472)
```
```
```docs
```
> fix: Fix the issues about #830 and #2472

- src/components/Forms/GrayRelease/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2522
```
```
```docs
```
> fix: Remove alias-name and description for grayrelease

- src/components/Forms/Workload/ClusterDiffSettings/ContainersMapper/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/852
```
```
```docs
```
> fix: Fix cluster overrides

- src/components/Forms/GrayRelease/Version/ContainerList/Card.jsx
- src/components/Forms/GrayRelease/Version/ContainerList/index.jsx
- src/components/Forms/GrayRelease/Version/ContainerList/index.scss
- src/components/Forms/GrayRelease/Version/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
- src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
- src/stores/grayrelease.js
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2525
#https://github.com/kubesphere/kubesphere/issues/2523
```
```
```docs
```
> fix: Fix grayrelease issues

- src/actions/workload.js
- src/components/Cards/Pods/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.scss
- src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
- src/locales/en/workload.js
- src/pages/projects/components/Modals/RollBack/index.jsx
- src/pages/projects/containers/Base/Detail/index.jsx
- src/pages/projects/containers/DaemonSets/Detail/index.jsx
- src/pages/projects/containers/Deployments/Detail/index.jsx
- src/pages/projects/containers/StatefulSets/Detail/index.jsx
- src/stores/workload/index.js
- src/stores/workload/revision.js
- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2171
```
```
```docs
```
> fix: Fix workload rollback

- src/pages/access/containers/Accounts/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/854
```
```
```docs
```
> fix: Fix role missing in user detail

- src/pages/clusters/components/ResourceTable/index.jsx
- src/pages/projects/containers/Overview/ResourceUsage/AppResourceItem/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/747
```
```
```docs
```
> fix: Fix project overview redirect in cluster management

- src/components/Tables/Base/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2521
```
```
```docs
```
> fix: Fix base table empty

- src/components/Forms/StorageClass/ProvisionerSettings/index.jsx
- src/components/Forms/StorageClass/StorageClassSettings/index.jsx
- src/utils/constants.js
/kind feature
Fixes #https://github.com/kubesphere/console/issues/858
```
```
```docs
```
> update: Support custom provisioner for storageclass

- src/components/Forms/Workload/ContainerSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/861
```
```
```docs
```
> fix: Fix statefulset service name generate rule

- src/components/Forms/Workload/VolumeSettings/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix volumeTemplate in statfulset

- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
- src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
- src/pages/projects/components/Cards/ImageBuilderLastRun/index.scss
- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/pages/projects/components/Cards/ImageRunRecord/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
- src/stores/container.js
- src/stores/devops/pipelines.js
- src/stores/s2i/run.js
/kind bug
Fixes [#2452](https://github.com/kubesphere/kubesphere/issues/2452) #446 
```
```
```docs
```
> fix: Fix the product download link and delete the search in the build mirror

- server/components/locale.js
- server/controllers/session.js
- server/controllers/view.js
- server/locales/en.properties
- server/locales/tc.properties
- server/locales/zh.properties
- src/utils/index.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/708
```
```
```docs
```
> fix: Add locales for tc and fix server default lang

- src/components/Modals/FedProjectCreate/index.jsx
- src/components/Modals/ProjectCreate/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2538
```
```
```docs
```
> refactor: Refactor project create name validation

- src/stores/node.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/871
```
```
```docs
```
> fix: Fix node detail missing kind

- server/config.yaml
- src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
- src/locales/en/nodes.js
- src/locales/en/workload.js
- src/locales/tc/workload.js
- src/locales/zh/nodes.js
- src/locales/zh/workload.js
- src/pages/clusters/containers/Nodes/Detail/RunningStatus/index.jsx
- src/pages/clusters/containers/Nodes/Detail/RunningStatus/index.scss
- src/pages/clusters/containers/Nodes/Detail/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/crd.resource.js
- src/stores/project.federated.js
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2481
```
```
```docs
```
> fix: Fix workspace projects and fedprojects permissions

- src/pages/workspaces/containers/FedProjects/index.jsx
- src/stores/project.federated.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix federated projects watch

- src/core/global.js
- src/pages/projects/App.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2535
```
```
```docs
```
> fix: Fix permission extend

- server/config.yaml
- src/components/Forms/GrayRelease/Version/index.jsx
- src/components/Forms/Service/BaseInfo/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/core/global.js
- src/locales/en/application.js
- src/locales/tc/application.js
- src/locales/zh/application.js
- src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
- src/pages/projects/components/WorkloadStatus/index.jsx
- src/utils/constants.js
- src/utils/status.js
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2545
#https://github.com/kubesphere/kubesphere/issues/2546
```
```
```docs
```
> fix: Fix workload name in service create

- src/pages/workspaces/containers/Members/Detail/index.jsx
Fix https://github.com/kubesphere/kubesphere/issues/2559
> fix workspace members button

- src/locales/en/application.js
- src/locales/tc/application.js
- src/locales/zh/application.js
> fix connection pool wording

- server/config.yaml
- src/components/Modals/CustomMonitoring/index.jsx
- src/components/Modals/EditAuthorization/index.jsx
- src/components/Modals/ProjectSelect/index.jsx
- src/components/Modals/RoleCreate/index.jsx
- src/locales/tc/role.js
- src/pages/access/containers/Roles/index.jsx
- src/pages/clusters/containers/Alerting/Messages/index.jsx
- src/pages/clusters/containers/Roles/index.jsx
- src/pages/devops/containers/Roles/index.jsx
- src/pages/fedprojects/containers/Alerting/Messages/index.jsx
- src/pages/fedprojects/containers/Overview/BaseInfo/index.jsx
- src/pages/fedprojects/containers/Overview/ResourceUsage/index.jsx
- src/pages/projects/containers/Alerting/Messages/index.jsx
- src/pages/projects/containers/CustomMonitoring/EditDashborad/index.jsx
- src/pages/projects/containers/CustomMonitoring/index.jsx
- src/pages/projects/containers/Network/Policies/IsolateInfo/index.jsx
- src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
- src/pages/projects/containers/Network/Policies/index.jsx
- src/pages/projects/containers/Roles/index.jsx
- src/pages/workspaces/containers/Base/List/index.jsx
- src/pages/workspaces/containers/BaseInfo/index.jsx
- src/pages/workspaces/containers/Members/Detail/index.jsx
- src/pages/workspaces/containers/Roles/index.jsx
- src/stores/user.js
/kind bug
2b76fa5 Fixes #https://github.com/kubesphere/kubesphere/issues/2553
1244ac8 Fixes #https://github.com/kubesphere/kubesphere/issues/2551
7ac7239 Fixes #https://github.com/kubesphere/kubesphere/issues/2558 #https://github.com/kubesphere/kubesphere/issues/2548
```
```
```docs
```
> Fix some permission issues

- src/pages/fedprojects/App.jsx
- src/pages/workspaces/containers/Repos/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix app repo index

- src/components/Forms/CICDs/AdvanceSettings/index.jsx
> chore: Fix the pipeline desction 

- .eslintrc.js
- package.json
- server/controllers/session.js
- server/libs/request.base.js
- server/middlewares/checkToken.js
- server/routes.js
- server/services/session.js
- yarn.lock
/kind bug
Fixes #
```
```
```docs
```
> update: Add token check and refresh token before expire

- src/pages/workspaces/containers/DevOps/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes [kubesphere/kubesphere #2571](https://github.com/kubesphere/kubesphere/issues/2571)
```
```
```docs
```
> fix: Add the alias name in devops list

- src/components/Modals/DevOpsCreate/index.jsx
/kind bug
Fixes [kubesphere/kubesphere #2569](https://github.com/kubesphere/kubesphere/issues/2569)
```
```
```docs
```
> fix: Add DevOps name validator in DevOps create modal

- src/pages/apps/containers/Categories/Apps/index.jsx
- src/pages/apps/containers/Reviews/index.jsx
- src/pages/apps/containers/Store/Detail/AuditRecord/index.jsx
- src/pages/apps/containers/Store/index.jsx
- src/pages/clusters/containers/Alerting/Messages/index.jsx
- src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
- src/pages/clusters/containers/Storage/Volumes/index.jsx
- src/pages/fedprojects/containers/Alerting/Messages/index.jsx
- src/pages/fedprojects/containers/Applications/index.jsx
- src/pages/projects/containers/Alerting/Messages/index.jsx
- src/pages/projects/containers/Applications/CRDApps.jsx
- src/pages/projects/containers/Applications/OPApps.jsx
- src/pages/projects/containers/Volumes/index.jsx
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2583
#https://github.com/kubesphere/console/issues/892
```
```
```docs
```
> fix: Fix table search for apps and volumes

- src/pages/workspaces/containers/Apps/index.jsx
- src/pages/workspaces/containers/Repos/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix workspace apps search

- server/config.yaml
- server/services/session.js
- src/actions/federated.js
- src/components/Cards/Pods/index.jsx
- src/components/Forms/StorageClass/StorageClassSettings/index.jsx
- src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
- src/components/Modals/History/index.jsx
- src/locales/en/cluster.js
- src/locales/tc/cluster.js
- src/locales/zh/cluster.js
- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
- src/pages/fedprojects/App.jsx
- src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
- src/pages/fedprojects/containers/QuotaManage/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/pages/workspaces/containers/FedProjects/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/storageClass.js
- src/stores/user.js
/kind bug
Fixes 
#https://github.com/kubesphere/console/issues/893
#https://github.com/kubesphere/kubesphere/issues/2587
#https://github.com/kubesphere/kubesphere/issues/2577
```
```
```docs
```
> fix: Fix user permissions

- src/components/Modals/DevOpsCreate/index.jsx
- src/pages/devops/containers/Credential/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/devops/credential.js
/kind bug
Fixes #896 #894 
```
```
```docs
```
> fix: Fix the total of the credentials list and the default cluster in the DevOps create modal

- src/components/Forms/AppDeploy/BasicInfo/index.jsx
- src/locales/en/application.js
- src/locales/es/application.js
- src/locales/tc/application.js
- src/locales/zh/application.js
- src/pages/appStore/containers/AppDetail/index.jsx
- src/pages/apps/components/VersionSelect/index.jsx
- src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
- src/pages/projects/components/Modals/RepoApp/AppDetail/index.jsx
- src/pages/projects/containers/Applications/OPApps.jsx
- src/stores/openpitrix/application.js
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2607
#https://github.com/kubesphere/kubesphere/issues/2606
#https://github.com/kubesphere/kubesphere/issues/2605
#https://github.com/kubesphere/kubesphere/issues/2604
```
```
```docs
```
> fix: Fix application issues

- src/pages/devops/containers/Roles/index.jsx
/kind bug
Fixes #920
```
```
```docs
```
> fix: Fix the page of role in the DevOps

- server/config.yaml
- src/pages/access/containers/Roles/Detail/AuthorizationList/index.jsx
- src/utils/index.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix role authorization list

- src/components/Forms/CICDs/RepoSelect/GithubForm/index.jsx
- src/components/Forms/CICDs/RepoSelect/subForm.jsx
- src/components/Forms/CICDs/paramsModal.jsx
- src/locales/en/cicd.js
- src/locales/tc/cicd.js
- src/locales/zh/cicd.js
- src/pages/devops/components/PipelineStatus/card.jsx
- src/pages/devops/containers/Credential/credentialModal.jsx
- src/pages/devops/containers/Credential/index.jsx
- src/stores/devops/credential.js
- src/stores/devops/pipelines.js
- src/stores/devops/scm.js
What type of PR is this?
/kind bug
What this PR does / why we need it:
Which issue(s) this PR fixes:
Fixes #904 #908 #910 #912 #913
Special notes for reviewers:
Additional documentation, usage docs, etc.:
> fix: Fix some issues in the DevOps

- src/pages/workspaces/containers/Projects/index.jsx
- src/stores/monitoring/base.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix workspace projects loading

- src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
- src/pages/projects/containers/CustomMonitoring/index.jsx
- src/stores/customMonitorDashboard.js
- src/utils/object.mapper.js
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2617
#https://github.com/kubesphere/kubesphere/issues/2616
#https://github.com/kubesphere/kubesphere/issues/2615
#https://github.com/kubesphere/kubesphere/issues/2614
```
```
```docs
```
> fix: Fix custom monitoring issues

- server/controllers/session.js
- src/pages/clusters/containers/Projects/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/932
```
```
```docs
```
> fix: Fix cluster projects search

- src/components/Modals/CustomMonitoring/components/TimeRangeSelect/index.jsx
- src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
- src/pages/fedprojects/components/ClusterWorkloadStatus/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/936
```
```
```docs
```
> fix: Fix cluster cards in federated deployment detail

- src/pages/clusters/containers/LogCollections/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/881
```
```
```docs
```
> fix: Fix log collections default tab

- src/components/Cards/Pods/index.jsx
- src/pages/projects/containers/Volumes/Detail/Snapshots/index.jsx
- src/stores/storageclasscapabilities.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2632
```
```
```docs
```
> fix: Fix snapshot pagination in volume detail

- src/actions/pipeline.js
- src/locales/en/cicd.js
- src/locales/tc/cicd.js
- src/locales/zh/cicd.js
- src/pages/devops/components/Pipeline/StepModals/input.jsx
- src/pages/devops/containers/Credential/credentialModal.jsx
- src/pages/devops/containers/Credential/index.jsx
- src/pages/devops/containers/Members/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops/pipelines.js
/kind bug
Fixes ##927 #929 #931 #937 #945 #949 #960
```
```
```docs
```
> fix: Fix some issues in the pipeline and the credential

- src/locales/tc/base.js
- src/locales/zh/base.js
Signed-off-by: Ray Zhou <ray@yunify.com>
/kind cleanup
> Chore(locales): minor change

- package.json
- src/locales/en/base.js
- src/locales/en/lego.js
- src/locales/es/base.js
- src/locales/tc/base.js
- src/locales/zh/base.js
- src/locales/zh/lego.js
- yarn.lock
> chore: Update lego locales

- src/components/Modals/ProjectSelect/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix multi-cluster projects in project select modal

- src/components/Cards/Pods/index.jsx
- src/core/containers/Base/List/index.jsx
- src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
- src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix pods updating

- src/locales/en/role.js
- src/locales/es/cicd.js
- src/locales/es/role.js
- src/locales/tc/role.js
Add "grant permission to" for role desc, fix https://github.com/kubesphere/console/issues/965, add missing UI key for Spanish and Traditional Chinese
> Role desc readability improvement

- src/components/Forms/CICDs/paramsModal.jsx
- src/components/Modals/DevOpsEdit/index.jsx
- src/pages/devops/components/Modals/DevOpsEdit/index.jsx
- src/pages/devops/components/Pipeline/StepModals/input.jsx
- src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/devops.js
- src/stores/devops/pipelines.js
/kind bug
Fixes ##952 ##953 #[#2625](https://github.com/kubesphere/kubesphere/issues/2625)
```
```
```docs
```
> fix: Fix the alias name and the add credential modal in the devOps

- src/utils/monitoring.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/974
```
```
```docs
```
> fix: Fix fill empty metrics algorithm

- src/pages/access/containers/Accounts/Detail/LoginHistory/index.jsx
- src/pages/access/containers/Accounts/Detail/LoginHistory/index.scss
- src/pages/access/containers/Accounts/Detail/index.jsx
- src/pages/access/containers/Accounts/index.jsx
- src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.jsx
- src/pages/clusters/containers/LogCollections/Detail/routes.js
- src/pages/clusters/containers/Members/index.jsx
- src/pages/console/containers/Dashboard/index.jsx
- src/pages/devops/containers/Members/index.jsx
- src/pages/projects/containers/Members/index.jsx
- src/pages/workspaces/containers/Members/index.jsx
- src/stores/user.js
- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/495
```
```
```docs
```
> fix: Fix user login records

- src/components/Base/Indicator/index.scss
- src/locales/tc/base.js
- src/locales/zh/base.js
- src/utils/constants.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2513
```
```
```docs
```
> fix: Fix cronjob status search

- src/locales/en/lego.js
Year fix in calendar; not applicable to English
> Year display fix

- src/stores/devops.js
> update :Update the devOps list api  in the devOps

- src/components/Forms/Workload/ContainerSettings/ContainerForm/SyncTimeZone/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/SyncTimeZone/index.scss
- src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/components/Forms/Workload/VolumeSettings/AddHostPath/index.jsx
- src/components/Forms/Workload/VolumeSettings/AddVolume/index.jsx
- src/locales/en/workload.js
- src/locales/es/workload.js
- src/locales/tc/workload.js
- src/locales/zh/workload.js
/kind feature
Fixes #https://github.com/kubesphere/kubesphere/issues/1492
```
```
```docs
```
> feat: Add sync host timezone for container

- src/utils/fed.templates.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/936
```
```
```docs
```
> fix: override annotations of federated project

- src/components/Forms/AppDeploy/AppConfig/index.jsx
- src/locales/en/app.js
- src/locales/es/app.js
- src/locales/tc/app.js
- src/locales/zh/app.js
/kind update
Fixes #
```
```
```docs
```
> fix: Fix app deploy form and yaml mode

- src/components/Modals/Network/Policies/IpBlock.jsx
- src/components/Modals/Network/Policies/index.scss
- src/locales/en/network.js
- src/locales/zh/network.js
/kind bug
Fix network policy valid bugs
Fixes https://github.com/kubesphere/kubesphere/issues/2554
> fix: Fix network policy valid bugs

- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/stores/devops.js
- src/stores/s2i/run.js
/kind bug
Fixes ##935 #[kubesphere/kubesphere #2624](https://github.com/kubesphere/kubesphere/issues/2624) #[kubesphere/kubesphere #2627](https://github.com/kubesphere/kubesphere/issues/2627)
```
```
```docs
```
> fix: Fix the si2 log in build mirror

- src/components/Modals/Delete/index.jsx
- src/locales/en/cluster.js
- src/locales/es/cluster.js
- src/locales/tc/cluster.js
- src/locales/zh/cluster.js
- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/992
```
```
```docs
```
> fix: Add confirm to removing worksapce from cluster visibility

- src/locales/en/monitoring.js
- src/locales/es/monitoring.js
- src/locales/tc/monitoring.js
Add en, es, tc capitalized key for https://github.com/kubesphere/console/issues/901
> add chart display desc

- src/locales/en/network.js
- src/locales/es/network.js
- src/locales/tc/network.js
- src/locales/zh/network.js
Add missing capitalized key for es and tc in network policy for https://github.com/kubesphere/console/pull/995
> Add missing cap key for all languages

- src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1000
```
```
```docs
```
> fix: Fix event detail timestamp format

- server/config.yaml
- src/pages/clusters/containers/Storage/Volumes/index.jsx
- src/pages/projects/containers/Applications/OPAppDetail/index.jsx
- src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
- src/pages/projects/containers/Volumes/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2687
```
```
```docs
```
> fix: Fix volumes auth key

- src/utils/monitoring.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2686
```
```
```docs
```
> fix: Show second in monitoing realtime

- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/495
```
```
```docs
```
> fix: Fix user last login time

- src/pages/clusters/containers/Storage/Volumes/index.jsx
- src/pages/projects/containers/Volumes/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix volume list status

- src/components/Forms/Workload/ClusterDiffSettings/ContainersMapper/index.jsx
- src/pages/fedprojects/components/ClusterWorkloadStatus/index.jsx
- src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1010
#https://github.com/kubesphere/console/issues/790
```
```
```docs
```
> fix: Fix multicluster workload cluster diff settings

- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/devops.js
- src/utils/constants.js
- src/utils/object.mapper.js
/kind bug
Fixes ##903 #[#kubesphere/kubesphere/2626](https://github.com/kubesphere/kubesphere/issues/2626)
```
```
```docs
```
>  fix: Fix the devops list use websocket to update data 

- src/pages/workspaces/containers/DevOps/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Add the status in the devops list

- src/locales/en/user.js
- src/locales/es/user.js
- src/locales/tc/user.js
- src/locales/zh/user.js
Update email address desc based on https://github.com/kubesphere/console/pull/959
> Update email address desc

- src/locales/tc/app.js
- src/locales/tc/cluster.js
- src/locales/tc/monitoring.js
- src/locales/tc/network.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> update: Update tc locale, translate newly added sentences

- src/locales/en/role.js
Two undisplayed page fixed now; update DevOps desc for it by adding "grant permission to" to improve readability
> Improve DevOps role desc

- src/components/Cards/Containers/Item.jsx
- src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
- src/pages/workspaces/containers/BaseInfo/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix volumes detail permission

- src/components/Base/Form/Group.jsx
- src/components/Forms/Service/AdvanceSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1018
```
```
```docs
```
> fix: Fix service sessionAffinity

- src/locales/tc/role.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> update: Update tc locale, modify the new description of role.js

- src/components/Forms/Service/AdvanceSettings/index.jsx
- src/components/Forms/Workload/AdvanceSettings/index.jsx
- src/components/HOCs/withList.js
- src/components/Modals/QuotaEdit/index.jsx
- src/locales/en/base.js
- src/locales/en/workload.js
- src/locales/es/base.js
- src/locales/es/project.js
- src/locales/tc/base.js
- src/locales/zh/base.js
- src/locales/zh/project.js
- src/locales/zh/workload.js
- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.scss
- src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
- src/pages/projects/containers/Overview/LimitRange/index.jsx
- src/pages/projects/containers/Overview/LimitRange/index.scss
- src/pages/projects/containers/Overview/Quota/index.jsx
- src/pages/projects/containers/Overview/Quota/index.scss
- src/pages/projects/containers/Overview/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> update: Add project quota and limitrange not set tip

- src/pages/devops/components/Pipeline/StepModals/input.jsx
- src/pages/devops/components/Pipeline/StepsSelector/index.jsx
- src/pages/devops/components/Pipeline/store.js
- src/pages/devops/components/PipelineStatus/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
- src/stores/devops/pipelines.js
/kind bug
Fixes #1030 
```
```
```docs
```
> fix: Fix the error that the editor and replay the pipeline

- src/components/Forms/StorageClass/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2711
```
```
```docs
```
> fix: Fix storageclass name validate

- src/components/Cards/Events/index.jsx
- src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.jsx
- src/stores/event.js
- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1034
```
```
```docs
```
> fix: Fix events card

- src/components/Cards/Events/index.jsx
- src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.jsx
- src/stores/event.js
- src/utils/object.mapper.js
Reverts kubesphere/console#1035
> Revert "fix: Fix events card"

- src/locales/en/project.js
- src/locales/es/project.js
- src/locales/es/workload.js
- src/locales/tc/project.js
- src/locales/tc/workload.js
> Add new UI key for all locs

- src/components/Cards/Events/index.jsx
- src/locales/en/base.js
- src/locales/es/base.js
- src/locales/tc/base.js
- src/locales/zh/base.js
- src/pages/workspaces/containers/Members/Detail/DevOps/index.jsx
- src/pages/workspaces/containers/Members/Detail/DevOps/index.scss
- src/pages/workspaces/containers/Members/Detail/Projects/index.jsx
- src/pages/workspaces/containers/Members/Detail/Projects/index.scss
- src/stores/devops.js
- src/stores/event.js
- src/stores/project.js
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix projects list in workspace member detail

- server/controllers/session.js
- server/views/login.html
/kind bug
Fixes #
```
```
```docs
```
> fix: Remove password from login form

- src/components/Modals/ProjectCreate/index.jsx
- src/pages/workspaces/containers/Projects/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Add default cluster for project create in workspace

- src/actions/member.js
- src/actions/network.js
- src/actions/openpitrix.js
- src/actions/volume.js
- src/pages/projects/containers/Volumes/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2695
```
```
```docs
```
> fix: Fix modal submit loading

- src/components/Forms/CICDs/BaseInfo/index.jsx
- src/pages/devops/containers/Credential/credentialModal.jsx
- src/stores/devops/base.js
- src/stores/devops/credential.js
/kind bug
Fixes ##1019 ##1023 ##916
```
```
```docs
```
> fix: Fix the name of error message in pipeline and credential

- src/utils/index.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2690
```
```
```docs
```
> fix: encode query value

- src/components/Base/Form/Item.jsx
- src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
- src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
- src/locales/en/storage.js
- src/locales/es/storage.js
- src/locales/tc/storage.js
- src/locales/zh/storage.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2689
```
```
```docs
```
> fix: Fix volume create issues

- server/views/login.html
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix login security problem

- src/pages/devops/containers/Credential/index.jsx
- src/pages/devops/containers/Roles/index.jsx
- src/stores/devops/credential.js
- src/stores/devops/scm.js
/kind bug
This pr, in addition to the following issues, also fixes the query parameters of the credential list.
Fixes ##916 ##1046
```
```
```docs
```
> fix: Fix the paging of credential and the role name in the Devops

- src/actions/project.js
- src/components/Cards/Events/index.jsx
- src/components/Forms/Route/RouteRules/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
- src/components/Forms/Workload/VolumeSettings/index.jsx
- src/components/HOCs/withList.js
- src/pages/fedprojects/containers/Applications/Detail/AppComponents/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/AppIngresses/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/TrafficManangement/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/index.jsx
- src/pages/fedprojects/containers/Applications/index.jsx
- src/pages/fedprojects/containers/BaseInfo/index.jsx
- src/pages/fedprojects/containers/ConfigMaps/Detail/ConfigDetail/index.jsx
- src/pages/fedprojects/containers/ConfigMaps/index.jsx
- src/pages/fedprojects/containers/Overview/LimitRange/index.jsx
- src/pages/fedprojects/containers/Overview/LimitRange/index.scss
- src/pages/fedprojects/containers/Overview/index.jsx
- src/pages/fedprojects/containers/Secrets/Detail/SecretDetail/index.jsx
- src/pages/fedprojects/containers/Secrets/Detail/index.jsx
- src/pages/fedprojects/containers/Secrets/index.jsx
- src/pages/fedprojects/containers/Services/Detail/index.jsx
- src/pages/fedprojects/containers/Services/index.jsx
- src/pages/fedprojects/containers/StatefulSets/Detail/ServiceCard/index.jsx
- src/pages/fedprojects/containers/Volumes/Detail/index.jsx
- src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
- src/pages/projects/containers/Overview/ResourceUsage/index.jsx
- src/stores/federated.js
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> update: Refactor federated resources list with resource API

- src/components/Forms/CICDs/AdvanceSettings/index.jsx
- src/components/Forms/CICDs/BaseInfo/index.jsx
- src/components/Forms/CICDs/RepoSelect/BitBucketForm/index.jsx
- src/pages/devops/containers/Credential/index.jsx
- src/pages/devops/containers/Pipelines/Modals/editPipelineConfigModal.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops/credential.js
- src/stores/devops/pipelines.js
/kind bug
Fixes ##914
```
```
```docs
```
> fix: Fix the bug when editing the pipeline and add sortBy in the credential

- server/config.yaml
- src/core/global.js
- src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2739
```
```
```docs
```
> fix: Fix cluster crd permission

- server/config.yaml
- server/proxy.js
- src/components/Layout/Header/index.jsx
- src/pages/appStore/containers/AppDetail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2674
```
```
```docs
```
> fix: Fix app store not login page

- server/config.yaml
- src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
- src/pages/projects/containers/VolumeSnapshots/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2746
```
```
```docs
```
> fix: Fix volume snapshots auth key

- server/config.yaml
- src/core/global.js
- src/pages/console/containers/Dashboard/index.jsx
- src/pages/projects/containers/Base/List/index.jsx
- src/pages/projects/containers/BaseInfo/index.jsx
/kind bug
Fixes 
#https://github.com/kubesphere/kubesphere/issues/2746
#https://github.com/kubesphere/kubesphere/issues/2747
#https://github.com/kubesphere/kubesphere/issues/2748
```
```
```docs
```
> fix: Show project overview when user can view workloads

- src/actions/devops.js
- src/components/Forms/CICDs/RepoSelect/BitBucketForm/index.jsx
- src/components/Modals/DevOpsCreate/index.jsx
- src/pages/devops/components/Pipeline/StepModals/input.jsx
- src/pages/devops/components/Pipeline/store.js
- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/devops.js
- src/stores/devops/scm.js
/kind bug
Fixes ##961 ##1055 ##1030  #[#kubesphere/kubesphere2736](https://github.com/kubesphere/kubesphere/issues/2736)
```
```
```docs
```
> fix: Fix the issues about the devops create and edit, verify the access,the reviewer

- src/pages/projects/containers/Volumes/Detail/Snapshots/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2632
```
```
```docs
```
> fix: Fix volume snapshots paging

- src/pages/console/containers/Dashboard/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix dashboard redirect

- src/components/Forms/AppDeploy/AppConfig/index.jsx
/kind bug
Fixes #https://kubesphere.com.cn/forum/d/1847-v3-0-0-chart
```
```
```docs
```
> fix: Fix heml chart without schema deploy

- src/locales/en/app_store.js
- src/locales/es/app_store.js
- src/locales/tc/app_store.js
- src/locales/zh/app_store.js
- src/pages/appStore/components/AppInfo/index.jsx
- src/pages/appStore/components/AppInfo/index.scss
- src/pages/appStore/containers/AppDetail/index.jsx
- src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
/kind bug
Fixes #[#2469](https://github.com/kubesphere/kubesphere/issues/2469) #[#1957](https://github.com/kubesphere/kubesphere/issues/1957)
```
```
```docs
```
> fix: add the version description in app info and title in build mirror

- src/pages/devops/containers/Roles/index.jsx
/kind bug
Fixes ##1072
```
```
```docs
```
> fix: Fix the role delete when it has authorized users

- src/pages/projects/containers/Applications/OPApps.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix op app list data getting

- server/services/session.js
- src/components/KubeTools/index.jsx
- src/pages/clusters/containers/Overview/Dashboard/index.jsx
- src/pages/clusters/containers/Projects/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1085
```
```
```docs
```
> fix: Fix operations for platform-admin

- src/components/Base/Breadcrumb/index.jsx
- src/components/Base/Breadcrumb/index.test.js
- src/core/layouts/Detail/index.jsx
- src/pages/devops/containers/Credential/detail/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
/kind bug
Fixes #[#kubesphere/kubesphere/1744](https://github.com/kubesphere/kubesphere/issues/1744)
```
```
```docs
```
> fix: Delete the back icon in pipeline breadcrumb

- src/pages/devops/containers/BaseInfo/index.jsx
- src/pages/devops/containers/BaseInfo/index.scss
- src/pages/projects/containers/BaseInfo/index.jsx
/kind bug
0ac14b103ed913b17e78d224486434d3d5254a46 Fixes #https://github.com/kubesphere/console/issues/1070
```
```
```docs
```
> fix: Fix project base info

- src/locales/en/component.js
- src/locales/es/component.js
- src/locales/tc/component.js
- src/locales/zh/component.js
Fix https://github.com/kubesphere/console/issues/918
> add component UI text

- src/locales/en/role.js
- src/locales/es/role.js
- src/locales/tc/role.js
- src/locales/zh/role.js
- src/pages/projects/containers/Applications/CRDAppDetail/routes.js
- src/pages/projects/containers/Applications/OPAppDetail/routes.js
/kind bug
Fixes #
```
```
```docs
```
> chore: Update locales for projec role description

- src/actions/imagebuilder.js
- src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
- src/components/Forms/ImageBuilder/RerunForm/index.jsx
- src/components/Modals/DevOpsEdit/index.jsx
- src/pages/devops/components/Modals/DevOpsEdit/index.jsx
- src/pages/devops/containers/Pipelines/index.jsx
/kind bug
Fixes ##1092 #[#2741](https://github.com/kubesphere/kubesphere/issues/2741)
```
```
```docs
```
> fix: Fix some issues about alias, get the pipeline data and the build mirror restart

- src/locales/zh/base.js
Signed-off-by: zackzhangkai <zackzhang@yunify.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> modify doc

- server/config.yaml
- src/components/Modals/EditAuthorization/CheckItem.jsx
- src/pages/clusters/containers/Overview/Dashboard/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/GrayRelease/index.jsx
- src/pages/projects/containers/GrayRelease/Categories/index.jsx
- src/pages/projects/containers/GrayRelease/index.jsx
- src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2764
```
```
```docs
```
> fix: Fix resource permission

- src/pages/workspaces/containers/BaseInfo/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix workspace network policy

- src/pages/clusters/actions/cluster.js
- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
- src/pages/clusters/containers/Visibility/index.jsx
- src/stores/cluster/index.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1105
```
```
```docs
```
> fix: Fix cluster visibility for public cluster

- src/pages/clusters/containers/Projects/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1114
```
```
```docs
```
> fix: Fix redirect after project deleted

- src/components/Forms/Volume/VolumeSettings/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix type switch in volume create modal

- src/locales/en/user.js
- src/locales/es/user.js
- src/locales/tc/user.js
- src/locales/zh/user.js
> Add new account status UI

- src/components/Forms/StorageClass/BaseInfo/index.jsx
- src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
- src/pages/clusters/containers/Storage/StorageClasses/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2793
```
```
```docs
```
> update: Update storageclass description

- src/components/Modals/EditAuthorization/constants.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix credential management in devops role create

- src/components/Modals/UserSetting/BaseInfo/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2794
```
```
```docs
```
> fix: Fix use settings modal restore

- package.json
- src/components/Base/Dragger/index.jsx
- src/components/Base/ScrollLoad/index.jsx
- src/components/Base/Steps/index.jsx
- src/components/Forms/GrayRelease/Components/Card/index.jsx
- src/components/Forms/ImageBuilder/B2IForm/index.jsx
- src/components/Graph/Detail/Monitors/TrafficCard.jsx
- src/components/Inputs/InputPassword/index.jsx
- src/components/Modals/AuditingSearch/Auditing/Detail/MetadataModal/Metadata/index.jsx
- src/components/Modals/CustomMonitoring/components/Form/GraphTargetsForm/index.jsx
- src/components/Modals/CustomMonitoring/components/FormInput/TableColumnStyle/index.jsx
- src/components/Modals/CustomMonitoring/components/RowTitleEditor/index.jsx
- src/components/Modals/CustomMonitoring/components/TableColumnStyleModal/index.jsx
- src/components/Modals/EventSearch/Event/Detail/MetadataModal/Metadata/index.jsx
- src/components/Tables/Ranking/index.jsx
- src/components/TextPreview/index.jsx
- src/pages/appStore/components/AppPreview/index.jsx
- src/pages/appStore/components/Banner/index.jsx
- src/pages/devops/components/Cards/CodeQualityResult/StatusCard.jsx
- src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
- src/pages/devops/components/Pipeline/StepsEditor/index.jsx
- src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
- src/pages/projects/components/Cards/ImageArtifacts/Item/index.jsx
- src/pages/projects/components/Modals/RepoApp/AppDetail/Banner/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix code erros tip by eslint

- src/components/Base/Search/index.jsx
- src/components/Tables/Base/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2786
```
```
```docs
```
> fix: Trim space of search word

- src/pages/appStore/containers/AppDetail/index.scss
- src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
- src/pages/projects/containers/VolumeSnapshots/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2808
```
```
```docs
```
> fix: Fix volume snapshots

- src/pages/clusters/containers/Projects/Detail/index.jsx
- src/pages/clusters/containers/Projects/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2785
```
```
```docs
```
> fix: Fix cluster projects operations

- src/locales/en/network.js
> Chore(locales): minor grammar fix

- src/components/Forms/Secret/SecretSettings/index.jsx
- src/locales/en/secret.js
- src/locales/es/secret.js
- src/locales/tc/secret.js
- src/locales/zh/secret.js
> fix secret UI

- src/components/Forms/CICDs/BaseInfo/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops.js
- src/stores/devops/pipelines.js
/kind bug
Fixes #[#kubesphere/kubesphere/2810](https://github.com/kubesphere/kubesphere/issues/2810) #[#kubesphere/kubesphere/2811](https://github.com/kubesphere/kubesphere/issues/2811)
```
```
```docs
```
> fix: Fix the name's length limitation and the description don't displayed in pipeline.

- src/pages/clusters/containers/Projects/Detail/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix cluster project detail

- src/components/Charts/Pie/PieChart/index.jsx
- src/components/Forms/Workload/AdvanceSettings/Metadata/index.jsx
- src/components/Forms/Workload/AdvanceSettings/index.jsx
- src/components/Forms/Workload/AdvanceSettings/index.scss
- src/stores/cluster/index.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix advance settings of federated resource

- src/pages/apps/components/Modals/AppEdit/index.jsx
- src/utils/constants.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1135
#https://github.com/kubesphere/console/issues/1137
```
```
```docs
```
> fix: Fix errors in app edit

- src/pages/clusters/containers/Projects/Detail/Quota/index.jsx
- src/pages/clusters/containers/Projects/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1139
```
```
```docs
```
> fix: Fix project detail reload in cluster pages

- src/actions/openpitrix.js
- src/locales/en/app.js
- src/locales/es/app.js
- src/locales/tc/app.js
- src/locales/zh/app.js
- src/pages/workspaces/containers/Apps/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2832
```
```
```docs
```
> fix: Add remove tip for app template

- src/pages/clusters/containers/Projects/Detail/index.jsx
- src/pages/clusters/containers/Projects/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2828
```
```
```docs
```
> fix: Fix project edit in cluster management

- src/configs/openpitrix/app.js
- src/locales/en/app.js
- src/locales/es/app.js
- src/locales/tc/app.js
- src/locales/zh/app.js
- src/pages/apps/components/Cards/CreateInfo/index.jsx
- src/pages/apps/components/Forms/AppBaseEdit/index.jsx
- src/stores/openpitrix/file.js
/kind bug
Fixes ##1133 ##1132
```
```
```docs
```
> fix: Fix the size of the upload icon should not exceed 96px and add the jpg, tgz MIME type

- src/pages/fedprojects/containers/Volumes/Detail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1151
```
```
```docs
```
> fix: Fix volumes detail

- src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
- src/components/Modals/AuditingSearch/Auditing/Detail/index.scss
- src/components/Modals/EventSearch/Event/Detail/index.jsx
- src/components/Modals/EventSearch/Event/Detail/index.scss
- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/components/Modals/LogSearch/Logging/Search/index.jsx
- src/components/Modals/LogSearch/Logging/Search/index.scss
- src/components/Tables/Visible/index.jsx
- src/components/Tables/Visible/index.scss
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2665
```
```
```docs
```
> fix: Fix log search results order

- src/components/Forms/CICDs/RepoSelect/GitForm/index.jsx
- src/components/Forms/CICDs/RepoSelect/SVNForm/index.jsx
- src/components/Forms/CICDs/RepoSelect/subForm.jsx
- src/pages/devops/components/Pipeline/StepModals/checkout.jsx
- src/pages/devops/components/Pipeline/StepModals/git.jsx
- src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
- src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
- src/pages/devops/components/Pipeline/store.js
- src/pages/devops/containers/Credential/index.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops/credential.js
- src/stores/devops/scm.js
/kind bug
Fixes ##1134 #[kubesphere/kubesphere#2826](https://github.com/kubesphere/kubesphere/issues/2826)
```
```
```docs
```
> fix: Fix the filter in pipeline table and get more then 10 items in the credential list

- src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
- src/components/Inputs/ProjectSelect/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Filter terminating project

- src/components/Forms/ImageBuilder/S2IForm/index.jsx
The UI text here should be the same as the one in locales. Add "the" and the period.
> Unify code repo UI

- src/components/Forms/Workload/ContainerSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2825
```
```
```docs
```
> fix: Fix volumes missing in workload container setting

- src/utils/constants.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2803
```
```
```docs
```
> fix: Fix ceph rbd provisioner

- server/middlewares/checkIfExist.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Restore check if exist api

- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/locales/en/workload.js
- src/locales/es/workload.js
- src/locales/tc/workload.js
- src/locales/zh/workload.js
Fixes #https://github.com/kubesphere/kubesphere/issues/2855
```
```
```docs
```
> chore: Add locales for deployment location

- src/locales/en/s2i.js
- src/locales/es/s2i.js
- src/locales/tc/s2i.js
- src/locales/zh/s2i.js
- src/pages/devops/containers/Pipelines/index.jsx
- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/pages/projects/components/Cards/S2iBuilder/index.jsx
- src/pages/projects/components/Cards/S2iBuilder/log.jsx
- src/pages/projects/components/Health/index.jsx
- src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/utils/request.js
/kind bug
Fixes ##1152 #[#kubesphere/kubesphere/2849](https://github.com/kubesphere/kubesphere/issues/2849) #[#kubesphere/kubesphere/2853](https://github.com/kubesphere/kubesphere/issues/2853)
```
```
```docs
```
> fix: Fix some issues in pipeline and s2i

- src/components/Forms/Service/AdvanceSettings/index.jsx
- src/components/Forms/Service/BaseInfo/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Omit version in service selector

- src/core/global.js
- src/pages/projects/containers/Applications/OPAppDetail/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1166
#https://github.com/kubesphere/console/issues/1165
```
```
```docs
```
> fix: Fix project applications permission and operations

- src/components/Forms/CICDs/RepoSelect/BitBucketForm/index.jsx
- src/components/Forms/CICDs/RepoSelect/GithubForm/index.jsx
- src/components/Forms/CICDs/RepoSelect/index.jsx
- src/pages/devops/components/Pipeline/StepModals/script.jsx
- src/pages/devops/components/Pipeline/store.js
- src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
- src/stores/devops/run.js
- src/stores/devops/scm.js
- src/stores/notification/mailService.js
- src/utils/index.js
- src/utils/request.js
/kind bug
Fixes #[kubesphere/kubesphere/#2865](https://github.com/kubesphere/kubesphere/issues/2865) #[kubesphere/kubesphere/#2861](https://github.com/kubesphere/kubesphere/issues/2861) #[kubesphere/kubesphere/#2859](https://github.com/kubesphere/kubesphere/issues/2859)
```
```
```docs
```
> fix: Fix some issues about the BitBucket and jenkinsfile

- src/components/Charts/Area/MultiArea/index.jsx
- src/components/Charts/Area/PercentArea/index.jsx
- src/components/Charts/Bar/SimpleBar/index.jsx
- src/components/Charts/Bar/StackedBar/index.jsx
- src/components/Forms/Service/BaseInfo/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/stores/service.js
- src/utils/monitoring.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix monitoring date in xAxis

- docs/development-workflow.md
Signed-off-by: pmc <pangmengchen@deepexi.com>
don't
```docs
just chang 'folk' to 'fork' on docs/development-workflow.md
```
> docs: chang 'folk' to 'fork'

- src/actions/volume.js
- src/components/Cards/Volumes/Item.jsx
- src/components/Cards/Volumes/index.jsx
- src/components/Clusters/ClusterWrapper/index.scss
- src/components/Forms/Volume/ClusterDiffSettings/EditForm/index.jsx
- src/components/Forms/Volume/ClusterDiffSettings/EditForm/index.scss
- src/components/Forms/Volume/ClusterDiffSettings/VolumeSettings/index.jsx
- src/components/Forms/Volume/ClusterDiffSettings/VolumeSettings/index.scss
- src/components/Forms/Volume/ClusterDiffSettings/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/ContainerImage/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/ContainerPorts/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/Environments/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/VolumeTemplate/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/VolumesMapper/index.jsx
- src/components/Forms/Workload/ClusterDiffSettings/VolumesMapper/index.scss
- src/components/Forms/Workload/ClusterDiffSettings/index.jsx
- src/locales/en/storage.js
- src/locales/es/storage.js
- src/locales/tc/base.js
- src/locales/tc/storage.js
- src/locales/zh/base.js
- src/locales/zh/storage.js
- src/pages/fedprojects/containers/Volumes/index.jsx
- src/pages/projects/containers/Pods/Containers/ResourceStatus.jsx
- src/pages/projects/containers/Pods/Detail/ResourceStatus.jsx
- src/utils/index.js
- src/utils/monitoring.js
/kind feature
Fixes #https://github.com/kubesphere/console/issues/1169
```
```
```docs
```
> update: Add volume cluster diff setting

- src/actions/log.collection.js
- src/components/Forms/Elasticsearch/Settings/index.jsx
- src/components/Modals/LogCollectionCreate/config.js
- src/locales/en/logging.js
- src/locales/es/logging.js
- src/locales/tc/logging.js
- src/locales/zh/logging.js
- src/pages/clusters/containers/LogCollections/Detail/Configuration/index.jsx
- src/pages/clusters/containers/LogCollections/config.js
- src/pages/clusters/containers/LogCollections/index.scss
- src/stores/logging/collection/output.js
- src/utils/constants.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1174
```
```
```docs
```
> fix: Fix log collection form

- src/locales/en/s2i.js
- src/locales/en/storage.js
- src/locales/es/s2i.js
- src/locales/es/storage.js
- src/locales/tc/s2i.js
- src/locales/zh/s2i.js
- src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
- src/pages/projects/components/Cards/S2iBuilder/log.jsx
> chore(locales): minor wording update

- src/locales/en/workload.js
- src/locales/es/workload.js
- src/locales/tc/workload.js
- src/locales/zh/workload.js
- src/pages/clusters/containers/Workload/Jobs/index.jsx
- src/pages/projects/containers/Jobs/index.jsx
- src/utils/object.mapper.js
- src/utils/workload.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2873
```
```
```docs
```
> fix: Fix job update time

- src/utils/index.test.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Remove unit test for getLocalTime

- src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
- src/pages/fedprojects/components/ClusterWorkloadStatus/index.jsx
- src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
- src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1179
```
```
```docs
```
> fix: Fix federated workload edit permission

- src/locales/tc/app.js
- src/locales/tc/base.js
- src/locales/tc/logging.js
- src/locales/tc/s2i.js
- src/locales/tc/storage.js
- src/locales/tc/workload.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> chore(locales): Update tc locale

- src/pages/devops/containers/Credential/index.jsx
/kind bug
Fixes ##1183
```
```
```docs
```
> fix: Fix the empty list display the wrong desc in the credential of devops

- src/stores/workload/index.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2876
```
```
```docs
```
> fix: Fix created success tip when workload requests empty

- src/pages/fedprojects/containers/Volumes/Detail/index.jsx
- src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix create time format in volume detail

- src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
- src/pages/devops/containers/Pipelines/index.jsx
- src/stores/devops/base.js
- src/stores/devops/scm.js
- src/utils/request.js
/kind bug
Fixes #[#kubesphere/kubesphere/2849](https://github.com/kubesphere/kubesphere/issues/2849)
```
```
```docs
```
> fix: Fix the run pipeline in the branch and pipeline list

- src/components/Forms/Route/RouteRules/RuleForm/index.jsx
- src/core/containers/Base/Detail/BaseInfo/Attributes/index.scss
- src/pages/clusters/containers/Workload/Routes/index.jsx
- src/pages/clusters/containers/Workload/Services/index.jsx
- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
- src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
- src/pages/fedprojects/containers/Services/Detail/Ports/index.jsx
- src/pages/projects/components/Cards/Services/Item.jsx
- src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
- src/pages/projects/components/Modals/CreateApp/index.jsx
- src/pages/projects/components/ServiceAccess/index.jsx
- src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
- src/pages/projects/containers/Routes/Detail/index.jsx
- src/pages/projects/containers/Routes/index.jsx
- src/pages/projects/containers/Services/Detail/Ports/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/pages/projects/containers/Services/index.jsx
- src/utils/object.mapper.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix loadbalancer info of service, ingress and gateway

- src/pages/projects/containers/Services/Detail/Ports/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Remove click access of service

- src/locales/en/component.js
- src/locales/es/component.js
- src/locales/tc/component.js
- src/locales/zh/component.js
Add service component desc; fix https://github.com/kubesphere/website/issues/118
> Add service component desc

- src/components/Forms/LoggingCollection/Status/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix log collection text

- src/components/Forms/CICDs/AdvanceSettings/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix the default value of shallow clone is false

- src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Show volume usage card for all types

- src/pages/devops/containers/Pipelines/index.jsx
/kind bug
Fixes #[#kubesphere/kubekey/#230](https://github.com/kubesphere/kubekey/issues/230)
```
```
```docs
```
> fix: Fix the pipeline list had no access control

- src/stores/openpitrix/application.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Change pending op application to failed

- src/components/Base/Dragger/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix Dragger onClick event

- src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
- src/components/Inputs/PropertiesInput/index.jsx
- src/scss/lego.custom.scss
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2895
```
```
```docs
```
> fix: Fix PropertiesInput controled mode

- src/locales/tc/component.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> chore(locales): Update tc locale, modify component.js

- src/components/Graph/Detail/Pods/Item.jsx
- src/components/Graph/Detail/Pods/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix pod link error in graph detail

- src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
- src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
- src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix loadBalancerIngress undefined error

- src/components/Graph/Detail/PolicyForm/Session.jsx
- src/components/Graph/Detail/PolicyForm/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Add validator for servicemesh policy form

- src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
- src/stores/cluster/index.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2896
```
```
```docs
```
> fix: Fix clusters fetch API when creating workspace

- src/actions/service.js
- src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
- src/pages/projects/components/Modals/ServiceSetting/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/2895
```
```
```docs
```
> fix: Fix service edit cluster info missing

- server/config.yaml
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
>
Fixes #
```
```
```docs
```
> add documentation links

- src/pages/clusters/components/ResourceTable/index.jsx
- src/pages/clusters/containers/Nodes/Detail/RunningStatus/ConditionCard/index.jsx
- src/pages/clusters/containers/Nodes/Detail/RunningStatus/TaintCard/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix node conditions card

- src/utils/index.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix docs link

- src/pages/projects/components/Cards/Placement/index.jsx
- src/pages/projects/containers/Volumes/Detail/index.jsx
- src/stores/storageclasscapabilities.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix volume detail incorrect info

- src/actions/devops.js
- src/pages/workspaces/containers/DevOps/index.jsx
/kind bug
Fixes ##1210
```
```
```docs
```
> fix: Fix batch deletion items by rowkey in the Devops list

- server/config.yaml
- src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> chore: Update docs links

- src/pages/devops/containers/Pipelines/index.jsx
/kind bug
Fixes #[#kubesphere/kubesphere/#2905](https://github.com/kubesphere/kubesphere/issues/2905)
```
```
```docs
```
> fix: Fix the run job in the pipeline list have no parameters

- src/components/DiffYaml/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> update: Show entire yaml file of workload revision

- src/pages/clusters/containers/LogCollections/Detail/Configuration/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix log collection detail info

- src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
- src/stores/openpitrix/application.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix app deploy placement and app status

- src/locales/en/storage.js
- src/locales/es/storage.js
- src/locales/tc/storage.js
- src/locales/zh/storage.js
- src/pages/fedprojects/containers/Volumes/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Volumes/Detail/ResourceStatus/UsageCard/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> update: Add volume monitor tip

- src/components/Forms/CICDs/paramsModal.jsx
/kind bug
Fixes #[#kubesphere/kubesphere#2924](https://github.com/kubesphere/kubesphere/issues/2924)
```
```
```docs
```
> fix: Fix the error which the type of choice in the parameters have no choices

- src/components/Base/Markdown/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Support rendering html in markdown component.

- src/locales/tc/storage.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
```
```docs
```
> chore(locales): Update tc locale, modify storage.js

- src/components/Modals/Node/TaintManagement/TaintInput/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Support empty node taint value.

- src/components/Cards/LogQuery/index.jsx
- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/stores/logging/index.js
- src/stores/logging/query.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix log query export url

- cypress/integration/projects/deployments/detail.spec.js
- src/components/Cards/Banner/Tip.jsx
- src/components/Cards/Banner/index.jsx
- src/components/Modals/About/index.jsx
- src/components/Modals/History/index.jsx
- src/pages/apps/components/Cards/TestSteps/index.jsx
- src/pages/apps/components/Modals/AppCreate/index.jsx
- src/pages/apps/components/Modals/HelmUpload/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
- src/pages/devops/components/Cards/CodeQualityIssues/issue.jsx
- src/pages/devops/components/Cards/CodeQualityResult/StatusCard.jsx
- src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
- src/pages/fedprojects/containers/Overview/Help/index.jsx
- src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Rule/index.jsx
- src/pages/fedprojects/containers/Services/Detail/Ports/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/Ingresses/Item.jsx
- src/pages/projects/containers/Overview/Help/index.jsx
- src/pages/projects/containers/Routes/Detail/ResourceStatus/Rule.jsx
- src/pages/settings/components/Modals/GithubOAuth/index.jsx
- src/pages/settings/containers/BaseInfo/index.jsx
- src/stores/devops/credential.js
- src/utils/constants.js
> /kind flake
Fixes #
```
```
```docs
```
> fix: Fix the incomplete URL substring sanitization

- package.json
Signed-off-by: pmc <pangmengchen@gmail.com>
>
Fixes #https://github.com/kubesphere/console/issues/1229
on windows  run `yarn start`
```docs
```
> fix: start script support windows platform

- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/components/Modals/LogSearch/Logging/Detail/index.scss
/kind bug
Restore pod/container select in log search modal.
Fixes #
```
```
```docs
```
> update: Restore pod and container select in log search

- src/components/Base/TypeSelect/index.jsx
- src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
- src/components/Forms/Volume/VolumeSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1237
```
```
```docs
```
> fix: Fix volume create from snapshot spec error

- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/stores/project.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix log search link error

- src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
- src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
- src/components/Forms/Volume/VolumeSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1237
```
```
```docs
```
> fix: Fix create volume from snapshot validating

- src/components/Forms/GrayRelease/PolicyConfig/Bluegreen/VersionSelect/index.jsx
- src/locales/en/grayrelease.js
- src/locales/es/grayrelease.js
- src/locales/tc/grayrelease.js
- src/locales/zh/grayrelease.js
Update blue-green deployment wording
> update traffic management wording

- src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
- src/components/Forms/Secret/SecretSettings/DataList/index.jsx
- src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/index.jsx
- src/pages/fedprojects/containers/Secrets/Detail/SecretDetail/index.jsx
- src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx
- src/stores/devops/credential.js
- src/stores/openpitrix/file.js
- src/stores/workload/env.js
- src/utils/app.js
- src/utils/base64.js
- src/utils/base64.test.js
- src/utils/index.js
- src/utils/object.mapper.js
> fix: Fix the Chinese encoding problem of the username in the credential

- yarn.lock
Reverts kubesphere/console#1234
May cause break changes.
> Revert "chore: Upgrade dependencies"

- babel.config.js
- cypress/integration/workspaces/members.spec.js
- package.json
- src/components/Graph/Detail/Monitors/TrafficCard.jsx
- src/components/Graph/Detail/PolicyForm/index.scss
- src/components/Inputs/AddonsInput/index.scss
- src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
- src/components/Modals/AuditingSearch/Auditing/Detail/index.scss
- src/components/Modals/AuditingSearch/Auditing/Home/index.scss
- src/components/Modals/CustomMonitoring/components/TimeRangeSelect/index.scss
- src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.scss
- src/components/Modals/EventSearch/Event/Detail/index.jsx
- src/components/Modals/EventSearch/Event/Detail/index.scss
- src/components/Modals/EventSearch/Event/Home/index.scss
- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/components/Modals/LogSearch/Logging/Detail/index.scss
- src/components/Modals/LogSearch/Logging/Home/index.scss
- src/components/Modals/LogSearch/Logging/Search/index.scss
- src/core/App.jsx
- src/core/i18n.js
- src/pages/apps/components/Cards/CreateInfo/index.scss
- src/pages/apps/components/Modals/HelmUpload/index.scss
- src/pages/devops/components/Pipeline/store.js
- src/scss/custom.scss
- src/scss/main.scss
- src/stores/devops/run.js
- yarn.lock
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix log search styles

- src/stores/devops/run.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix the parallel display problem of pipeline in details

- scripts/webpack.prod.js
/kind bug
Fixes #
```
```
```docs
```
> chore: Add css extract for kube-design styles

- server/components/boot.js
Signed-off-by: qinyueshang <yue_hong_y@163.com>
/kind bug
Fixes #
```
```
```docs
```
> fix:  Add a filter file type

- src/components/Base/CodeEditor/index.jsx
- src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix code editor value update

- Dockerfile.arm64
/kind bug
old image may cause OOM error
Fixes #
```
```
```docs
```
> chore: Change arm64 base image

- src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix audit status code error

- package.json
- yarn.lock
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix form onChange not response

- src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix gateway loadBalancerIngress error

- package.json
- scripts/webpack.base.js
- scripts/webpack.dev.js
- yarn.lock
/kind feature
Add react-refresh https://github.com/pmmmwh/react-refresh-webpack-plugin for development.
Fixes #
```
```
```docs
```
> chore: Add react fast refresh

- src/components/Forms/GrayRelease/Components/index.jsx
/kind bug
Remove the application fetching limit when creating a grayrelease.
Fixes #
```
```
```docs
```
> fix: Remove application fetching limit in grayrelease modal

- src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Show replicas control with HPA

- src/pages/projects/containers/Services/Detail/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Add service DNS info

- src/components/KubeTools/index.jsx
- src/components/KubeTools/index.scss
/kind bug
Save kube tools position to local storage.
Fixes #https://kubesphere.com.cn/forum/d/2594
```
```
```docs
```
> fix: Save kube tools position to local storage

- src/components/Forms/Pipelines/AdvanceSettings/index.jsx
- src/pages/appStore/containers/AppDeploy/index.jsx
- src/pages/devops/components/Cards/CodeQualityResult/index.jsx
- src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
- src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
- src/stores/openpitrix/app.js
/kind bug
Fixes ##1250 ##1269 ##1278 ##1289
```
```
```docs
```
> fix: Fix some bugs about cron and pipeline stage

- package.json
- yarn.lock
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix unexpect token ... error

- src/components/Forms/Pipelines/AdvanceSettings/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
/kind bug
Fixes ##1289 
```
```
```docs
```
> fix: Fix the webhook address in the pipeline edit page

- src/components/Forms/Cluster/AdvanceSettings/index.jsx
- src/components/Forms/Cluster/ClusterSettings/index.jsx
- src/components/Forms/Cluster/NodeList/AddNode.jsx
- src/locales/en/cluster.js
- src/locales/es/cluster.js
- src/locales/tc/cluster.js
- src/locales/zh/cluster.js
- src/pages/clusters/containers/Overview/Initializing/KubeKeyCluster/Progress/index.jsx
- src/pages/clusters/containers/Overview/Initializing/KubeKeyCluster/Progress/index.scss
- src/stores/cluster/kubekey.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix cluster creating form errors

- src/configs/openpitrix/version.js
- src/locales/en/dashboard.js
- src/locales/en/version.js
- src/locales/es/version.js
- src/locales/tc/version.js
- src/locales/zh/version.js
- src/pages/apps/components/Cards/TestSteps/index.jsx
- src/pages/apps/components/Modals/VersionSubmit/index.jsx
> Chore(locales): refine some UI

- src/stores/application/crd.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix health data filter in app traffic monitor

- package.json
- src/components/Base/Cascader/Item.jsx
- src/components/Base/Cascader/index.jsx
- src/components/Base/Cascader/index.scss
- src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.jsx
- src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.scss
- src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/Item.jsx
- src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/index.jsx
- src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/index.scss
- src/components/Modals/CustomMonitoring/components/PromQLInput/grammar.js
- src/components/Modals/CustomMonitoring/components/PromQLInput/index.jsx
- src/components/Modals/CustomMonitoring/components/PromQLInput/index.scss
- src/components/Modals/CustomMonitoring/components/PromQLInput/promql.js
- yarn.lock
/kind feature
See https://github.com/kubesphere/kubesphere/issues/3067 and [e2-promql-autocompletion-and-syntax-highlighting](https://github.com/kubesphere/community/blob/master/sig-observability/concepts-and-designs/202009_custom-monitoring-enhancement.md#e2-promql-autocompletion-and-syntax-highlighting
)
Fixes #
```
```
```docs
```
> feat: Support promql highlight and suggestions

- src/pages/projects/components/Modals/RepoApp/AppDetail/index.jsx
/kind bug
The previous PR https://github.com/kubesphere/console/pull/1293 should be committed with a sign, and the code style is inconsistent with the console.
The previous PR has not been updated in the last 12 days, so we replace the previous PR with this.
Fixes #https://github.com/kubesphere/console/issues/1291
```
```
```docs
```
> fix: Fix TypeSelect import missing

- src/stores/devops/run.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1309
```
```
```docs
```
> fix: Add table query limit in pipeline run

- README.md
- docker-compose.builder.yaml
- docker-compose.yaml
- docs/access-backend.md
- docs/development-with-docker.md
> chore: Optimize volume mount for developing with docker

- src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.jsx
- src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.scss
- src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/index.jsx
- src/components/Modals/CustomMonitoring/components/PromQLInput/history.js
- src/components/Modals/CustomMonitoring/components/PromQLInput/index.jsx
- src/components/Modals/CustomMonitoring/components/PromQLInput/index.scss
- src/components/Modals/CustomMonitoring/components/PromQLInput/promql.js
- src/stores/monitoring/custom/labelsets.js
> update: Support labelsets suggestion for promql

- src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/Placement/index.scss
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/pages/projects/components/Modals/CreateApp/Services/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3133
```
```
```docs
```
> fix: Fix image search error in multi cluster project

- package.json
- src/components/Cards/ContainerLog/index.jsx
- src/components/Inputs/StringInput/index.jsx
- src/components/Modals/LogSearch/Logging/Detail/index.jsx
- src/components/Modals/LogSearch/Logging/Detail/index.scss
- src/components/Modals/LogSearch/Logging/Search/index.jsx
- src/scss/base.scss
- yarn.lock
> update: Support ansi color in container log

- src/components/Forms/GrayRelease/Components/index.jsx
- src/components/Forms/GrayRelease/Version/index.jsx
- src/components/Forms/GrayRelease/Version/index.scss
- src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
- src/pages/projects/components/Modals/GrayReleaseDetail/index.scss
- src/stores/grayrelease.js
- src/utils/object.mapper.js
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3128
```
```
```docs
```
> fix: Fix grayrelease strategy workloads info

- src/components/Inputs/SelectInput/index.jsx
- src/components/Inputs/SelectInput/index.scss
> update: Optimize SelectInput

- scripts/webpack.dev.js
> chore: disable react refresh overlay

- src/components/Forms/Workload/ContainerSettings/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1254
```
```
```docs
```
> fix: Fix spec.clusterIP for stateful service

- src/stores/terminal.js
Fixes #https://github.com/kubesphere/console/issues/1300
```
```
```docs
```
> update: Update terminal API

- server/controllers/session.js
- server/views/login.html
Fixes #https://github.com/kubesphere/console/issues/1281
```
```
```docs
```
> refactor: Refact oauth login process to support sso

- server/controllers/view.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1255
```
```
```docs
```
> update: Remove login error tip from server log

- src/components/Inputs/ContainerPort/index.jsx
- src/components/Inputs/ContainerServicePort/index.jsx
- src/components/Inputs/ServicePort/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1243
```
```
```docs
```
> fix: Fill service port name input with defaultValue if undefined

- src/components/Modals/CustomMonitoring/components/PromQLInput/promql.js
- src/pages/projects/components/Modals/ServiceMonitor/Authorization/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix unsafe external link and incomplete sanitization

- package.json
- src/core/index.js
- yarn.lock
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix promise polyfills

- src/components/Forms/StorageClass/StorageClassSettings/index.jsx
- src/locales/en/storage.js
- src/locales/es/storage.js
- src/locales/tc/storage.js
- src/locales/zh/storage.js
- src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
> Chore(locales): minor wording fix in storage UI

- src/stores/devops/pipelines.js
/kind bug
Fixes #
```
```
```docs
```
> chore: Modify the RegExp in pipeline

- server/controllers/session.js
- server/services/session.js
- src/actions/user.js
- src/core/containers/PasswordConfirm/index.jsx
- src/core/containers/PasswordConfirm/index.scss
- src/core/routes.js
- src/locales/en/login.js
- src/locales/es/login.js
- src/locales/tc/login.js
- src/locales/zh/login.js
- src/stores/user.js
/kind feature
Confirm the password when a new user first login. 
Fixes #
```
```
```docs
```
> feat: Add user password confirm step

- src/components/Cards/ContainerLog/index.jsx
- src/components/Modals/ContainerLog/index.jsx
- src/stores/container.js
/kind feature
Fixes #https://github.com/kubesphere/kubesphere/issues/3172#event-4061770475
```
```
```docs
```
> feat: Fetch previous log for terminated container

- server/controllers/session.js
- server/controllers/view.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix password confirm redirect

- server/controllers/session.js
- server/controllers/view.js
- server/services/session.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Check password confirm redirect when use login

- src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
- src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.scss
- src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
- src/components/Forms/Pipelines/RepoSelect/subForm.jsx
- src/components/Modals/Pipelines/AdvanceEdit/index.jsx
- src/locales/en/pipeline.js
- src/locales/es/pipeline.js
- src/locales/tc/pipeline.js
- src/locales/zh/pipeline.js
- src/utils/constants.js
/kind feature
Fixes ##1316
```
```
```docs
```
> feature: Add GitLab in pipeline creating

- src/components/Forms/ImageBuilder/B2IForm/index.jsx
- src/components/Forms/ImageBuilder/S2IForm/index.jsx
- src/locales/en/s2i.js
- src/locales/es/s2i.js
- src/locales/tc/s2i.js
- src/locales/zh/s2i.js
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
/kind feature
Fixes ##1337
```
```
```docs
```
> feat: Add trigger for s2i

- src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
The timer trigger needs a regular expression. It‘s more friendly to disable the time trigger default.
> improvement: defautl disable time trigger

- src/components/Forms/ImageBuilder/B2IForm/index.jsx
- src/components/Forms/ImageBuilder/S2IForm/index.jsx
- src/pages/projects/containers/ImageBuilder/Detail/index.jsx
1. fix regular expression
2. improvement trigger URL when the secret code is empty
/cc @harrisonliu5 
/assgin @leoendless
> improvement: secret url and regular pattern

- src/components/Modals/Monitoring/ApplicationResource/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix project select in cluster monitoring modal

- package.json
- scripts/webpack.base.js
- src/components/Graph/App/index.jsx
- src/components/Graph/Card/index.jsx
- src/components/Graph/Detail/Monitors/index.jsx
- src/locales/en/grayrelease.js
- src/locales/es/grayrelease.js
- src/locales/tc/grayrelease.js
- src/locales/zh/application.js
- src/locales/zh/grayrelease.js
- src/pages/projects/components/Modals/GrayReleaseDetail/Monitor/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/TrafficManangement/index.jsx
- src/pages/projects/containers/GrayRelease/Jobs/Item.jsx
- src/stores/application/crd.js
- src/stores/grayrelease.js
- src/utils/object.mapper.js
- yarn.lock
Fixes #https://github.com/kubesphere/kubesphere/issues/3143
```
```
```docs
```
> update: Update kiali API

- server/controllers/session.js
- server/services/session.js
- src/locales/en/user.js
- src/locales/es/user.js
- src/locales/tc/user.js
- src/locales/zh/user.js
- src/utils/constants.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix pre-register user username

- src/actions/cluster.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix import cluster function error

- src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
- src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.scss
> fix: Fix image registry validate style

- src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
- src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.scss
- src/components/Forms/Pipelines/RepoSelect/subForm.jsx
/kind feature
Fixes ##1361
```
```
```docs
```
> feat: Add the credentials in gltlab form

- src/pages/devops/containers/Pipelines/Detail/CodeQuality/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
- src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
- src/stores/devops/pipelines.js
/kind bug
Fixes ##1367
```
```
```docs
```
> fix: Fix the sonarqube page could not get data

- src/core/global.js
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1370
```
```
```docs
```
> fix: Fix nav items filter error in global.js

- src/components/Cards/Pods/Item.jsx
- src/components/Cards/Pods/index.jsx
/kind bug
Pods may have the same name in one node.
Fixes #
```
```
```docs
```
> fix: Fix pods card item key

- src/components/Forms/Pipelines/ActionsInput/Item.jsx
- src/components/Forms/Pipelines/ActionsInput/index.jsx
- src/components/Forms/Pipelines/AdvanceSettings/index.jsx
- src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
- src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
- src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
- src/components/Forms/Pipelines/RepoSelect/subForm.jsx
- src/stores/devops/scm.js
/kind feature
Fixes ##1310
```
```
```docs
```
> feat: Add discovering tags in multi-branch pipeline

- src/locales/en/base.js
- src/locales/en/pipeline.js
- src/locales/es/base.js
- src/locales/es/pipeline.js
- src/locales/tc/pipeline.js
- src/locales/zh/pipeline.js
- src/pages/devops/components/Cards/CodeQualityIssues/index.jsx
- src/pages/devops/components/Cards/CodeQualityResult/index.jsx
- src/pages/devops/components/Modals/JenkinsEdit/index.jsx
- src/pages/devops/components/PipelineStatus/card.jsx
- src/pages/devops/containers/Pipelines/Detail/CodeQuality/index.jsx
/kind bug
/kind feature
Add confirm in leaving edit Jenkins
Add approve button permission
Modify `secret_text` to `Secret Text`
Fixes ##1336 ##1379 ##1378
```
```
```docs
```
> feat: Add two features in pipeline

- src/components/Forms/Service/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.scss
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
- src/components/Forms/Workload/ContainerSettings/index.jsx
- src/stores/service.js
- src/utils/index.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix image pull secret error when edit container form

- src/pages/clusters/containers/Nodes/Detail/Monitoring/index.jsx
- src/pages/clusters/containers/Nodes/Detail/RunningStatus/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix node monitoring for edge nodes

- .github/workflows/nightly-builds.yml
/kind cleanup
You can give more details about why I create this PR from https://github.com/kubesphere/kubesphere/pull/3228
None.
> Add a GitHub action for building nightly images

- .github/workflows/nightly-builds.yml
/kind cleanup
None
Please add a secret into GitHub settings with `SLACK_WEBHOOK_URL`. Here is [a tutorial](https://www.chenshaowen.com/blog/using-terraform-and-github-actions-to-test-iac.html#34-%E5%A6%82%E4%BD%95%E7%BB%99-github-actions-%E9%85%8D%E7%BD%AE-slack-%E9%80%9A%E7%9F%A5) about how to add a Slack webhook.
None.
This should be part of #1386
> Add a Slack notification

- .github/workflows/nightly-builds.yml
/kind cleanup
As the title said.
None.
None.
None.
> Fix the docker hub login issues due to wrong secret var

- src/pages/clusters/containers/Monitor/Cluster/Monitor/Etcd/index.jsx
/kind bug
Fixes #https://kubesphere.com.cn/forum/d/3300
```
```
```docs
```
> fix: Fix member cluster etcd monitor data

- .github/workflows/nightly-builds.yml
> Fix the wrong secret usage of docker hub

- src/pages/devops/components/Pipeline/Sider/index.jsx
- src/pages/devops/components/Pipeline/Sider/index.scss
- src/pages/devops/components/Pipeline/StepsEditor/index.jsx
- src/pages/devops/components/Pipeline/index.jsx
- src/pages/devops/components/Pipeline/store.js
/kind feature
Fixes ##1371 ##1348
```
```
```docs
```
> feat: Add agent in stage

- src/pages/clusters/containers/Workload/Deployments/index.jsx
- src/pages/clusters/containers/layout.jsx
- src/stores/devops.js
- src/stores/project.js
- src/utils/request.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix project error catch when cluster crack

- src/pages/projects/containers/Applications/CRDApps.jsx
- src/pages/projects/containers/Applications/OPApps.jsx
- src/pages/workspaces/containers/Apps/index.jsx
kind bug
Fixed #1374 
Fixed #1374
> fix bug 1374

- src/components/Forms/Pipelines/ActionsInput/Item.jsx
- src/components/Forms/Pipelines/ActionsInput/index.jsx
- src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
- src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
- src/components/Forms/Pipelines/RepoSelect/subForm.jsx
- src/pages/devops/components/Pipeline/store.js
- src/utils/constants.js
/kind bug
Fixes ##1405
```
```
```docs
```
> fix: Fix the discover_tag to discover_tags

- src/components/Forms/Route/RouteRules/RuleList/Item.jsx
/kind bug
Fixes #https://github.com/kubesphere/console/issues/1404#issuecomment-754442652
```
```
```docs
```
> fix: Fix missing rule clusters info

- .github/workflows/deploy-backend-daily.yaml
- .github/workflows/deploy-backend.yml
- .github/workflows/deploy-backend/install.sh
- .github/workflows/deploy-backend/kubesphere.tf
- .github/workflows/deploy-backend/var.tf
- .github/workflows/deploy-pr-close.yml
- .github/workflows/deploy-pr.yml
/kind feature
Make the process of development more agile
1. Add actions to update development environment
**Deploy-Backend** reset the development environment
**Deploy-Backend-Daily** update deploys，ks-apiserver/ks-controller-manager/ks-console daily.
2. Reply /deploy to deploy a preview for pr
The System will build a kubespheredev/ks-console:actions-pr-14 to run the server. e.g https://github.com/shaowenchen/console/pull/14
3. Reply /clear to clean the deployment for pr
In order to use it normally, It needs to configure some variables.
QING_EIP/QING_EIP_ID : provide an access entry 
QING_PASSWORD: password of the root user …
> feature: add auto deploy

- src/pages/clusters/containers/ConfigMaps/index.jsx
- src/pages/clusters/containers/Secrets/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix secrets link in cluster

- src/pages/projects/components/Cards/ServiceMonitors/Item.jsx
- src/pages/projects/components/Cards/ServiceMonitors/index.scss
/kind bug
Fixes https://github.com/kubesphere/console/issues/1394
```
```
```docs
```
> fix: Remove view monitor in application detail

- src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
/kind bug
Fixes https://github.com/kubesphere/console/issues/1393
```
```
```docs
```
> fix: Fix add component error in application detail

- server/config.yaml
- src/components/Forms/Service/AdvanceSettings/index.jsx
- src/components/Forms/Workload/AdvanceSettings/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix ippool cluster module

- src/actions/application.js
- src/pages/clusters/containers/Workload/DaemonSets/index.jsx
- src/pages/projects/components/Cards/Services/Item.jsx
- src/pages/projects/components/Cards/Workloads/Item.jsx
- src/pages/projects/components/Cards/Workloads/index.jsx
- src/pages/projects/components/Modals/ServiceMonitor/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
- src/stores/application/crd.js
> fix: Fix app worklaod info

- .github/workflows/deploy-backend/kubesphere.tf
The default disk size for the node is only 20GB. It's not enough.
> improvement: set os disk size

- src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
- src/stores/devops/scm.js
/kind feature
Fixes ##1387 
```
```
```docs
```
> feat: Add GitLab server and repo list API

- src/components/Terminal/terminal.jsx
- src/utils/socket.client.js
> optimization: Reconnect websocket when the terminal disconnects unexpectedly

- src/components/Forms/Pipelines/AdvanceSettings/index.jsx
- src/components/Forms/Pipelines/AdvanceSettings/index.scss
- src/components/Modals/Pipelines/ScanRepositoryLogs/index.jsx
- src/pages/devops/components/PipelineStatus/card.jsx
- src/pages/devops/components/PipelineStatus/card.scss
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
- src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
- src/stores/devops/scm.js
/kind bug
Fixes ##1397 ##1250 ##1432 ##1431
```
```
```docs
```
> fix: Auto-refresh Pipeline running page

- locales/en/pipeline.js
- locales/es/pipeline.js
- locales/tc/pipeline.js
- locales/zh/pipeline.js
- src/components/Forms/Pipelines/BaseInfo/index.jsx
- src/components/Modals/Pipelines/PipelineEdit/index.jsx
- src/components/Modals/Pipelines/PipelineEdit/index.scss
- src/pages/devops/components/Pipeline/Card/index.jsx
- src/pages/devops/components/Pipeline/Card/index.scss
- src/pages/devops/components/Pipeline/Edges/index.jsx
- src/pages/devops/components/Pipeline/PipelineTemplate/index.jsx
- src/pages/devops/components/Pipeline/Sider/index.jsx
- src/pages/devops/components/Pipeline/StepsEditor/StepCard.jsx
- src/pages/devops/components/Pipeline/StepsEditor/StepContainer.jsx
- src/pages/devops/components/Pipeline/StepsEditor/index.jsx
- src/pages/devops/components/Pipeline/nodesRender.jsx
- src/pages/devops/components/PipelineStatus/card.scss
- src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
> chore: Modify the pipeline display and repeated rendering of components

- src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
- src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/logItem.jsx
- src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
/kind feature
Fixes #1326 #1406 
```
```
```docs
```
/area devops
> feat: The pipeline Log show more Message about error or queued

- locales/en/base.js
- locales/es/base.js
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
- src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
/kind bug
Fixes #
```
```
```docs
```
/area devops
> fix: Auto-refresh running page of pipeline branch

- src/pages/projects/containers/Services/Topology/Detail/Childrens/index.jsx
- src/pages/projects/containers/Services/Topology/Detail/Table/index.scss
- src/pages/projects/containers/Services/Topology/Detail/index.jsx
- src/pages/projects/containers/Services/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix topology error link

- src/pages/projects/components/Cards/HPA/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix hpa memory metric value

- locales/tc/application.js
- locales/tc/cluster.js
> Update Traditional Chinese translations

- src/components/Forms/Pipelines/ParamsFormModal/index.jsx
/kind bug
- fix https://github.com/kubesphere/console/issues/1428 
- add `main` to default branch
> fix: fixup dirbranch error and improve display name

- locales/en/pipeline.js
- locales/es/pipeline.js
- locales/tc/pipeline.js
- locales/zh/pipeline.js
- src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
- src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
/kind feature
Fixes #
```
```
```docs
```
> chore: Add Multi-Branch does not support batch operation

- package.json
- src/components/Graph/Card/index.jsx
- src/components/Graph/Card/index.scss
- src/components/Graph/Detail/Monitors/ServiceMonitor.jsx
- src/components/Graph/Detail/Monitors/WorkloadMonitor.jsx
- src/components/Graph/Detail/Monitors/WorkloadSelect/index.jsx
- src/components/Graph/Detail/Monitors/WorkloadSelect/index.scss
- src/components/Graph/Detail/Monitors/index.jsx
- src/components/Graph/Detail/Monitors/index.scss
- src/components/Graph/Detail/Pods/index.jsx
- src/components/Graph/Detail/index.jsx
- src/components/Graph/Detail/index.scss
- src/components/Graph/index.jsx
- src/pages/projects/components/Modals/CreateApp/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.jsx
- src/pages/projects/containers/GrayRelease/Categories/index.jsx
- yarn.lock
Show both service metrics and workload metrics
Fixes #
```
```
```docs
```
> update: Update application service mesh monitor

- locales/en/group.js
- locales/es/group.js
- locales/tc/group.js
- locales/zh/group.js
- src/components/Modals/GroupDelete/index.jsx
- src/components/Modals/GroupDelete/index.scss
- src/components/Tree/style.scss
- src/pages/workspaces/components/Modals/EditGroup/Detail/Form/DevopsSelect.jsx
- src/pages/workspaces/components/Modals/EditGroup/Detail/index.jsx
- src/pages/workspaces/components/Modals/EditGroup/Detail/index.scss
- src/pages/workspaces/components/Modals/EditGroup/index.jsx
- src/pages/workspaces/containers/Groups/GroupUser/User.jsx
- src/pages/workspaces/containers/Groups/GroupUser/index.scss
- src/utils/group.js
> /kind bug
Fixes [#3306](https://github.com/kubesphere/kubesphere/issues/3306) [#3303](https://github.com/kubesphere/kubesphere/issues/3303) [#3302](https://github.com/kubesphere/kubesphere/issues/3302) [#3301](https://github.com/kubesphere/kubesphere/issues/3301) [#3300](https://github.com/kubesphere/kubesphere/issues/3300) [#3298](https://github.com/kubesphere/kubesphere/issues/3298)
```
```
```docs
```
> fix workspace groups module

- src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
- src/stores/devops/scm.js
Fixes #
```
```
```docs
```
/area devops
> chore: Change the URL of the GitLab projectList API with params

- src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
- src/components/Forms/Workload/VolumeSettings/index.jsx
> /kind bug
Fixes #1464
```
```
```docs
```
> fix: fix namespace spell err and can't get SC data in AddVolumeTemplate

- src/pages/workspaces/components/Modals/EditGroup/Detail/Card/index.scss
- src/pages/workspaces/components/Modals/EditGroup/Detail/index.scss
- src/pages/workspaces/containers/Groups/GroupTree/index.jsx
- src/pages/workspaces/containers/Groups/GroupUser/index.scss
- src/pages/workspaces/containers/Groups/index.jsx
> /kind bug
Fixes #[3302](https://github.com/kubesphere/kubesphere/issues/3302)
```
```
```docs
```
> fix: Fix too long text and the style is not friendly

- src/components/Tree/style.scss
- src/pages/workspaces/containers/Groups/GroupTree/index.jsx
- src/pages/workspaces/containers/Groups/GroupTree/index.scss
> fix: Fix tree overflow

- locales/en/pipeline.js
- locales/es/pipeline.js
- locales/tc/pipeline.js
- locales/zh/pipeline.js
- package.json
- src/components/Forms/Pipelines/RepoSelect/subForm.jsx
- src/pages/devops/components/Pipeline/StepModals/branch.jsx
- src/pages/devops/containers/Pipelines/Detail/routes.js
- src/stores/devops/scm.js
- yarn.lock
/kind bug
Fixes #1458 #1471
```
```
```docs
```
/area devops
> fix: Fix the create credential modal in repo form have not to submit

- src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
/kind bug
Fixes #https://kubesphere.com.cn/forum/d/3703-bug/2
```
```
```docs
```
> fix: Fix application ingress edit error

- src/components/Base/CodeEditor/AceEditor.jsx
- src/components/Base/CodeEditor/custom.css
- src/components/Base/CodeEditor/index.jsx
> chore: Support search and vscode keymap in CodeEditor

- src/pages/workspaces/components/Modals/EditGroup/Department/index.jsx
- src/pages/workspaces/components/Modals/EditGroup/Department/index.scss
- src/pages/workspaces/containers/Groups/GroupTree/index.jsx
- src/pages/workspaces/containers/Groups/GroupTree/index.scss
- src/pages/workspaces/containers/Groups/index.jsx
> Fix: fix group multiple refresh and modal tree overflow

- locales/en/workload.js
- locales/es/workload.js
- locales/tc/workload.js
- locales/zh/workload.js
- src/components/Forms/Pipelines/RepoSelect/subForm.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
- src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss
- src/stores/container.js
Fixes #1455
```
```
```docs
```
/area devops
> feat: Add Ignore Cert in the Image

- src/pages/console/containers/Dashboard/Admin/History/Card.jsx
Remove cluster info in project card.
Fixes #
```
```
```docs
```
> fix: Fix history card style in single cluster mode

- src/components/Modals/ObjectEdit/index.jsx
Fixes #1483 
```
```
```docs
```
> chore: Update object edit modal locales

- src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/Secret.jsx
> /kind bug
fix: kubeconfig editor error in service account detail page
> fix:code editor error

- server/controllers/session.js
- server/routes.js
- server/services/session.js
/kind feature
backend pr: https://github.com/kubesphere/kubesphere/pull/3352
Fixes #
```
```
```docs
```
> update: Update oauth callback to support cas

- locales/tc/base.js
- locales/zh/base.js
- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
- src/stores/devops/run.js
/kind bug
Fixes #1029 
```
```
```docs
```
/area devops
> fix: Fix the message of commit in pipeline Pull-Request detail

- locales/en/base.js
- locales/es/base.js
- locales/tc/base.js
- locales/zh/base.js
- src/components/Modals/ProjectCreate/index.jsx
Signed-off-by: fukiki <one.fhh@163.com>
Fixes #1491
> Feat: Namespace started with kube- is not allowed

- src/pages/clusters/components/Modals/ClusterVisibility/WorkspaceItem/index.jsx
- src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3402
```
```
```docs
```
> fix: Remove system-workspace from cluster visibility list

- src/components/Tree/style.scss
> fix: tree node style

- locales/en/devops.js
- locales/es/devops.js
- locales/tc/devops.js
- locales/zh/devops.js
/area devops
KubeSphere already covered the Gitlab support. It's necessary to add it in the description
None.
None.
None.
> Add Gitlab as the scm support type

- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
- src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
- src/stores/devops/pipelines.js
/kind bug
Fixes #1494
```
```
```docs
```
/area devops
> fix: Fix the error tip when the empty active page in the brach page 

- locales/en/service.js
- locales/es/service.js
- locales/tc/service.js
- locales/zh/service.js
- scripts/locale-plugin.js
- src/pages/projects/containers/Services/Topology/Detail/Table/index.jsx
- src/pages/projects/containers/Services/Topology/Service/index.jsx
- src/pages/projects/containers/Services/Topology/Service/index.scss
- src/pages/projects/containers/Services/Topology/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3401 #https://github.com/kubesphere/kubesphere/issues/3399
```
```
```docs
```
> fix: Fix service topology detail error

- src/components/HOCs/withList.js
- src/pages/projects/containers/Applications/OPApps.jsx
- src/stores/openpitrix/application.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Support op applications watch

- locales/tc/app.js
> Update Traditional Chinese translations in app.js

- locales/en/alerting.js
- locales/es/alerting.js
- locales/zh/alerting.js
- src/actions/alerting.js
- src/components/Cards/Monitoring/Controller/TimeSelector/index.jsx
- src/components/Cards/Monitoring/Controller/TimeSelector/utils.js
- src/components/Charts/Area/MultiArea/index.jsx
- src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/NodeSelect.jsx
- src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/WorkloadSelect.jsx
- src/components/Forms/AlertingPolicy/AlertingRule/QueryMonitor/index.jsx
- src/components/Forms/AlertingPolicy/AlertingRule/RuleInput/index.jsx
- src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
- src/components/Modals/CustomMonitoring/components/PromQLInput/index.jsx
- src/configs/alerting/metrics/rule.config.js
/kind bug
Fixes #1512 #1510 #1509 #1508 #1507 #1505
```
```
```docs
```
> fix: Fix custom alerting issues

- locales/en/workload.js
- locales/es/workload.js
- locales/tc/workload.js
- locales/zh/workload.js
- src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix workspace quota locales

- src/actions/workspace.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix edit workspace quota

- locales/tc/ippool.js
> Update Traditional Chinese translations in ippool.js

- locales/en/alerting.js
- locales/es/alerting.js
- locales/tc/alerting.js
- locales/zh/alerting.js
- src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
- src/pages/projects/containers/Alerting/Policies/index.jsx
/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/3421
```
```
```docs
```
> fix: Fix alert active time locale

- .github/workflows/deploy-pr.yml
/kind bug
ubuntu-test can't find sshpass  in github actions.
> fix:sshpass for  actions

- .github/workflows/deploy-pr.yml
> improvement: add images name to the comment

- locales/tc/serviceaccounts.js
> Update Traditional Chinese translations in serviceaccounts.js

- locales/tc/workspace.js
> Update Traditional Chinese translations in workspace.js

- locales/tc/workload.js
>
> /kind bug
> /kind design
Fixes #
```
```
```docs
```
> update: Update tc locales, the workload.js part has been translated.

- src/configs/alerting/metrics/rule.config.js
- src/utils/monitoring.js
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix alerting rule unit and monitor data process

- locales/en/service.monitor.js
- locales/es/service.monitor.js
- locales/tc/service.monitor.js
- locales/zh/service.monitor.js
- src/actions/service.js
- src/components/Inputs/SecretSelect/index.jsx
- src/pages/projects/components/Cards/ServiceMonitors/Item.jsx
- src/pages/projects/components/Cards/ServiceMonitors/index.jsx
- src/pages/projects/components/Cards/ServiceMonitors/index.scss
- src/pages/projects/components/Cards/Workloads/Item.jsx
- src/pages/projects/components/Modals/ServiceMonitor/Authorization/index.jsx
- src/pages/projects/components/Modals/ServiceMonitor/Endpoint/index.jsx
- src/pages/projects/components/Modals/ServiceMonitor/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/Components/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
- src/pages/projects/containers/Applications/OPAppDetail/ResourceStatus/index.jsx
- src/pages/projects/containers/Applications/OPAppDetail/index.jsx
- src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
- src/pages/projects/containers/Services/Detail/index.jsx
- src/utils/object.mapper.js
> refactor: Move service monitor to service detail page

- locales/en/pipeline.js
- locales/es/pipeline.js
- locales/tc/pipeline.js
- locales/zh/pipeline.js
- src/pages/devops/containers/Credential/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
- src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
- src/pages/workspaces/containers/DevOps/index.jsx
- src/stores/devops/pipelines.js
/kind feature
Fixes #1519
```
```
```docs
```
/area devops
> feat: Add sync status in pipeline and credential

- locales/tc/workspace.js
* Adjust the layout and the description of the docs\development-workflow.md to make it easier for readers to start.
* Adjust the layout and the description of the docs\development-workflow.md to make it easier for readers to start.
Fixes #
```
```
```docs
```
> Update Traditional Chinese translations in workspace.js 

- src/components/Modals/ProjectSelect/index.jsx
- src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix app tracing error

- src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
- src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
- src/utils/constants.js
/kind bug
Fixes #1495 #1515
```
```
```docs
```
/area devops
> chore: remove branch select and re-order the SCM source

- locales/en/application.js
- locales/en/devops.js
- locales/en/service.js
- locales/en/workload.js
> UI modification trial

- locales/en/index.js
- locales/es/index.js
- locales/tc/index.js
- locales/zh/index.js
- package.json
- scripts/webpack.base.js
- scripts/webpack.dev.js
- scripts/webpack.e2e.js
- scripts/webpack.locale.js
- scripts/webpack.prod.js
- server/components/boot.js
- server/controllers/view.js
- server/libs/utils.js
- server/views/index.html
- src/core/i18n.js
- src/pages/clusters/containers/Workload/StatefulSets/index.jsx
- yarn.lock
> chore: Refactor webpack dev server and locales build script

- scripts/locale-plugin.js
/kind bug
Fixes #
```
```
```docs
```
> chore: Fix locale plugin write to disk

- locales/en/alerting.js
- locales/en/role.js
- locales/es/alerting.js
- locales/es/role.js
- locales/tc/role.js
- locales/zh/alerting.js
- locales/zh/role.js
- scripts/locale-plugin.js
- src/components/Modals/EditAuthorization/CheckItem.jsx
- src/core/containers/PasswordConfirm/index.jsx
- src/pages/clusters/containers/ServiceAccounts/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Add uncheck tip for role authorize edit

- locales/en/serviceaccounts.js
- locales/es/serviceaccounts.js
- locales/tc/serviceaccounts.js
- locales/zh/serviceaccounts.js
- src/actions/serviceaccount.js
- src/pages/clusters/containers/ServiceAccounts/index.jsx
- src/pages/projects/containers/ServiceAccounts/Detail/index.jsx
- src/pages/projects/containers/ServiceAccounts/index.jsx
> /kind bug
Fixes #1545 #1547 #1548 #1551 
```
```
```docs
```
> fix: fix serviceaccount issues

- package.json
/kind bug
Fixes #
```
```
```docs
```
> chore: Fix lint-staged rules

- server/config.yaml
- src/components/Modals/EditAuthorization/constants.js
- src/core/global.js
- src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
- src/pages/projects/containers/Applications/Banner.jsx
- src/pages/projects/containers/Applications/OPApps.jsx
- src/pages/projects/containers/Overview/index.jsx
- src/pages/projects/routes/index.js
/kind bug
Fixes #
```
```
```docs
```
> update: Update op module key

- src/pages/fedprojects/components/ClusterSelect/index.scss
- src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
- src/pages/fedprojects/containers/Applications/Detail/Tracing/index.scss
- src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
/kind bug
Fixes #
```
```
```docs
```
> fix: Fix multicluster application tracing page error
