kubesphere/console

server/config.yaml
server/proxy.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/index.jsx
src/locales/zh/devops.js

> /kind bug
we used `followRedirects` options in http-proxy at initial, but it cant set headers(backend need to remove auth header after redirect) after getting redirect url, so this pr write a special proxy to  set headers between redirecting
Fixes 
https://github.com/kubesphere/kubesphere/issues/1546

fix download b2i file error

---

src/components/Modals/ContianerTerminal/index.jsx
src/components/Modals/KubeCtl/index.jsx
src/components/Terminal/terminal.jsx
src/stores/terminal.js

/kind bug
fix bug get buffer y prop when xterm.buffer is undefined
instead of getter by a method to get websocket link
Fixes #32

fix(container-terminal): component crash when ws error before term init

---

src/components/Forms/ImageBuilder/B2IForm/index.jsx
src/components/Forms/ImageBuilder/S2IForm/index.jsx
src/stores/service.js

> /kind bug
when creating s2i service use private image repo, deployment image name not container private image   repo url, and cant get this image source.

fix: create b2i service when push image to private image repo bug

---

src/stores/notification/mailService.js

/kind bug
use base64 format for alert mail config apis

refactor: use base64 format in mail config api

---

src/components/Modals/LogSearch/Logging/Detail/index.jsx
src/components/Modals/LogSearch/Logging/Detail/index.scss
src/stores/logging/query.js

> /kind bug
miss sort filter when fetching logs 
Fixes #48

fix: miss sort filter in log query api

---

src/pages/devops/components/Pipeline/StepsEditor/index.jsx

> /kind bug
https://github.com/kubesphere/console/issues/62
sort error when  drag  `not nested`  steps

fix: sort pipeline steps error

---

src/components/Base/Card/index.jsx
src/components/Base/CodeEditor/index.jsx
src/components/Forms/Base/Confirm/index.jsx
src/components/Forms/Base/Confirm/index.scss
src/components/Graph/index.jsx
src/components/Modals/Edit/Form/index.jsx
src/components/Modals/Edit/Form/index.scss
src/components/Modals/Edit/Form/wrapper.jsx
src/core/containers/Base/Detail/index.jsx
src/core/index.js
src/core/layouts/Detail/index.jsx
src/locales/zh/base.js
src/pages/apps/components/Lists/AuditRecord/index.jsx
src/pages/clusters/containers/Workspaces/index.jsx
src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
src/pages/devops/containers/layout.jsx
src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
src/pages/projects/containers/Applications/Detail/TrafficManangement/index.jsx
src/pages/projects/containers/Deployments/Detail/RevisionControl/index.jsx
src/pages/projects/containers/GrayRelease/Jobs/index.jsx
src/pages/projects/containers/ImageBuilder/Detail/index.jsx
src/pages/projects/containers/layout.jsx
src/pages/workspaces/containers/layout.jsx

/kind bug
1. replace footer actions with confirm for sub forms in edit-template 
>编辑模板中，进入子表单时，Footer 上的保存按钮难以发现，并带有歧义，调整子表单的保存方式为确认框
2. add loading status to detail layout to prevent permission judgment errors
>详情页模板添加加载中状态，避免 UI 在基础数据获取完成前渲染，导致详情页操作可能展示不出来
3. resize the loading icon
>优化加载中图标显示，更改图标大小为默认 medium
Fixes #
```
```
```docs
```

fix: Replace footer actions with confirm for sub forms in edit-template

---

src/components/Modals/Node/TaintManagement/Batch.jsx

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/console/issues/21
```
```
```docs
```

fix: Hide common taints if only one node selected

---

src/pages/projects/components/WorkloadStatus/index.jsx
src/stores/container.js
src/utils/status.js

after created s2i deployment, deploy lists only show `build image successful`, no more detail about pods status.
if build s2i success, show pods status

fix: show pods status after build s2i

---

src/pages/projects/containers/Applications/index.jsx

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubesphere/kubesphere/issues/1898
```
```
```docs
```

fix: jump to template list after template app create

---

src/stores/openpitrix/base.js

> /kind bug
[issue 1900 question 1: the default version of Grafana is the oldest one. Should be the latest one.](https://github.com/kubesphere/kubesphere/issues/1900)

fix: Fix openpitrix resources list orders

---

src/locales/zh/workspace.js

fix：a small issue, delete a constant which is duplicate defined and unused 'Enter Workspace', there is a same constant 'View Workspace'.
一个小的规范性问题：常量”Enter Workspace“没有用过，console中用到的是”View Workspace“。

fix：delete a constant which is duplicate defined and unused 'Enter Workspace', there is a same constant 'View Workspace'

---

server/config.yaml
src/actions/project.js
src/components/Modals/ProjectCreate/index.jsx
src/locales/en/workspace.js
src/locales/zh/workspace.js
src/pages/clusters/containers/layout.jsx
src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
src/pages/workspaces/components/ResourceTable/index.jsx
src/pages/workspaces/containers/BaseInfo/index.jsx
src/pages/workspaces/containers/BaseInfo/index.scss
src/pages/workspaces/containers/Clusters/index.jsx
src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
src/pages/workspaces/containers/Overview/UsageRanking/index.jsx

/kind bug
1. Add an empty tip when the workspace has no authorized cluster.
2. crd list now can only be viewed by platform-admin.
3. fix missing param `cluster` of project creation in cluster management.
4. fix data fetching in cluster layout wrapper when the cluster isn't ready.

fix: Add empty tip if workspace has no cluster

---

src/pages/clusters/containers/Overview/Dashboard/ServiceComponents/index.jsx

/kind bug
Service components now only show installed.
Fixes https://github.com/kubesphere/console/issues/363
```
```
```docs
```

fix: Fix service components in cluster overview page

---

src/stores/monitoring/custom/monitor.js

fixing a bug when __name__ is null
Fixes #
```
```
```docs
```

fix(custom-monitor): can not generete metirc id when __name__ is null

---

src/components/Modals/DevOpsCreate/index.jsx
src/components/Modals/DevOpsCreate/index.scss
src/locales/en/devops.js
src/locales/zh/devops.js
src/pages/workspaces/containers/DevOps/index.jsx

/kind bug
In the DevOps project, it is not judged whether there is DevOps in the current cluster

fix: Not allowed to select a cluster without Devops

---

server/config.yaml
src/components/Tables/Base/index.jsx
src/core/global.js
src/pages/workspaces/components/ResourceTable/index.jsx
src/pages/workspaces/containers/DevOps/index.jsx
src/stores/devops.js

/kind bug
Hide devops nav when devops module not installed in single cluster mode.
Fix https://github.com/kubesphere/kubesphere/issues/2210

fix: Fix devops page when devops not installed

---

src/stores/node.js

/kind bug
Fix cluster nodes filtered by role. Using `labelSelector=node-role.kubernetes.io/${role}` to instead the old way.
Fixes #
```
```
```docs
```

fix: Fix cluster nodes filter by role

---

src/components/Inputs/AnnotationsInput/index.jsx
src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/875
```
```
```docs
```

fix: Fix metrics auto complete error

---

src/locales/en/logging.js
src/locales/es/logging.js
src/locales/tc/application.js
src/locales/tc/logging.js
src/locales/zh/application.js
src/locales/zh/logging.js
src/pages/clusters/containers/LogCollections/Detail/index.jsx
src/pages/clusters/containers/LogCollections/index.jsx

Update the translation of “接收者” to "receiver" instead of "collector".
No change is needed for Traditional Chinese. I will notify our Spanish partner of this change after the pr is merged.

Update log receiver

---

server/config.yaml
server/store/index.js

/kind bug
The TTL of the session is too long.  Creating sessions frequently will consume a lot of memory.
Fixes #
```
```
```docs
```

fix: Fix redis session expire time too long

---

src/locales/en/monitoring.js
src/locales/en/storage.js
src/locales/es/monitoring.js
src/locales/es/storage.js
src/locales/tc/monitoring.js
src/locales/zh/monitoring.js
src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
src/utils/constants.js
src/utils/index.js

Signed-off-by: Ray Zhou <ray@yunify.com>
/kind cleanup

change K8S/k8s to K8s which is the official spelling from Kubernetes

---

src/components/Base/Panel/index.jsx
src/components/Base/Panel/index.scss
src/pages/projects/components/Modals/ServiceMonitor/index.jsx

/kind bug
Add preset label {'app.kubernetes.io/vendor': 'kubesphere'} to service monitor yaml.
Fixes #
```
```
```docs
```

fix: Add app.kubernetes.io/vendor label for service monitor

---

src/pages/projects/components/Cards/Ingresses/Item.jsx
src/pages/projects/components/Cards/Services/Item.jsx
src/pages/projects/components/Cards/Workloads/Item.jsx

>
In some application scenarios, users will pay attention to the alias , not only the name.
Fixes #1351

fix: Display the name and alias in Applications details page

---

src/stores/devops/pipelines.js

/kind bug
/area devops
Fixes kubesphere/kubesphere#3102
The wrong request is:
`http://localhost:8000/kapis/devops.kubesphere.io/v1alpha2/search?start=0&limit=10&q=type%3Apipeline%3Borganization%3Ajenkins%3Bpipeline%3Aasdfjgq2f%2F%2A%3BexcludedFromFlattening%3Ajenkins.branch.MultiBranchProject%2Chudson.matrix.MatrixProject%26filter%3Dno-folders`
The correct request is:
`http://localhost:8000/kapis/devops.kubesphere.io/v1alpha2/search?start=0&limit=10&q=type%3Apipeline%3Borganization%3Ajenkins%3Bpipeline%3Aasdfjgq2f%2F%2A%3BexcludedFromFlattening%3Ajenkins.branch.MultiBranchProject%2Chudson.matrix.MatrixProject&filter=no-folder`

Fix the wrong query of pipeline list

---

src/components/Forms/Pipelines/AdvanceSettings/index.jsx

/kind bug
/area devops
None.
The error log output from Jenkins:
```
2020-12-28 06:16:36.495+0000 [id=14]    WARNING h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID bd273797-7a0f-44a4-a88f-25113a0f4809
java.lang.IllegalArgumentException: Invalid filter type specified.
at io.jenkins.blueocean.service.embedded.rest.ContainerFilter.getFilters(ContainerFilter.java:95)
at io.jenkins.blueocean.service.embedded.rest.ContainerFilter.filter(ContainerFilter.java:46)
at io.jenkins.blueocean.service.embedded.rest.ContainerFilter.filter(ContainerFilter.java:39)
at io.jenkins.blueocean.service.embedded.rest.PipelineSearch.search( …
```

Fix the wrong job filter with job search API

---

src/components/Graph/index.scss
src/components/Graph/utils.js

/kind bug
Remove workaround SVG CSS styles.
Calculate edge position data with source node position and target node position.
Fixes #
```
```
```docs
```

refactor: Refactor traffic graph display algorithm

---

src/pages/apps/components/Modals/AppCreate/index.jsx
src/pages/apps/components/Modals/HelmUpload/index.jsx

The Chinese guillemets should be used only for Chinese. Not applicable to English.

Delete Chinese guillemets

---

locales/tc/alerting.js
locales/tc/app.js
locales/tc/application.js
locales/tc/base.js

* The commit fixed some words ,sentences and typo for Traditional Chinese translations
>
* The commit fixed some words ,sentences and typo for Traditional Chinese translations
Fixes #
```
```
```docs
```

Fix typo in Traditional Chinese translations

---

src/stores/devops/scm.js

/kind bug
basic-auth secret corresponding to usernamePassword credential in Jenkins, so the fields should be username and password
None.
None.
None.

Fix the field of basic-auth secret

---

Dockerfile.multistage
Makefile
README.md

/kind cleanup
For some users who might don't have the NodeJs environment, it's not easy to build KubeSphere Console. So I provide a multi-stage Dockerfile, people just need to have a Docker environment.
None.
None.
I already added the related document in the README file.

Add a multi-stage dockerfile to build console

---

src/components/Modals/CredentialCreate/index.jsx

/kind bug
Fixes ##1907
```
```
```docs
```

fix: Content is reset while editing credential with kubeconfig

---

src/components/Forms/Pipelines/AdvanceSettings/index.jsx

>
/kind bug
Fixes #[#kubesphere/kubesphere/3857](https://github.com/kubesphere/kubesphere/issues/3857)
```
```
```docs
```

fix: Fix the webhook url in the single cluster

---

server/config.yaml

/kind bug
The reason why a web terminal can't be displayed on the system-workspace is because the projects are only allowed to edit and view , so I did this change
Fixes ##1915
```
```
```docs
```

fix: Modify system workspace rules control to show a web terminal on container of system-workspace

---

locales/en/alerting.js
locales/es/alerting.js
locales/tc/alerting.js
locales/zh/alerting.js
src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
src/configs/alerting/metrics/rule.config.js

/kind bug
1.Set the alarm duration to a pure number.
2.Set the min value for ```cpu average load(1m 5m 15m)/iops``` .
Fixes #[#kubesphere/kubesphere/3755](https://github.com/kubesphere/kubesphere/issues/3755)
```
```
https://user-images.githubusercontent.com/63338728/121646764-38ca8b00-cac8-11eb-8087-92dd284d8069.mov
```docs
```

fix: Modify the validation rules for the input box on the alerting policy page

---

.github/workflows/main.yaml

Signed-off-by: Roland.Ma <rolandma@yunify.com>
Use the `--pull` option in the `docker build` command to prevent the docker image cache. So we can update the Alpine base image with the latest fixes.

Force pull base image

---

.dockerignore

Signed-off-by: Roland.Ma <rolandma@yunify.com>
/kind cleanup
Remove yarn.lock file from the docker image.
There are some false positive CVE issues were reported by the scaner, which try to detect issues with the yarn.lock file. But some of those packages were not compiled into the release.
Fixes #

yarn.lock file isn't required by runtime

---

src/pages/projects/components/Modals/WorkloadDelete/index.jsx

/kind feature
Fixes ##1735
```
```
https://user-images.githubusercontent.com/63338728/120985710-74a2df00-c7ae-11eb-8688-7e3934e5bbd4.mov
```docs
```

fix: Add 'select all' option when deleting related resource of a specified workload

---

src/components/Forms/Dashboard/BaseInfo/index.jsx

/kind bug
Referring to the Create Storage Class Modal, I set the first app template to be selected by default
Fixes #[#kubesphere/kubesphere/3734](https://github.com/kubesphere/kubesphere/issues/3734)
```
```
```docs
```

fix: Set the first app template to default.

---

.github/workflows/deploy-pr.yml

/kind cleanup
PR deploy is failing, because kubectl --export is deprecated on version 1.19.8, update workflow yaml with `kubectl neat`
Fixes #
```
```
```docs
```

--export is deprecated on kubectl:v1.19.8, use kubectl neat instead

---

src/actions/service.js
src/pages/projects/components/Cards/ServiceMonitors/index.jsx
src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
src/pages/projects/containers/Services/Detail/index.jsx

/kind bug
Fixes #[#kubesphere/kubesphere/3992](https://github.com/kubesphere/kubesphere/issues/3992) #[#kubesphere/kubesphere/3993](https://github.com/kubesphere/kubesphere/issues/3993)
```
```
```docs
```
/assign @junotx

fix: Service monitor is not associated when service is viewed and deleted

---

.github/workflows/main.yaml

Signed-off-by: Zhengyi Lai <zheng1@kubesphere.io>
The image tag previously built from the tag is `3.1.1-rc.0`, the correction should be `v3.1.1-rc.0`

Fix the incorrect tag of CI auto-push image

---

locales/en/pipeline.js
locales/es/pipeline.js
locales/tc/pipeline.js
locales/zh/pipeline.js
src/components/Forms/Pipelines/AdvanceSettings/index.jsx
src/components/Modals/Pipelines/ScanRepositoryLogs/index.jsx
src/pages/devops/components/Pipeline/StepModals/environment.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
src/utils/constants.js

Reverts kubesphere/console#2077

Revert "[release-3.1] feat: Add scan repo trigger in GitLab"

---

src/components/Cards/ContainerLog/index.scss

/kind bug
Display log contents correctly.
Fixes #
```
```
```docs
```
| before | After |
| ------ | ----- |
|    <img width="2007" alt="Snipaste_2021-07-12_23-41-44" src="https://user-images.githubusercontent.com/21301288/125317394-8e19e680-e36b-11eb-8f60-37e74bca0cea.png"> |  <img width="2009" alt="Snipaste_2021-07-12_23-41-26" src="https://user-images.githubusercontent.com/21301288/125317444-970ab800-e36b-11eb-825a-cec6fe7dd286.png"> |
|   <img width="2007" alt="Snipaste_2021-07-12_23-46-58" src="https://user-images.githubusercontent.com/21301288/125317483-9e31c600-e36b-11eb-97e7-b36e0951fa24.png"> |  <img …

fix: Container logs do not display full Spaces.

---

src/components/Inputs/ResourceLimit/index.jsx

/kind bug
Fixes ##1224
```
```
```docs
```

fix: Modify the width of marks and let words not be squeezed

---

src/components/Modals/About/index.jsx

/kind bug
To fix 'About' window can't be closed automatically when moving mouse and clicking out of 'About' window
Fixes ##2110
```release-note
let 'About' window can be closed automatically
```
```
```
https://user-images.githubusercontent.com/63338728/126419630-ae5edbb4-424c-4f1a-93b9-689f26653144.mov
```docs
```

fix: Fix 'About' window can't be closed automatically

---

src/pages/projects/components/Selector/index.scss

/kind bug
Fixes ##2080
```
```
```release-note
show cursor on project's Selector
```
```docs
```

fix: Fix the cursor of project's Selector

---

src/pages/projects/components/Modals/CreateAppService/index.jsx

/kind bug
Fixes ##2136 
```
```
```release-note
```
```docs
```

fix: Fix pop up window cannot be closed

---

src/pages/devops/components/Pipeline/StepModals/script.jsx
src/pages/devops/components/Pipeline/StepModals/shell.jsx

/kind bug
When the pipeline is edited again and no input is made, the initial value cannot be saved
Fixes ##https://github.com/kubesphere/kubesphere/issues/3950
```
```
```release-note
```
```docs
```

fix:  Pipeline editor cant save init value

---

package.json
scripts/checkRepeat.js
scripts/locale-plugin.js

/kind feature
To  detect UI text entries in different locale files after `yarn start` and `git commit`
Fixes #[#kubesphere/issues/4125](https://github.com/kubesphere/kubesphere/issues/4125)
```
```
`yarn start`
https://user-images.githubusercontent.com/63338728/129128297-a3f17c6b-b62d-433e-afbd-3ee0d7c733b4.mov
`git commit`
https://user-images.githubusercontent.com/63338728/129128328-a083b66b-9301-48b7-9f01-8afdd110b454.mov
```release-note
Add feature about detecting UI text entries for duplication
```
```docs
```

fix: Detect UI text entries in different locale files.

---

Makefile

/kind cleanup
Cannot get a correct image tag when the git tag name like `fix/xxx`. See also the following test result:
Before:
```
gitpod /workspace/console $ make image image-push
rm -rf build && mkdir -p build
tar --exclude=".git" --exclude='node_modules' --exclude='build' --warning=no-file-changed -czf build/console.tar.gz .
docker build build -t surenpi:bugfix/editor-cant-save-init-value-dev -f Dockerfile.multistage
invalid argument "surenpi:bugfix/editor-cant-save-init-value-dev" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [Makefile:22: image] Error 125
```
After:
```
gitpod /workspace/console $ git checkout -b fix/image
Switched to a new branch 'fix/image'
gitpod /workspace/console $ make image
rm -rf build && mkdir -p build
tar …
```

Improve the image tag name in the makefile

---

src/actions/project.js
src/components/Inputs/ResourceLimit/index.jsx

/kind bug
Fixes ##2102
(1) now, we can enter a number with two places of decimal, eg: 0.02, 3.23.
https://user-images.githubusercontent.com/33231138/127299025-64cb4586-7486-4b96-b6e1-664398ae7ef8.mov
(2) we can not input a number bigger than 8, the maximum is from the props, it 's default value is 4(cpu)/8000(memory)
https://user-images.githubusercontent.com/33231138/127299064-87ec9fd8-f47e-4b1d-bf7f-a394c3bb3b79.mov
```release-note
fix: enter a number with two places of decimal directly and limit input maximum. (#2102, @weili520  )
```

fix: enter a number with two places of decimal directly and limit input maximum

---

locales/en/scheduleDeployment.js
locales/es/scheduleDeployment.js
locales/tc/scheduleDeployment.js
locales/zh/scheduleDeployment.js
src/actions/storageclass.js
src/components/Modals/VolumeFunctionManage/index.jsx
src/components/Modals/VolumeFunctionManage/index.scss
src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
src/pages/projects/containers/Volumes/Detail/index.jsx

/kind feature
- use the judgment field as follows:
- annotations['storageclass.kubesphere.io/allow-clone'] :  'true'
- annotations['storageclass.kubesphere.io/allow-snapshot'] :  'true'
- allowVolumeExpansion: true
Fixes ##2158
```
```
https://user-images.githubusercontent.com/33231138/131305218-c53ff323-cea4-4b1b-9fe0-9bf067385d33.mov
```release-note
Change the judgment field in storage management 
```
```docs
```

feat: Change the judgment field in storage management

---

src/pages/projects/containers/Alerting/Messages/index.jsx
src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx
src/utils/alerting.js
src/utils/constants.js

Fixes #
```
```
```release-note
Fix the pod render in workload of alerting
```
```docs
```

fix: Fix the pod render in workload of alerting

---

src/components/Base/List/Item.jsx

/kind bug
Fixes ##2197
```
```
```release-note
Fix the css of hammer icon
```
```docs
```

fix: Fix the position of hammer icon when title is empty on Create ConfigMap modal

---

src/pages/clusters/containers/BaseInfo/index.jsx

/kind bug
Host cluster can't be unbind, so hide the unbind cluster panel in the host cluser
Fixes ##2209
```
```
```release-note
Hide unbind cluster panel in the host cluster
```
```docs
```

fix: Hide unbind cluster panel in the host cluster

---

.gitpod.yml

/kind cleanup
Users don't need to log in to their docker hub account manually.
How to?
You can put these env into your GitPod account: `DOCKER_USER` and `DOCKER_PASSWD`
None.
```
None
```
```release-note
None
```
```docs
None
```

Support to login docker in GitPod automatically

---

src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx

/kind bug
hide the cluster status icon.
Fixes ##2201
```release-note
NONE
```

fix: Remove node status icon

---

server/config.yaml
server/controllers/session.js
server/services/session.js

Signed-off-by: hongming <hongming@kubesphere.io>
For security reasons, client authentication for confidential clients is required when posting an access token request. `client_secret` and `client_id` are configurable.
Fixes #2256
```release-note
None
```

support client authentication

---

src/core/index.js

/kind bug
Fixes ##1962
this bug maybe caused by  safari zoom mechanism, see more: [Safari zoom in/out ruins page layout (doesn't change font-size well)](https://stackoverflow.com/questions/8038876/safari-zoom-in-out-ruins-page-layout-doesnt-change-font-size-well/8457784#8457784)
https://user-images.githubusercontent.com/33231138/127466770-efa248e5-dcf8-443a-85e6-049df563491d.mov
```release-note
NONE
```

fix: disallow user zoom out below 75% in safari browser

---

src/utils/constants.js

/kind feature
Fixes https://github.com/kubesphere/kubesphere/issues/4158
```
```
```release-note
Init the single cluster name with config
```
```docs
```

feat: Init the single cluster name with config

---

src/pages/clusters/containers/Storage/PV/index.jsx
src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
src/pages/clusters/containers/Storage/Volumes/index.jsx
src/stores/base.js
src/utils/object.mapper.js

/kind bug
Fixes #
if  the ksVersion Less than 3.2, the pv manage tab will not show.
```release-note
NONE
```

fix: Check the backend if support pv manag

---

.gitpod.yml

/kind cleanup
With the help of gitpod, users can build and push ks-console image to dockerhub easily. With these changes, users don't need to do anything except opening the gitpod adress.
Fixes #
```
? Which should be the base repository (used for e.g. querying issues) for this directory?  [Use arrows to move, type to filter]
> kubesphere/console
harrisonliu5/console
```
With these changes, users don't need to type anything:
```
HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
git config --global user.name $GIT_AUTHOR_NAME
git config --global user.email $GIT_COMMITTER_EMAIL
[[ ! -z "${DOCKER_USER}" && ! -z "${DOCKER_PASSWD}" ]] && docker login -u${DOCKER_USER} -p${DOCKER_PASSWD}
[[ ! -z "${GITHUB_USER}" && ! -z "${GITHUB_TOKEN}" ]] && docker login ghcr.io -u${GITHUB_USER} -p${GITHUB_TOKEN} …
```

Avoid gh repo fork prompt

---

src/pages/fedprojects/containers/Overview/ResourceUsage/index.jsx
src/pages/projects/containers/Overview/ResourceUsage/index.jsx

…
/kind bug
Fixes ##2338
```
```
https://user-images.githubusercontent.com/63338728/135040635-abec5257-50b8-42f4-b135-c17258afe432.mov
```release-note
Fix the default time range for displaying errors
```
```docs
```

fix: Fix the default time range is displayed incorrectly on the overview page

---

docs/access-backend.md

remove service port name.
If the user sets the port name of service `ks-apiserver`. Then this cluster cannot be imported as a member cluster. Because the host ks-apiserver use the path `/api/v1/namespaces/kubesphere-system/services/:ks-apiserver:/proxy/kapis/version` to access the member ks-apiserver. As there is a port-name in the service `ks-apiserver`, the path must be `/api/v1/namespaces/kubesphere-system/services/:ks-apiserver:ks-apiserver/proxy/kapis/version`  or `/api/v1/namespaces/kubesphere-system/services/:ks-apiserver:80/proxy/kapis/version`, the host cluster will get an error.
https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls
https://github.com/kubesphere/kubesphere/blob/master/pkg/kapis/cl …

remove service port name

---

src/pages/apps/components/AppBase/index.jsx
src/pages/apps/components/Modals/AppCreate/index.jsx
src/pages/apps/components/Modals/HelmUpload/index.jsx

/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```

fix: The data is empty when create a app with template

---

src/components/Forms/Volume/VolumeSettings/AccessModeSelectForm/index.jsx
src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
src/pages/projects/containers/Volumes/index.jsx

/kind bug
Fixes #2183
```
```
```release-note
Change pvc access modes to list
```
```docs
```

fix: Change pvc access modes to list 

---

src/components/Forms/Workload/ContainerSettings/Affinity/index.jsx

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Fix the bug have no formProps onChange func in affinity form

---

src/pages/devops/containers/Pipelines/PipelinesList/index.jsx

/kind bug
Number of branch should not be 0 if the Pipeline is not a multi-branch Pipeline
Fixes #2499
```release-note
None
```

Fix the branch column of pipeline list

---

src/pages/devops/containers/Pipelines/PipelinesList/index.jsx

/kind bug
Fixes #2533 
```
```
```release-note
None
```
```docs
```

fix:Remove the Activity option in the operation drop-down list of the pipeline list page

---

src/components/Base/List/index.scss

/kind bug
Fixes #[#4388](https://github.com/kubesphere/kubesphere/issues/4388)
```release-note
NONE
```
```docs
```

fix: Configmap's secret text too long

---

src/components/Modals/QuotaEdit/index.jsx
src/pages/fedprojects/containers/Overview/LimitRange/index.jsx
src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
src/utils/workload.js

/kind bug
At before，the available quota is the workspace lefted quota, it is Incorrect，the project available quota should be the sum of workspace lefted quota and project used.
Fixes #
the workspace in shire cluster total quota is: 
limits.cpu:  2 Core
limits.memory: 6G
the lcj-test-shire namespace total quota is:
limits.cpu:  1 Core
limits.memory: 2G
the workload that we created quota is:
limits.cpu:  0.5 Core
limits.memory: 1G
https://user-images.githubusercontent.com/33231138/141942391-b61b01ef-6f09-4378-97ab-a87c0cdb737d.mov
At before, if we create a workload as the video shown, the available quota as follows:
```release-note
Project avaliable quota inccrect. It should be the sum of workspace remaining quota and project used quota. 
```
```docs
```

fix: Update project available quota when editing project quota

---

src/components/Modals/LogSearch/Logging/Search/index.jsx
src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.jsx

/kind bug
Fixes ##2464,##2250
```release-note
Log matched keywords highlight is [Object Object].
```

fix: Log detail highlight keyword is [Object Object]

---

src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx

Signed-off-by: TheYoungManLi <33231138+weili520@users.noreply.github.com>
/kind bug
Fixes ##2309
```release-note
Volume status label inccrect when editing deployment settings.
```

fix: Status label inccrect

---

src/actions/project.js
src/pages/fedprojects/containers/BaseInfo/index.jsx
src/pages/fedprojects/containers/Overview/LimitRange/index.jsx
src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx

/kind feature
The project resource default quota maximum should be the smallest of workspace lefted quota and namespace quota limit.
Fixes #
```
The workspace lcj-auto-quota's has two single cluster project in it: test2、lcj-test1. 
The quota of cluster rohan as follows:
requests.cpu: 1 Core   requests.memory: 1 G
limits.cpu: 4 Core     limits.cpu: 8 Core
the lcj-test1 project quota is: 
request.cpu: 0.9 Core  reqests.memory: Not limit
limits.cpu: Not limit  limits.cpu: 6.5 Core
so container default quota maximum is : 
request.cpu: 0.9 Core  reqests.memory: 1 G
limits.cpu: 4 Core     limits.cpu: 6.5 G
For multi cluster project, it also work on this, It will compares all cluster quota limit.
``` …

feat: Add avalibale quota tip when edting project resource default quota

---

src/pages/clusters/containers/Workload/Pods/index.jsx
src/pages/projects/containers/Pods/index.jsx
src/utils/constants.js

Signed-off-by: TheYoungManLi <33231138+weili520@users.noreply.github.com>
/kind feature
Fixes ##2592
https://user-images.githubusercontent.com/33231138/142154430-831dbf16-bc15-4d83-9fca-68bea7d739b1.mov
```release-note
Support search pods by pod status in pods management page. 
```

feat: Add status filter in pods manage page

---

src/stores/pv.js

/kind bug
Fixes ##2597
```release-note
No kind information on view volume instance yaml page.
```

fix: No kind information on view volume instance yaml page

---

locales/en/notification.js
locales/es/notification.js
locales/tc/notification.js
locales/zh/notification.js
src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
src/utils/constants.js

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Notification condition to add new tag validation rules

---

src/components/Cards/Volumes/Item.jsx
src/components/Forms/Workload/VolumeSettings/AddVolume/index.jsx
src/components/Forms/Workload/VolumeSettings/index.jsx

/kind bug
At before, we can't switch the type of mounted volume for deolyment, because the update volume didn't  be removed from the deloyment spec.
Fixes ##2467,##2505,##2345
https://user-images.githubusercontent.com/33231138/143185226-a14b2f34-67c2-4d28-8655-f960a632f365.mov
```release-note
Update volume info for deolyment failed.
```
```docs
```

fix: Can't update volume for deloyment

---

src/components/Inputs/ResourceLimit/index.jsx

/kind bug
Now, user can't input the number like '01'.
Fixes ##2484
```
```
```release-note
NONE
```

fix: Update gpu limit number verification rule

---

src/components/HOCs/withList.js

/kind bug
Fixes #
No searchApp params in queryString
```release-note
NONE
```

fix: Search params problem

---

src/utils/index.js

/kind bug
Fixes #
```release-note
AccessMode abbreviation error in volume manage page
```

fix: AccessMode abbreviation error in volume manage page

---

src/components/Forms/Route/RouteRules/index.jsx
src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
src/pages/clusters/containers/Projects/Detail/Gateway/index.jsx
src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
src/pages/fedprojects/containers/Gateway/Access/index.jsx
src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
src/pages/fedprojects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
src/pages/projects/components/Modals/CreateApp/index.jsx
src/pages/projects/containers/Gateway/index.jsx
src/pages/projects/containers/Routes/Detail/ResourceStatus/index.jsx
src/pages/projects/containers/Routes/index.jsx
src/stores/gateway.js

/kind bug
Fixes #
```
```
```release-note
Fix the error of failure to get gateway without cluster permission in the project
```
```docs
```

fix: Fix the error of failure to get gateway without cluster permission in the project

---

src/utils/index.js

/kind bug
Fixes ##2614
```
The problem is described in the process of editing services, 
the switch yaml file has invalid template parameter spec.template，
delete invalid parameters of services in the filtered resource template 
```
```
After modification, the invalid parameters in the red box above will no longer be displayed 
```
```release-note
NONE
```

fix: Remove the invalid parameter template in the service edit mode

---

server/config.yaml
src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx

Signed-off-by: mango <xu.weiKyrie@foxmail.com>
/kind bug
Please see #2696. 
When verify credential, only display the type is equip to `username_password` 
Fixes ##2696
```release-note
None
```

fix: Certificate verification problem

---

src/utils/index.js

/kind bug
User can't enter ther container terminal page when the browser language is not en, zh and zh-tw
Fixes #
```release-note
User can't enter ther container terminal page when the browser language is not en, zh and zh-tw.
```

fix: User can't open container terminal

---

src/components/Base/Card/index.scss

/kind bug
Fixes ##2677
https://user-images.githubusercontent.com/33231138/144206222-93600687-3eee-4bef-88d5-d0fc705f6623.mov
```release-note
Cluster resource usage time controller is covered up.
```
```docs
```

fix: Cluster resource usage time controller is covered up

---

src/components/Modals/Monitoring/ApplicationResource/index.jsx
src/components/Modals/Monitoring/Controller/index.jsx

/kind bug
Resource Monitor Modal selected time range does not work.
Fixes ##2674 
https://user-images.githubusercontent.com/33231138/144350615-97e74df8-7a79-4231-b41b-462f898997c2.mov
```release-note
Resource Monitor Modal selected time range does not work.
```

fix: Resource Monitor Modal selected time range does not work

---

src/components/Forms/Workload/VolumeSettings/index.jsx

/kind bug
Fixes ##[4432](https://github.com/kubesphere/kubesphere/issues/4432)
https://user-images.githubusercontent.com/33231138/144388003-d993f6f6-78ac-46fe-a134-8109b5f475d0.mov
```release-note
Failed to create a statefulSet with a volume template added.
```

fix: Failed to create a statefulSet with a volume template added

---

src/components/Forms/Route/RouteRules/RuleForm/index.jsx
src/stores/devops/pipelines.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/2747
```
```
```release-note
```
```docs
```

fix: Fix the branch name not encode.

---

src/components/Inputs/ResourceLimit/index.jsx

/kind bug
Before, if we don't set a quota limit for the project and workspace, the quota tips will not show.
Fixes ##2767
https://user-images.githubusercontent.com/33231138/144995575-75cd966c-0a30-47cd-a6c2-e475595ffafe.mov
```release-note
NONE
```

fix: Gpu limit validation error

---

server/services/session.js

/kind bug
If user not login, the terminal will log an error as follows:
```
{
code: 403,
kind: 'Status',
apiVersion: 'v1',
metadata: {},
status: 'Failure',
message: 'nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope',
reason: 'Forbidden',
details: { kind: 'nodes' },
statusText: 'Forbidden'
}
```
Fixes #
```
```
```release-note
NONE
```

fix: Terminal log 403 error if user not login

---

src/pages/apps/containers/Home/index.jsx

/kind bug
Fixes ##2631
```release-note
NONE
```

fix: App categories name is 'all'

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.scss
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss

/kind bug
Fixes #
```
```
```release-note
fix: Fix the wrong url of the harbor image
```
```docs
```

fix: Fix the wrong url of the harbor image

---

src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/2780
```
```
```release-note
None
```
```docs
```

fix: Hide the operation button that is no run id in pipeline

---

src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
src/pages/clusters/containers/Gateway/Detail/AnnotationsCard/index.jsx
src/pages/clusters/containers/Gateway/Detail/GatewayConfig/index.jsx
src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx
src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/2777
```
```
```release-note
```
```docs
```

fix: Fix the null of gateway data in access page of composing app

---

build/Dockerfile

Signed-off-by: Roland.Ma <rolandma@kubesphere.io>
/kind flake
Upgrade base image to `node:12-alpine3.14` to fix  CVE-2021-28831 in the docker base image
Fixes #
```
```
```release-note
None
```
```docs
```

Fix CVE-2021-28831

---

src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx

/kind bug
Fixes ##2810
https://user-images.githubusercontent.com/33231138/145422191-ce5aeebd-ffe6-4551-b700-8ed381ca343e.mov
```release-note
NONE
```

fix: After editing the pipeline configuration, the pipeline disappears

---

docs/join-the-kubesphere-localization-project.md

Add preview environment address to l10n guide.
/assign @harrisonliu5 @xuliwenwenwen @FeynmanZhou 
```release-note
None
```

docs: Add preview environment address to l10n guide.

---

locales/en/l10n-projects-applicationWorkloads-deployments-list.js
src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
src/utils/workload.js

/kind bug
Now, if the user didn't set a resource limit for the container, the tip title will be 'Resource occupation is unset', and if the limit setting is beyond the available quota, the title will be 'The current resource occupation has exceeded the remaining'.
Fixes ##2672
https://user-images.githubusercontent.com/33231138/145358264-5f001d15-e88f-4a38-9d94-746e7f7b7894.mov
```release-note
NONE
```
```docs
```

fix: Incorrect information for exceeding the resource limit

---

build/Dockerfile

/kind bug
/kind failing-test
Dockerfile base image `node:12-alpine3.14` failed to install python2 https://prow.kubesphere.io/view/s3/prow-logs/logs/pull-console-build-image/1469202824981123072. 
Previously,  `app add python` to python2, but the package name renamed to python2 in `node:12-alpine3.14`.
Fixes #
```
```
```release-note
None
```
```docs
```

fix failing docker build

---

locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
locales/zh/l10n-platformSettings-notificationManagement-notificationConfiguration.js
src/components/Inputs/TagInput/autosuggest.jsx

/kind bug
Fixes ##2816 
```
```
```release-note
None
```
```docs
```

fix: Notification condition filter custom tag value validation rules.

---

src/pages/projects/components/Modals/CreateAppService/index.jsx

/kind bug
Fixes ##2774
https://user-images.githubusercontent.com/33231138/145944239-10c3ee60-b1a9-44fe-a5cd-836b4b9d19d3.mov
```release-note
The data is empty when modifying the stateful service during creating apps.
```

fix: The data is empty when modifying the stateful service during creating apps

---

src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx

/kind bug
> During creating a deployment, if the workspace or project has a quota limit, the container should also need to set resource limits, otherwise, we should give them an error tip. 
For example, the project `hello`'s project quota limit is as follows:
```
requests.cpu: 1 core requests.memory: 2 Gi
limits.cpu: 2 core   limits.memory: Not limited
```
and the container's default resource quota is:
```
requests.cpu: 1 core requests.memory: 1 Gi
limits.cpu: 4 core   limits.memory: 4 Gi 
```
so, if we don't update container's quota during creating deployment, the tip info should be this:
and then update it to:
```
requests.cpu: 1 core requests.memory: 1 Gi
limits.cpu: Not limited   limits.memory: 4 Gi
```
the tip should be as this:
Fixes …

fix: Update container resource occupation validation strategy

---

src/actions/secret.js
src/stores/federated.js

/kind bug
This problem was caused by the response data lost 'kind' and 'apiVersion' fields in multi-cluster projects.
Fixes ##2854
Before, the put request body lose 'kind' and 'apiVersion' field.
> ![截屏2021-12-20 16 13 09](https://user-images.githubusercontent.com/33231138/146734261-271647ce-6cf4-4bc9-8361-9eb612dfe3ee.png)
At now:
> ![截屏2021-12-20 16 11 10](https://user-images.githubusercontent.com/33231138/146734487-76c5210e-4eeb-45b7-b931-832a99c0feb9.png)
```release-note
Update Secrets failed for multi cluster project.
```

fix: Update Secrets failed for multi cluster project

---

src/actions/configmap.js

/kind bug
This problem was caused by the response data lost 'kind' and 'apiVersion' fields in multi-cluster projects.
Fixes ##2854
```
```
```release-note
Update configMap failed for multi-cluster project.
```

fix: Update configMap failed for multi-cluster project

---

src/actions/router.js

/kind bug
The failed reason is the `spec.placement.cluster` fields should include all clusters are mentioned in the `spec.template.spec` fields, otherwise, the update will fail.
Fixes ##2855
```
I create a route, includes Rohan and Shire two clusters, it works well.
```
```release-note
Update application routes failed for multi-cluster project
```

fix: Update application routes failed for multi-cluster project

---

src/stores/base.js
src/stores/service.js

/kind bug
This problem is caused by the getFilterParams function in the store/base.js, it makes us cant search table data in multi-cluster projects.
Fixes ##2851
```
```
```release-note
Can't search table data by name in multi-cluster projects.
```

fix: Can't search table data by name

---

src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx

/kind bug
The host cluster's name always is 'host' in multi-project, so it can't validate the image registry information when the user had updated the host cluster's name to 'host-test'.
Fixes ##2853
```
It works well
```
```release-note
Can't validate Image registry information after updating host cluster name in the multi-cluster project.
```

fix: Can't validate Image registry information after updating host cluster name in multi-cluster project

---

server/config.yaml
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/components/Inputs/ResourceLimit/index.jsx
src/components/Modals/QuotaEdit/Quotas/index.jsx
src/components/Modals/QuotaEdit/index.jsx
src/pages/fedprojects/components/ContainerSetting/index.jsx
src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
src/utils/index.js

/kind bug
This problem is caused by the response data includes other fields such as `count/pods` when we get the project quota
Fixes ##2861
```
When supported gpu just one type
```
+ `single cluster project`
+ `multi-cluster project`
```
supported gpu has more type
```
https://user-images.githubusercontent.com/33231138/146679307-e4ba06bb-deea-4a5d-8eb9-5573e7864e74.mov
```release-note
NONE
```

fix: Gpu tip info error and gpu limit number error

---

src/components/Modals/LogSearch/Logging/Detail/index.jsx

/kind bug
Fixes ##2850
```
The tip works when the mouse hover
```
```release-note
Add prompt information for button in log search detail page
```

fix: Add prompt information for button in log search detail page

---

src/pages/fedprojects/containers/QuotaManage/ResourceQuota/QuotaItem/index.jsx
src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.jsx

/kind feature
Fixes ##2877,##2798
- No GPU info in the resource card for a multi-cluster project
- No user-defined resource quota in the resource card
> For user-defined field, all user-defined field fields will not translate their name to another name and will use the same `resource` icon
```release-note
User-defined resource quota and GPU limit are not displayed in the quotas card for the multi-cluster project.
```

fix: User-defined resource quota and GPU limit are not displayed in the quotas card for the multi-cluster project

---

src/stores/node.js

/kind bug
Fixes ##2875
```release-note
The number of worker nodes is incorrect on the cluster nodes page.
```

fix: The number of worker nodes is incorrect

---

src/actions/project.js
src/components/Inputs/ResourceLimit/index.jsx
src/components/Modals/QuotaEdit/index.jsx
src/stores/federated.js
src/stores/limitrange.js
src/utils/index.js

/kind bug
This is part of the work about #2870. In order to avoid adding the GPU field into the yaml, we need to get GPU info from the requests field and save the GPU limit into the requests and limits field in the ResourceLimit component, so some operations about the GPU are no longer needed.
Fixes ##2870
```
No UI change
```
```release-note
NONE
```

fix: Cancel gpu field when edit project quota

---

src/actions/project.js
src/components/Inputs/ResourceLimit/index.jsx
src/pages/fedprojects/containers/BaseInfo/DefaultResource/index.jsx
src/pages/fedprojects/containers/BaseInfo/DefaultResource/index.scss
src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
src/pages/projects/containers/BaseInfo/DefaultResource/index.jsx

/kind bug
- This part of the job of #2870
- Add GPU limit info in the default container quotas card in the multi-cluster project.
Fixes ##2870
- Add GPU limit info 
- delete GPU field
```release-note
Add GPU limit info in the default container quotas card in the multi-cluster project.
```
This one should be merged after #2878, and it will need to resolve conflicts.

fix: Delete gpu field when editing project default resource

---

src/components/Modals/QuotaEdit/Quotas/Item.jsx

/kind bug
Before, when users edit project resource quotas, if they set the key as counts/pods, so the value of limit can be set as '20G' and override the pods' limits., it is incorrect.
Fixes ##2797
```release-note
The unit of project resource quotas limit is incorrect.
```
Now, if users set the key as one of the follows, the value only can be an integer:
- `limits.cpu`
- `requests.cpu`
-  `limits.memory`
- `requests.memory`
- `count/pods` or `pods`
- `count/deployments.apps` or `deployments`
- `count/statefulsets.apps` or `statefulsets`
- `count/daemonsets.apps` or  `daemonsets`
- `count/jobs.batch` or `jobs`
- `count/cronjobs.batch` or `cronjobs`
- `persistentvolumeclaims`
- `count/services` or `services`
- `count/ingresses.extensions` or …

fix: The quantity unit of the container group quota is incorrect

---

src/components/Forms/Dashboard/BaseInfo/index.jsx

/kind bug
the YAML content is not matched with the monitoring template type after creating a dashboard.
Fixes ##2848
```
No UI problem
```
```release-note
Yaml content is not matched with the monitoring template type after creating a dashboard.
```
This problem is caused by the template.json being referenced by the page data, its 'settings. title' field will be overridden with the monitoring template type.

fix: Yaml content is not matched with the monitoring template type

---

src/pages/projects/components/Modals/CreateApp/Services/ServiceList/index.scss

/kind bug
The replicas count will hide when the user hovers the service.
Fixes ##2776
https://user-images.githubusercontent.com/33231138/147638233-99b24b0a-a88a-43fa-b4ef-3b17851edeb1.mov
```release-note
The replicas count is covered by the operation button when creating a composing Application in the multi-cluster project.
```

fix: The replicas count is covered by the operation button when creating a composing Application in the multi-cluster project

---

src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx

/kind bug
Fixes ##2732
If the pipeline record doesn't have the start time, the start time will be '-'.
```release-note
The update time of pipeline is displayed as 'Invalid date'.
```

fix: Pipeline start time invalid

---

src/stores/pv.js

/kind bug
The problem is caused by the request URL lost cluster field.
Fixes ##2891
Rohan cluster is a member cluster
https://user-images.githubusercontent.com/33231138/148345432-e90ccd66-edc8-4edf-bac1-a0ee4380e79b.mov
```release-note
Can't enter PV detail page in member cluster
```

fix: Can't enter PV detail page in member cluster

---

src/actions/application.js
src/actions/federated.js
src/actions/workload.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx
src/pages/fedprojects/components/ContainerSetting/index.jsx
src/utils/constants.js
src/utils/index.js

/kind bug
- This part of the job of #2870
- There is no need to deal with GPU field anymore, so delete redundant operations.
Fixes ##2870
```
Create a deployment, and then switch to edit YAML mode
```
```release-note
Use kubectl to apply the YAML which is copied from the deployments detail page failed.
```

fix: Delete gpu field when creating workload

---

src/components/Forms/ImageBuilder/B2IForm/index.jsx

/kind bug
Fixes ##2886
The workspace `Test-url`  includes cluster host and cluster member. 
The project `hellos` is a single cluster project in workspace `Test-url`,  located in the member cluster.
```release-note
Invalid API request of listing s2ibuilder templates in the multi-cluster environment
```

fix: Invalid API request of listing s2ibuildertemplates in multi-cluster environment

---

src/components/Modals/DevOpsCreate/index.jsx
src/stores/base.js

Signed-off-by: mango <xu.weiKyrie@foxmail.com>
/kind bug
/area devops
Fixes #2707
```
```
The screentshot like below:
```release-note
None
```

fix: Verify devops project name input

---

src/components/Inputs/ResourceLimit/index.jsx

/kind bug
During creating a deployment, if the user creates a container without a requests limit, and then he wants to edit it again, the edit page will be broken.
`Note`: it does not affect programs that have already been released.
`How to reproduce`:
https://user-images.githubusercontent.com/33231138/149311872-1afd20f2-429f-4288-88ad-065bed2f493e.mov
Fixes #
```
```
```release-note
NONE
```

fix: User can't edit resource limit for workload during create deloyment

---

src/components/Forms/Workload/ContainerSettings/Metadata/index.jsx

/kind bug
During creating a workload, if the user sets metadata for the container and validates failure, the user can't save it and enter the next step. Until then, we did not limit it.
Part of the work of  ##2431
https://user-images.githubusercontent.com/33231138/149309979-f2bb3df6-972e-47d7-86e9-c004a9a4e0ae.mov
```release-note
Block users from going to the next step when the metadata validation fails
```

 fix: Block users from going to the next step when the metadata validation fails

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/Environments/index.jsx
src/components/Inputs/ArrayInput/Item.jsx
src/components/Inputs/ArrayInput/index.jsx
src/components/Inputs/EnvironmentInput/Item.jsx
src/components/Inputs/EnvironmentInput/index.jsx

/kind bug
During creating a workload, if the user set environment variables for the container and validate failure, the user can't save it and enter the next step. Until then, we did not limit it.
Part of the work of ##2431
```release-note
Block users submit updates when environment variable verification fails
```

fix: Block users submit updates when environment variable verification fails

---

locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
src/components/Forms/Notification/WebhookForm/index.jsx

/kind bug
Fixes ##[kubesphere/kubesphere#4310](https://github.com/kubesphere/kubesphere/issues/4310)
```
```
```release-note
fix: Webhook token and auth should be required fields.
```
```docs
```

fix: Webhook token and auth should be required fields

---

src/components/Forms/Notification/WeComForm/index.jsx

/kind bug
WeCom receive settings should be set to required.
Fixes #
```
```
```release-note
fix: Wecom receiver should be required.
```
```docs
```

fix: Wecom receiver should be required

---

src/components/Graph/Detail/Monitors/ServiceMonitor.jsx
src/components/Graph/Detail/Monitors/WorkloadMonitor.jsx
src/stores/application/crd.js

Signed-off-by: Roland.Ma <rolandma@kubesphere.io>
/kind bug
2 issues were fixed.
1. Service tab should only have inbound traffic data.
2. TCP traffic should be displayed in the Workload tab
Fixes# #https://github.com/kubesphere/kubesphere/issues/4498
```release-note
The TCP traffic data in traffic monitoring is empty
```
```docs
```
/cc @harrisonliu5

fix: Fix The TCP traffic data in traffic monitoring is empty

---

src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx

/kind bug
Cannot be modified when the value of the livenessProbe is {} in container data.
Fixes #https://github.com/kubesphere/kubesphere/issues/4345
```
```
```release-note
fix: Delete the livenessProbe that it is empty
```
```docs
```

fix: Delete the livenessProbe that it is empty

---

locales/en/terminal.js
locales/zh/terminal.js
src/stores/terminal.js

/kind bug
Fix the problem of websocket proxy configuration on the proxy server. If there is a problem, can't access terminal.
Fixes [#kubesphere/kubesphere/4444](https://github.com/kubesphere/kubesphere/issues/4444)
```
```
```release-note
fix: Can't access terminal on pods
```
```docs
```

fix: Can't access terminal on pods

---

src/pages/projects/containers/ServiceAccounts/Detail/routes.js

Fix an improper description of a tab on the Service Accounts details page.
```
1. Log in to the KubeSphere web console.
2. Select Cluster Management > Configurations > Service Accounts.
3. Click the name of a service account to view its details page.
The change has been made on the service account details page. I changed **Resource Status** to **Data**, which, in my opinion, better describe this area.
```
```release-note
None
```
/assign @Patrick-LuoYu @harrisonliu5 
Please take a look, thanks!

docs: Fix an improper description on a tab.

---

src/components/Forms/Pipelines/PipelineTemplateParams/params.jsx

/area devops
Make required field decide whether the form item is required. 
We have decided to add a required field to determine whether the parameter is required to input instead of using `default` field. See
- https://github.com/kubesphere/ks-devops/pull/489
for more.
Fixes #
Steps to test:
1. Apply a ClusterTemplate for test:
```bash
cat <<'EOF' | kubectl apply -f -
apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterTemplate
metadata:
name: echo
spec:
parameters:
- default: John
name: 姓
required: false
- default: Niang
name: 名
required: true
template: |
pipeline {
agent none
stages {
stage('echo') {
steps {
echo 'Hello, $(.params.姓)-$(.params.名)!'
}
}
}
}
EOF
```
1. Create a Pipeline for test
2. Edit Pipeline and select the ClusterTemplate created just now
3. See …

Make required field determine whether the parameter is required

---

src/pages/devops/components/Pipeline/Sider/index.jsx

/area devops
As I mentioned in the title, I remove default value of label field when editing Pipeline and select agent type into kubernetes.
See #2986 for more.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/16865714/158756142-c0092b32-614f-4a2f-89e8-aa62fdf58610.png)|![image](https://user-images.githubusercontent.com/16865714/158755950-c331d383-72ef-4e37-b7d0-c774fddef110.png)|
Fixes #2986 
```
```
```release-note
Remove default value of label field when editing Pipeline and select agent type into Kubernetes
```
```docs
```
/cc @kubesphere/sig-devops 
/cc @kubesphere/sig-console

Remove default value of label field when agent type is kubernetes

---

src/components/Modals/KubeCtl/index.jsx
src/components/Modals/KubeCtl/index.scss
src/components/Terminal/index.jsx
src/components/Terminal/terminal.jsx
src/pages/clusters/containers/Nodes/index.jsx

/kind bug
Fixes ##2902
```
Now, it will hide the select component when it connects to the node cluster,
and the error tip will switch to `Could not connect to the node. Do you have sufficient privileges?`
```
```release-note
Update terminal prompt.
```

fix: Update terminal prompt.

---

src/pages/projects/components/Modals/ResourceSnapshot/index.jsx

/kind bug
user can't create snapshot from volume detail page.
Which version: nightly-20220327
Fixes #
```
```
```release-note
NONE
```

fix: Can't create snapshot from volume detail page

---

src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx

/kind bug
The 'Access mode' should be removed in pvc list.
Fixes #
```
```
```release-note
NONE
```

fix: Pvc list ui problem

---

locales/en/l10n-clusterManagement-storage-storageClasses-list.js
src/components/Forms/StorageClass/StorageClassSettings/index.jsx

Correct an inconsistent name of a parameter in the Create Storage Class dialog box.
In the Create Storage Class dialog box, the name of the parameter is **Storage System**.
But on the storage class list page, the name of exactly the same parameter is **Provisioner**.
I consulted @stoneshi-yunify and we concluded that these two parameters should have a consistent name **Provisioner**.
```
None
```
```release-note
None
```
/assign @harrisonliu5 Please take a look and help merge this PR. Thx.

docs: Update UI text.

---

src/components/Forms/StorageClass/StorageClassSettings/index.jsx

/kind bug
Fixes ##3033
```
Now, the key of parameters is lowercase.
```
```release-note
NONE
```

fix: Update parameters's key to lowercase

---

src/stores/cd.js

/kind bug
/area devops
As I mentioned in the title. The default cluster name should be `in-cluster` instead of `default`.
Before:
After:
Fixes #
```
```
```release-note
None
```
```docs
```

Fix the default cluster name of the argo app destination

---

src/components/Forms/StorageClass/StorageClassSettings/index.jsx
src/utils/form.templates.js

/kind bug
Fixes ##3032
```
Now
```
```release-note
The volumeBindingMode of the created storageClass is always 'Immediate'
```

fix: The volumeBindingMode of the created storageClass is always 'Immediate'

---

locales/en/l10n-projects-applicationWorkloads-deployments-details.js
locales/zh/l10n-projects-applicationWorkloads-deployments-details.js
src/components/Forms/Workload/VolumeSettings/index.jsx
src/components/Inputs/EnvironmentInput/ArrowModal/index.jsx
src/components/Inputs/EnvironmentInput/ArrowModal/index.scss
src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.jsx
src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.scss
src/components/Inputs/EnvironmentInput/Item.jsx
src/components/Inputs/EnvironmentInput/index.jsx
src/components/Inputs/EnvironmentInput/index.scss
src/components/Inputs/EnvironmentInput/index.test.js

/kind feature
Fixes #[#4410](https://github.com/kubesphere/kubesphere/issues/4410)
https://user-images.githubusercontent.com/33231138/161249262-ef0a4bb5-f29e-49c6-91c5-a3adfef0a0b7.mov
```release-note
Support load the entire configmap or secret as environment variables for a deployment.
```

feat: Support load the entire configmap as environment variables

---

server/controllers/view.js
server/services/session.js
src/pages/workspaces/containers/BaseInfo/index.jsx

/kind bug
- Disable management function in accounts and workspaces manage page when user login in a member cluster.
- Update workspace related api's version, refer to this: [Refactor workspace API and introduced tenant v1alpha3 version](https://github.com/kubesphere/kubesphere/pull/4721).
Fixes ##[4610](https://github.com/kubesphere/kubesphere/issues/4610)
```
No management button in accounts and workspaces page.
```
```release-note
Disable management function in accounts and workspaces manage page when user login in a member cluster
```

fix: Disable management function in accounts and workspaces manage page when user login in a member cluster

---

locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
locales/zh/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
src/pages/clusters/containers/Nodes/Detail/Monitoring/index.jsx

/kind feature
Fixes #https://github.com/kubesphere/kubesphere/issues/4532
```release-note
feat: Add disk usage per hard disk
```
```docs
```

feat: Add disk usage per hard disk

---

locales/en/l10n-clusterManagement-storage-volumeSnapshotClasses-list.js
locales/zh/l10n-clusterManagement-storage-volumeSnapshotClasses-list.js
server/config.yaml
src/actions/volume.js
src/components/Forms/VolumeSnapshot/SnapshotClassSettings/index.jsx
src/configs/steps/volume.snapshot.class.js
src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.jsx
src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/index.jsx
src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/routes.js
src/pages/clusters/containers/Storage/VolumeSnapshotClasses/index.jsx
src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
src/pages/clusters/routes/detail.js
src/pages/clusters/routes/index.js
src/utils/constants.js
src/utils/form.templates.js
src/utils/object.mapper.js

/kind feature
- The last part of work about ##2930
- Add snapshot class management page
- snapshot class list page
- snapshot class detail page
- create snapshot class
```release-note
Add snapshot class management page
```
`Requirements`: 
- KubeSphere version should be greater than 3.3

feat: Add snapshot class management page

---

src/pages/clusters/containers/Workload/Routes/index.jsx

/kind bug
Fixes ##3057
```release-note
NONE
```

fix: No description for routes item in cluster management page

---

src/components/Modals/ContianerTerminal/index.jsx

/kind bug
Fixes ##3040
https://user-images.githubusercontent.com/33231138/162903939-7893295e-4894-4de7-a8b1-3ec6ebe4ee1f.mov
```release-note
Container terminal doesn't change when switching to another container
```

fix: Container terminal doesn't change when switching to another container

---

server/services/session.js

/kind bug
+ If a user use latest console image(v3.3.0-alpha.0) to connect a cluster which kubesphere version is v3.2.1, it will be error
Fixes #
```
```
```release-note
NONE
```

fix: Can't connect to the cluster which kubesphere version below v3.3

---

src/components/Cards/Containers/EnvVariables/index.scss

/kind bug
Fixes # #3073
```release-note
NONE
```

fix: Environment variable display is occluded

---

src/components/Inputs/EnvironmentInput/Item.jsx
src/utils/constants.js

/kind bug
Fixes # #3078
+ It will be error
+ No error
```release-note
NONE
```

fix: Environment variables do not support key names containing hyphens (-) and periods (.)

---

src/pages/projects/containers/Deployments/Detail/RevisionControl/index.jsx

/kind bug
Fixes ##2987
```release-note
Remove the Version field on the Revision Records tab page
```

fix: Remove the Version field on the Revision Records tab page

---

locales/en/l10n-clusterManagement-storage-storageClasses-details.js
locales/zh/l10n-clusterManagement-storage-storageClasses-details.js
src/components/Modals/StorageclassAutoresizer/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx

/kind bug
Fixes #
+ Old
+ New 
+ The default storage limit value is: `10000Gi`
```release-note
NONE
```

fix: Update PVC autoresizer text

---

src/pages/clusters/containers/Clusters/index.jsx

/kind bug
Fixes ##3097
```release-note
NONE
```
```docs
```

fix: Remove 'update kubeconfig' and 'unbind cluster' button in host cluster card

---

src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
src/stores/base.js
src/stores/validateWebhookCF.js
src/utils/constants.js

/kind bug
If the user uses the latest version console to connect the cluster which version is v3.2.1, here will has an error as follows:
~~So this management function needs kubesphere version greater than 3.3.~~
So we should check if k8s supports accessor resource when kubesphere verison below 3.3.
Fixes #
```
```
```release-note
NONE
```

fix: StorageClass accessor manage URL error

---

src/pages/projects/containers/Services/Topology/Detail/Containers/index.jsx

/kind bug
Fixes ##3108
https://user-images.githubusercontent.com/33231138/163371048-efe52134-ba58-4152-bbf5-59f0ed15fbe8.mov
```release-note
Service topology map container monitoring's data doesn't change with the data request
```
```docs
```

fix: Service topology map container monitoring's data doesn't change with the data request

---

src/utils/form.templates.js

/kind bug
Storageclass's accessor should in dsiabled status by default.
Fixes ##3141
```
```
```release-note
NONE
```

fix: Storageclass's accessor should in dsiabled status by default

---

src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```

fix: Storageclass autoresizer function should be disabled when it volume expansion funciton is disabled

---

src/components/Forms/Dashboard/BaseInfo/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3115
```
```
```release-note
Fix the data is residual when after is created the custom monitor
```
```docs
```

fix: Fix the data is residual when after is created the custom monitor

---

locales/en/l10n-clusterManagement-storage-storageClasses-details.js
src/actions/storageclass.js
src/pages/clusters/components/Modals/Accessor/index.jsx
src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
src/stores/base.js

/kind bug
If kubesphere backend is lack of accessor CRD, it will create 404 warning as follow:
So we should prompt the user to upgrade the ks-installer to v3.3.0 and above or manually install the storageclass-accessor component.
```release-note
NONE
```

fix: Backend is lack of accessor crd will create 404 warning

---

src/components/Modals/CustomMonitoring/components/Graph/Compose/index.jsx

/kind bug
This problem is caused by the bar interval being bigger than the data interval, the response data just has one and its position is at the first of the response data, so the bar will be out of the boundary.
So, if the response data is just one and it is at the start or tail of xAxis, we will add padding for xAxis and adjust the width of the bar to avoid this problem.
Fixes ##3118
```release-note
Bars of a custom monitoring dashboard exceed the boundary
```

fix: Bars of a custom monitoring dashboard exceed the boundary

---

src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx

/kind feature
/area devops
Many users hope they can create a single role to only support trigger Pipelines instead of having full control of the Pipeline management permission.
With this PR, users can do it. Please see the following screenshot (including regular and multi-branch Pipelines):
See also the original feature request from [the KubeSphere Chinese forum](https://kubesphere.com.cn/forum/d/4048-devopsbug/4).
fix https://github.com/kubesphere/ks-devops/issues/155
Fixes #
hi @harrisonliu5 , I'm not familiar with the front-end code base. Please help me to review this PR. Thanks!
```release-note
Support creates a role that can only trigger a Pipeline
```
```docs
```

Support creates a role that can only trigger a Pipeline

---

src/pages/projects/components/Modals/ResourceSnapshot/index.jsx

/kind bug
Fixes:
- User still can create a snapshot while selected volume's storageclass has been deleted
- Update the method that get the snapshotclass
Now, it will disallow user to create it
```release-note
NONE
```

fix: User still can create a snapshot while selected volume's storageclass has been deleted

---

src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
src/stores/volumeSnapshotClasses.js

/kind bug
Fixes #[#4808](https://github.com/kubesphere/kubesphere/issues/4808)
User cant create a volume from snapshot if its snapshotclass has been deleted.
```release-note
NONE
```

fix: User still can create a volume from a snapshot after its snapshot class has been deleted

---

src/actions/storageclass.js
src/stores/accessor.js

/kind bug
If user cluster lack of accosser related resource, here will create a 404 warning when user delete a storagclass.
Fixes #
```
```
```release-note
NONE
```

fix: Delete a storageclass with 404 warning

---

src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx

/kind bug
Fixes ##3166
https://user-images.githubusercontent.com/33231138/164612295-b2349a7c-c373-494e-8d40-e796774d286a.mov
```release-note
Storageclass name incrrect when creating a volume from a snapshot
```

fix: Storageclass name incrrect when creating a volume from a snapshot

---

src/components/Forms/Dashboard/BaseInfo/index.jsx
src/stores/dashboard.js

/kind bug
Fixes #[#4822](https://github.com/kubesphere/kubesphere/issues/4822)
The create path is: `/kapis/clusters/host/monitoring.kubesphere.io/v1alpha3/namespaces/lcj-grafana/dashboards/test/template`
```release-note
NONE
```

feat: Support the grafana dashboard at the namespace

---

src/pages/clusters/containers/Network/IPPools/Detail/index.jsx

/kind bug
Fixes ##3192
```
```
```release-note
NONE
```

fix: The end ip address of calico should be the broadcast address

---

src/actions/pipeline.js
src/components/Forms/Pipelines/PipelineTemplate/index.scss
src/components/Forms/Pipelines/PipelineTemplateParams/index.jsx
src/components/Forms/Pipelines/PipelineTemplateParams/index.scss
src/pages/devops/components/Pipeline/PipelineTemplate/index.scss
src/pages/devops/containers/CD/Components/ChartCard/index.jsx
src/pages/devops/containers/CD/Components/ChartCard/index.scss
src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx

/kind design
Fixes #
```release-note
None
```
```docs
```

fix: Optimize the ui

---

src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
src/utils/constants.js

/kind bug
Fixes #
```release-note
NONE
```

fix: Update storagecontent table icon when list data is empty

---

src/stores/workspace.js

/kind bug
Fixes #[#4610](https://github.com/kubesphere/kubesphere/issues/4610)
The workspace test was create in host cluster:
https://user-images.githubusercontent.com/33231138/168566915-d254b88b-6f61-428f-aafd-ecd042b92767.mov
The workspace list in member cluster:
https://user-images.githubusercontent.com/33231138/168567202-c12d6458-96d9-4cd3-bfcc-8034130ba7ff.mov
```release-note
NONE
```

fix: No workspace created in host cluster on the console page of member cluster

---

src/pages/workspaces/components/Modals/WorkspaceDelete/index.jsx

Fixes #
```release-note
None
```
```docs
```

fix: Deleting a workspace does not select any resources from it

---

src/components/Modals/ContianerTerminal/index.jsx
src/stores/terminal.js

/kind bug
Fixes #
It will use the webSocket url with '/exec'  first and try the old url without '/exec' after the connection failed.
```release-note
NONE
```

fix: Can't connect to conatiner's kubectl

---

src/pages/workspaces/containers/DevOps/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3298
```
```
```release-note
None
```
```docs
```

fix: Remove devops id in devops list

---

locales/en/l10n-appStoreManagement-appReview-list.js
src/pages/workspaces/containers/Apps/Detail/index.jsx

Remove the 'App ID' and 'Category' parameters of app template.
```release-note
None
```

docs: Remove the 'App ID' and 'Category' parameters of app template

---

src/core/global.js
src/pages/clusters/containers/Base/List/index.jsx
src/pages/clusters/containers/layout.jsx
src/stores/cluster/index.js

/kind bug
Sometimes, the member cluster's configz will be an empty object when adding a member to the host cluster.
Fixes ##3334
```
```
```release-note
NONE
```

fix: Service Account can not use in member-cluster

---

src/pages/projects/components/Modals/HPA/index.jsx
src/pages/projects/containers/Services/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/qkcp/issues/248
```
```
```release-note
None
```
```docs
```

fix: Remove the limit of cpu use in hpa

---

src/components/Inputs/ContainerPort/index.jsx
src/components/Inputs/ContainerPort/index.test.js
src/components/Inputs/ContainerServicePort/index.jsx
src/components/Inputs/ContainerServicePort/index.test.js

/kind bug
Fixes ##[4955](https://github.com/kubesphere/kubesphere/issues/4955)
https://user-images.githubusercontent.com/33231138/173728546-37e2fb46-53e1-45d9-a7b2-27e2a5f0ffd8.mov
```release-note
NONE
```
```docs
```

fix: Users can't just only edit container port

---

src/actions/cluster.js
src/components/Forms/Secret/SecretSettings/DataForm/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/4965
```
```
```release-note
```
```docs
```

fix: Fix the data is incorre when twice update the cluster kubeconfig

---

server/views/blank_markdown.html
src/components/Modals/StorageclassAutoresizer/index.jsx
src/pages/projects/containers/Services/Topology/Service/index.jsx
src/pages/projects/containers/Volumes/Detail/index.jsx

/kind bug
Fixes ##3405,###3406
1)
2)
3)
4):
```release-note
NONE
```
```docs
```

fix: Storage class editing automatic extension maximum value does not take effect

---

src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx

/kind bug
User can't save.
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Form can't save when creating a workload

---

scripts/checkRepeat.js

/kind bug
There will be an error in the window environment when adding translation files
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Path parsing error in windows environment

---

src/components/Forms/Pipelines/ParamsFormModal/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/ks-devops/issues/537
```
```
```release-note
None
```
```docs
```

fix: Render wrong form item while multiple branch

---

locales/ar/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/es/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/fr/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/hi/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/ko/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/lt/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/pl/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/tc/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/tr/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
src/components/Forms/Workload/VolumeSettings/AddHostPath/index.jsx

/kind bug
1. During the creation of a homemade application, when the hostpath storage volume type is mounted, an error message(Deployment.apps \"ss-v1\" is invalid: [spec.template.spec.volumes[0].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: \"test-zhh\"]) is displayed if the hostpath is not specified. If the hostpath is specified, the application is successfully created.
2. On the other hand, I looked up the Kubernetes API documentation(https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) and the host path is a property that must be set .
```
```
```release-note
Setting the hostpath is required when mounting the hostpath storage volume to an …
```

Setting the hostpath is required when mounting the hostpath storage volume to an application 

---

src/components/Forms/GrayRelease/PolicyConfig/Canary/OSSelect/index.jsx
src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx

/kind bug
canary publishing is invalid when multiple operating systems are selected. 
If a separate operating system (Window or MacOS) is selected for grayscale publishing, the traffic can be switched normally. However, if multiple operating systems (Windows and MacOS) are selected, traffic switchover fails. For example, if other systems release version V1, Windows and MacOS release version V2, both systems still use version V1.
in addition, my version is 3.2.1
```
/assign @patrick-luoyu
```
```release-note
fix: canary publishing is invalid when multiple operating systems are selected. 
```

fix: canary release is invalid, when multiple operating systems are selected

---

src/pages/projects/components/Modals/HPA/index.jsx

/kind bug
The associated hpa hasn't been deleted when use the command line to delete the deployment.
```
/assign @patrick-luoyu
```
```release-note
None
```

fix:the associated hpa hasn't been deleted when use the command line to delete the deployment

---

src/pages/projects/components/Cards/Workloads/Item.jsx

/kind bug
Fixes ##[4986](https://github.com/kubesphere/kubesphere/issues/4986)
```
```
```release-note
NONE
```
```docs
```

fix: Display the type of each workload on the app details page

---

src/pages/projects/containers/Applications/CRDAppDetail/index.jsx

/kind bug
Fixes ##[4987](https://github.com/kubesphere/kubesphere/issues/4987)
```
```
```release-note
NONE
```
```docs
```

fix: Remove the 'App' field on the composed app details page

---

src/components/Base/Cascader/index.jsx

/kind bug
The problem caused by the options's top hight incorrect, It will appears when the options length less than 8.
Fixes ##3358
```release-note
NONE
```
```docs
```

fix: Add monitoring items to the custom monitoring panel, and the monitoring indicators display errors

---

package.json
src/pages/projects/containers/Services/index.jsx
src/pages/workspaces/containers/Repos/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5010 #https://github.com/kubesphere/console/issues/3399
```
```
```release-note
fix: Fix the External services cause the "Services" page to crash
```
```docs
```

fix: Fix the External services cause the "Services" page to crash

---

src/components/Forms/Notification/FeiShuForm/index.jsx
src/pages/console/containers/Dashboard/index.jsx
src/pages/settings/containers/Notification/DingTalk/index.jsx
src/pages/settings/containers/Notification/FeiShu/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5029
https://user-images.githubusercontent.com/17872673/181445348-02a7924a-8e40-48a0-b2e1-7b89d2bc1372.mov
```release-note
None
```
```docs
```

fix: Modify the route of the dashboard when another role login in.

---

src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx

/kind bug
Fixes ##3465
```
```
```release-note
NONE
```
```docs
```

fix: When you do not select key or path to save, there is no prompt information on the page.

---

src/core/containers/Login/index.jsx
src/utils/index.js

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: Replace atob for encod encryption in login

---

src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/Card.jsx
src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/index.jsx
src/components/Forms/Workload/VolumeSettings/index.jsx

/kind bug
Fixes ##[#4196](https://github.com/kubesphere/kubesphere/issues/4196)
```release-note
NONE
```
```docs
```

fix: Display volume template info in statefulsets setting modal

---

src/utils/object.mapper.js

/kind bug
in the application detail page, the updatetime is always the current time. i check the Application CRD, it has not the updatetime attribution. 
```
```
```release-note
fix: hide the updatetime of application
```

fix: application's updatetime always is current time

---

src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx

/kind bug
the traffic allocation fails, after a version takes over traffic in the canary release modal. The concrete representation is:
1. the page traffic allocation conflicts with the top prompt
2. The service version was not changed according to the traffic allocation rules
```
```
```release-note
fix: the traffic allocation fails, after a version takes over traffic in the canary release modal.
```

fix: traffic allocation fails after taking over traffic in the canary release modal.

---

src/stores/devops/pipelines.js

Signed-off-by: Bunny <qimiao@yunify.com>
/kind bug
Filter the being deleting Pipelines in the pipeline list
Fixes #[736](https://github.com/kubesphere/ks-devops/issues/736)
```
```
```release-note
NONE
```
```docs
```

fix: Avoid the being deleting Pipelines on the list page

---

src/components/Modals/ContianerTerminal/index.jsx
src/pages/clusters/containers/Clusters/index.jsx
src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
src/pages/workspaces/components/Modals/WorkspaceSelect/index.jsx
src/pages/workspaces/containers/Projects/index.jsx
src/stores/cluster/index.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5059
```
```
```release-note
fix: Modify the api of get cluster list in different user login
```
```docs
```

fix: Modify the api of get cluster list in different user login

---

locales/ar/l10n-projects-applicationWorkloads-deployments-list.js
locales/en/l10n-projects-applicationWorkloads-deployments-list.js
locales/es/l10n-projects-applicationWorkloads-deployments-list.js
locales/fr/l10n-projects-applicationWorkloads-deployments-list.js
locales/hi/l10n-projects-applicationWorkloads-deployments-list.js
locales/ko/l10n-projects-applicationWorkloads-deployments-list.js
locales/lt/l10n-projects-applicationWorkloads-deployments-list.js
locales/pl/l10n-projects-applicationWorkloads-deployments-list.js
locales/tc/l10n-projects-applicationWorkloads-deployments-list.js
locales/tr/l10n-projects-applicationWorkloads-deployments-list.js
locales/zh/l10n-projects-applicationWorkloads-deployments-list.js
src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx

/kind bug
/kind feature
1. When a container with the same name is edited, the modified container configuration is always updated to the first container with the same name.
2. When a container with the same name is deleted, all containers with the same name are deleted
In addition, duplicate container names are not allowed in the kubernetes, So It is necessary to add duplicate name validation to avoid the operation bug of same container name.
```
```
```release-note
feat: add duplicate name validation to the container name
```

fix: misbehaving when editing or deleting an image of the same name

---

locales/ar/l10n-projects-applicationWorkloads-deployments-list.js
locales/en/l10n-projects-applicationWorkloads-deployments-list.js
locales/es/l10n-projects-applicationWorkloads-deployments-list.js
locales/fr/l10n-projects-applicationWorkloads-deployments-list.js
locales/hi/l10n-projects-applicationWorkloads-deployments-list.js
locales/ko/l10n-projects-applicationWorkloads-deployments-list.js
locales/lt/l10n-projects-applicationWorkloads-deployments-list.js
locales/pl/l10n-projects-applicationWorkloads-deployments-list.js
locales/tc/l10n-projects-applicationWorkloads-deployments-list.js
locales/tr/l10n-projects-applicationWorkloads-deployments-list.js
locales/zh/l10n-projects-applicationWorkloads-deployments-list.js

/kind bug
When adding an init container, the prompt "Please add at least one container" is still misleading to the user.
```
```
```release-note
fix: correct the container missing validation hints
```

fix: inaccurate container missing validation hints

---

src/components/Cards/ContainerLog/index.scss

/kind bug
```
```
```release-note
None
```
```docs
```

fix: Support the logs wrapping

---

src/actions/volume.js
src/pages/projects/containers/Volumes/Detail/index.jsx

/kind bug
Fixes ##3565
```
```
```release-note
NONE
```
```docs
```

fix: Get snapshotclass api warning

---

locales/en/workload.js
src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx

/kind bug
Fixes ##3465,##3567
```
```
```release-note
NONE
```
```docs
```

fix: When you do not select key or path to save, you cant save it

---

src/utils/object.mapper.js

/kind bug
In the ipv6 and ipv4 dual-stack environment, the creation of routing rules fails because the K8S ingress host property does not support colons, whereas ipv6 has colons.
```
```
```release-note
fix: filter the ipv6 address when automatically generate routing rules
```

fix: failed to create routing rules in ipv6 and ipv4 dual-stack environment

---

build/Dockerfile.dapper
hack/docker_build_multiarch.sh

Signed-off-by: zhoutian <zhoutian@yunify.com>
we can build image easily by this PR.
when to webpack to get the javascript file,its will cost much time in linux/arm64, so we just get the  javascript file in linux/amd64,and then build the final images in  linux/amd64or linux/arm64.
Fixes #
```
optimization the image building of KubeSphere/console
```
```release-note
first we build the pre-image to get the file by webpacking
then we can build the image of linux/amd64,linux/arm64  by copy the file
finally we will rmi the pre-image and rm the file by webpacking
```
```docs
```

optimization the image building of KubeSphere/console

---

src/pages/devops/components/Pipeline/store.js

Signed-off-by: elichen95 <elichen95@163.com>
/kind bug
Fixes #https://github.com/kubesphere/ks-devops/issues/800
```
```
```release-note
None
```
```docs
```

fix: generate random string to replace numberic name

---

src/pages/clusters/containers/ConfigMaps/index.jsx

/kind bug
Fixes ##3638
```
```
```release-note
NONE
```
```docs
```

fix: The list ofconfigmap is not displayed correctly

---

src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx

/kind bug
Fixes ##3568
```
```
```release-note
NONE
```
```docs
```

fix: There is a delete button for project management permissions to view the details of grayscale publishing tasks

---

src/components/Forms/Workload/ContainerSettings/index.jsx

/kind bug
Fixes #3575
```
```
```release-note
NONE
```
```docs
```

fix: An error is displayed after deleting the container

---

src/components/Forms/Service/BaseInfo/index.jsx
src/pages/projects/components/Modals/CreateApp/Services/index.jsx
src/pages/projects/components/Modals/CreateAppService/index.jsx

/kind bug
/kind feature
When a service with the same name is edited, the modified service configuration is always updated to the first service with the same name.
```
```
```release-note
feat: add duplicate name validation to the service name
```

fix: misbehaving when editing the same name service

---

src/components/Base/List/index.scss
src/pages/clusters/containers/BaseInfo/index.jsx

/kind bug
Fixes ##[5222](https://github.com/kubesphere/kubesphere/issues/5222)
```
```
```release-note
NONE
```
```docs
```

fix: Proxy connected clusters should not have an update kubeconfig button

---

src/components/Forms/Service/BaseInfo/index.jsx
src/components/Forms/Workload/ContainerSettings/index.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Add app label

---

src/pages/projects/containers/Services/index.jsx

/kind bug
Fixes ##3651
```
```
```release-note
NONE
```
```docs
```

fix: Display app name

---

src/components/Charts/Area/MediumArea/index.jsx

Signed-off-by: moweiwei <mo.weiwei@99cloud.net>
/kind bug
Fixes #3737 
```
```
```release-note
None
```
```docs
```

fix: fix lastValue return err in workspace overview page

---

src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/logItem.jsx

/kind bug
The duration may be negative cause by jenkins.
Fixes https://github.com/kubesphere/ks-devops/issues/826
```
None
```
```release-note
None
```
```docs
None
```

fix: Show '-' when duration is negative

---

src/components/Modals/EditAuthorization/CheckItem.jsx

/kind bug
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: User can't click permissions field when editing workspace role

---

src/utils/status.js

/kind bug
If a pod item's conditions object has nother field, such as: { type: 'ContainerDiskPrssuer', status: 'False' }, it's status will be in pending in the table list.
Fixes #
```
```
```release-note
NONE
```
```docs
```

fix: Pods status display is incorrect

---

src/pages/projects/containers/Services/Detail/index.jsx

/kind bug
the update time is always the latest time on the service detail page. And the status has not conditions property to get the update time.
```
```
```release-note
delete the update time property on the detail page.
```

fix: the update time is always the latest time on the service detail page

---

src/components/Inputs/ResourceLimit/index.jsx
src/utils/index.js

/kind bug
Fixes #https://github.com/kubesphere/console/issues/3806
```
```
```release-note
fix: Remove slider in resource quota and can set value to 0
```
```docs
```

fix: Remove slider in resource quota and can set value to 0

---

src/actions/cd.js
src/utils/form.templates.js

/kind design
We use the 
```yaml
apiVersion: gitops.kubesphere.io/v1alpha1
kind: Application
spec:
kind: argocd
argoApp:
```
or 
```yaml
apiVersion: gitops.kubesphere.io/v1alpha1
kind: Application
spec:
kind: fluxcd
fluxApp:
```
to identify the kind of this application is `argocd` or `fluxcd`.
See also: https://github.com/kubesphere/ks-devops/pull/778
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

feat: Change the kind from 'argo-project' to 'argocd'

---

src/pages/projects/containers/Pods/Containers/Detail.jsx

/kind bug
Fixes #
Before
After
```release-note
None
```
```docs
```

fix: Fixed the CPU value of the container details that is displayed incorrectly because it has units.

---

src/pages/fedprojects/containers/Secrets/Detail/SecretDetail/index.jsx
src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx

/kind bug
Fixes #
before 
after
```release-note
Fix the value encoded of the secret displayed incorrectly on the detail page
```
```docs
```

fix: Fix the value encoded of the secret displayed incorrectly on the detail page

---

server/services/session.js

/kind chore
It should be `argocd` for now.
https://github.com/kubesphere/console/pull/3761#discussion_r992942415
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

fix: Change Default GitOpsEngine from fluxcd to argocd

---

src/actions/fluxcd.js
src/components/Forms/CD/FluxCD/Advance/index.jsx

/kind feature
We need pass raw json values into `config.helmRelease.values` field like below:
```yaml
replicaCount: 6
service: 
type: LoadBalancer
```
We can use `ArrayInput` and `ObjectInput` components to collect k&v then convert these strings to Object.
Result:
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

feat: change helm values Input component to ArrayInput and ObjectInput

---

package.json

/kind bug
npm start run failed on window.
```
```
```release-note
None
```

fix: npm start command failed to run on window

---

src/actions/fluxcd.js
src/components/Forms/CD/FluxCD/Advance/index.jsx

/kind feature
The [ValuesFrom](https://fluxcd.io/flux/components/helm/helmreleases/#values-overrides) is a feature provided by FluxCD.
I think we can pass a list of the below Objects by ArrayInput and Object Input Components.
```golang
type ValuesReference struct {
Kind string `json:"kind"`
Name string `json:"name"`
ValuesKey string `json:"valuesKey,omitempty"`
}
```
Result:
Fixes #
```
None
```
```release-note
None
```
```docs
None
```

feat: Add helm valuesFrom

---

src/components/Forms/Pipelines/RepoSelect/index.jsx

/kind bug
Fixes ##[3235](https://github.com/kubesphere/console/issues/3235)
```release-note
NONE
```
```docs
```

fix: Display optimization in code repository

---

src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx

/kind bug
Add link for aborted status pipelinerun
Fixes #https://github.com/kubesphere/ks-devops/issues/859
```
```
```release-note
Fix bug: add link for aborted status pipelinerun
```
```docs
```

fix:Fix ks-devops issue 859, add link for aborted status pipelinerun

---

src/pages/clusters/containers/Gateway/Components/Pods/index.jsx
src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx
src/stores/gateway.js

/kind bug
Fixes ##[5368](https://github.com/kubesphere/kubesphere/issues/5368)
https://user-images.githubusercontent.com/33231138/212251061-3a5767ad-91ac-4a09-83cd-dd3e31d5f1a4.mov
```release-note
fix: Gateway does not automatically refresh after a Resource Status change
```
```docs
```

fix: Gateway does not automatically refresh after a Resource Status change

---

locales/en/l10n-projects-projectSettings-networkIsolation.js

Signed-off-by: Bettygogo2021 <bettygogo@kubesphere.io>
/assign @harrisonliu5 @zheng1 @wenxin-01 
Pls help review and merge this PR.
Fixes #
```
```
```release-note
none
```
```docs
```

change cluster to workspace

---

locales/en/l10n-accessControl-workspaces-list.js
src/components/Clusters/ClusterWrapper/index.jsx
src/pages/access/containers/Workspaces/index.jsx
src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.jsx

/kind bug
System-workspace cluster field shows 'all' for multi-cluster 
Fixes #https://github.com/kubesphere/issues/issues/184
Fixes #https://github.com/kubesphere/console/issues/4043
```
```
```release-note
fix: System-workspace cluster field shows 'all' for multi-cluster 
```
```docs
```

fix: System-workspace cluster field shows 'all' for multi-cluster 

---

src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.scss
src/components/Forms/Service/ContainerSetting/index.jsx
src/stores/service.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5410
```
```
```release-note
fix: Fix the image not match when created service by jar/war
```
```docs
```

fix: Fix the image not match when created service by jar/war

---

src/stores/devops/pipelines.js

/kind bug
Add pipeline activity list id then id is empty
Fixes #https://github.com/kubesphere/ks-devops/issues/863
```
```
```release-note
fixed: Add pipeline activity list id then id is empty
```
```docs
```

fixed: Add pipeline activity list id then id is empty

---

locales/ar/l10n-clusterManagement-clusterSettings-logReceivers-list.js

Fixes #
```
```
```release-note
NONE
```
```docs
```

feat: Add log receiver translate filed

---

locales/en/l10n-clusterManagement-projects-list.js

Fixes # 814
```
```
```release-note
none
```
```docs
```

Fix: fix alias desc

---

locales/en/l10n-clusterManagement-clusterSettings-logReceivers-details.js

/kind bug
Fixes :
```
```
```release-note
NONE
```
```docs
```

fix: LOG_RECEIVER field not be translated

---

src/utils/object.mapper.js

/kind bug
Fixes #[#5604](https://github.com/kubesphere/kubesphere/issues/5604)
```
```
```release-note
NONE
```
```docs
```

fix: The 'Cluster Gateway' page keeps loading and reports an error 'evaluating e.ip.includes'

---

locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js

Fixes #
```
```
```release-note
none
```
```docs
```

fix: fix translation

---

locales/en/l10n-devopsProjects-pipeline-details.js

/kind bug
feat: add devops locale
Fixes #https://github.com/kubesphere/issues/issues/1198
```
```
```release-note
None
```
```docs
```

feat: add devops locale

---

locales/en/l10n-clusterManagement-baseicInformation.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js

Fixes #
```
```
```release-note
none
```
```docs
```

Update: update alerts

---

src/pages/projects/containers/Network/Policies/IsolateInfo/index.scss
src/pages/projects/containers/Network/Policies/RuleInfo/index.scss

/kind bug
Fixes #4179 
```release-note
Fixed the incorrect style for IsolateInfo and RuleInfo of Network Policy panel.
```

style: fix incorrect style for IsolateInfo and RuleInfo of Network Policy panel

---

src/stores/crd.resource.js
src/utils/object.mapper.js

/kind bug
/kind feature
Updating crd resource on ks-console page loses status information.
When the user modifies the crd through ks-console, it may cause some unexpected problems.
Fixes https://github.com/kubesphere/console/issues/3865
```release-note
When editing the crd resource through ks-console, the original status information will be loaded
```
before: does not contain `status` information
after: contain `status` information

fix:Updating crd resource on ks-console page loses status information

---

src/components/EditForms/Workload/TerminationSeconds/index.jsx
src/components/Forms/Workload/ContainerSettings/TerminationSeconds/index.jsx
src/pages/fedprojects/components/ConfigTemplate/config.js
src/pages/projects/components/Modals/ConfigTemplate/config.js

/kind bug
fix: No termination seconds in multi project (#1001)
Fixes #https://github.com/kubesphere/kubesphere/issues/5830
link #https://github.com/kubesphere/issues/issues/865
```
```
```release-note
None
```
```docs
```

fix: No termination seconds in multi project (#1001)

---

src/components/Tables/Base/CustomColumns/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/console/issues/4171
```
```
```release-note
fix: Count table body height for filter button's dropdown content
```
```docs
```

fix: Count table body height for filter button's dropdown content

---

locales/ar/l10n-devopsProjects-pipeline-details.js
locales/de/l10n-devopsProjects-pipeline-details.js
locales/en/l10n-devopsProjects-pipeline-details.js
locales/es/l10n-devopsProjects-pipeline-details.js
locales/fr/l10n-devopsProjects-pipeline-details.js
locales/hi/l10n-devopsProjects-pipeline-details.js
locales/ko/l10n-devopsProjects-pipeline-details.js
locales/lt/l10n-devopsProjects-pipeline-details.js
locales/pl/l10n-devopsProjects-pipeline-details.js
locales/pt/l10n-devopsProjects-pipeline-details.js
locales/tc/l10n-devopsProjects-pipeline-details.js
locales/tr/l10n-devopsProjects-pipeline-details.js
locales/zh/l10n-devopsProjects-pipeline-details.js
src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
src/pages/devops/containers/Pipelines/Detail/Parameters/Item.jsx
src/pages/devops/containers/Pipelines/Detail/Parameters/index.jsx
src/pages/devops/containers/Pipelines/Detail/Parameters/item.scss
src/pages/devops/containers/Pipelines/Detail/routes.js

/kind feature
feat: Devops pipeline run detail page add params tab
Fixes #https://github.com/kubesphere/ks-devops/issues/911
```
```
```release-note
Devops pipeline run detail page add params tab
```
```docs
```

[ks-3.4.1]feat: Devops pipeline run detail page add params tab

---

src/components/Inputs/RulePath/index.jsx

/kind bug
/kind regression
-->
Fixes #https://github.com/kubesphere/console/issues/4177
```
```
```release-note
fix: Fix the type of number when entering the routing rule path
```
```docs
```

fix: Fix the type of number when entering the routing rule path

---

src/pages/workspaces/containers/DevOps/index.jsx

/kind bug
fix: Set disabled when cluster is not ready or not install devops
Fixes #https://github.com/kubesphere/ks-devops/issues/607
```
```
```release-note
None
```
```docs
```

fix: Set disabled when cluster is not ready or not install devops

---

src/components/Forms/Pipelines/ParamsFormModal/index.jsx

/kind bug
fix: Fix parameters defined in pipeline not passed to jenkins
Fixes #https://github.com/kubesphere/ks-devops/issues/980
```
```
```release-note
None
```
```docs
```

fix: Fix parameters defined in pipeline not passed to jenkins

---

server/proxy.js
src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/FullLogs/index.jsx
src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.scss
src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
src/pages/devops/containers/layout.jsx
src/stores/devops/run.js
src/utils/request.js

* fix: fix devops pipeline run log
* fix: update pipeline run log refresh icon
* fix: fix devops pipeline run log refresh action
* fix: fix devops history card name
---------
/kind bug
Limit the size of online run log to 20MB, with each request size being 100KB. 
Change the download method to download the log from the server.
Fix other bugs in devops.
Fixes #https://github.com/kubesphere/ks-devops/issues/986
Fixes #https://github.com/kubesphere/ks-devops/issues/978
Fixes #https://github.com/kubesphere/ks-devops/issues/752
Fixes #https://github.com/kubesphere/ks-devops/issues/993
Fixes #https://github.com/kubesphere/issues/issues/1989
```
```
```release-note
None
```
```docs
```

fix: [devops 3.4.1] fix devops pipeline run log (#1772)

---

src/actions/pipeline.js
src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx

/kind bug
fix: Notify message before run pipeline
Fixes #https://github.com/kubesphere/ks-devops/issues/986
```
```
```release-note
None
```
```docs
```

fix: notify message before run pipeline

---

src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx

/kind bug
fix: Add link at pipeline run log list to detail page
Fixes #https://github.com/kubesphere/ks-devops/issues/953
```
```
```release-note
None
```
```docs
```

fix: Add link at pipeline run log list to detail page

---

src/components/Modals/CredentialCreate/index.jsx

/kind bug
Fixes #https://github.com/kubesphere/issues/issues/2007
```
```
```release-note
None
```
```docs
```

fix: Remove kubeconfig type when create credential

---

src/pages/apps/components/Modals/AppDeploy/index.jsx
src/stores/openpitrix/base.js

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5873
```
```
```release-note
fix: Fix deploy the app by template not get the detail
```
```docs
```

fix: Fix deploy the app by template not get the detail

---

package.json
src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
src/components/Inputs/TagInput/autosuggest.jsx
src/components/Inputs/TagInput/index.scss
yarn.lock

/kind bug
Fixes #https://github.com/kubesphere/kubesphere/issues/5847
```
```
```release-note
fix: Optimize the tag input to automatically fill in the value when it loses focus
```
```docs
```

fix: Optimize the tag input to automatically fill in the value when it loses focus

---

locales/en/l10n-projects-imageBuilders-list.js
locales/zh/l10n-projects-imageBuilders-list.js
server/config.yaml
src/actions/devopsImageBuilder.js
src/components/Forms/DevopsImageBuilder/LanguageSelect/index.jsx
src/components/Forms/DevopsImageBuilder/LanguageSelect/index.scss
src/components/Forms/DevopsImageBuilder/RerunForm/index.jsx
src/components/Forms/DevopsImageBuilder/RerunForm/index.scss
src/components/Forms/DevopsImageBuilder/S2IForm/TemplateSelect/index.jsx
src/components/Forms/DevopsImageBuilder/S2IForm/TemplateSelect/index.scss
src/components/Forms/DevopsImageBuilder/S2IForm/index.jsx
src/components/Forms/DevopsImageBuilder/S2IForm/index.scss
src/configs/steps/devopsImageBuilder.js
src/pages/devops/containers/ImageBuilder/Detail/BuildRecords/index.jsx
src/pages/devops/containers/ImageBuilder/Detail/BuildRecords/index.scss
src/pages/devops/containers/ImageBuilder/Detail/index.jsx
src/pages/devops/containers/ImageBuilder/Detail/index.scss
src/pages/devops/containers/ImageBuilder/Detail/routes.js
src/pages/devops/containers/ImageBuilder/index.jsx
src/pages/devops/containers/ImageBuilder/index.scss
src/pages/devops/routes/index.js
src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
src/pages/projects/components/Cards/ImageRunRecord/Item/devops.jsx
src/pages/projects/components/Cards/ImageRunRecord/Item/index.scss
src/pages/projects/components/Cards/ImageRunRecord/devops.jsx
src/stores/devops/imageBuildStrategies.js
src/stores/devops/imageBuilderRun.js
src/stores/devops/imgBuilder.js

/kind design
Add a Shipwright-based ImageBuilder under the devpos page
```release-note
None
```

feat: Add imagebuilder in DevOps module

---

src/components/Modals/CredentialCreate/index.jsx

/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/5971
Related PR
https://github.com/kubesphere/console/pull/4222
```release-note
None
```
```docs
```

revert: recovery kubeconfig type when create credential

---

server/services/session.js
src/stores/workload/hpa.js
src/utils/constants.js
src/utils/workload.js

/kind bug
Fixes https://github.com/kubesphere/kubesphere/issues/5872
```
```
```release-note
None
```
```docs
```

fix: HPA api response 404

---

src/pages/clusters/containers/Projects/index.jsx

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: projects of cluster has no create button

---

src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
yarn.lock

/kind bug
fix: Fix gitlab source repo options error
Fixes #https://github.com/kubesphere/ks-devops/issues/1039
```
```
```release-note
none
```
```docs
```

fix: Fix gitlab source repo options error

---

.github/workflows/release.yml
hack/docker_build_multiarch.sh

sync image to aliyuns repo when tag is vx.x.x.x
Fixes #
testresult: run action in my private project is ok: https://github.com/redscholar/ks-console/actions/runs/10771207686
the image id is not changed
```
```
```release-note
none
```
```docs
```

fix: sync image to aliyuns repo

---

src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
yarn.lock

/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```

fix: resourceStatus get podNums

---

.github/workflows/sync-to-kse.yml

Fixes #
```
```
```release-note
None
```
```docs
```

ci: add .github/workflows/sync-to-kse.yml

---

locales/en/custom.js
locales/es/custom.js
locales/tc/custom.js
locales/zh/custom.js
packages/console/src/pages/workspaces/containers/Devops/ClusterSelect.tsx
packages/console/src/pages/workspaces/containers/Devops/index.tsx
packages/core/src/components/GlobalStyles/index.tsx

/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```

fix: Fix devops bugs

---

packages/bootstrap/webpack/webpack.base.conf.js
packages/shared/src/components/Layouts/NavMenu/NavItem/index.tsx
packages/shared/src/constants/env.ts

Fixes #
```
```
```release-note
None
```
```docs
```

fix: fix the issue of checking licenses in ks

---

packages/bootstrap/webpack/config.js
packages/bootstrap/webpack/webpack.base.conf.js
packages/bootstrap/webpack/webpack.dll.conf.js

Fixes #
```
```
```release-note
None
```
```docs
```

build: add KUBESPHERE_EDITION constant to config files

---

packages/core/src/stores/marketplace.ts

/kind cleanup
The current version does not require `kapis/config.kubesphere.io/v1alpha2/configs/marketplace`
Fixes #
```
```
```release-note
None
```
```docs
```

chore: disable kapis/config.kubesphere.io/v1alpha2/configs/marketplace

---

server/controllers/view.js

When an error occurs in Node.js, the page may only display "Not Found".
The error prompt has now been improved.
before
after
Fixes #
```
```
```release-note
None
```
```docs
```

chore: improve page error messages

---

packages/shared/src/components/Modals/KubeCtl/index.tsx

/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```

fix: Filter clusters by status of ready in kubectl modal

---

packages/shared/src/components/Base/Card/MonitorController/Modal/index.tsx
packages/shared/src/components/TimeSelector/CustomRange.tsx
packages/shared/src/components/TimeSelector/index.tsx

/kind bug
Links #https://github.com/kubesphere/project/issues/4881
```
```
```release-note
None
```
```docs
```

fix: Fix the z-index of monitorController modal

---

packages/shared/src/components/ProjectLayout/ProjectsSelectorModal/hooks.ts

/kind bug
https://github.com/user-attachments/assets/8761f7b2-5390-4dde-aa9d-e5486b96b825
Links https://github.com/kubesphere/project/issues/5122
```
Added the page parameter in useFetchProjectsByTypeInfiniteQuery
```
```release-note
None
```
```docs
```

fix: missing page param in useFetchProjectsByTypeInfiniteQuery

---

server/controllers/view.js
server/views/consolev3.html
server/views/index.html
server/views/terminal.html

/kind bug
fix: Update global variable handling in views to use decodeURIComponent
Links #https://github.com/kubesphere/project/issues/5222
https://github.com/kubesphere/project/issues/4826
```
```
```release-note
none
```
```docs
```

fix: Update global variable handling in views to use decodeURIComponent

---

packages/console/src/pages/access/containers/Workspaces/index.tsx
packages/shared/src/stores/workspace.ts

/kind bug
Links #https://github.com/kubesphere/project/issues/4803
```
```
```release-note
None
```
```docs
```

fix: Fix delete workspace with deleting project on workspace baseinfo page

---

locales/en/l10n-appStoreManagement-appCategories-list.js
locales/es/l10n-appStoreManagement-appCategories-list.js
locales/tc/l10n-appStoreManagement-appCategories-list.js
locales/zh/l10n-appStoreManagement-appCategories-list.js
packages/shared/src/constants/patterns.ts

/kind bug 
Links #https://github.com/kubesphere/project/issues/4876
```
need to make some modifications in openpitrix extension 
```
```release-note
None
```
```docs
```

fix: add rule on app category name to match backend rule

---

packages/core/src/containers/Extensions/Management/components/ResetDefaultConfigTip/ResetDefaultConfigConfirmModal.tsx
packages/shared/src/components/Modals/Confirm/ConfirmModal.constants.ts
packages/shared/src/components/Modals/Confirm/ConfirmModal.helpers.tsx
packages/shared/src/components/Modals/Confirm/ConfirmModal.styles.ts
packages/shared/src/components/Modals/Confirm/ConfirmModal.tsx
packages/shared/src/components/Modals/Confirm/ConfirmModal.types.ts
packages/shared/src/components/Modals/Confirm/index.ts
packages/shared/src/components/index.ts

Links #
```
```
```release-note
None
```
```docs
```

chore: sync codes

---

packages/core/package.json
packages/core/src/components/GlobalStyles/index.tsx
packages/core/src/containers/Extensions/Management/components/Extensions/Extensions.styles.ts
packages/core/src/containers/Extensions/Management/components/Extensions/Extensions.tsx
packages/core/src/containers/Extensions/Management/components/Extensions/ExtensionsEmpty.styles.ts
packages/core/src/containers/Extensions/Management/components/Extensions/ExtensionsEmpty.tsx
packages/core/src/containers/Extensions/Management/constants/index.ts
packages/core/src/containers/Extensions/components/ExtensionsEmpty/ExtensionsEmpty.tsx

Links #
```
```
```release-note
None
```
```docs
```

refactor: refactor extensions management using DataTable

---

packages/shared/src/utils/table/hooks/useUrlSearchParamsStatus.ts

… 
/kind bug
feat: enhance useUrlSearchParamsStatus hook with reset pageIndex when columnFilters has changed
Links #https://github.com/kubesphere/project/issues/5429
```
```
```release-note
none
```
```docs
```

feat: enhance useUrlSearchParamsStatus hook with reset pageIndex when columnFilters has changed

---

packages/core/src/containers/Extensions/Management/Detail/index.tsx
packages/core/src/containers/Extensions/Management/constants/index.ts
packages/core/src/stores/extension.ts

Before:
1. Both Extension and WebSocket have WebSocket.
2. Extension and WebSocket will establish a new WebSocket connection based on changes in resourceVersion.
After:
1. Cancel the WebSocket connection of Extension, keeping only the WebSocket connection of InstallPlan.
2. InstallPlan's WebSocket only connects 1, and does not establish a new WebSocket connection based on changes in resourceVersion.
3. If there is no resourceVersion, the WebSocket parameters of InstallPlan will not include resourceVersion; if there is a resourceVersion, the WebSocket parameters of InstallPlan will include the resourceVersion from the first HTTP response.
Links
https://github.com/kubesphere/project/issues/5458
https://github.com/kubesphere/project/issues/5419#issuecomment-2588897224
```
```
```release-note …
```

refactor: the WebSocket logic in the details page of the expansion center

---

packages/shared/src/stores/role.ts

/kind bug
Links https://github.com/kubesphere/project/issues/5405
```
```
```release-note
None
```
```docs
```

fix: the description of the role uses data from the API

---

packages/shared/src/components/Apps/AppForms/AppBaseInfoForm/BasicInfoForm/index.tsx
packages/shared/src/components/Apps/AppVersionSelector/index.tsx

Add 'versionName' ordering parameter to useAppVersionList hook calls in BasicInfoForm and AppVersionSelector components to ensure consistent version display order
Links #https://github.com/kubesphere/kubesphere/issues/6343
```
```
```release-note
none
```
```docs
```

fix(app): add version name ordering in app version lists

---

packages/shared/src/components/Inputs/PropertiesInput/index.tsx

/kind bug
Links #https://github.com/kubesphere/project/issues/3376
```
this is a temporary fix
```
```release-note
None
```
```docs
```

fix: temporary fix for PropertiesInput focus loss problem

---

packages/shared/src/components/Apps/AppCreate/CreateYamlApp/index.tsx

/kind bug
Links #https://github.com/kubesphere/project/issues/5492
```
```
```release-note
None
```
```docs
```

fix: add create yaml app description input max length

---

packages/shared/src/utils/monitoring.ts

/kind bug
Links #https://github.com/kubesphere/console/issues/4447
```
```
```release-note
None
```
```docs
```

fix: Update fillEmptyMetrics rules

---

packages/console/src/pages/workspaces/components/WorkspaceBasicInfoForm/WorkspaceBasicInfoForm.styles.ts
packages/console/src/pages/workspaces/components/WorkspaceBasicInfoForm/WorkspaceManagerField.tsx

/kind bug
Links #https://github.com/kubesphere/project/issues/5061
```
```
```release-note
None
```
```docs
```

fix: Fix the edit manager permission on create workspace

---

server/controllers/session.js

/kind bug
Links https://github.com/kubesphere/project/issues/5512
```
```
```release-note
None
```
```docs
```

fix(node): update logout handling to redirect instead of returning URL by OIDC

---

packages/shared/src/components/PodsCard/utils.ts

/kind bug
Links #
```
```
```release-note
None
```
```docs
```

fix: pod remove ownerkind parameter

---

server/middlewares/checkToken.js
server/middlewares/proxy.js

/kind bug
Whenever the token is about to expire, a new token will be obtained through refresh_token, and then a 302 redirect will occur. However, the client cannot handle the redirect normally, which will cause some errors on the page. 
Therefore, we should adjust the logic here and use the new token to continue subsequent request processing so that the client can obtain the correct API request result.
Some error page rendering phenomena：
home page
pod detail page
Links #
```
```
```release-note
solve client api request that can't handle 302 redirects
```
```docs
```

fix: solve client api request that can't handle 302 redirects

---

packages/shared/src/components/Apps/Applications/DetailInfo/index.tsx

/kind bug
optimize app-releases detail page mange permission
Fixes # [6273](https://github.com/kubesphere/kubesphere/issues/6273)
```
```
```release-note
adjust app-releases button permission
```
```docs
```

adjust app-releases button permission

---

packages/core/src/containers/Session/LoginConfirm/index.tsx
server/services/session.js

/kind bug
Links https://github.com/kubesphere/kubesphere/issues/6394
```
```
```release-note
None
```
```docs
```

fix: update username field handling in login confirmation

---

packages/shared/src/components/DataTable/TableEmpty/CreateButton.tsx
packages/shared/src/components/DataTable/TableEmpty/index.tsx

Links #
```
```
```release-note
None
```
```docs
```

feat: add customizable text for create button in DataTable component

---

packages/shared/src/components/Apps/AppForms/AppBaseInfoForm/PlacementForm/ConfigForm/index.tsx

To solve the problem of a blank screen when the workspace is empty.
Links #
```
```
```release-note
none
```
```docs
```

fix: Adjust the workspace assignment logic in PlacementConfigForm to ensure the correct retrieval of patchWorkspaces names

---

packages/core/src/constants/extension.ts
packages/core/src/containers/Extensions/Management/actions/index.ts
packages/core/src/stores/extension.ts

- Updated the extension status handling in core constants and related files to use a constant map instead of an enum.
- Adjusted imports and references in the management actions and stores to align with the new structure.
Links #
```
```
```release-note
None
```
```docs
```

refactor: replace ExtensionStatusState enum with EXTENSION_STATUS_STATE_MAP for improved consistency and readability

---

packages/shared/src/utils/uiState.ts

- Renamed `Value` type to `ResolvableBoolean` for better understanding of its purpose.
- Updated `resolveValue` to `resolveBoolean` for improved clarity in function naming.
- Refactored `UIState` interface to use `ResolvableBoolean` for all boolean properties.
- Renamed `shouldDisplay` to `resolveVisibilityState` and adjusted its logic to return visibility and hidden states.
- Renamed `getDisabledState` to `resolveEnabledState` and streamlined the logic for determining enabled and disabled states.
Links #
```
```
```release-note
None
```
```docs
```

refactor: rename and enhance UI state utility functions for clarity and consistency

---

packages/core/src/stores/extension.ts

/kind bug
- Updated the `refetch` function to call `refetchClusters` instead of `refetchInstallPlan` for improved clarity in its purpose.
Links #
```
```
```release-note
None
```
```docs
```

fix: rename refetch function for clarity in extension store

---

packages/shared/src/components/Base/Button/Copy/index.tsx
packages/shared/src/components/Base/Button/Copy/styles.ts
packages/shared/src/components/Base/Button/index.ts
packages/shared/src/components/Base/index.ts

Links #
```
```
```release-note
None
```
```docs
```

feat: export Button component from Base index for improved accessibility

---

OWNERS

Links #
```
```
```release-note
None
```
```docs
```

ci: update OWNERS
